#!/usr/bin/env python3
"""R15 Phase 5: item icon graphics family generator.

Consumes the checked-in sources of truth and emits the family metadata:
  * catalog.generated.toml
  * bindings.generated.toml
  * ownership.generated.toml
  * inventory.generated.toml

Resource keys: emerald:item-icon/<slug> for icons,
                emerald:item-icon-pal/<slug> for palettes.

Determinism: sorted output; regeneration must be a no-op diff.
"""
import hashlib
import os
import re
import sys

def manifest_map(family_dir):
    """id -> canonical_decoded_sha256 from the production manifest."""
    p = f"resources/extraction/emerald/bpee01/{family_dir}/manifest.production.toml"
    out = {}
    try:
        text = open(p).read()
        for block in text.split('[[records]]')[1:]:
            m_id = re.search(r'id = "([^"]+)"', block)
            m_sha = re.search(r'canonical_decoded_sha256 = "([0-9a-f]+)"', block)
            if m_id and m_sha:
                out[m_id.group(1)] = m_sha.group(1)
    except OSError:
        pass
    return out

from collections import OrderedDict

INCBIN_RE = re.compile(
    r'const u32 (gItemIcon\w+)\[\]\s*=\s*'
    r'INCBIN_U32\(\s*"([^"]+)"\);')

def parse_incbins(path):
    out = OrderedDict()
    for line in open(path):
        m = INCBIN_RE.match(line.strip())
        if m:
            out[m.group(1)] = m.group(2)
    return out

def slug_of(artifact):
    # graphics/items/icons/<name>.4bpp.lz -> <name>
    # graphics/items/icon_palettes/<name>.gbapal.lz -> <name>
    name = os.path.basename(artifact)
    if name.endswith('.4bpp.lz'):
        name = name[:-len('.4bpp.lz')]
    elif name.endswith('.gbapal.lz'):
        name = name[:-len('.gbapal.lz')]
    return name

def parse_item_icon_table(path):
    """Parse gItemIconTable rows: [ITEM_X] = ITEM_ICON_ROW(gItemIcon_Y, gItemIconPalette_Z)"""
    rows = []
    pat = re.compile(r'\[(\w+)\]\s*=\s*ITEM_ICON_ROW\((\w+),\s*(\w+)\)')
    for line in open(path):
        m = pat.search(line)
        if m:
            rows.append((m.group(1), m.group(2), m.group(3)))
    return rows

def main():
    root = sys.argv[1] if len(sys.argv) > 1 else "."
    out_dir = sys.argv[2] if len(sys.argv) > 2 else \
        "resources/extraction/emerald/bpee01/item_icon"

    incbins = parse_incbins(f"{root}/src/data/graphics/items.h")
    table_rows = parse_item_icon_table(f"{root}/src/data/item_icon_table.h")

    # Separate icons and palettes
    icon_symbols = {k: v for k, v in incbins.items() if 'Palette' not in k}
    palette_symbols = {k: v for k, v in incbins.items() if 'Palette' in k}

    print(f"Found {len(icon_symbols)} icons, {len(palette_symbols)} palettes, "
          f"{len(table_rows)} table rows")

    os.makedirs(out_dir, exist_ok=True)

    # Build resource ID lists
    icon_ids = OrderedDict()
    palette_ids = OrderedDict()

    for sym, art in sorted(icon_symbols.items()):
        slug = slug_of(art)
        rid = f"emerald:item-icon/{slug}"
        icon_ids[rid] = (sym, art)

    for sym, art in sorted(palette_symbols.items()):
        slug = slug_of(art)
        rid = f"emerald:item-icon-pal/{slug}"
        palette_ids[rid] = (sym, art)

    all_ids = OrderedDict()
    all_ids.update(icon_ids)
    all_ids.update(palette_ids)

    # --- catalog ---
    cat = ["# Generated by tools/gen3_resources/item_icon_family/gen_item_icon.py",
           "# Do not edit by hand; regeneration must be a no-op diff.",
           "catalog_version = 1", 'namespace = "emerald"',
           'resource_api = "1.0.0"',
           'game = "emerald"', 'rom_profile = "bpee01-rev0"', ""]
    for rid in icon_ids:
        cat.append("[[resources]]")
        cat.append(f'id = "{rid}"')
        cat.append('type = "tile-graphics"')
        cat.append("schema = 1")
        cat.append("required_for_base = true")
    for rid in palette_ids:
        cat.append("[[resources]]")
        cat.append(f'id = "{rid}"')
        cat.append('type = "palette"')
        cat.append("schema = 1")
        cat.append("required_for_base = true")

    # --- bindings ---
    bin_ = ["# Generated by tools/gen3_resources/item_icon_family/gen_item_icon.py",
            "# Do not edit by hand; regeneration must be a no-op diff.",
            "bindings_version = 1", 'game = "emerald"',
            'rom_profile = "bpee01-rev0"', ""]
    for rid, (sym, art) in icon_ids.items():
        enc = "gba-lz77"
        data = open(f"{root}/{art}", "rb").read()
        if data[0] & 0x0F == 0 and len(data) >= 4:
            dec = data[1] | (data[2] << 8) | (data[3] << 16)
        else:
            enc = "raw"
            dec = len(data)
        bin_.append("[[bindings]]")
        bin_.append(f'id = "{rid}"')
        bin_.append(f'symbol = "{sym}"')
        bin_.append(f'source_artifact = "{art}"')
        bin_.append(f'source_encoding = "{enc}"')
        bin_.append('canonical_representation = "gba-4bpp-tiles"')
        bin_.append(f"expected_decoded_size = {dec}")
    for rid, (sym, art) in palette_ids.items():
        enc = "gba-lz77"
        data = open(f"{root}/{art}", "rb").read()
        if data[0] & 0x0F == 0 and len(data) >= 4:
            dec = data[1] | (data[2] << 8) | (data[3] << 16)
        else:
            enc = "raw"
            dec = len(data)
        bin_.append("[[bindings]]")
        bin_.append(f'id = "{rid}"')
        bin_.append(f'symbol = "{sym}"')
        bin_.append(f'source_artifact = "{art}"')
        bin_.append(f'source_encoding = "{enc}"')
        bin_.append('canonical_representation = "gba-bgr555-palette"')
        bin_.append(f"expected_decoded_size = {dec}")

    # --- ownership ---
    canon = manifest_map("item_icon") or {}
    own = ["# Generated by tools/gen3_resources/item_icon_family/gen_item_icon.py",
           "# Do not edit by hand; regeneration must be a no-op diff.",
           "ownership_version = 1", 'game = "emerald"',
           'rom_profile = "bpee01-rev0"', ""]
    fallbacks = {"gItemIcon_QuestionMark", "gItemIcon_ReturnToFieldArrow",
                 "gItemIconPalette_QuestionMark", "gItemIconPalette_ReturnToFieldArrow"}
    for rid, (sym, art) in icon_ids.items():
        if sym in fallbacks:
            continue  # shared fallbacks stay compiled on native (not records)
        key = hashlib.sha256(b"gen3-resource-id-v1\x00" + rid.encode()).hexdigest()
        enc = "gba-lz77"
        data = open(f"{root}/{art}", "rb").read()
        if data[0] & 0x0F == 0 and len(data) >= 4:
            dec = data[1] | (data[2] << 8) | (data[3] << 16)
        else:
            enc = "raw"
            dec = len(data)
        encoded_len = len(data)
        src_sha = hashlib.sha256(data).hexdigest()
        own.append("[[resources]]")
        own.append(f'id = "{rid}"')
        own.append(f'key = "{key}"')
        own.append(f'legacy_symbol = "{sym}"')
        own.append('type = "tile-graphics"')
        own.append("schema = 1")
        own.append(f'source_artifact = "{art}"')
        own.append(f'encoded_length = {encoded_len}')
        own.append(f'decoded_length = {dec}')
        own.append(f'source_encoding = "{enc}"')
        own.append(f'source_encoded_sha256 = "{src_sha}"')
        own.append(f'canonical_decoded_sha256 = "{canon.get(rid, "")}"')
        own.append('ownership_state = "ROM_BASE_ONLY"')
        own.append("")
        own.append("[resources.targets]")
        own.append('native = "ROM_BASE_ONLY"')
        own.append('gba = "COMPILED"')
    for rid, (sym, art) in palette_ids.items():
        if sym in fallbacks:
            continue  # shared fallbacks stay compiled on native (not records)
        key = hashlib.sha256(b"gen3-resource-id-v1\x00" + rid.encode()).hexdigest()
        enc = "gba-lz77"
        data = open(f"{root}/{art}", "rb").read()
        if data[0] & 0x0F == 0 and len(data) >= 4:
            dec = data[1] | (data[2] << 8) | (data[3] << 16)
        else:
            enc = "raw"
            dec = len(data)
        encoded_len = len(data)
        src_sha = hashlib.sha256(data).hexdigest()
        own.append("[[resources]]")
        own.append(f'id = "{rid}"')
        own.append(f'key = "{key}"')
        own.append(f'legacy_symbol = "{sym}"')
        own.append('type = "palette"')
        own.append("schema = 1")
        own.append(f'source_artifact = "{art}"')
        own.append(f'encoded_length = {encoded_len}')
        own.append(f'decoded_length = {dec}')
        own.append(f'source_encoding = "{enc}"')
        own.append(f'source_encoded_sha256 = "{src_sha}"')
        own.append(f'canonical_decoded_sha256 = "{canon.get(rid, "")}"')
        own.append('ownership_state = "ROM_BASE_ONLY"')
        own.append("")
        own.append("[resources.targets]")
        own.append('native = "ROM_BASE_ONLY"')
        own.append('gba = "COMPILED"')

    # --- inventory ---
    inv = ["# Generated by tools/gen3_resources/item_icon_family/gen_item_icon.py",
           "# Do not edit by hand; regeneration must be a no-op diff.",
           "inventory_version = 1",
           'family = "item_icon"',
           'game = "emerald"',
           'rom_profile = "bpee01-rev0"', ""]
    for rid, (sym, art) in all_ids.items():
        inv.append("[[resources]]")
        inv.append(f'symbol = "{sym}"')
        inv.append(f'source_artifact = "{art}"')
        inv.append(f'canonical_id = "{rid}"')
        inv.append("")
    for item, icon, pal in table_rows:
        icon_rid = None
        pal_rid = None
        for rid, (sym, _) in all_ids.items():
            if sym == icon:
                icon_rid = rid
            if sym == pal:
                pal_rid = rid
        inv.append("[[table_slots]]")
        inv.append(f'item = "{item}"')
        inv.append(f'icon = "{icon_rid}"')
        inv.append(f'palette = "{pal_rid}"')

    # Write files
    for name, lines in [("catalog.generated.toml", cat),
                         ("bindings.generated.toml", bin_),
                         ("ownership.generated.toml", own),
                         ("inventory.generated.toml", inv)]:
        with open(f"{out_dir}/{name}", "w") as f:
            f.write("\n".join(lines) + "\n")
    print(f"Emitted {len(all_ids)} resources to {out_dir}")

    # --- native compat slot map (C header) ---
    # Build a resource index map: icon resources first, then palette resources
    idx_of = {}
    idx = 0
    for rid in icon_ids:
        idx_of[rid] = idx
        idx += 1
    for rid in palette_ids:
        idx_of[rid] = idx
        idx += 1

    h = ["/* Generated by tools/gen3_resources/item_icon_family/gen_item_icon.py",
         " * Do not edit by hand; regeneration must be a no-op diff.",
         " *",
         " * R15 Phase 5: native compat slot map for the item-icon table.",
         " * kItemIconSlots maps each ITEM_* row to its icon + palette",
         " * resource indices. */",
         "#ifndef EMERALD_RESOURCES_ITEM_ICON_SLOTS_GENERATED_H",
         "#define EMERALD_RESOURCES_ITEM_ICON_SLOTS_GENERATED_H",
         "",
         "#include <stdint.h>",
         '#include "gen3/resources/resource_types.h"',
         '#include "emerald/resources/emerald_resource_ranges.h"',
         ""]
    h.append(f"#define ITEM_ICON_RESOURCE_COUNT {len(all_ids)}u")
    h.append(f"#define ITEM_ICON_TABLE_ROWS {len(table_rows)}u")
    h.append("")
    h.append("struct ItemIconResource")
    h.append("{")
    h.append("    const char *id;")
    h.append("    uint32_t expectedSize;")
    h.append("    enum Gen3ResourceType type;")
    h.append("    uint32_t schema;")
    h.append("    uint32_t role;")
    h.append("};")
    h.append("")
    h.append("static const struct ItemIconResource")
    h.append("    kItemIconResources[ITEM_ICON_RESOURCE_COUNT] =")
    h.append("{")
    for rid in icon_ids:
        sym, art = icon_ids[rid]
        data = open(f"{root}/{art}", "rb").read()
        dec = data[1] | (data[2] << 8) | (data[3] << 16)
        h.append(f'    {{ "{rid}", {dec}u, GEN3_RESOURCE_TYPE_TILE_GRAPHICS, 1u, EMERALD_RESOURCE_ROLE_LEGACY_LZ }},')
    for rid in palette_ids:
        sym, art = palette_ids[rid]
        data = open(f"{root}/{art}", "rb").read()
        dec = data[1] | (data[2] << 8) | (data[3] << 16)
        h.append(f'    {{ "{rid}", {dec}u, GEN3_RESOURCE_TYPE_PALETTE, 1u, EMERALD_RESOURCE_ROLE_LEGACY_LZ }},')
    h.append("};")
    h.append("")
    h.append("// kItemIconSlots[item_row * 2 + 0] = icon resource index")
    h.append("// kItemIconSlots[item_row * 2 + 1] = palette resource index")
    h.append("// -1 = not found (fallback to question mark)")
    h.append("static const int32_t kItemIconSlots[ITEM_ICON_TABLE_ROWS * 2] =")
    h.append("{")
    for item, icon, pal in table_rows:
        icon_idx = -1
        pal_idx = -1
        for rid, (sym, _) in all_ids.items():
            if sym == icon:
                icon_idx = idx_of[rid]
            if sym == pal:
                pal_idx = idx_of[rid]
        h.append(f"    {icon_idx}, {pal_idx}, /* {item} */")
    h.append("};")
    h.append("")
    h.append("#endif")
    with open("include/emerald/resources/item_icon_slots.generated.h", "w") as f:
        f.write("\n".join(h) + "\n")
    print("slot map emitted")

    # --- native accessor macros ---
    a = ["/* Generated by tools/gen3_resources/item_icon_family/gen_item_icon.py",
         " * Do not edit by hand; regeneration must be a no-op diff.",
         " *",
         " * R15 Phase 5: on native every legacy item-icon symbol name redirects",
         " * to the compat seam accessor; on GBA the names stay the real INCBIN",
         " * arrays. */"]
    a.append("#if defined(NATIVE_LINUX)")
    a.append('#include "emerald/resources/emerald_item_icon_compat.h"')
    for rid, (sym, art) in all_ids.items():
        if sym in fallbacks:
            continue  # compiled fallbacks keep their real arrays on native
        a.append(f'#define {sym} ItemIcon_Get("{rid}")')
    a.append("#endif")
    with open("include/emerald/resources/item_icon_accessors.generated.h", "w") as f:
        f.write("\n".join(a) + "\n")
    print("accessor macros emitted")

if __name__ == "__main__":
    main()