#!/usr/bin/env python3
"""R15 UI family: generate ownership.generated.toml from the committed
production manifest.

Every canonical UI record is ROM_BASE_ONLY: its payload is pack-served and
must be absent from the native link. Two fork-diverged resources stay
compiled on native by design (NATIVE_DIVERGENCE) and are therefore NOT
records here, mirroring the R9 §6 external-slot policy:

    gNamingScreenCursor_Gfx   (fork-extended cursor graphics)
    gPokedexBgHoenn_Pal       (fork-diverged Hoenn dex palette)

Usage: gen_ui_ownership.py [--check]
"""
import re
import sys

ROOT = "/home/tristen/work/pokeemerald-recomp"
MANIFEST = f"{ROOT}/resources/extraction/emerald/bpee01/ui/manifest.production.toml"
OWNERSHIP = f"{ROOT}/resources/extraction/emerald/bpee01/ui/ownership.generated.toml"

# Fork-diverged resources that stay compiled on native (R9 §6 policy:
# external slots are not ownership records).
NATIVE_DIVERGENCE = {"gNamingScreenCursor_Gfx", "gPokedexBgHoenn_Pal"}

# Cross-family slots: these payloads are also declared by the tileset
# family (emerald:tileset-anim/..., emerald:tileset/...) whose native seam
# keeps the legacy symbol as a session-published array. Their native
# lifecycle is owned by that family; the UI manifest duplicates are pack
# records only and are not UI ownership records (R9 §6 policy).
CROSS_FAMILY_SEAM = {
    "gTilesetAnims_BattleDomePals0_0",
    "gTilesetAnims_BattleDomePals0_1",
    "gTilesetAnims_BattleDomePals0_2",
    "gTilesetAnims_BattleDomePals0_3",
    "gTilesetTiles_General",
}

HEADER = """# Generated by R15 UI family generator (unified)
# Do not edit by hand; regenerate with gen_ui_ownership.py --check.
#
# Every record is ROM_BASE_ONLY: the canonical payload is pack-served and
# must be absent from the native link. The two fork-diverged resources
# that stay compiled on native by design (gNamingScreenCursor_Gfx,
# gPokedexBgHoenn_Pal) are NOT records here (R9 §6 external-slot policy).
ownership_version = 1
game = "emerald"
rom_profile = "bpee01-rev0"
"""


def parse_manifest():
    records = []
    text = open(MANIFEST).read()
    for block in text.split("[[records]]")[1:]:
        rec = {}
        for m in re.finditer(r'(\w+) = "([^"]*)"|\b(\w+) = (\d+)', block):
            if m.group(1):
                rec[m.group(1)] = m.group(2)
            else:
                rec[m.group(3)] = int(m.group(4))
        if "symbol" in rec:
            records.append(rec)
    return records


def source_artifact_map():
    """legacy symbol -> INCBIN artifact path, from the checked-in C
    definitions (src/graphics.c and src/data/graphics/pokemon.h)."""
    import glob
    artifacts = {}
    for c in glob.glob(f"{ROOT}/src/**/*.c", recursive=True) + \
            glob.glob(f"{ROOT}/src/**/*.h", recursive=True):
        for m in re.finditer(
            r'const\s+\w+\s+(\w+)\[\]\s*=\s*INCBIN_\w+\("([^"]+)"\);',
            open(c).read()):
            artifacts[m.group(1)] = m.group(2)
    return artifacts


def main():
    check = "--check" in sys.argv
    records = parse_manifest()
    artifacts = source_artifact_map()
    kept = [r for r in records
            if r["symbol"] not in NATIVE_DIVERGENCE
            and r["symbol"] not in CROSS_FAMILY_SEAM]
    missing = [r["symbol"] for r in kept if r["symbol"] not in artifacts]
    if missing:
        raise SystemExit(f"no INCBIN artifact path for: {missing}")
    out = [HEADER]
    for r in kept:
        out.append("[[resources]]\n")
        out.append(f"id = \"{r['id']}\"\n")
        out.append(f"key = \"{r['key']}\"\n")
        out.append(f"legacy_symbol = \"{r['symbol']}\"\n")
        out.append(f"type = \"{r['type']}\"\n")
        out.append(f"schema = {r['schema']}\n")
        out.append(f"source_artifact = \"{artifacts[r['symbol']]}\"\n")
        out.append(f"encoded_length = {r['encoded_length']}\n")
        out.append(f"decoded_length = {r['decoded_length']}\n")
        out.append(f"source_encoding = \"{r['source_encoding']}\"\n")
        out.append(f"source_encoded_sha256 = \"{r['source_encoded_sha256']}\"\n")
        out.append(f"canonical_decoded_sha256 = \"{r['canonical_decoded_sha256']}\"\n")
        out.append('ownership_state = "ROM_BASE_ONLY"\n')
        out.append("\n[resources.targets]\n")
        out.append('native = "ROM_BASE_ONLY"\n')
        out.append('gba = "COMPILED"\n')
    generated = "".join(out)
    if check:
        current = open(OWNERSHIP).read()
        if current != generated:
            raise SystemExit("ownership.generated.toml differs from generator output")
        print("gen_ui_ownership --check: byte-identical")
        return
    open(OWNERSHIP, "w").write(generated)
    print(f"regenerated: {len(kept)} ROM_BASE_ONLY records "
          f"({len(records)} manifest records, "
          f"{len(records) - len(kept)} divergence/cross-family excluded)")


if __name__ == "__main__":
    main()
