/* Generated by tools/gen3_resources/battle_family/h4_generate.py.
 * Do not edit by hand; re-run the generator (regeneration must
 * be a no-op diff).
 *
 * R13-H4 production live table: battle-anim + field-effect
 * arenas, relocs and semantic bindings. Family/arena enum
 * values come from battle_native.generated.h so the state
 * adapter's surface identities line up unchanged.
 */

#ifndef EMERALD_RESOURCES_BATTLE_LIVE_GENERATED_H
#define EMERALD_RESOURCES_BATTLE_LIVE_GENERATED_H

#include <stdint.h>
#include "emerald/resources/battle_native.generated.h"

#define EMERALD_BATTLE_LIVE_ARENA_COUNT 3u
#define EMERALD_BATTLE_LIVE_MODULE_COUNT 1371u
#define EMERALD_BATTLE_LIVE_PAYLOAD_MODULE_COUNT 1363u
#define EMERALD_BATTLE_LIVE_ALIAS_COUNT 8u
#define EMERALD_BATTLE_LIVE_BOUNDARY_COUNT 13446u
#define EMERALD_BATTLE_LIVE_EXPORT_ROW_COUNT 1391u
#define EMERALD_BATTLE_LIVE_RELOC_COUNT 5963u
#define EMERALD_BATTLE_LIVE_BINDING_COUNT 718u
#define EMERALD_BATTLE_LIVE_REFUSE_ONLY_BINDING_COUNT 4u
#define EMERALD_BATTLE_LIVE_SCRIPT_TARGET_WORD_COUNT 1172u
#define EMERALD_BATTLE_LIVE_CANONICAL_BYTES 78220u
#define EMERALD_BATTLE_LIVE_LAYOUT_COUNT 2u
#define EMERALD_BATTLE_LIVE_ROUTING_COUNT 5u
#define EMERALD_BATTLE_LIVE_LABEL_COUNT 199u
#define EMERALD_BATTLE_LIVE_GRAMMAR_ENTRY_COUNT 300u

struct EmeraldBattleLiveGrammarEntry
{
    uint8_t opcode;
    uint8_t size;
    uint8_t operandCount;
    uint8_t widths[4];
};

/* Battle routing tables (H1 sec 6): the canonical GBA address of
 * each pointer-bearing routing module. The live seam reads the
 * arena-owned rows; the compiled tables are dead at runtime. */
enum EmeraldBattleLiveRouting
{
    EMERALD_BATTLE_ROUTING_MOVEEFFECTS = 0u, /* emerald:battle-script/g-battle-scripts-for-move-effects @ 0x82d86a8 */
    EMERALD_BATTLE_ROUTING_BALLTHROW = 1u, /* emerald:battle-script/g-battlescripts-for-ball-throw @ 0x82dbd08 */
    EMERALD_BATTLE_ROUTING_USINGITEM = 2u, /* emerald:battle-script/g-battlescripts-for-using-item @ 0x82dbd3c */
    EMERALD_BATTLE_ROUTING_RUNNINGBYITEM = 3u, /* emerald:battle-script/g-battlescripts-for-running-by-item @ 0x82dbd54 */
    EMERALD_BATTLE_ROUTING_SAFARIACTIONS = 4u, /* emerald:battle-script/g-battlescripts-for-safari-actions @ 0x82dbd58 */
};

enum EmeraldBattleLiveRelocClass
{
    EMERALD_BATTLE_LIVE_RELOC_SCRIPT_TARGET = 0u,
    EMERALD_BATTLE_LIVE_RELOC_ENGINE_SPRITE_TEMPLATE_TARGET = 1u,
    EMERALD_BATTLE_LIVE_RELOC_ENGINE_CALLBACK = 2u,
    EMERALD_BATTLE_LIVE_RELOC_ENGINE_GFX_TARGET = 3u,
    EMERALD_BATTLE_LIVE_RELOC_ENGINE_TABLE_TARGET = 4u,
    EMERALD_BATTLE_LIVE_RELOC_ENGINE_EWRAM_TARGET = 5u,
};

struct EmeraldBattleLiveArena
{
    uint32_t family; /* EmeraldBattleNativeFamily */
    uint32_t schema;
    uint32_t gbaStart;
    uint32_t gbaEnd; /* exclusive */
    uint32_t hullBytes;
    uint32_t layoutSize[EMERALD_BATTLE_LIVE_LAYOUT_COUNT];
    uint32_t layoutOffset[EMERALD_BATTLE_LIVE_LAYOUT_COUNT];
    /* within the combined live buffer */
    uint32_t moduleFirst;
    uint32_t moduleCount;
};

struct EmeraldBattleLiveModule
{
    const char *id;
    uint8_t key[32];
    uint32_t schema;
    uint32_t family; /* EmeraldBattleNativeFamily */
    uint32_t arena; /* index into table.arenas */
    uint32_t gbaStart;
    uint32_t byteCount;
    uint8_t digest[32];
    uint32_t layoutOffset[EMERALD_BATTLE_LIVE_LAYOUT_COUNT];
    /* arena-relative */
    uint32_t boundaryFirst;
    uint32_t boundaryCount;
    uint32_t exportFirst;
    uint32_t exportCount;
    uint32_t relocFirst;
    uint32_t relocCount;
    uint32_t mapKind; /* EmeraldBattleNativeMapKind */
};

struct EmeraldBattleLiveAlias
{
    const char *id;
    uint32_t family;
    uint32_t ownerModule; /* canonical payload owner */
    uint32_t gbaStart;
};

struct EmeraldBattleLiveBinding
{
    const char *name;
    uint8_t letter; /* 'A'..'F' */
    uint32_t word; /* stored word (base + addend for 'A') */
    uintptr_t address; /* native host address; 0 = refuse-only */
    uint32_t baseWord; /* 'A': encoded base value; else = word */
    uint32_t addend; /* 'A': validated field offset */
    uint32_t allowedOffset; /* 'A': ELF size bound */
};

struct EmeraldBattleLiveLabel
{
    const char *name;
    uint32_t word; /* canonical GBA address of the root */
    uint32_t module; /* payload module index */
    uint32_t offset; /* payload offset of the export */
};

struct EmeraldBattleLiveReloc
{
    uint32_t module; /* payload module index */
    uint32_t operandOffset;
    uint32_t expectedWord;
    uint16_t relocClass; /* EmeraldBattleLiveRelocClass */
    uint16_t width;
    uint32_t target; /* SCRIPT_TARGET: module index;
                       ENGINE_*: binding index */
    uint32_t targetOffset; /* SCRIPT_TARGET only */
};

struct EmeraldBattleLiveTable
{
    uint32_t moduleCount;
    uint32_t payloadModuleCount;
    uint32_t aliasCount;
    uint32_t arenaCount;
    uint32_t boundaryCount;
    uint32_t exportRowCount;
    uint32_t relocCount;
    uint32_t bindingCount;
    uint32_t refuseOnlyBindingCount;
    uint32_t scriptTargetWordCount;
    uint32_t canonicalBytes;
    uint32_t labelCount;
    const struct EmeraldBattleLiveArena *arenas;
    const struct EmeraldBattleLiveModule *modules;
    const struct EmeraldBattleNativeBoundary *boundaries;
    const struct EmeraldBattleNativeExport *exports;
    const struct EmeraldBattleLiveAlias *aliases;
    const struct EmeraldBattleLiveReloc *relocs;
    const struct EmeraldBattleLiveBinding *bindings;
    const uint32_t *scriptTargetWords;
    const struct EmeraldBattleLiveLabel *labels;
    const struct EmeraldBattleLiveGrammarEntry *grammar;
};

extern const struct EmeraldBattleLiveTable kEmeraldBattleLiveTable;

/* Native-address accessors (battle_live_native.generated.c;
 * production-linked). Return 0 for out-of-range / non-native
 * rows. */
uintptr_t EmeraldBattleLiveNative_BindingAddress(uint32_t index);
uintptr_t EmeraldBattleLiveNative_LabelAddress(uint32_t index);

#endif /* EMERALD_RESOURCES_BATTLE_LIVE_GENERATED_H */
