/* Generated by tools/gen3_resources/battle_family/h3_generate.py.
 * Do not edit by hand; re-run the generator (regeneration must
 * be a no-op diff).
 *
 * R13-H3 shadow seam + state adapter compilation table, derived
 * from the R13-H2 sidecars. Physical layouts are generation
 * choices; semantic identity (family/module/offset) is not.
 */

#ifndef EMERALD_RESOURCES_BATTLE_NATIVE_GENERATED_H
#define EMERALD_RESOURCES_BATTLE_NATIVE_GENERATED_H

#include <stdint.h>

#define EMERALD_BATTLE_FAMILY_COUNT 5u
#define EMERALD_BATTLE_MODULE_COUNT 2089u
#define EMERALD_BATTLE_PAYLOAD_MODULE_COUNT 2081u
#define EMERALD_BATTLE_ALIAS_COUNT 8u
#define EMERALD_BATTLE_BOUNDARY_COUNT 15861u
#define EMERALD_BATTLE_EXPORT_ROW_COUNT 2109u
#define EMERALD_BATTLE_CANONICAL_BYTES 90047u
#define EMERALD_BATTLE_LAYOUT_COUNT 2u

enum EmeraldBattleNativeFamily
{
    EMERALD_BATTLE_FAMILY_BATTLE_SCRIPT = 0u,
    EMERALD_BATTLE_FAMILY_BATTLE_ANIM_SCRIPT = 1u,
    EMERALD_BATTLE_FAMILY_BATTLE_AI = 2u,
    EMERALD_BATTLE_FAMILY_CONTEST_AI = 3u,
    EMERALD_BATTLE_FAMILY_FIELD_EFFECT_SCRIPT = 4u,
};

enum EmeraldBattleNativeMapKind
{
    EMERALD_BATTLE_MAP_BYTECODE = 0,
    EMERALD_BATTLE_MAP_DATA = 1,
    EMERALD_BATTLE_MAP_ROUTING = 2,
    EMERALD_BATTLE_MAP_EMPTY = 3,
};

enum EmeraldBattleNativeExportKind
{
    EMERALD_BATTLE_EXPORT_OFFSET_ZERO = 0,
    EMERALD_BATTLE_EXPORT_ALIAS = 1,
};

struct EmeraldBattleNativeBoundary
{
    uint32_t payloadOffset;
    uint32_t length;
};

struct EmeraldBattleNativeExport
{
    uint32_t payloadOffset;
    uint8_t kind; /* EmeraldBattleNativeExportKind */
};

struct EmeraldBattleNativeArena
{
    const char *name;
    uint32_t gbaStart;
    uint32_t gbaEnd; /* exclusive */
    uint32_t hullBytes;
    uint32_t layoutSize[EMERALD_BATTLE_LAYOUT_COUNT];
    uint32_t layoutOffset[EMERALD_BATTLE_LAYOUT_COUNT];
    uint32_t holeFirst;
    uint32_t holeCount;
};

struct EmeraldBattleNativeModule
{
    const char *id;
    uint8_t key[32];
    uint32_t schema;
    uint32_t family; /* EmeraldBattleNativeFamily */
    uint32_t arena;
    uint32_t gbaStart;
    uint32_t byteCount;
    uint8_t digest[32];
    uint32_t layoutOffset[EMERALD_BATTLE_LAYOUT_COUNT];
    uint32_t boundaryFirst;
    uint32_t boundaryCount;
    uint32_t exportFirst;
    uint32_t exportCount;
    uint32_t mapKind; /* EmeraldBattleNativeMapKind */
};

struct EmeraldBattleNativeAlias
{
    const char *id;
    uint32_t family;
    uint32_t ownerModule; /* canonical payload owner */
    uint32_t gbaStart;
};

struct EmeraldBattleNativeHole
{
    uint32_t arena;
    uint32_t gbaStart;
    uint32_t length;
};

struct EmeraldBattleNativeFamilyInfo
{
    const char *name;
    const char *prefix;
    uint32_t schema;
};

struct EmeraldBattleNativeTable
{
    uint32_t moduleCount;
    uint32_t payloadModuleCount;
    uint32_t aliasCount;
    uint32_t boundaryCount;
    uint32_t exportRowCount;
    uint32_t arenaCount;
    const struct EmeraldBattleNativeFamilyInfo *families;
    const struct EmeraldBattleNativeArena *arenas;
    const struct EmeraldBattleNativeModule *modules;
    const struct EmeraldBattleNativeBoundary *boundaries;
    const struct EmeraldBattleNativeExport *exports;
    const struct EmeraldBattleNativeAlias *aliases;
    const struct EmeraldBattleNativeHole *holes;
};

extern const struct EmeraldBattleNativeTable kEmeraldBattleCompatTable;

#endif /* EMERALD_RESOURCES_BATTLE_NATIVE_GENERATED_H */
