/* Generated by tools/gen3_resources/gameplay_family/gen_gameplay_family.py.
 * Do not edit by hand; re-run the generator and --check it.
 *
 * R13-E3a-1 frontier publication maps and constants. The frontier seam
 * rebuilds the native Battle Frontier trainer/mon tables into their
 * HOST_DATA fill targets (frontier_data_native.c) from the pack.
 * kFrontierTrainerKeys[i] is the 52-byte GBA trainer metadata row;
 * kFrontierMonSetKeys[i] its 0xFFFF-terminated u16 index stream into
 * the shared 882-row gBattleFrontierMons pool (the seam validates each
 * row's GBA monSet pointer resolves to its leaf and every index is in
 * range, then rebuilds the native monSet into its mon-set arena).
 */
#ifndef EMERALD_RESOURCES_FRONTIER_NATIVE_GENERATED_H
#define EMERALD_RESOURCES_FRONTIER_NATIVE_GENERATED_H

#include <stdint.h>

#define EMERALD_FRONTIER_SCHEMA_TRAINER     21u
#define EMERALD_FRONTIER_SCHEMA_MON_SET     22u
#define EMERALD_FRONTIER_SCHEMA_MON         23u
#define EMERALD_FRONTIER_SCHEMA_HELD_ITEMS 24u
#define EMERALD_FRONTIER_SCHEMA_BANNED     25u
#define EMERALD_FRONTIER_TRAINER_COUNT      300u
#define EMERALD_FRONTIER_MONS_COUNT        882u
#define EMERALD_FRONTIER_HELDITEMS_COUNT     63u
#define EMERALD_FRONTIER_BANNED_COUNT        11u
#define EMERALD_FRONTIER_TENT_TRAINER_COUNT 30u
#define EMERALD_FRONTIER_TENT_SLATEPORT_MONS    70u
#define EMERALD_FRONTIER_TENT_VERDANTURF_MONS   45u
#define EMERALD_FRONTIER_TENT_FALLARBOR_MONS    45u
#define EMERALD_FRONTIER_MON_WIRE 16u
#define EMERALD_FRONTIER_MON_NATIVE 14u
#define EMERALD_FRONTIER_TRAINER_WIRE 52u
#define EMERALD_FRONTIER_TRAINER_NATIVE 56u

enum FrontierTentTag
{
    FRONTIER_TENT_SLATEPORT = 0,
    FRONTIER_TENT_VERDANTURF = 1,
    FRONTIER_TENT_FALLARBOR = 2,
    FRONTIER_TENT_COUNT_ = 3,
};

/* frontier trainer index -> metadata resource key */
extern const char *const kFrontierTrainerKeys[EMERALD_FRONTIER_TRAINER_COUNT];
/* frontier trainer index -> mon-set leaf resource key */
extern const char *const kFrontierMonSetKeys[EMERALD_FRONTIER_TRAINER_COUNT];
extern const char *const kFrontierMonsKey;
extern const char *const kFrontierHeldItemsKey;
extern const char *const kFrontierBannedSpeciesKey;
/* tent (slateport/verdanturf/fallarbor) trainer index -> keys */
extern const char *const kFrontierTentTrainerKeys[3][EMERALD_FRONTIER_TENT_TRAINER_COUNT];
extern const char *const kFrontierTentMonSetKeys[3][EMERALD_FRONTIER_TENT_TRAINER_COUNT];
extern const char *const kFrontierTentMonsKeys[3];

#endif /* EMERALD_RESOURCES_FRONTIER_NATIVE_GENERATED_H */
