/* Generated by tools/gen3_resources/gameplay_family/gen_gameplay_family.py.
 * Do not edit by hand; re-run the generator and --check it.
 *
 * R13-E3a-2 frontier facility AUX publication maps. The frontier seam
 * rebuilds the Battle Factory/Palace/Arena/Pike/Pyramid/Brain/Apprentice native tables + the pike/pyramid wild-encounter handoff from
 * the pack. kFrontierAux* arrays pair each facility table with its
 * resource key; the wild info table carries the header->info->slot edge
 * metadata (rates + GBA address linkage) the seam validates then rebuilds
 * into its own packed wild slot/info arena.
 */
#ifndef EMERALD_RESOURCES_FRONTIER_AUX_NATIVE_GENERATED_H
#define EMERALD_RESOURCES_FRONTIER_AUX_NATIVE_GENERATED_H

#include <stdint.h>

#define EMERALD_FRONTIER_AUX_SCHEMA_FACTORY        26u
#define EMERALD_FRONTIER_AUX_SCHEMA_PALACE         27u
#define EMERALD_FRONTIER_AUX_SCHEMA_ARENA          28u
#define EMERALD_FRONTIER_AUX_SCHEMA_PIKE_NPC       29u
#define EMERALD_FRONTIER_AUX_SCHEMA_PIKE_SPEECH    30u
#define EMERALD_FRONTIER_AUX_SCHEMA_PYRAMID_FLOOR 31u
#define EMERALD_FRONTIER_AUX_SCHEMA_PYRAMID_ITEM  32u
#define EMERALD_FRONTIER_AUX_SCHEMA_PYRAMID_SLOTS 33u
#define EMERALD_FRONTIER_AUX_SCHEMA_BRAIN         34u
#define EMERALD_FRONTIER_AUX_SCHEMA_APPRENTICE    35u
#define EMERALD_FRONTIER_AUX_SCHEMA_WILD_HEADERS  36u
#define EMERALD_FRONTIER_AUX_SCHEMA_WILD          37u

#define EMERALD_FRONTIER_AUX_PIKE_NPC_SLOTS     25u   /* 25 rows GBA 8 B -> native 6 B */
#define EMERALD_FRONTIER_AUX_PIKE_NPC_WIRE      8u
#define EMERALD_FRONTIER_AUX_PIKE_NPC_NATIVE    6u
#define EMERALD_FRONTIER_AUX_PYRAMID_FLOOR_SLOTS 16u /* 16 rows GBA 16 B -> native 13 B */
#define EMERALD_FRONTIER_AUX_PYRAMID_FLOOR_WIRE 16u
#define EMERALD_FRONTIER_AUX_PYRAMID_FLOOR_NATIVE 13u
#define EMERALD_FRONTIER_AUX_APPRENTICE_ROWS    16u  /* 16 rows GBA 88 B -> native 86 B */
#define EMERALD_FRONTIER_AUX_APPRENTICE_WIRE    88u
#define EMERALD_FRONTIER_AUX_APPRENTICE_NATIVE  86u
#define EMERALD_FRONTIER_AUX_BRAIN_MONS        42u  /* FrontierBrainMon 20 B, GBA==native */
#define EMERALD_FRONTIER_AUX_BRAIN_MONS_WIRE    20u
#define EMERALD_FRONTIER_AUX_WILD_SLOT_ROWS     12u  /* WildPokemon 4 B/row */
#define EMERALD_FRONTIER_AUX_WILD_SLOT_WIRE      4u
#define EMERALD_FRONTIER_AUX_WILD_INFO_WIRE      8u
#define EMERALD_FRONTIER_AUX_PIKE_WILD_SETS      4u
#define EMERALD_FRONTIER_AUX_PYRAMID_WILD_SETS   7u
#define EMERALD_FRONTIER_AUX_WILD_INFO_COUNT   11u

extern const char *const kFrontierAuxFactoryMoves[7];
extern const char *const kFrontierAuxPalaceEarlyKey;
extern const char *const kFrontierAuxPalaceLateKey;
extern const char *const kFrontierAuxArenaShortKey;
extern const char *const kFrontierAuxArenaLongKey;
extern const char *const kFrontierAuxPikeNpcKey;
extern const char *const kFrontierAuxPikeSpeeches[3];
extern const char *const kFrontierAuxPikeWildMons[8];
extern const char *const kFrontierAuxPyramidFloor[2];
extern const char *const kFrontierAuxPyramidItemKey;
extern const char *const kFrontierAuxPyramidSlotsKey;
extern const char *const kFrontierAuxBrainIdsKey;
extern const char *const kFrontierAuxBrainMonsKey;
extern const char *const kFrontierAuxBrainStreakKey;
extern const char *const kFrontierAuxApprenticeKeys[16];
extern const char *const kFrontierAuxPikeWildHeadersKey;
extern const char *const kFrontierAuxPyramidWildHeadersKey;

/* wild slot-set metadata: rate + header->info->slot GBA address linkage */
struct FrontierWildInfoMeta
{
    const char *key;
    uint16_t rate;
    uint16_t slotRows;
    uint32_t gbaInfoAddr;
    uint32_t gbaSlotAddr;
};
extern const struct FrontierWildInfoMeta kFrontierAuxPikeWildInfos[4];
extern const struct FrontierWildInfoMeta kFrontierAuxPyramidWildInfos[7];

#endif /* EMERALD_RESOURCES_FRONTIER_AUX_NATIVE_GENERATED_H */
