/* Generated by tools/gen3_resources/gameplay_family/gen_gameplay_family.py.
 * Do not edit by hand; re-run the generator and --check it.
 *
 * R13-D1 seam inventory for the gameplay-data families. Enumerates
 * every canonical resource the production pack publishes for the
 * D1 species/move/shared/font families, with the canonical id, the
 * native fill-target symbol, canonical size and the family schema.
 * The gameplay seam (EmeraldGameplayCompat) validates the session's
 * pack against this exact table (name/size/schema set equality)
 * before computing any fill -- a missing entry, a size/schema
 * drift, or an unexpected extra is a REFUSED publication.
 */
#ifndef EMERALD_RESOURCES_GAMEPLAY_NATIVE_GENERATED_H
#define EMERALD_RESOURCES_GAMEPLAY_NATIVE_GENERATED_H

#include <stdint.h>

#define GAMEPLAY_NATIVE_RESOURCE_COUNT 8438u
#define GAMEPLAY_NATIVE_SPECIES_COUNT 412u
#define GAMEPLAY_NATIVE_TRAINER_COUNT 855u
#define GAMEPLAY_NATIVE_CLASS_COUNT 66u
#define GAMEPLAY_NATIVE_TRAINER_PARTY_COUNT 854u

struct GameplayNativeResource
{
    const char *name;         /* canonical resource id */
    const char *legacySymbol; /* native fill-target symbol */
    uint32_t size;            /* canonical payload bytes */
    uint8_t schema;           /* D1 family schema code */
};

extern const struct GameplayNativeResource kGameplayNativeResources[GAMEPLAY_NATIVE_RESOURCE_COUNT];

/* species index -> levelup resource canonical key (shared leaf:
 * SPECIES_NONE points at bulbasaur's leaf). The seam rebuilds the
 * native gLevelUpLearnsets pointer table from this map. */
extern const char *const kGameplayLevelupSpeciesKeys[GAMEPLAY_NATIVE_SPECIES_COUNT];

/* species index -> base species resource key (emerald:data/species/
 * <name>); sub-keys add /name, /tmhm, /tutor, /egg-moves. */
extern const char *const kGameplaySpeciesKeys[GAMEPLAY_NATIVE_SPECIES_COUNT];
/* move index -> base move resource key (emerald:data/move/<name>);
 * sub-keys add /name, /contest. */
#ifndef GAMEPLAY_NATIVE_MOVE_COUNT
#define GAMEPLAY_NATIVE_MOVE_COUNT 355u
#endif
extern const char *const kGameplayMoveKeys[GAMEPLAY_NATIVE_MOVE_COUNT];

/* item index -> item resource key (emerald:data/item/<name>). */
#ifndef GAMEPLAY_NATIVE_ITEM_COUNT
#define GAMEPLAY_NATIVE_ITEM_COUNT 377u
#endif
extern const char *const kGameplayItemKeys[GAMEPLAY_NATIVE_ITEM_COUNT];

#endif /* EMERALD_RESOURCES_GAMEPLAY_NATIVE_GENERATED_H */
