/* Generated by tools/gen3_resources/gameplay_family/gen_gameplay_family.py.
 * Do not edit by hand; re-run the generator and --check it.
 *
 * R13-D2 item-use callback registry. Every distinct GBA use-function
 * address across the 377 gItems rows, mapped to a stable semantic
 * action token. The gameplay seam resolves an item row's two GBA
 * callback addresses (fieldUseFunc/battleUseFunc) through this table
 * and maps the action to a native ItemUseFunc via the compiled seam
 * table (gameplay_item_callbacks_native.c). The pack resource NEVER
 * stores a native function pointer: it holds the exact 44-byte ROM
 * row (GBA addresses included) and the seam does the validation +
 * resolution.
 */
#ifndef EMERALD_RESOURCES_GAMEPLAY_CALLBACKS_GENERATED_H
#define EMERALD_RESOURCES_GAMEPLAY_CALLBACKS_GENERATED_H

#include <stdint.h>

#define GAMEPLAY_ITEM_CALLBACK_COUNT 27u

enum GameplayItemUseAction
{
    GAMEPLAY_ITEM_USE_ACTION_OUTOFBATTLE_MAIL = 0,
    GAMEPLAY_ITEM_USE_ACTION_OUTOFBATTLE_BIKE = 1,
    GAMEPLAY_ITEM_USE_ACTION_OUTOFBATTLE_ROD = 2,
    GAMEPLAY_ITEM_USE_ACTION_OUTOFBATTLE_ITEMFINDER = 3,
    GAMEPLAY_ITEM_USE_ACTION_OUTOFBATTLE_POKEBLOCKCASE = 4,
    GAMEPLAY_ITEM_USE_ACTION_OUTOFBATTLE_COINCASE = 5,
    GAMEPLAY_ITEM_USE_ACTION_OUTOFBATTLE_POWDERJAR = 6,
    GAMEPLAY_ITEM_USE_ACTION_OUTOFBATTLE_WAILMERPAIL = 7,
    GAMEPLAY_ITEM_USE_ACTION_OUTOFBATTLE_MEDICINE = 8,
    GAMEPLAY_ITEM_USE_ACTION_OUTOFBATTLE_REDUCEEV = 9,
    GAMEPLAY_ITEM_USE_ACTION_OUTOFBATTLE_SACREDASH = 10,
    GAMEPLAY_ITEM_USE_ACTION_OUTOFBATTLE_PPRECOVERY = 11,
    GAMEPLAY_ITEM_USE_ACTION_OUTOFBATTLE_PPUP = 12,
    GAMEPLAY_ITEM_USE_ACTION_OUTOFBATTLE_RARECANDY = 13,
    GAMEPLAY_ITEM_USE_ACTION_OUTOFBATTLE_TMHM = 14,
    GAMEPLAY_ITEM_USE_ACTION_OUTOFBATTLE_REPEL = 15,
    GAMEPLAY_ITEM_USE_ACTION_OUTOFBATTLE_BLACKWHITEFLUTE = 16,
    GAMEPLAY_ITEM_USE_ACTION_OUTOFBATTLE_ESCAPEROPE = 17,
    GAMEPLAY_ITEM_USE_ACTION_OUTOFBATTLE_EVOLUTIONSTONE = 18,
    GAMEPLAY_ITEM_USE_ACTION_INBATTLE_POKEBALL = 19,
    GAMEPLAY_ITEM_USE_ACTION_INBATTLE_STATINCREASE = 20,
    GAMEPLAY_ITEM_USE_ACTION_INBATTLE_MEDICINE = 21,
    GAMEPLAY_ITEM_USE_ACTION_INBATTLE_PPRECOVERY = 22,
    GAMEPLAY_ITEM_USE_ACTION_INBATTLE_ESCAPE = 23,
    GAMEPLAY_ITEM_USE_ACTION_OUTOFBATTLE_ENIGMABERRY = 24,
    GAMEPLAY_ITEM_USE_ACTION_INBATTLE_ENIGMABERRY = 25,
    GAMEPLAY_ITEM_USE_ACTION_OUTOFBATTLE_CANNOTUSE = 26,
    GAMEPLAY_ITEM_USE_ACTION_COUNT,
};

struct GameplayItemCallback
{
    uint32_t gbaAddr;       /* reference GBA function address */
    uint32_t action;        /* enum GameplayItemUseAction */
    const char *symbol;     /* reference pret symbol name */
};

extern const struct GameplayItemCallback kGameplayItemCallbacks[GAMEPLAY_ITEM_CALLBACK_COUNT];

#endif /* EMERALD_RESOURCES_GAMEPLAY_CALLBACKS_GENERATED_H */
