/* Generated by tools/gen3_resources/leaf_family/gen_leaf_family.py.
 * Do not edit by hand; re-run the generator and --check it
 * (tests/gen3_resources/run_r13b_leaf.sh).
 *
 * R13-B seam slot table for the leaf payload families. The table
 * enumerates every canonical resource the pack publishes (the
 * shared movement set + the two multiboot programs) with its
 * canonical id, the compiled native symbol, canonical payload size
 * and schema (1 = movement, 2 = multiboot). R13-B is additive-
 * only: every entry stays COMPILED_PENDING_MIGRATION and no
 * consumer is redirected; the seam (EmeraldLeafCompat) publishes
 * the arena after validating the session against this exact
 * inventory. The 3 recomp-local movement labels
 * (Ferry_DepartIsland*, Route103_RivalExitFacingNorth2, 12 B) and
 * the pret-only union objects are not resources and are not
 * listed. The table DEFINITION is emitted separately as
 * src/emerald/resources/leaf_native_table.generated.c.
 */
#ifndef EMERALD_RESOURCES_LEAF_NATIVE_GENERATED_H
#define EMERALD_RESOURCES_LEAF_NATIVE_GENERATED_H

#include <stdint.h>

#define LEAF_NATIVE_MOVEMENT_COUNT 1055u
#define LEAF_NATIVE_MULTIBOOT_COUNT 2u
#define LEAF_NATIVE_RESOURCE_COUNT 1057u

struct LeafNativeResource
{
    const char *name;         /* canonical resource id, e.g. 
                                 emerald:movement/<canonical> */
    const char *legacySymbol; /* compiled native symbol (recomp 
                                 naming; differs from the pret name
                                 only for the ereader multiboot 
                                 program) */
    uint32_t size;            /* canonical payload bytes */
    uint8_t schema;           /* 1 = movement, 2 = multiboot */
};

extern const struct LeafNativeResource kLeafNativeResources[LEAF_NATIVE_RESOURCE_COUNT];

#endif /* EMERALD_RESOURCES_LEAF_NATIVE_GENERATED_H */