// Generated by tools/gen3_resources/object_event_family/gen_object_event_family.
// Do not edit by hand; edit the object-event inventory and re-run the generator.
// Native-only: the payload leaves are ROM_BASE; the compiled arrays carry
// NULL sentinels and the compat seam publishes session streams.

/* Include-once toggle: define OBJECT_EVENT_NATIVE_DEFINE in exactly one TU
 * (the compat seam) to emit the definitions; every other includer gets
 * the declarations. The initializer is a variadic argument so the
 * commas inside the frame-array braced lists are not macro
 * separators. */
#if defined(OBJECT_EVENT_NATIVE_DEFINE)
#define OE_NATIVE_ARRAY(decl, ...) decl = __VA_ARGS__
#else
#define OE_NATIVE_ARRAY(decl, ...) extern decl
#endif

/* Migrated payload leaves: session-published arrays. */
OE_NATIVE_ARRAY(u32 gObjectEventPic_AguavBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Anabel[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_AquaMemberF[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_AquaMemberM[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Archie[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Artist[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_AspearBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Azumarill[384 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Azurill[384 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_AzurillDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BallCushion[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BaltoyDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Beauty[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BerryTreeDirtPile[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BerryTreeSprout[256 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BigBlastoiseDoll[512 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BigCharizardDoll[512 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BigLaprasDoll[512 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BigRegiceDoll[512 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BigRegirockDoll[512 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BigRegisteelDoll[512 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BigRhydonDoll[512 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BigSnorlaxDoll[512 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BigVenusaurDoll[512 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BigWailmerDoll[512 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BirchsBag[128 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_BirthIslandStone[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BirthIslandStone[512 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BlackBelt[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Boy1[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Boy2[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Boy3[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Brandon[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Brawly[768 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BreakableRock[512 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_Brendan[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BrendanAcroBike[13824 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BrendanDecorating[256 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BrendanFieldMove[2560 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BrendanFishing[6144 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BrendanMachBike[4608 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BrendanNormal[2304 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_BrendanReflection[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BrendanRunning[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BrendanSurfing[3072 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BrendanUnderwater[2048 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BrendanWatering[3072 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_BridgeReflection[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_BugCatcher[2304 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_CableCar[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_CableCar[2048 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Cameraman[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Camper[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_CheriBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_ChestoBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_ChikoritaDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_ClefairyDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_ContestJudge[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Cook[768 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_CornnBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_CuttableTree[512 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_CyclingTriathleteF[4608 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_CyclingTriathleteM[4608 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_CyndaquilDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_Deoxys[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Deoxys[1024 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_DevonEmployee[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_DiamondCushion[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_DittoDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Drake[768 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_DurinBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Dusclops[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_DuskullDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_EnemyZigzagoon[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_EnemyZigzagoon[4608 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_ExpertF[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_ExpertM[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_FatMan[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_FigyBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_FireCushion[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Fisherman[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Flannery[768 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Fossil[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_GameboyKid[768 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Gentleman[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Girl1[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Girl2[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Girl3[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Glacia[768 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_GrassCushion[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_GrepaBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Greta[2304 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_Groudon[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Groudon[2048 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_GroudonReflection[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_GulpinDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_HexManiac[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Hiker[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_HondewBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_HoOh[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_HoOh[1024 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_HotSpringsOldWoman[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_IapapaBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_ItemBall[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_JigglypuffDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Juan[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Kecleon[384 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_KecleonDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_KelpsyBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Kirlia[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_KissCushion[128 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_Kyogre[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Kyogre[2048 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_KyogreReflection[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_LansatBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Lass[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_LatiasLatios[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Leaf[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_LeppaBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_LiechiBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_LinkReceptionist[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_LittleBoy[1152 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_LittleGirl[1152 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Liza[768 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_LotadDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Lucy[2304 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_Lugia[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Lugia[1024 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_LumBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_MagmaMemberF[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_MagmaMemberM[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_MagoBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Man1[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Man2[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Man3[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Man4[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Man5[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Maniac[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_MarillDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_MartEmployee[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_MauvilleOldMan1[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_MauvilleOldMan2[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Maxie[2304 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_May[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_MayAcroBike[13824 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_MayDecorating[256 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_MayFieldMove[2560 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_MayFishing[6144 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_MayMachBike[4608 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_MayNormal[2304 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_MayReflection[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_MayRunning[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_MaySurfing[3072 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_MayUnderwater[2048 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_MayWatering[3072 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_MeowthDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Mew[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Mom[2304 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_MovingBox[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_MovingBox[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_MrBrineysBoat[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_MudkipDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_MysteryEventDeliveryman[768 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_NinjaBoy[1152 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Noland[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_NomelBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Norman[2304 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_Npc1[16], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_Npc1Reflection[16], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_Npc2[16], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_Npc2Reflection[16], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_Npc3[16], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_Npc3Reflection[16], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_Npc4[16], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_Npc4Reflection[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Nurse[1024 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_OldMan[768 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_OldWoman[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_OranBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_PamtreBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_PechaBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_PersimBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Phoebe[768 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_PichuDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Picnicker[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Pikachu[384 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_PikachuDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_PikaCushion[128 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_PlayerUnderwater[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_PokefanF[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_PokefanM[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_PomegBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_Poochyena[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Poochyena[4608 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_ProfBirch[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_PsychicM[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_PushableBoulder[128 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_QuintyPlump[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_QuintyPlump[3584 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_QuintyPlumpReflection[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_RabutaBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_RawstBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Rayquaza[10240 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_RayquazaStill[2048 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_RazzBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Red[2304 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_RedLeaf[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Regi[512 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_ReporterF[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_ReporterM[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_RichBoy[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_RooftopSaleWoman[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_RoundCushion[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Roxanne[768 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_RubySapphireBrendan[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_RubySapphireBrendanNormal[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_RubySapphireBrendanRunning[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_RubySapphireLittleBoy[1152 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_RubySapphireMay[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_RubySapphireMayNormal[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_RubySapphireMayRunning[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_RunningTriathleteF[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_RunningTriathleteM[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Sailor[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_SchoolKidM[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Scientist1[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Scientist2[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Scott[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_SeedotDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Sidney[768 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_SitrusBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Skitty[384 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_SkittyDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_SmoochumDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_SpelonBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Spenser[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_SpinCushion[128 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_SSTidal[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_SSTidal[1920 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Statue[256 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Steven[2304 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_SubmarineShadow[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_SubmarineShadow[1408 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Sudowoodo[768 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_SwabluDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_SwimmerF[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_SwimmerM[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_TamatoBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Tate[768 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Teala[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_TogepiDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_TorchicDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_TotodileDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_TreeckoDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_Truck[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Truck[1152 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_TuberF[1152 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_TuberM[1152 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_TuberMSwimming[1152 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Tucker[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Twin[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_UnionRoomAttendant[768 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_UnusedMagnemiteDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_UnusedNatuDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_UnusedPikachuDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_UnusedPorygon2Doll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_UnusedSquirtleDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_UnusedWoman[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_UnusedWooperDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u16 gObjectEventPal_Vigoroth[16], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Vigoroth[2560 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Wallace[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Wally[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_WaterCushion[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Wattson[768 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_WepearBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_WikiBerryTree[1536 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Wingull[768 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Winona[768 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Woman1[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Woman2[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Woman3[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Woman4[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Woman5[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_WynautDoll[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Youngster[2304 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_ZigzagCushion[128 / 4], {0});
OE_NATIVE_ARRAY(u32 gObjectEventPic_Zigzagoon[384 / 4], {0});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_AguavBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Anabel[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_AquaMemberF[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_AquaMemberM[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Archie[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Artist[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_AspearBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Azumarill[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Azurill[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_AzurillDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_BallCushion[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_BaltoyDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Beauty[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_BigBlastoiseDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_BigCharizardDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_BigLaprasDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_BigRegiceDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_BigRegirockDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_BigRegisteelDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_BigRhydonDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_BigSnorlaxDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_BigVenusaurDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_BigWailmerDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_BirchsBag[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_BirthIslandStone[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_BlackBelt[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Boy1[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Boy2[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Boy3[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Brandon[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Brawly[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_BreakableRock[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_BrendanAcroBike[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_BrendanDecorating[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_BrendanFieldMove[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_BrendanFishing[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_BrendanMachBike[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_BrendanNormal[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_BrendanSurfing[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_BrendanUnderwater[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_BrendanWatering[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_BugCatcher[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_CableCar[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Cameraman[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Camper[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_CheriBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_ChestoBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_ChikoritaDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_ClefairyDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_ContestJudge[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Cook[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_CornnBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_CuttableTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_CyclingTriathleteF[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_CyclingTriathleteM[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_CyndaquilDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Deoxys[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_DevonEmployee[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_DiamondCushion[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_DittoDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Drake[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_DurinBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Dusclops[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_DuskullDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_EnemyZigzagoon[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_ExpertF[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_ExpertM[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_FatMan[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_FigyBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_FireCushion[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Fisherman[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Flannery[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Fossil[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_GameboyKid[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Gentleman[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Girl1[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Girl2[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Girl3[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Glacia[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_GrassCushion[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_GrepaBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Greta[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_GroudonFront[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_GroudonSide[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_GulpinDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_HexManiac[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Hiker[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_HoOh[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_HondewBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_HotSpringsOldWoman[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_IapapaBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_ItemBall[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_JigglypuffDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Juan[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Kecleon[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_KecleonDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_KelpsyBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Kirlia[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_KissCushion[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_KyogreFront[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_KyogreSide[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_LansatBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Lass[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_LatiasLatios[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Leaf[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_LeppaBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_LiechiBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_LinkReceptionist[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_LittleBoy[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_LittleGirl[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Liza[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_LotadDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Lucy[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Lugia[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_LumBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_MagmaMemberF[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_MagmaMemberM[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_MagoBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Man1[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Man2[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Man3[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Man4[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Man5[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Maniac[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_MarillDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_MartEmployee[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_MauvilleOldMan1[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_MauvilleOldMan2[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Maxie[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_MayAcroBike[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_MayDecorating[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_MayFieldMove[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_MayFishing[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_MayMachBike[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_MayNormal[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_MaySurfing[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_MayUnderwater[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_MayWatering[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_MeowthDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Mew[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Mom[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_MovingBox[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_MrBrineysBoat[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_MudkipDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_MysteryEventDeliveryman[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_NinjaBoy[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Noland[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_NomelBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Norman[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Nurse[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_OldMan[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_OldWoman[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_OranBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_PamtreBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_PechaBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_PersimBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Phoebe[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_PichuDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Picnicker[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_PikaCushion[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Pikachu[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_PikachuDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_PokefanF[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_PokefanM[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_PomegBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Poochyena[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_ProfBirch[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_PsychicM[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_PushableBoulder[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_QuintyPlump[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_RabutaBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_RawstBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Rayquaza[],
{
    { .data = NULL, .size = 2048 },
    { .data = NULL, .size = 2048 },
    { .data = NULL, .size = 2048 },
    { .data = NULL, .size = 2048 },
    { .data = NULL, .size = 2048 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_RayquazaStill[],
{
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_RazzBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Red[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Regi[],
{
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_ReporterF[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_ReporterM[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_RichBoy[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_RooftopSaleWoman[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_RoundCushion[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Roxanne[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_RubySapphireBrendan[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_RubySapphireLittleBoy[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_RubySapphireMay[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_RunningTriathleteF[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_RunningTriathleteM[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_SSTidal[],
{
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Sailor[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_SchoolKidM[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Scientist1[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Scientist2[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Scott[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_SeedotDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Sidney[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_SitrusBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Skitty[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_SkittyDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_SmoochumDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_SpelonBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Spenser[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_SpinCushion[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Statue[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Steven[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_SubmarineShadow[],
{
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Sudowoodo[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_SwabluDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_SwimmerF[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_SwimmerM[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_TamatoBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Tate[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Teala[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_TogepiDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_TorchicDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_TotodileDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_TreeckoDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Truck[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_TuberF[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_TuberM[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_TuberMSwimming[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Tucker[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Twin[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_UnionRoomAttendant[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_UnusedMagnemiteDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_UnusedNatuDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_UnusedPikachuDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_UnusedPorygon2Doll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_UnusedSquirtleDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_UnusedWooperDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_VigorothCarryingBox[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_VigorothFacingAway[],
{
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
    { .data = NULL, .size = 512 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Wallace[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Wally[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_WaterCushion[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Wattson[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_WepearBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_WikiBerryTree[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Wingull[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Winona[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Woman1[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Woman2[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Woman3[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Woman4[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Woman5[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_WynautDoll[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Youngster[],
{
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
    { .data = NULL, .size = 256 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_ZigzagCushion[],
{
    { .data = NULL, .size = 0 },
});

OE_NATIVE_ARRAY(struct SpriteFrameImage sPicTable_Zigzagoon[],
{
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
    { .data = NULL, .size = 128 },
});

