/* Generated by tools/gen3_resources/text_family/gen_text_family.py.
 * Do not edit by hand; re-run the generator and --check it.
 *
 * R13-C seam inventory for the emerald:text family. The table
 * enumerates every canonical text resource the production pack
 * publishes (4,844 per-label: 4,824 C-side + 20 mystery-gift, the
 * R13-G2 §7.3 handoff; + 363 bundles) with its canonical id and
 * payload size. The seam (EmeraldTextCompat) validates the
 * session's pack against this exact inventory (name/size/schema
 * set equality) before allocating family arenas - drift is a
 * publish failure, never a partial publication.
 */
#ifndef EMERALD_RESOURCES_TEXT_NATIVE_GENERATED_H
#define EMERALD_RESOURCES_TEXT_NATIVE_GENERATED_H

#include <stdbool.h>
#include <stdint.h>

#define TEXT_NATIVE_RESOURCE_COUNT 5207u
#define TEXT_NATIVE_LABEL_COUNT 4844u
#define TEXT_NATIVE_BUNDLE_COUNT 363u

struct TextNativeResource
{
    const char *name;         /* canonical resource id, e.g. 
                                 emerald:text/battle/s-text-win */
    uint32_t size;            /* canonical payload bytes */
    bool isBundle;            /* constructed blob (no ROM slice) */
    uint32_t arenaIndex;      /* family arena (ARENA_KEYS order) for
                                 per-label resources; 0 (unused) for
                                 bundles - their labels span arenas
                                 (bundle index is authoritative) */
};

extern const struct TextNativeResource kTextNativeResources[TEXT_NATIVE_RESOURCE_COUNT];

#endif /* EMERALD_RESOURCES_TEXT_NATIVE_GENERATED_H */