/* Generated by tools/gen3_resources/text_family/gen_text_family.py.
 * Do not edit by hand; re-run the generator and --check it.
 *
 * R13-C §10 slot bindings: one entry per host-data pointer slot
 * (see text_slots.generated.h) naming the published resource the
 * seam must fill it from at publish. No hand-maintained list.
 */
#ifndef EMERALD_RESOURCES_TEXT_SLOT_BINDINGS_GENERATED_H
#define EMERALD_RESOURCES_TEXT_SLOT_BINDINGS_GENERATED_H

#include <stdint.h>

struct TextSlotBinding
{
    const uint8_t *const *slot;  /* &gText_X (the host slot object) */
    const char *name;       /* full resource id */
};

#define TEXT_SLOT_BINDING_COUNT 3118u

extern const struct TextSlotBinding kTextSlotBindings[TEXT_SLOT_BINDING_COUNT];

#endif /* EMERALD_RESOURCES_TEXT_SLOT_BINDINGS_GENERATED_H */