/* Generated by tools/gen3_resources/text_family/gen_text_family.py.
 * Do not edit by hand; re-run the generator and --check it.
 *
 * R13-C §12 bundle-local label index: stable label-level offsets
 * inside every script bundle blob (future ROM-hack importing can
 * emit targeted overrides); also the sorted bundle id table the
 * seam resolves kind-1 fills through.
 */
#ifndef EMERALD_RESOURCES_TEXT_BUNDLE_INDEX_GENERATED_H
#define EMERALD_RESOURCES_TEXT_BUNDLE_INDEX_GENERATED_H

#include <stdint.h>

struct TextBundleEntry
{
    const char *name;       /* canonical label (lower-dash) */
    uint32_t bundleIndex;   /* index into kTextBundleIds */
    uint32_t blobOffset;    /* byte offset in the bundle blob */
    uint32_t size;          /* canonical bytes (incl. 0xFF) */
    uint32_t arenaIndex;    /* arena (ARENA_KEYS order) */
};

#define TEXT_BUNDLE_ENTRY_COUNT 7953u
#define TEXT_BUNDLE_COUNT 363u

extern const struct TextBundleEntry kTextBundleIndex[TEXT_BUNDLE_ENTRY_COUNT];
extern const char *const kTextBundleIds[TEXT_BUNDLE_COUNT];

#endif /* EMERALD_RESOURCES_TEXT_BUNDLE_INDEX_GENERATED_H */