/* Generated by tools/gen3_resources/text_family/gen_text_family.py.
 * Do not edit by hand; re-run the generator and --check it.
 *
 * R13-C §8/§14 per-family deterministic arenas: 16 summary rows.
 * labelCount is the number of labels (C + bundle-local) packed
 * into the arena; byteTotal is their canonical bytes (incl.
 * 0xFF terminators) before 16-alignment padding.
 */
#ifndef EMERALD_RESOURCES_TEXT_ARENAS_GENERATED_H
#define EMERALD_RESOURCES_TEXT_ARENAS_GENERATED_H

#include <stdint.h>

struct TextArenaSummary
{
    const char *key;
    uint32_t labelCount;
    uint32_t byteTotal;
};

#define TEXT_ARENA_COUNT 16u

extern const struct TextArenaSummary kTextArenaSummaries[TEXT_ARENA_COUNT];

#endif /* EMERALD_RESOURCES_TEXT_ARENAS_GENERATED_H */