/* Generated by tools/gen3_resources/text_family/gen_text_family.py.
 * Do not edit by hand; re-run the generator and --check it.
 *
 * R13-C §10 host arrays: one object per native text-pointer table
 * cut over. Every row is NULL at load; the seam fills the non-NULL
 * rows at publish (per-label rows from the family arenas,
 * bundle-local rows from the bundle blobs, sub-table rows from the
 * target table's own array). The compiled definitions are
 * NATIVE_LINUX-guarded off by the cutover; these externs replace
 * them for every consumer, so old compiled string symbol storage
 * is not required for converted labels (proven by link).
 */
#ifndef EMERALD_RESOURCES_TEXT_SKELETON_ARRAYS_GENERATED_H
#define EMERALD_RESOURCES_TEXT_SKELETON_ARRAYS_GENERATED_H

#include "gba/defines.h"
#include "global.h"
#include "easy_chat.h"
#include "frontier_pass.h"
#include "list_menu.h"
#include "match_call.h"
#include "menu.h"
#include "naming_screen.h"
#include "pokedex.h"
#include "pokemon_storage_system.h"
#include "pokenav.h"
#include "union_room_chat.h"

#ifdef NATIVE_LINUX

extern HOST_DATA const u8 *sMessages_berry_crush[9];
extern HOST_DATA const u8 *sRecordsTexts_dodrio_berry_picking[3];
extern HOST_DATA const u8 *sDeptStoreFloorNames[16];
extern HOST_DATA const u8 *sBattleFrontier_TutorMoveDescriptions1[11];
extern HOST_DATA const u8 *sBattleFrontier_TutorMoveDescriptions2[11];
extern HOST_DATA const u8 *sMalePresetNames[20];
extern HOST_DATA const u8 *sFemalePresetNames[20];
extern HOST_DATA const u8 *sRecordsTexts_pokemon_jump[3];
extern HOST_DATA struct StorageMessage sMessages_pokemon_storage_system[31];
extern HOST_DATA const u8 *sModeStrings[4];
extern HOST_DATA const u8 *sFrontierExchangeCorner_Decor1Descriptions[11];
extern HOST_DATA const u8 *sFrontierExchangeCorner_Decor2Descriptions[6];
extern HOST_DATA const u8 *sFrontierExchangeCorner_VitaminsDescriptions[7];
extern HOST_DATA const u8 *sFrontierExchangeCorner_HoldItemsDescriptions[10];
extern HOST_DATA const u8 *gStatusConditionStringsTable[7][2];
extern HOST_DATA const u8 *gStatNamesTable[8];
extern HOST_DATA const u8 *gPokeblockWasTooXStringTable[5];
extern HOST_DATA const u8 *gBattleStringsTable[369];
extern HOST_DATA const u8 *sStatNamesTable2[6];
extern HOST_DATA const u8 *gRoundsStringTable[4];
extern HOST_DATA const u8 *gRefereeStringsTable[9];
extern HOST_DATA struct MenuAction sMenuActions[6];
extern HOST_DATA const u8 *sResultsTexts[6];
extern HOST_DATA const u8 *sBerryFirmnessStrings[5];
extern HOST_DATA const u8 *sTrainerCardColorNames[4];
extern HOST_DATA const u8 *sContestCategoryNames_Unused[5];
extern HOST_DATA const u8 *sContestRankNames[5];
extern HOST_DATA const u8 *sMuseumCaptions[15];
extern HOST_DATA struct ListMenuItem sLevelMenuItems[3];
extern HOST_DATA const u8 *sCompatibilityMessages[4];
extern HOST_DATA const u8 *sDecorationCategoryNames[8];
extern HOST_DATA struct MenuAction sDecorationMainMenuActions[4];
extern HOST_DATA const u8 *sSecretBasePCMenuItemDescriptions[4];
extern HOST_DATA const u8 *sRankingTexts[5];
extern HOST_DATA struct EasyChatScreenTemplate sEasyChatScreenTemplates[21];
extern HOST_DATA const u8 *sFooterTextOptions[3][4];
extern HOST_DATA const u8 *sEasyChatGroupNamePointers[22];
extern HOST_DATA const u8 *sScrollableMultichoiceOptions[13][16];
extern HOST_DATA const u8 *sPassAreaDescriptions[15];
extern HOST_DATA struct MapLandmark sMapLandmarks[7];
extern HOST_DATA const u8 *sRecordsWindowChallengeTexts[10][2];
extern HOST_DATA const u8 *sLevelModeText[2];
extern HOST_DATA const u8 *sHallFacilityToRecordsText[10];
extern HOST_DATA struct MenuAction sItemMenuActions[15];
extern HOST_DATA struct MenuAction sMenuActions_Gender[2];
extern HOST_DATA struct MatchCallText sMatchCallWildBattleTexts[15];
extern HOST_DATA struct MatchCallText sMatchCallNegativeBattleTexts[14];
extern HOST_DATA struct MatchCallText sMatchCallPositiveBattleTexts[14];
extern HOST_DATA struct MatchCallText sMatchCallSameRouteBattleRequestTexts[14];
extern HOST_DATA struct MatchCallText sMatchCallDifferentRouteBattleRequestTexts[14];
extern HOST_DATA struct MatchCallText sMatchCallPersonalizedTexts[64];
extern HOST_DATA struct MatchCallText sMatchCallBattleFrontierStreakTexts[14];
extern HOST_DATA struct MatchCallText sMatchCallBattleFrontierRecordStreakTexts[14];
extern HOST_DATA struct MatchCallText sMatchCallBattleDomeTexts[14];
extern HOST_DATA struct MatchCallText sMatchCallBattlePikeTexts[14];
extern HOST_DATA struct MatchCallText sMatchCallBattlePyramidTexts[14];
extern HOST_DATA struct MultiTrainerMatchCallText sMultiTrainerMatchCallTexts[6];
extern HOST_DATA const u8 *sBattleFrontierFacilityNames[7];
extern HOST_DATA const u8 *sLvlUpStatStrings[6];
extern HOST_DATA struct ListMenuItem sListMenuItems_CardsOrNews[3];
extern HOST_DATA struct ListMenuItem sListMenuItems_WirelessOrFriend[3];
extern HOST_DATA struct ListMenuItem sListMenuItems_ReceiveSendToss[4];
extern HOST_DATA struct ListMenuItem sListMenuItems_ReceiveToss[3];
extern HOST_DATA struct ListMenuItem sListMenuItems_ReceiveSend[3];
extern HOST_DATA struct ListMenuItem sListMenuItems_Receive[2];
extern HOST_DATA const u8 *sUnusedMenuTexts[4];
extern HOST_DATA const u8 *sTransferredToPCMessages[4];
extern HOST_DATA struct NamingScreenTemplate sPlayerNamingScreenTemplate;
extern HOST_DATA struct NamingScreenTemplate sPCBoxNamingTemplate;
extern HOST_DATA struct NamingScreenTemplate sMonNamingScreenTemplate;
extern HOST_DATA struct NamingScreenTemplate sWaldaWordsScreenTemplate;
extern HOST_DATA const u8 *sOptionMenuItemsNames[8];
extern HOST_DATA const u8 *sItemStorage_OptionDescriptions[4];
extern HOST_DATA struct MenuAction sPlayerPCMenuActions[4];
extern HOST_DATA struct MenuAction sItemStorage_MenuActions[4];
extern HOST_DATA struct MenuAction gMailboxMailOptions[4];
extern HOST_DATA const u8 *gPokeblockNames[15];
extern HOST_DATA struct MenuAction sPokeblockMenuActions[6];
extern HOST_DATA struct SearchMenuTopBarItem sSearchMenuTopBarItems[3];
extern HOST_DATA struct SearchMenuItem sSearchMenuItems[7];
extern HOST_DATA struct SearchOptionText sDexModeOptions[3];
extern HOST_DATA struct SearchOptionText sDexOrderOptions[7];
extern HOST_DATA struct SearchOptionText sDexSearchNameOptions[11];
extern HOST_DATA struct SearchOptionText sDexSearchColorOptions[12];
extern HOST_DATA struct SearchOptionText sDexSearchTypeOptions[19];
extern HOST_DATA struct MainMenuText sMainMenuTexts[5];
extern HOST_DATA const u8 *sMenuTexts[39];
extern HOST_DATA const u8 *sHelpBarTexts[12];
extern HOST_DATA struct MatchCallCheckPageOverride sCheckPageOverrides[4];
extern HOST_DATA struct MatchCallStructNPC sMrStoneMatchCallHeader;
extern HOST_DATA struct MatchCallStructTrainer sNormanMatchCallHeader;
extern HOST_DATA struct MatchCallBirch sProfBirchMatchCallHeader;
extern HOST_DATA struct MatchCallStructNPC sMomMatchCallHeader;
extern HOST_DATA struct MatchCallStructNPC sStevenMatchCallHeader;
extern HOST_DATA struct MatchCallRival sMayMatchCallHeader;
extern HOST_DATA struct MatchCallRival sBrendanMatchCallHeader;
extern HOST_DATA struct MatchCallWally sWallyMatchCallHeader;
extern HOST_DATA struct MatchCallStructNPC sScottMatchCallHeader;
extern HOST_DATA struct MatchCallStructTrainer sRoxanneMatchCallHeader;
extern HOST_DATA struct MatchCallStructTrainer sBrawlyMatchCallHeader;
extern HOST_DATA struct MatchCallStructTrainer sWattsonMatchCallHeader;
extern HOST_DATA struct MatchCallStructTrainer sFlanneryMatchCallHeader;
extern HOST_DATA struct MatchCallStructTrainer sWinonaMatchCallHeader;
extern HOST_DATA struct MatchCallStructTrainer sTateLizaMatchCallHeader;
extern HOST_DATA struct MatchCallStructTrainer sJuanMatchCallHeader;
extern HOST_DATA struct MatchCallStructTrainer sSidneyMatchCallHeader;
extern HOST_DATA struct MatchCallStructTrainer sPhoebeMatchCallHeader;
extern HOST_DATA struct MatchCallStructTrainer sGlaciaMatchCallHeader;
extern HOST_DATA struct MatchCallStructTrainer sDrakeMatchCallHeader;
extern HOST_DATA struct MatchCallStructTrainer sWallaceMatchCallHeader;
extern HOST_DATA struct MatchCallTextDataStruct sMrStoneTextScripts[12];
extern HOST_DATA struct MatchCallTextDataStruct sNormanTextScripts[10];
extern HOST_DATA struct MatchCallTextDataStruct sMomTextScripts[4];
extern HOST_DATA struct MatchCallTextDataStruct sStevenTextScripts[8];
extern HOST_DATA struct MatchCallTextDataStruct sMayTextScripts[16];
extern HOST_DATA struct MatchCallTextDataStruct sBrendanTextScripts[16];
extern HOST_DATA struct MatchCallTextDataStruct sWallyTextScripts[8];
extern HOST_DATA struct MatchCallTextDataStruct sScottTextScripts[8];
extern HOST_DATA struct MatchCallTextDataStruct sRoxanneTextScripts[5];
extern HOST_DATA struct MatchCallTextDataStruct sBrawlyTextScripts[5];
extern HOST_DATA struct MatchCallTextDataStruct sWattsonTextScripts[5];
extern HOST_DATA struct MatchCallTextDataStruct sFlanneryTextScripts[5];
extern HOST_DATA struct MatchCallTextDataStruct sWinonaTextScripts[5];
extern HOST_DATA struct MatchCallTextDataStruct sTateLizaTextScripts[5];
extern HOST_DATA struct MatchCallTextDataStruct sJuanTextScripts[5];
extern HOST_DATA struct MatchCallTextDataStruct sSidneyTextScripts[2];
extern HOST_DATA struct MatchCallTextDataStruct sPhoebeTextScripts[2];
extern HOST_DATA struct MatchCallTextDataStruct sGlaciaTextScripts[2];
extern HOST_DATA struct MatchCallTextDataStruct sDrakeTextScripts[2];
extern HOST_DATA struct MatchCallTextDataStruct sWallaceTextScripts[2];
extern HOST_DATA const u8 *sMatchCallOptionTexts[3];
extern HOST_DATA const u8 *sPageDescriptions[14];
extern HOST_DATA const u8 *sEverGrandeCityNames[2];
extern HOST_DATA struct MenuAction sRegistryMenuActions[2];
extern HOST_DATA struct MenuAction sShopMenuActions_BuySellQuit[3];
extern HOST_DATA struct MenuAction sShopMenuActions_BuyQuit[2];
extern HOST_DATA const u8 *sPyramidFloorNames[8];
extern HOST_DATA struct MenuAction sStartMenuItems[13];
extern HOST_DATA const u8 *gBagMenu_ReturnToStrings[12];
extern HOST_DATA const u8 *gPyramidBagMenu_ReturnToStrings[4];
extern HOST_DATA const u8 *gPocketNamesStringsTable[5];
extern HOST_DATA const u8 *gTextTable_Players[4];
extern HOST_DATA const u8 *sDefaultTraderNames[4];
extern HOST_DATA const u8 *sLinkBattleTexts[3];
extern HOST_DATA const u8 *sFloorStrings[4];
extern HOST_DATA struct MessageWindowInfo sDisplayStdMessages[11];
extern HOST_DATA struct MenuAction sKeyboardPageTitleTexts[5];
extern HOST_DATA const u8 *sConditionNames[5];
extern HOST_DATA const u8 *sHeaderTexts[5];
extern HOST_DATA const u8 *gAbilityDescriptionPointers[78];
extern HOST_DATA const u8 *gGiftRibbonDescriptionPointers[64][2];
extern HOST_DATA const u8 *gMatchCallFlavorTexts[78][4];
extern HOST_DATA const u8 *gMoveDescriptionPointers[354];
extern HOST_DATA const u8 *gNatureNamePointers[25];
extern HOST_DATA const u8 *gRibbonDescriptionPointers[25][2];
extern HOST_DATA const u8 *gContestEffectDescriptionPointers[48];
extern HOST_DATA const u8 *sUnusedComboMoveNameTexts[14];
extern HOST_DATA const u8 *gContestMoveTypeTextPointers[5];
extern HOST_DATA const u8 *sUnusedAppealResultTexts[13];
extern HOST_DATA const u8 *sRoundResultTexts[32];
extern HOST_DATA const u8 *sAppealResultTexts[62];
extern HOST_DATA const u8 *sContestConditions[5];
extern HOST_DATA const u8 *sInvalidContestMoveNames[6];
extern HOST_DATA struct MenuAction MultichoiceList_BrineyOnDewford[3];
extern HOST_DATA struct MenuAction MultichoiceList_EnterInfo[3];
extern HOST_DATA struct MenuAction MultichoiceList_ContestInfo[4];
extern HOST_DATA struct MenuAction MultichoiceList_ContestType[6];
extern HOST_DATA struct MenuAction MultichoiceList_BasePCWithRegistry[4];
extern HOST_DATA struct MenuAction MultichoiceList_BasePCNoRegistry[3];
extern HOST_DATA struct MenuAction MultichoiceList_RegisterMenu[4];
extern HOST_DATA struct MenuAction MultichoiceList_Bike[2];
extern HOST_DATA struct MenuAction MultichoiceList_StatusInfo[6];
extern HOST_DATA struct MenuAction MultichoiceList_BrineyOffDewford[2];
extern HOST_DATA struct MenuAction MultichoiceList_ViewedPaintings[2];
extern HOST_DATA struct MenuAction MultichoiceList_YesNoInfo2[3];
extern HOST_DATA struct MenuAction MultichoiceList_ChallengeInfo[3];
extern HOST_DATA struct MenuAction MultichoiceList_LevelMode[3];
extern HOST_DATA struct MenuAction MultichoiceList_Mechadoll1_Q1[3];
extern HOST_DATA struct MenuAction MultichoiceList_Mechadoll1_Q2[3];
extern HOST_DATA struct MenuAction MultichoiceList_Mechadoll1_Q3[3];
extern HOST_DATA struct MenuAction MultichoiceList_Mechadoll2_Q1[3];
extern HOST_DATA struct MenuAction MultichoiceList_Mechadoll2_Q2[3];
extern HOST_DATA struct MenuAction MultichoiceList_Mechadoll2_Q3[3];
extern HOST_DATA struct MenuAction MultichoiceList_Mechadoll3_Q1[3];
extern HOST_DATA struct MenuAction MultichoiceList_Mechadoll3_Q2[3];
extern HOST_DATA struct MenuAction MultichoiceList_Mechadoll3_Q3[3];
extern HOST_DATA struct MenuAction MultichoiceList_Mechadoll4_Q1[3];
extern HOST_DATA struct MenuAction MultichoiceList_Mechadoll4_Q2[3];
extern HOST_DATA struct MenuAction MultichoiceList_Mechadoll4_Q3[3];
extern HOST_DATA struct MenuAction MultichoiceList_Mechadoll5_Q1[3];
extern HOST_DATA struct MenuAction MultichoiceList_Mechadoll5_Q2[3];
extern HOST_DATA struct MenuAction MultichoiceList_Mechadoll5_Q3[3];
extern HOST_DATA struct MenuAction MultichoiceList_VendingMachine[4];
extern HOST_DATA struct MenuAction MultichoiceList_MachBikeInfo[4];
extern HOST_DATA struct MenuAction MultichoiceList_AcroBikeInfo[4];
extern HOST_DATA struct MenuAction MultichoiceList_Satisfaction[2];
extern HOST_DATA struct MenuAction MultichoiceList_SternDeepSea[3];
extern HOST_DATA struct MenuAction MultichoiceList_UnusedAshVendor[8];
extern HOST_DATA struct MenuAction MultichoiceList_GameCornerDolls[4];
extern HOST_DATA struct MenuAction MultichoiceList_GameCornerTMs[6];
extern HOST_DATA struct MenuAction MultichoiceList_GameCornerCoins[3];
extern HOST_DATA struct MenuAction MultichoiceList_HowsFishing[2];
extern HOST_DATA struct MenuAction MultichoiceList_SSTidalSlateportWithBF[3];
extern HOST_DATA struct MenuAction MultichoiceList_SSTidalBattleFrontier[3];
extern HOST_DATA struct MenuAction MultichoiceList_RightLeft[2];
extern HOST_DATA struct MenuAction MultichoiceList_SSTidalSlateportNoBF[2];
extern HOST_DATA struct MenuAction MultichoiceList_Floors[6];
extern HOST_DATA struct MenuAction MultichoiceList_ShardsR[2];
extern HOST_DATA struct MenuAction MultichoiceList_ShardsY[2];
extern HOST_DATA struct MenuAction MultichoiceList_ShardsRY[3];
extern HOST_DATA struct MenuAction MultichoiceList_ShardsB[2];
extern HOST_DATA struct MenuAction MultichoiceList_ShardsRB[3];
extern HOST_DATA struct MenuAction MultichoiceList_ShardsYB[3];
extern HOST_DATA struct MenuAction MultichoiceList_ShardsRYB[4];
extern HOST_DATA struct MenuAction MultichoiceList_ShardsG[2];
extern HOST_DATA struct MenuAction MultichoiceList_ShardsRG[3];
extern HOST_DATA struct MenuAction MultichoiceList_ShardsYG[3];
extern HOST_DATA struct MenuAction MultichoiceList_ShardsRYG[4];
extern HOST_DATA struct MenuAction MultichoiceList_ShardsBG[3];
extern HOST_DATA struct MenuAction MultichoiceList_ShardsRBG[4];
extern HOST_DATA struct MenuAction MultichoiceList_ShardsYBG[4];
extern HOST_DATA struct MenuAction MultichoiceList_ShardsRYBG[5];
extern HOST_DATA struct MenuAction MultichoiceList_TourneyWithRecord[6];
extern HOST_DATA struct MenuAction MultichoiceList_TourneyNoRecord[5];
extern HOST_DATA struct MenuAction MultichoiceList_Tent[2];
extern HOST_DATA struct MenuAction MultichoiceList_LinkServicesNoBerry[4];
extern HOST_DATA struct MenuAction MultichoiceList_YesNoInfo[3];
extern HOST_DATA struct MenuAction MultichoiceList_BattleMode[5];
extern HOST_DATA struct MenuAction MultichoiceList_LinkServicesNoRecord[4];
extern HOST_DATA struct MenuAction MultichoiceList_LinkServicesAll[5];
extern HOST_DATA struct MenuAction MultichoiceList_LinkServicesNoRecordBerry[3];
extern HOST_DATA struct MenuAction MultichoiceList_WirelessMinigame[3];
extern HOST_DATA struct MenuAction MultichoiceList_LinkLeader[3];
extern HOST_DATA struct MenuAction MultichoiceList_ContestRank[5];
extern HOST_DATA struct MenuAction MultichoiceList_FrontierItemChoose[3];
extern HOST_DATA struct MenuAction MultichoiceList_LinkContestInfo[4];
extern HOST_DATA struct MenuAction MultichoiceList_LinkContestMode[3];
extern HOST_DATA struct MenuAction MultichoiceList_ForcedStartMenu[8];
extern HOST_DATA struct MenuAction MultichoiceList_FrontierGamblerBet[4];
extern HOST_DATA struct MenuAction MultichoiceList_UnusedSSTidal1[3];
extern HOST_DATA struct MenuAction MultichoiceList_UnusedSSTidal2[3];
extern HOST_DATA struct MenuAction MultichoiceList_UnusedSSTidal3[3];
extern HOST_DATA struct MenuAction MultichoiceList_UnusedSSTidal4[4];
extern HOST_DATA struct MenuAction MultichoiceList_Fossil[3];
extern HOST_DATA struct MenuAction MultichoiceList_YesNo[2];
extern HOST_DATA struct MenuAction MultichoiceList_FrontierRules[6];
extern HOST_DATA struct MenuAction MultichoiceList_FrontierPassInfo[4];
extern HOST_DATA struct MenuAction MultichoiceList_BattleArenaRules[5];
extern HOST_DATA struct MenuAction MultichoiceList_BattleTowerRules[5];
extern HOST_DATA struct MenuAction MultichoiceList_BattleDomeRules[4];
extern HOST_DATA struct MenuAction MultichoiceList_BattleFactoryRules[6];
extern HOST_DATA struct MenuAction MultichoiceList_BattlePalaceRules[6];
extern HOST_DATA struct MenuAction MultichoiceList_BattlePyramidRules[5];
extern HOST_DATA struct MenuAction MultichoiceList_BattlePikeRules[4];
extern HOST_DATA struct MenuAction MultichoiceList_GoOnRecordRestRetire[4];
extern HOST_DATA struct MenuAction MultichoiceList_GoOnRestRetire[3];
extern HOST_DATA struct MenuAction MultichoiceList_GoOnRecordRetire[3];
extern HOST_DATA struct MenuAction MultichoiceList_GoOnRetire[2];
extern HOST_DATA struct MenuAction MultichoiceList_TVLati[2];
extern HOST_DATA struct MenuAction MultichoiceList_BattleTowerFeelings[4];
extern HOST_DATA struct MenuAction MultichoiceList_WheresRayquaza[4];
extern HOST_DATA struct MenuAction MultichoiceList_SlateportTentRules[6];
extern HOST_DATA struct MenuAction MultichoiceList_FallarborTentRules[6];
extern HOST_DATA struct MenuAction MultichoiceList_TagMatchType[5];
extern HOST_DATA struct MenuAction MultichoiceList_Exit[1];
extern HOST_DATA const u8 *gStdStrings[30];
extern HOST_DATA const u8 *sPCNameStrings[4];
extern HOST_DATA const u8 *sLilycoveSSTidalDestinations[7];
extern HOST_DATA const u8 *sActionStringTable[27];
extern HOST_DATA const u8 *sDescriptionStringTable[13];
extern HOST_DATA const u8 *sUnionRoomTradeMessages[9];
extern HOST_DATA const u8 *sUnused_StatStrings[6];
extern HOST_DATA const u8 *sMessages[9];
extern HOST_DATA const u8 *sFavorLadyRequests[6];
extern HOST_DATA const u8 *sContestLadyMonNames[5];
extern HOST_DATA const u8 *sContestLadyCategoryNames[5];
extern HOST_DATA const u8 *sContestNames[5];
extern HOST_DATA struct ListMenuItem sRegisterForTradeListMenuItems[3];
extern HOST_DATA const struct MatchCallText *sMatchCallBattleTopics[3];
extern HOST_DATA const struct MatchCallText *sMatchCallBattleRequestTopics[2];
extern HOST_DATA const struct MatchCallText *sMatchCallGeneralTopics[6];
extern HOST_DATA const struct NamingScreenTemplate *sNamingScreenTemplates[5];
extern HOST_DATA const u8 *gText_123Dot[3];

#endif /* NATIVE_LINUX */
#endif /* EMERALD_RESOURCES_TEXT_SKELETON_ARRAYS_GENERATED_H */