/* Generated by tools/gen3_resources/gameplay_family/gen_gameplay_family.py.
 * Do not edit by hand; re-run the generator and --check it.
 *
 * R13-E1 trainer publication maps. Index-aligned with the native
 * gTrainers table (855 trainers). kGameplayTrainerKeys[i] is the
 * metadata resource key (emerald:data/trainer/<name>);
 * kGameplayTrainerPartyKeys[i] is that trainer's party leaf key
 * (emerald:data/trainer/<name>/party) or "" for the NULL-party
 * TRAINER_NONE row; kGameplayTrainerPartyMeta[i] carries the
 * canonical (partySize, variant) such that the variant equals the
 * row's (partyFlags & 3). kGameplayTrainerClassKeys[c] maps each
 * class index (0..65) to its class-name resource key.
 */
#ifndef EMERALD_RESOURCES_TRAINER_NATIVE_GENERATED_H
#define EMERALD_RESOURCES_TRAINER_NATIVE_GENERATED_H

#include <stdint.h>
#include "emerald/resources/gameplay_native.generated.h"

enum GameplayTrainerPartyVariant
{
    GAMEPLAY_TRAINER_PARTY_NO_ITEM_DEFAULT_MOVES = 0,
    GAMEPLAY_TRAINER_PARTY_NO_ITEM_CUSTOM_MOVES = 1,
    GAMEPLAY_TRAINER_PARTY_ITEM_DEFAULT_MOVES = 2,
    GAMEPLAY_TRAINER_PARTY_ITEM_CUSTOM_MOVES = 3,
};

struct GameplayTrainerPartyMeta
{
    uint8_t partySize;  /* canonical party size (wire partySize) */
    uint8_t variant;    /* enum GameplayTrainerPartyVariant */
};

/* trainer id -> metadata resource key */
extern const char *const kGameplayTrainerKeys[GAMEPLAY_NATIVE_TRAINER_COUNT];
/* trainer id -> party leaf resource key ("" for NULL party) */
extern const char *const kGameplayTrainerPartyKeys[GAMEPLAY_NATIVE_TRAINER_COUNT];
/* trainer id -> canonical (partySize, variant) */
extern const struct GameplayTrainerPartyMeta kGameplayTrainerPartyMeta[GAMEPLAY_NATIVE_TRAINER_COUNT];
/* class index -> class-name resource key */
extern const char *const kGameplayTrainerClassKeys[GAMEPLAY_NATIVE_CLASS_COUNT];

#endif /* EMERALD_RESOURCES_TRAINER_NATIVE_GENERATED_H */
