/* Generated by R15 UI family generator
 * Do not edit by hand.
 *
 * R15: on native every legacy UI symbol name redirects
 * to the compat seam accessor; on GBA the names stay the real INCBIN
 * arrays. Each symbol also carries a <Symbol>_SIZE literal (expected
 * decoded payload size from the slot map) for runtime code that needs
 * the byte size of the payload. */
#if defined(NATIVE_LINUX)
#include "emerald/resources/emerald_ui_compat.h"
#define gBagFemaleTiles ((const u32 *)UI_Get("emerald:ui/bag/gbagfemaletiles"))
#define gBagFemaleTiles_SIZE 12288u
#define gBagMaleTiles ((const u32 *)UI_Get("emerald:ui/bag/gbagmaletiles"))
#define gBagMaleTiles_SIZE 12288u
#define gBagMenuHMIcon_Gfx ((const u8 *)UI_Get("emerald:ui/bag/gbagmenuhmicon_gfx"))
#define gBagMenuHMIcon_Gfx_SIZE 128u
#define gBagPalette ((const u32 *)UI_Get("emerald:ui/bag/gbagpalette"))
#define gBagPalette_SIZE 32u
#define gBagScreenFemale_Pal ((const u32 *)UI_Get("emerald:ui/bag/gbagscreenfemale_pal"))
#define gBagScreenFemale_Pal_SIZE 64u
#define gBagScreenMale_Pal ((const u32 *)UI_Get("emerald:ui/bag/gbagscreenmale_pal"))
#define gBagScreenMale_Pal_SIZE 64u
#define gBagScreen_Gfx ((const u32 *)UI_Get("emerald:ui/bag/gbagscreen_gfx"))
#define gBagScreen_Gfx_SIZE 1696u
#define gBagScreen_GfxTileMap ((const u32 *)UI_Get("emerald:ui/bag/gbagscreen_gfxtilemap"))
#define gBagScreen_GfxTileMap_SIZE 2048u
#define gBattlePyramidBagInterface_Pal ((const u32 *)UI_Get("emerald:ui/bag/gbattlepyramidbaginterface_pal"))
#define gBattlePyramidBagInterface_Pal_SIZE 32u
#define gBattlePyramidBagTilemap ((const u32 *)UI_Get("emerald:ui/bag/gbattlepyramidbagtilemap"))
#define gBattlePyramidBagTilemap_SIZE 2048u
#define gBattlePyramidBag_Gfx ((const u32 *)UI_Get("emerald:ui/bag/gbattlepyramidbag_gfx"))
#define gBattlePyramidBag_Gfx_SIZE 2048u
#define gBattlePyramidBag_Pal ((const u32 *)UI_Get("emerald:ui/bag/gbattlepyramidbag_pal"))
#define gBattlePyramidBag_Pal_SIZE 64u
#define UnusedLevelupAnimationGfx ((const u32 *)UI_Get("emerald:ui/battle_anims/unusedlevelupanimationgfx"))
#define UnusedLevelupAnimationGfx_SIZE 448u
#define UnusedLevelupAnimationTilemap ((const u32 *)UI_Get("emerald:ui/battle_anims/unusedlevelupanimationtilemap"))
#define UnusedLevelupAnimationTilemap_SIZE 2048u
#define gCureBubblesGfx ((const u32 *)UI_Get("emerald:ui/battle_anims/gcurebubblesgfx"))
#define gCureBubblesGfx_SIZE 512u
#define gCureBubblesPal ((const u32 *)UI_Get("emerald:ui/battle_anims/gcurebubblespal"))
#define gCureBubblesPal_SIZE 32u
#define gCureBubblesTilemap ((const u32 *)UI_Get("emerald:ui/battle_anims/gcurebubblestilemap"))
#define gCureBubblesTilemap_SIZE 2048u
#define gMetalShineGfx ((const u32 *)UI_Get("emerald:ui/battle_anims/gmetalshinegfx"))
#define gMetalShineGfx_SIZE 2048u
#define gMetalShinePalette ((const u32 *)UI_Get("emerald:ui/battle_anims/gmetalshinepalette"))
#define gMetalShinePalette_SIZE 32u
#define gMetalShineTilemap ((const u32 *)UI_Get("emerald:ui/battle_anims/gmetalshinetilemap"))
#define gMetalShineTilemap_SIZE 2048u
#define gSmokescreenImpactPalette ((const u32 *)UI_Get("emerald:ui/battle_anims/gsmokescreenimpactpalette"))
#define gSmokescreenImpactPalette_SIZE 32u
#define gSmokescreenImpactTiles ((const u32 *)UI_Get("emerald:ui/battle_anims/gsmokescreenimpacttiles"))
#define gSmokescreenImpactTiles_SIZE 384u
#define gStatAnim_Accuracy_Pal ((const u32 *)UI_Get("emerald:ui/battle_anims/gstatanim_accuracy_pal"))
#define gStatAnim_Accuracy_Pal_SIZE 32u
#define gStatAnim_Attack_Pal ((const u32 *)UI_Get("emerald:ui/battle_anims/gstatanim_attack_pal"))
#define gStatAnim_Attack_Pal_SIZE 32u
#define gStatAnim_Decrease_Tilemap ((const u32 *)UI_Get("emerald:ui/battle_anims/gstatanim_decrease_tilemap"))
#define gStatAnim_Decrease_Tilemap_SIZE 2048u
#define gStatAnim_Defense_Pal ((const u32 *)UI_Get("emerald:ui/battle_anims/gstatanim_defense_pal"))
#define gStatAnim_Defense_Pal_SIZE 32u
#define gStatAnim_Evasion_Pal ((const u32 *)UI_Get("emerald:ui/battle_anims/gstatanim_evasion_pal"))
#define gStatAnim_Evasion_Pal_SIZE 32u
#define gStatAnim_Gfx ((const u32 *)UI_Get("emerald:ui/battle_anims/gstatanim_gfx"))
#define gStatAnim_Gfx_SIZE 2048u
#define gStatAnim_Increase_Tilemap ((const u32 *)UI_Get("emerald:ui/battle_anims/gstatanim_increase_tilemap"))
#define gStatAnim_Increase_Tilemap_SIZE 2048u
#define gStatAnim_Multiple_Pal ((const u32 *)UI_Get("emerald:ui/battle_anims/gstatanim_multiple_pal"))
#define gStatAnim_Multiple_Pal_SIZE 32u
#define gStatAnim_SpAttack_Pal ((const u32 *)UI_Get("emerald:ui/battle_anims/gstatanim_spattack_pal"))
#define gStatAnim_SpAttack_Pal_SIZE 32u
#define gStatAnim_SpDefense_Pal ((const u32 *)UI_Get("emerald:ui/battle_anims/gstatanim_spdefense_pal"))
#define gStatAnim_SpDefense_Pal_SIZE 32u
#define gStatAnim_Speed_Pal ((const u32 *)UI_Get("emerald:ui/battle_anims/gstatanim_speed_pal"))
#define gStatAnim_Speed_Pal_SIZE 32u
#define gSubstituteDollBackGfx ((const u32 *)UI_Get("emerald:ui/battle_anims/gsubstitutedollbackgfx"))
#define gSubstituteDollBackGfx_SIZE 2048u
#define gSubstituteDollFrontGfx ((const u32 *)UI_Get("emerald:ui/battle_anims/gsubstitutedollfrontgfx"))
#define gSubstituteDollFrontGfx_SIZE 2048u
#define gSubstituteDollPal ((const u32 *)UI_Get("emerald:ui/battle_anims/gsubstitutedollpal"))
#define gSubstituteDollPal_SIZE 32u
#define gUnusedGfx_Goosuto ((const u32 *)UI_Get("emerald:ui/battle_anims/gunusedgfx_goosuto"))
#define gUnusedGfx_Goosuto_SIZE 1536u
#define gUnusedPal_Goosuto ((const u32 *)UI_Get("emerald:ui/battle_anims/gunusedpal_goosuto"))
#define gUnusedPal_Goosuto_SIZE 32u
#define gUnusedTilemap_Goosuto ((const u32 *)UI_Get("emerald:ui/battle_anims/gunusedtilemap_goosuto"))
#define gUnusedTilemap_Goosuto_SIZE 2048u
#define gBattleArenaJudgmentSymbolsGfx ((const u32 *)UI_Get("emerald:ui/battle_frontier/gbattlearenajudgmentsymbolsgfx"))
#define gBattleArenaJudgmentSymbolsGfx_SIZE 512u
#define gBattleArenaJudgmentSymbolsPalette ((const u32 *)UI_Get("emerald:ui/battle_frontier/gbattlearenajudgmentsymbolspalette"))
#define gBattleArenaJudgmentSymbolsPalette_SIZE 32u
#define gDomeTourneyInfoCardBg_Tilemap ((const u32 *)UI_Get("emerald:ui/battle_frontier/gdometourneyinfocardbg_tilemap"))
#define gDomeTourneyInfoCardBg_Tilemap_SIZE 2048u
#define gDomeTourneyInfoCard_Gfx ((const u32 *)UI_Get("emerald:ui/battle_frontier/gdometourneyinfocard_gfx"))
#define gDomeTourneyInfoCard_Gfx_SIZE 16384u
#define gDomeTourneyInfoCard_Tilemap ((const u32 *)UI_Get("emerald:ui/battle_frontier/gdometourneyinfocard_tilemap"))
#define gDomeTourneyInfoCard_Tilemap_SIZE 8192u
#define gDomeTourneyLineDown_Tilemap ((const u32 *)UI_Get("emerald:ui/battle_frontier/gdometourneylinedown_tilemap"))
#define gDomeTourneyLineDown_Tilemap_SIZE 2048u
#define gDomeTourneyLineUp_Tilemap ((const u32 *)UI_Get("emerald:ui/battle_frontier/gdometourneylineup_tilemap"))
#define gDomeTourneyLineUp_Tilemap_SIZE 2048u
#define gDomeTourneyLine_Gfx ((const u32 *)UI_Get("emerald:ui/battle_frontier/gdometourneyline_gfx"))
#define gDomeTourneyLine_Gfx_SIZE 8192u
#define gDomeTourneyMatchCardBg_Pal ((const u32 *)UI_Get("emerald:ui/battle_frontier/gdometourneymatchcardbg_pal"))
#define gDomeTourneyMatchCardBg_Pal_SIZE 32u
#define gDomeTourneyTreeButtons_Gfx ((const u32 *)UI_Get("emerald:ui/battle_frontier/gdometourneytreebuttons_gfx"))
#define gDomeTourneyTreeButtons_Gfx_SIZE 1536u
#define gDomeTourneyTreeButtons_Pal ((const u32 *)UI_Get("emerald:ui/battle_frontier/gdometourneytreebuttons_pal"))
#define gDomeTourneyTreeButtons_Pal_SIZE 512u
#define gDomeTourneyTree_Gfx ((const u32 *)UI_Get("emerald:ui/battle_frontier/gdometourneytree_gfx"))
#define gDomeTourneyTree_Gfx_SIZE 8192u
#define gDomeTourneyTree_Pal ((const u32 *)UI_Get("emerald:ui/battle_frontier/gdometourneytree_pal"))
#define gDomeTourneyTree_Pal_SIZE 512u
#define gDomeTourneyTree_Tilemap ((const u32 *)UI_Get("emerald:ui/battle_frontier/gdometourneytree_tilemap"))
#define gDomeTourneyTree_Tilemap_SIZE 2048u
#define gFrontierFactoryMenu_Gfx ((const u16 *)UI_Get("emerald:ui/battle_frontier/gfrontierfactorymenu_gfx"))
#define gFrontierFactoryMenu_Gfx_SIZE 1088u
#define gFrontierFactoryMenu_Pal ((const u16 *)UI_Get("emerald:ui/battle_frontier/gfrontierfactorymenu_pal"))
#define gFrontierFactoryMenu_Pal_SIZE 64u
#define gFrontierFactoryMenu_Tilemap ((const u16 *)UI_Get("emerald:ui/battle_frontier/gfrontierfactorymenu_tilemap"))
#define gFrontierFactoryMenu_Tilemap_SIZE 2048u
#define gMultiBattleIntroBg_Opponent_Tilemap ((const u32 *)UI_Get("emerald:ui/battle_frontier/gmultibattleintrobg_opponent_tilemap"))
#define gMultiBattleIntroBg_Opponent_Tilemap_SIZE 4096u
#define gMultiBattleIntroBg_Player_Tilemap ((const u32 *)UI_Get("emerald:ui/battle_frontier/gmultibattleintrobg_player_tilemap"))
#define gMultiBattleIntroBg_Player_Tilemap_SIZE 4096u
#define gBattleInterfaceGfx_BattleBar ((const u32 *)UI_Get("emerald:ui/battle_interface/gbattleinterfacegfx_battlebar"))
#define gBattleInterfaceGfx_BattleBar_SIZE 1312u
#define gBattleInterfaceGfx_UnusedWindow1 ((const u32 *)UI_Get("emerald:ui/battle_interface/gbattleinterfacegfx_unusedwindow1"))
#define gBattleInterfaceGfx_UnusedWindow1_SIZE 8192u
#define gBattleInterfaceGfx_UnusedWindow2 ((const u32 *)UI_Get("emerald:ui/battle_interface/gbattleinterfacegfx_unusedwindow2"))
#define gBattleInterfaceGfx_UnusedWindow2_SIZE 4096u
#define gBattleInterfaceGfx_UnusedWindow2Bar ((const u32 *)UI_Get("emerald:ui/battle_interface/gbattleinterfacegfx_unusedwindow2bar"))
#define gBattleInterfaceGfx_UnusedWindow2Bar_SIZE 160u
#define gBattleInterfaceGfx_UnusedWindow3 ((const u32 *)UI_Get("emerald:ui/battle_interface/gbattleinterfacegfx_unusedwindow3"))
#define gBattleInterfaceGfx_UnusedWindow3_SIZE 1536u
#define gBattleInterfaceGfx_UnusedWindow4 ((const u32 *)UI_Get("emerald:ui/battle_interface/gbattleinterfacegfx_unusedwindow4"))
#define gBattleInterfaceGfx_UnusedWindow4_SIZE 4096u
#define gBattleInterfacePal_UnusedWindow1 ((const u32 *)UI_Get("emerald:ui/battle_interface/gbattleinterfacepal_unusedwindow1"))
#define gBattleInterfacePal_UnusedWindow1_SIZE 32u
#define gBattleInterface_BallDisplayPal ((const u16 *)UI_Get("emerald:ui/battle_interface/gbattleinterface_balldisplaypal"))
#define gBattleInterface_BallDisplayPal_SIZE 32u
#define gBattleInterface_BallStatusBarGfx ((const u32 *)UI_Get("emerald:ui/battle_interface/gbattleinterface_ballstatusbargfx"))
#define gBattleInterface_BallStatusBarGfx_SIZE 512u
#define gBattleInterface_BallStatusBarPal ((const u16 *)UI_Get("emerald:ui/battle_interface/gbattleinterface_ballstatusbarpal"))
#define gBattleInterface_BallStatusBarPal_SIZE 32u
#define gBattleTextboxPalette ((const u32 *)UI_Get("emerald:ui/battle_interface/gbattletextboxpalette"))
#define gBattleTextboxPalette_SIZE 64u
#define gBattleTextboxTilemap ((const u32 *)UI_Get("emerald:ui/battle_interface/gbattletextboxtilemap"))
#define gBattleTextboxTilemap_SIZE 4096u
#define gBattleTextboxTiles ((const u32 *)UI_Get("emerald:ui/battle_interface/gbattletextboxtiles"))
#define gBattleTextboxTiles_SIZE 8192u
#define gBattleWindowTextPalette ((const u32 *)UI_Get("emerald:ui/battle_interface/gbattlewindowtextpalette"))
#define gBattleWindowTextPalette_SIZE 32u
#define gEnemyMonShadow_Gfx ((const u32 *)UI_Get("emerald:ui/battle_interface/genemymonshadow_gfx"))
#define gEnemyMonShadow_Gfx_SIZE 128u
#define gHealthboxDoublesOpponentGfx ((const u32 *)UI_Get("emerald:ui/battle_interface/ghealthboxdoublesopponentgfx"))
#define gHealthboxDoublesOpponentGfx_SIZE 2048u
#define gHealthboxSafariGfx ((const u32 *)UI_Get("emerald:ui/battle_interface/ghealthboxsafarigfx"))
#define gHealthboxSafariGfx_SIZE 4096u
#define gHealthboxSinglesOpponentGfx ((const u32 *)UI_Get("emerald:ui/battle_interface/ghealthboxsinglesopponentgfx"))
#define gHealthboxSinglesOpponentGfx_SIZE 2048u
#define gHealthboxSinglesPlayerGfx ((const u32 *)UI_Get("emerald:ui/battle_interface/ghealthboxsinglesplayergfx"))
#define gHealthboxSinglesPlayerGfx_SIZE 4096u
#define gPPTextPalette ((const u16 *)UI_Get("emerald:ui/battle_interface/gpptextpalette"))
#define gPPTextPalette_SIZE 32u
#define gUnusedHpBar_Gfx ((const u32 *)UI_Get("emerald:ui/battle_interface/gunusedhpbar_gfx"))
#define gUnusedHpBar_Gfx_SIZE 384u
#define gBattleVSFrame_Gfx ((const u32 *)UI_Get("emerald:ui/battle_transitions/gbattlevsframe_gfx"))
#define gBattleVSFrame_Gfx_SIZE 512u
#define gBattleVSFrame_Pal ((const u32 *)UI_Get("emerald:ui/battle_transitions/gbattlevsframe_pal"))
#define gBattleVSFrame_Pal_SIZE 32u
#define gBattleVSFrame_Tilemap ((const u32 *)UI_Get("emerald:ui/battle_transitions/gbattlevsframe_tilemap"))
#define gBattleVSFrame_Tilemap_SIZE 2048u
#define gVsLettersGfx ((const u32 *)UI_Get("emerald:ui/battle_transitions/gvslettersgfx"))
#define gVsLettersGfx_SIZE 4096u
#define gBerryBlenderArrowPalette ((const u16 *)UI_Get("emerald:ui/berry_blender/gberryblenderarrowpalette"))
#define gBerryBlenderArrowPalette_SIZE 32u
#define gBerryBlenderBetaArrow_Gfx ((const u8 *)UI_Get("emerald:ui/berry_blender/gberryblenderbetaarrow_gfx"))
#define gBerryBlenderBetaArrow_Gfx_SIZE 512u
#define gBerryBlenderCenter_Gfx ((const u32 *)UI_Get("emerald:ui/berry_blender/gberryblendercenter_gfx"))
#define gBerryBlenderCenter_Gfx_SIZE 8192u
#define gBerryBlenderCountdownNumbers_Gfx ((const u8 *)UI_Get("emerald:ui/berry_blender/gberryblendercountdownnumbers_gfx"))
#define gBerryBlenderCountdownNumbers_Gfx_SIZE 1536u
#define gBerryBlenderMiscPalette ((const u16 *)UI_Get("emerald:ui/berry_blender/gberryblendermiscpalette"))
#define gBerryBlenderMiscPalette_SIZE 32u
#define gBerryBlenderOuter_Gfx ((const u32 *)UI_Get("emerald:ui/berry_blender/gberryblenderouter_gfx"))
#define gBerryBlenderOuter_Gfx_SIZE 8192u
#define gBerryBlenderOuter_Tilemap ((const u32 *)UI_Get("emerald:ui/berry_blender/gberryblenderouter_tilemap"))
#define gBerryBlenderOuter_Tilemap_SIZE 2048u
#define gBerryBlenderParticles_Gfx ((const u8 *)UI_Get("emerald:ui/berry_blender/gberryblenderparticles_gfx"))
#define gBerryBlenderParticles_Gfx_SIZE 224u
#define gBerryBlenderPlayerArrow_Gfx ((const u8 *)UI_Get("emerald:ui/berry_blender/gberryblenderplayerarrow_gfx"))
#define gBerryBlenderPlayerArrow_Gfx_SIZE 2048u
#define gBerryBlenderScoreSymbols_Gfx ((const u8 *)UI_Get("emerald:ui/berry_blender/gberryblenderscoresymbols_gfx"))
#define gBerryBlenderScoreSymbols_Gfx_SIZE 512u
#define gBerryBlenderStart_Gfx ((const u8 *)UI_Get("emerald:ui/berry_blender/gberryblenderstart_gfx"))
#define gBerryBlenderStart_Gfx_SIZE 1024u
#define gBerryCrush_Crusher_Gfx ((const u32 *)UI_Get("emerald:ui/berry_crush/gberrycrush_crusher_gfx"))
#define gBerryCrush_Crusher_Gfx_SIZE 8192u
#define gBerryCrush_Crusher_Pal ((const u16 *)UI_Get("emerald:ui/berry_crush/gberrycrush_crusher_pal"))
#define gBerryCrush_Crusher_Pal_SIZE 288u
#define gBerryCrush_TextWindows_Tilemap ((const u32 *)UI_Get("emerald:ui/berry_crush/gberrycrush_textwindows_tilemap"))
#define gBerryCrush_TextWindows_Tilemap_SIZE 200u
#define gCableCarBg_Gfx ((const u32 *)UI_Get("emerald:ui/cable_car/gcablecarbg_gfx"))
#define gCableCarBg_Gfx_SIZE 16384u
#define gCableCarBg_Pal ((const u16 *)UI_Get("emerald:ui/cable_car/gcablecarbg_pal"))
#define gCableCarBg_Pal_SIZE 128u
#define gCableCarCable_Gfx ((const u32 *)UI_Get("emerald:ui/cable_car/gcablecarcable_gfx"))
#define gCableCarCable_Gfx_SIZE 128u
#define gCableCarDoor_Gfx ((const u32 *)UI_Get("emerald:ui/cable_car/gcablecardoor_gfx"))
#define gCableCarDoor_Gfx_SIZE 64u
#define gCableCar_Gfx ((const u32 *)UI_Get("emerald:ui/cable_car/gcablecar_gfx"))
#define gCableCar_Gfx_SIZE 2048u
#define gCableCar_Pal ((const u16 *)UI_Get("emerald:ui/cable_car/gcablecar_pal"))
#define gCableCar_Pal_SIZE 32u
#define gContest2Pal ((const u32 *)UI_Get("emerald:ui/contest/gcontest2pal"))
#define gContest2Pal_SIZE 32u
#define gContestApplauseGfx ((const u32 *)UI_Get("emerald:ui/contest/gcontestapplausegfx"))
#define gContestApplauseGfx_SIZE 1024u
#define gContestApplauseMeterGfx ((const u8 *)UI_Get("emerald:ui/contest/gcontestapplausemetergfx"))
#define gContestApplauseMeterGfx_SIZE 128u
#define gContestAudienceGfx ((const u32 *)UI_Get("emerald:ui/contest/gcontestaudiencegfx"))
#define gContestAudienceGfx_SIZE 8192u
#define gContestAudienceTilemap ((const u32 *)UI_Get("emerald:ui/contest/gcontestaudiencetilemap"))
#define gContestAudienceTilemap_SIZE 2048u
#define gContestCurtainTilemap ((const u32 *)UI_Get("emerald:ui/contest/gcontestcurtaintilemap"))
#define gContestCurtainTilemap_SIZE 2048u
#define gContestFaces_Gfx ((const u32 *)UI_Get("emerald:ui/contest/gcontestfaces_gfx"))
#define gContestFaces_Gfx_SIZE 384u
#define gContestInterfaceAudiencePalette ((const u32 *)UI_Get("emerald:ui/contest/gcontestinterfaceaudiencepalette"))
#define gContestInterfaceAudiencePalette_SIZE 512u
#define gContestInterfaceGfx ((const u32 *)UI_Get("emerald:ui/contest/gcontestinterfacegfx"))
#define gContestInterfaceGfx_SIZE 8192u
#define gContestInterfaceTilemap ((const u32 *)UI_Get("emerald:ui/contest/gcontestinterfacetilemap"))
#define gContestInterfaceTilemap_SIZE 4096u
#define gContestJudgeGfx ((const u32 *)UI_Get("emerald:ui/contest/gcontestjudgegfx"))
#define gContestJudgeGfx_SIZE 2048u
#define gContestJudgeSymbolsGfx ((const u32 *)UI_Get("emerald:ui/contest/gcontestjudgesymbolsgfx"))
#define gContestJudgeSymbolsGfx_SIZE 896u
#define gContestJudgeSymbolsPal ((const u32 *)UI_Get("emerald:ui/contest/gcontestjudgesymbolspal"))
#define gContestJudgeSymbolsPal_SIZE 32u
#define gContestNextTurnGfx ((const u32 *)UI_Get("emerald:ui/contest/gcontestnextturngfx"))
#define gContestNextTurnGfx_SIZE 256u
#define gContestNextTurnNumbersGfx ((const u8 *)UI_Get("emerald:ui/contest/gcontestnextturnnumbersgfx"))
#define gContestNextTurnNumbersGfx_SIZE 128u
#define gContestNextTurnRandomGfx ((const u8 *)UI_Get("emerald:ui/contest/gcontestnextturnrandomgfx"))
#define gContestNextTurnRandomGfx_SIZE 32u
#define gContestPal ((const u16 *)UI_Get("emerald:ui/contest/gcontestpal"))
#define gContestPal_SIZE 32u
#define gContestResultsTitle_Beauty_Tilemap ((const u16 *)UI_Get("emerald:ui/contest/gcontestresultstitle_beauty_tilemap"))
#define gContestResultsTitle_Beauty_Tilemap_SIZE 20u
#define gContestResultsTitle_Cool_Tilemap ((const u16 *)UI_Get("emerald:ui/contest/gcontestresultstitle_cool_tilemap"))
#define gContestResultsTitle_Cool_Tilemap_SIZE 20u
#define gContestResultsTitle_Cute_Tilemap ((const u16 *)UI_Get("emerald:ui/contest/gcontestresultstitle_cute_tilemap"))
#define gContestResultsTitle_Cute_Tilemap_SIZE 20u
#define gContestResultsTitle_Hyper_Tilemap ((const u16 *)UI_Get("emerald:ui/contest/gcontestresultstitle_hyper_tilemap"))
#define gContestResultsTitle_Hyper_Tilemap_SIZE 40u
#define gContestResultsTitle_Link_Tilemap ((const u16 *)UI_Get("emerald:ui/contest/gcontestresultstitle_link_tilemap"))
#define gContestResultsTitle_Link_Tilemap_SIZE 20u
#define gContestResultsTitle_Master_Tilemap ((const u16 *)UI_Get("emerald:ui/contest/gcontestresultstitle_master_tilemap"))
#define gContestResultsTitle_Master_Tilemap_SIZE 40u
#define gContestResultsTitle_Normal_Tilemap ((const u16 *)UI_Get("emerald:ui/contest/gcontestresultstitle_normal_tilemap"))
#define gContestResultsTitle_Normal_Tilemap_SIZE 40u
#define gContestResultsTitle_Smart_Tilemap ((const u16 *)UI_Get("emerald:ui/contest/gcontestresultstitle_smart_tilemap"))
#define gContestResultsTitle_Smart_Tilemap_SIZE 20u
#define gContestResultsTitle_Super_Tilemap ((const u16 *)UI_Get("emerald:ui/contest/gcontestresultstitle_super_tilemap"))
#define gContestResultsTitle_Super_Tilemap_SIZE 40u
#define gContestResultsTitle_Tilemap ((const u16 *)UI_Get("emerald:ui/contest/gcontestresultstitle_tilemap"))
#define gContestResultsTitle_Tilemap_SIZE 24u
#define gContestResultsTitle_Tough_Tilemap ((const u16 *)UI_Get("emerald:ui/contest/gcontestresultstitle_tough_tilemap"))
#define gContestResultsTitle_Tough_Tilemap_SIZE 20u
#define gContestResults_Bg_Tilemap ((const u32 *)UI_Get("emerald:ui/contest/gcontestresults_bg_tilemap"))
#define gContestResults_Bg_Tilemap_SIZE 2048u
#define gContestResults_Gfx ((const u32 *)UI_Get("emerald:ui/contest/gcontestresults_gfx"))
#define gContestResults_Gfx_SIZE 8192u
#define gContestResults_Interface_Tilemap ((const u32 *)UI_Get("emerald:ui/contest/gcontestresults_interface_tilemap"))
#define gContestResults_Interface_Tilemap_SIZE 2048u
#define gContestResults_Pal ((const u32 *)UI_Get("emerald:ui/contest/gcontestresults_pal"))
#define gContestResults_Pal_SIZE 512u
#define gContestResults_WinnerBanner_Tilemap ((const u32 *)UI_Get("emerald:ui/contest/gcontestresults_winnerbanner_tilemap"))
#define gContestResults_WinnerBanner_Tilemap_SIZE 2048u
#define gContestSliderHeart_Gfx ((const u8 *)UI_Get("emerald:ui/contest/gcontestsliderheart_gfx"))
#define gContestSliderHeart_Gfx_SIZE 32u
#define gJPContestAudienceTilemap ((const u32 *)UI_Get("emerald:ui/contest/gjpcontestaudiencetilemap"))
#define gJPContestAudienceTilemap_SIZE 8192u
#define gJPContestBgTilemap ((const u32 *)UI_Get("emerald:ui/contest/gjpcontestbgtilemap"))
#define gJPContestBgTilemap_SIZE 2048u
#define gJPContestGfx1 ((const u32 *)UI_Get("emerald:ui/contest/gjpcontestgfx1"))
#define gJPContestGfx1_SIZE 8192u
#define gJPContestGfx2 ((const u32 *)UI_Get("emerald:ui/contest/gjpcontestgfx2"))
#define gJPContestGfx2_SIZE 16384u
#define gJPContestInterfaceTilemap ((const u32 *)UI_Get("emerald:ui/contest/gjpcontestinterfacetilemap"))
#define gJPContestInterfaceTilemap_SIZE 2048u
#define gJPContestPal ((const u32 *)UI_Get("emerald:ui/contest/gjpcontestpal"))
#define gJPContestPal_SIZE 512u
#define gJPContestVoltageGfx ((const u32 *)UI_Get("emerald:ui/contest/gjpcontestvoltagegfx"))
#define gJPContestVoltageGfx_SIZE 1152u
#define gJPContestVoltagePal ((const u32 *)UI_Get("emerald:ui/contest/gjpcontestvoltagepal"))
#define gJPContestVoltagePal_SIZE 32u
#define gJPContestWindowsTilemap ((const u32 *)UI_Get("emerald:ui/contest/gjpcontestwindowstilemap"))
#define gJPContestWindowsTilemap_SIZE 4096u
#define gEasyChatButtonWindow_Gfx ((const u32 *)UI_Get("emerald:ui/easy_chat/geasychatbuttonwindow_gfx"))
#define gEasyChatButtonWindow_Gfx_SIZE 2048u
#define gEasyChatButtonWindow_Pal ((const u16 *)UI_Get("emerald:ui/easy_chat/geasychatbuttonwindow_pal"))
#define gEasyChatButtonWindow_Pal_SIZE 32u
#define gEasyChatMode_Gfx ((const u32 *)UI_Get("emerald:ui/easy_chat/geasychatmode_gfx"))
#define gEasyChatMode_Gfx_SIZE 4096u
#define gEasyChatMode_Pal ((const u16 *)UI_Get("emerald:ui/easy_chat/geasychatmode_pal"))
#define gEasyChatMode_Pal_SIZE 32u
#define gEasyChatRectangleCursor_Gfx ((const u32 *)UI_Get("emerald:ui/easy_chat/geasychatrectanglecursor_gfx"))
#define gEasyChatRectangleCursor_Gfx_SIZE 4096u
#define gEasyChatRectangleCursor_Pal ((const u16 *)UI_Get("emerald:ui/easy_chat/geasychatrectanglecursor_pal"))
#define gEasyChatRectangleCursor_Pal_SIZE 32u
#define gEasyChatWindow_Gfx ((const u32 *)UI_Get("emerald:ui/easy_chat/geasychatwindow_gfx"))
#define gEasyChatWindow_Gfx_SIZE 1376u
#define gEasyChatWindow_Tilemap ((const u32 *)UI_Get("emerald:ui/easy_chat/geasychatwindow_tilemap"))
#define gEasyChatWindow_Tilemap_SIZE 2048u
#define gFrontierPassBg_Gfx ((const u32 *)UI_Get("emerald:ui/frontier_pass/gfrontierpassbg_gfx"))
#define gFrontierPassBg_Gfx_SIZE 16384u
#define gFrontierPassBg_Tilemap ((const u32 *)UI_Get("emerald:ui/frontier_pass/gfrontierpassbg_tilemap"))
#define gFrontierPassBg_Tilemap_SIZE 1280u
#define gFrontierPassCancelButtonHighlighted_Tilemap ((const u32 *)UI_Get("emerald:ui/frontier_pass/gfrontierpasscancelbuttonhighlighted_tilemap"))
#define gFrontierPassCancelButtonHighlighted_Tilemap_SIZE 36u
#define gFrontierPassCancelButton_Tilemap ((const u32 *)UI_Get("emerald:ui/frontier_pass/gfrontierpasscancelbutton_tilemap"))
#define gFrontierPassCancelButton_Tilemap_SIZE 36u
#define gFrontierPassCursor_Pal ((const u16 *)UI_Get("emerald:ui/frontier_pass/gfrontierpasscursor_pal"))
#define gFrontierPassCursor_Pal_SIZE 32u
#define gFrontierPassMapAndCard_Gfx ((const u32 *)UI_Get("emerald:ui/frontier_pass/gfrontierpassmapandcard_gfx"))
#define gFrontierPassMapAndCard_Gfx_SIZE 14336u
#define gFrontierPassMapCursor_Pal ((const u16 *)UI_Get("emerald:ui/frontier_pass/gfrontierpassmapcursor_pal"))
#define gFrontierPassMapCursor_Pal_SIZE 32u
#define gFrontierPassMedalsGold_Pal ((const u16 *)UI_Get("emerald:ui/frontier_pass/gfrontierpassmedalsgold_pal"))
#define gFrontierPassMedalsGold_Pal_SIZE 32u
#define gFrontierPassMedalsSilver_Pal ((const u16 *)UI_Get("emerald:ui/frontier_pass/gfrontierpassmedalssilver_pal"))
#define gFrontierPassMedalsSilver_Pal_SIZE 32u
#define gFrontierPassMedals_Gfx ((const u32 *)UI_Get("emerald:ui/frontier_pass/gfrontierpassmedals_gfx"))
#define gFrontierPassMedals_Gfx_SIZE 896u
#define gBlankGfxCompressed ((const u32 *)UI_Get("emerald:ui/interface/gblankgfxcompressed"))
#define gBlankGfxCompressed_SIZE 2048u
#define gMenuInfoElements1_Pal ((const u16 *)UI_Get("emerald:ui/interface/gmenuinfoelements1_pal"))
#define gMenuInfoElements1_Pal_SIZE 32u
#define gMenuInfoElements2_Pal ((const u16 *)UI_Get("emerald:ui/interface/gmenuinfoelements2_pal"))
#define gMenuInfoElements2_Pal_SIZE 32u
#define gMenuInfoElements3_Pal ((const u16 *)UI_Get("emerald:ui/interface/gmenuinfoelements3_pal"))
#define gMenuInfoElements3_Pal_SIZE 32u
#define gMenuInfoElements_Gfx ((const u8 *)UI_Get("emerald:ui/interface/gmenuinfoelements_gfx"))
#define gMenuInfoElements_Gfx_SIZE 8192u
#define gMonMarkingsMenu_Gfx ((const u8 *)UI_Get("emerald:ui/interface/gmonmarkingsmenu_gfx"))
#define gMonMarkingsMenu_Gfx_SIZE 800u
#define gMonMarkingsMenu_Pal ((const u16 *)UI_Get("emerald:ui/interface/gmonmarkingsmenu_pal"))
#define gMonMarkingsMenu_Pal_SIZE 32u
#define gStatusGfx_Icons ((const u32 *)UI_Get("emerald:ui/interface/gstatusgfx_icons"))
#define gStatusGfx_Icons_SIZE 1024u
#define gStatusPal_Icons ((const u32 *)UI_Get("emerald:ui/interface/gstatuspal_icons"))
#define gStatusPal_Icons_SIZE 32u
#define gSwapLineGfx ((const u32 *)UI_Get("emerald:ui/interface/gswaplinegfx"))
#define gSwapLineGfx_SIZE 256u
#define gSwapLinePal ((const u32 *)UI_Get("emerald:ui/interface/gswaplinepal"))
#define gSwapLinePal_SIZE 32u
#define gIntroCopyright_Gfx ((const u32 *)UI_Get("emerald:ui/intro/gintrocopyright_gfx"))
#define gIntroCopyright_Gfx_SIZE 1248u
#define gIntroCopyright_Pal ((const u16 *)UI_Get("emerald:ui/intro/gintrocopyright_pal"))
#define gIntroCopyright_Pal_SIZE 32u
#define gIntroCopyright_Tilemap ((const u32 *)UI_Get("emerald:ui/intro/gintrocopyright_tilemap"))
#define gIntroCopyright_Tilemap_SIZE 2048u
#define gConfetti_Gfx ((const u32 *)UI_Get("emerald:ui/misc/gconfetti_gfx"))
#define gConfetti_Gfx_SIZE 544u
#define gConfetti_Pal ((const u32 *)UI_Get("emerald:ui/misc/gconfetti_pal"))
#define gConfetti_Pal_SIZE 32u
#define gNamingScreenBackButton_Gfx ((const u32 *)UI_Get("emerald:ui/naming_screen/gnamingscreenbackbutton_gfx"))
#define gNamingScreenBackButton_Gfx_SIZE 480u
#define gNamingScreenBackground_Tilemap ((const u32 *)UI_Get("emerald:ui/naming_screen/gnamingscreenbackground_tilemap"))
#define gNamingScreenBackground_Tilemap_SIZE 1280u
#define gNamingScreenCursorFilled_Gfx ((const u32 *)UI_Get("emerald:ui/naming_screen/gnamingscreencursorfilled_gfx"))
#define gNamingScreenCursorFilled_Gfx_SIZE 160u
#define gNamingScreenCursorSquished_Gfx ((const u32 *)UI_Get("emerald:ui/naming_screen/gnamingscreencursorsquished_gfx"))
#define gNamingScreenCursorSquished_Gfx_SIZE 160u
#define gNamingScreenInputArrow_Gfx ((const u32 *)UI_Get("emerald:ui/naming_screen/gnamingscreeninputarrow_gfx"))
#define gNamingScreenInputArrow_Gfx_SIZE 32u
#define gNamingScreenKeyboardLower_Tilemap ((const u32 *)UI_Get("emerald:ui/naming_screen/gnamingscreenkeyboardlower_tilemap"))
#define gNamingScreenKeyboardLower_Tilemap_SIZE 1280u
#define gNamingScreenKeyboardSymbols_Tilemap ((const u32 *)UI_Get("emerald:ui/naming_screen/gnamingscreenkeyboardsymbols_tilemap"))
#define gNamingScreenKeyboardSymbols_Tilemap_SIZE 1280u
#define gNamingScreenKeyboardUpper_Tilemap ((const u32 *)UI_Get("emerald:ui/naming_screen/gnamingscreenkeyboardupper_tilemap"))
#define gNamingScreenKeyboardUpper_Tilemap_SIZE 1280u
#define gNamingScreenMenu_Gfx ((const u32 *)UI_Get("emerald:ui/naming_screen/gnamingscreenmenu_gfx"))
#define gNamingScreenMenu_Gfx_SIZE 1536u
#define gNamingScreenOKButton_Gfx ((const u32 *)UI_Get("emerald:ui/naming_screen/gnamingscreenokbutton_gfx"))
#define gNamingScreenOKButton_Gfx_SIZE 480u
#define gNamingScreenPageSwapButton_Gfx ((const u32 *)UI_Get("emerald:ui/naming_screen/gnamingscreenpageswapbutton_gfx"))
#define gNamingScreenPageSwapButton_Gfx_SIZE 256u
#define gNamingScreenPageSwapFrame_Gfx ((const u32 *)UI_Get("emerald:ui/naming_screen/gnamingscreenpageswapframe_gfx"))
#define gNamingScreenPageSwapFrame_Gfx_SIZE 640u
#define gNamingScreenPageSwapLower_Gfx ((const u32 *)UI_Get("emerald:ui/naming_screen/gnamingscreenpageswaplower_gfx"))
#define gNamingScreenPageSwapLower_Gfx_SIZE 160u
#define gNamingScreenPageSwapOthers_Gfx ((const u32 *)UI_Get("emerald:ui/naming_screen/gnamingscreenpageswapothers_gfx"))
#define gNamingScreenPageSwapOthers_Gfx_SIZE 160u
#define gNamingScreenPageSwapUpper_Gfx ((const u32 *)UI_Get("emerald:ui/naming_screen/gnamingscreenpageswapupper_gfx"))
#define gNamingScreenPageSwapUpper_Gfx_SIZE 160u
#define gNamingScreenUnderscore_Gfx ((const u32 *)UI_Get("emerald:ui/naming_screen/gnamingscreenunderscore_gfx"))
#define gNamingScreenUnderscore_Gfx_SIZE 32u
#define gPartyMenuBg_Gfx ((const u32 *)UI_Get("emerald:ui/party_menu/gpartymenubg_gfx"))
#define gPartyMenuBg_Gfx_SIZE 1984u
#define gPartyMenuBg_Pal ((const u32 *)UI_Get("emerald:ui/party_menu/gpartymenubg_pal"))
#define gPartyMenuBg_Pal_SIZE 352u
#define gPartyMenuBg_Tilemap ((const u32 *)UI_Get("emerald:ui/party_menu/gpartymenubg_tilemap"))
#define gPartyMenuBg_Tilemap_SIZE 2048u
#define gPartyMenuPokeballSmall_Gfx ((const u32 *)UI_Get("emerald:ui/party_menu/gpartymenupokeballsmall_gfx"))
#define gPartyMenuPokeballSmall_Gfx_SIZE 768u
#define gPartyMenuPokeball_Gfx ((const u32 *)UI_Get("emerald:ui/party_menu/gpartymenupokeball_gfx"))
#define gPartyMenuPokeball_Gfx_SIZE 1024u
#define gPartyMenuPokeball_Pal ((const u32 *)UI_Get("emerald:ui/party_menu/gpartymenupokeball_pal"))
#define gPartyMenuPokeball_Pal_SIZE 32u
#define gMenuPokeblockDevice_Gfx ((const u32 *)UI_Get("emerald:ui/pokeblock/gmenupokeblockdevice_gfx"))
#define gMenuPokeblockDevice_Gfx_SIZE 2048u
#define gMenuPokeblockDevice_Pal ((const u32 *)UI_Get("emerald:ui/pokeblock/gmenupokeblockdevice_pal"))
#define gMenuPokeblockDevice_Pal_SIZE 32u
#define gMenuPokeblock_Gfx ((const u32 *)UI_Get("emerald:ui/pokeblock/gmenupokeblock_gfx"))
#define gMenuPokeblock_Gfx_SIZE 1280u
#define gMenuPokeblock_Pal ((const u32 *)UI_Get("emerald:ui/pokeblock/gmenupokeblock_pal"))
#define gMenuPokeblock_Pal_SIZE 192u
#define gMenuPokeblock_Tilemap ((const u32 *)UI_Get("emerald:ui/pokeblock/gmenupokeblock_tilemap"))
#define gMenuPokeblock_Tilemap_SIZE 2048u
#define gPokeblockBlack_Pal ((const u32 *)UI_Get("emerald:ui/pokeblock/gpokeblockblack_pal"))
#define gPokeblockBlack_Pal_SIZE 32u
#define gPokeblockBlue_Pal ((const u32 *)UI_Get("emerald:ui/pokeblock/gpokeblockblue_pal"))
#define gPokeblockBlue_Pal_SIZE 32u
#define gPokeblockBrown_Pal ((const u32 *)UI_Get("emerald:ui/pokeblock/gpokeblockbrown_pal"))
#define gPokeblockBrown_Pal_SIZE 32u
#define gPokeblockFeedBg_Tilemap ((const u32 *)UI_Get("emerald:ui/pokeblock/gpokeblockfeedbg_tilemap"))
#define gPokeblockFeedBg_Tilemap_SIZE 2048u
#define gPokeblockGold_Pal ((const u32 *)UI_Get("emerald:ui/pokeblock/gpokeblockgold_pal"))
#define gPokeblockGold_Pal_SIZE 32u
#define gPokeblockGray_Pal ((const u32 *)UI_Get("emerald:ui/pokeblock/gpokeblockgray_pal"))
#define gPokeblockGray_Pal_SIZE 32u
#define gPokeblockGreen_Pal ((const u32 *)UI_Get("emerald:ui/pokeblock/gpokeblockgreen_pal"))
#define gPokeblockGreen_Pal_SIZE 32u
#define gPokeblockIndigo_Pal ((const u32 *)UI_Get("emerald:ui/pokeblock/gpokeblockindigo_pal"))
#define gPokeblockIndigo_Pal_SIZE 32u
#define gPokeblockLiteBlue_Pal ((const u32 *)UI_Get("emerald:ui/pokeblock/gpokeblockliteblue_pal"))
#define gPokeblockLiteBlue_Pal_SIZE 32u
#define gPokeblockOlive_Pal ((const u32 *)UI_Get("emerald:ui/pokeblock/gpokeblockolive_pal"))
#define gPokeblockOlive_Pal_SIZE 32u
#define gPokeblockPink_Pal ((const u32 *)UI_Get("emerald:ui/pokeblock/gpokeblockpink_pal"))
#define gPokeblockPink_Pal_SIZE 32u
#define gPokeblockPurple_Pal ((const u32 *)UI_Get("emerald:ui/pokeblock/gpokeblockpurple_pal"))
#define gPokeblockPurple_Pal_SIZE 32u
#define gPokeblockRed_Pal ((const u32 *)UI_Get("emerald:ui/pokeblock/gpokeblockred_pal"))
#define gPokeblockRed_Pal_SIZE 32u
#define gPokeblockWhite_Pal ((const u32 *)UI_Get("emerald:ui/pokeblock/gpokeblockwhite_pal"))
#define gPokeblockWhite_Pal_SIZE 32u
#define gPokeblockYellow_Pal ((const u32 *)UI_Get("emerald:ui/pokeblock/gpokeblockyellow_pal"))
#define gPokeblockYellow_Pal_SIZE 32u
#define gPokeblock_Gfx ((const u32 *)UI_Get("emerald:ui/pokeblock/gpokeblock_gfx"))
#define gPokeblock_Gfx_SIZE 32u
#define gUsePokeblockCondition_Gfx ((const u32 *)UI_Get("emerald:ui/pokeblock/gusepokeblockcondition_gfx"))
#define gUsePokeblockCondition_Gfx_SIZE 2048u
#define gUsePokeblockCondition_Pal ((const u16 *)UI_Get("emerald:ui/pokeblock/gusepokeblockcondition_pal"))
#define gUsePokeblockCondition_Pal_SIZE 32u
#define gUsePokeblockGraph_Gfx ((const u32 *)UI_Get("emerald:ui/pokeblock/gusepokeblockgraph_gfx"))
#define gUsePokeblockGraph_Gfx_SIZE 6656u
#define gUsePokeblockGraph_Pal ((const u16 *)UI_Get("emerald:ui/pokeblock/gusepokeblockgraph_pal"))
#define gUsePokeblockGraph_Pal_SIZE 32u
#define gUsePokeblockGraph_Tilemap ((const u32 *)UI_Get("emerald:ui/pokeblock/gusepokeblockgraph_tilemap"))
#define gUsePokeblockGraph_Tilemap_SIZE 1280u
#define gUsePokeblockNatureWin_Pal ((const u16 *)UI_Get("emerald:ui/pokeblock/gusepokeblocknaturewin_pal"))
#define gUsePokeblockNatureWin_Pal_SIZE 96u
#define gUsePokeblockUpDown_Gfx ((const u8 *)UI_Get("emerald:ui/pokeblock/gusepokeblockupdown_gfx"))
#define gUsePokeblockUpDown_Gfx_SIZE 512u
#define gUsePokeblockUpDown_Pal ((const u16 *)UI_Get("emerald:ui/pokeblock/gusepokeblockupdown_pal"))
#define gUsePokeblockUpDown_Pal_SIZE 32u
#define gPokedexAreaScreenAreaUnknown_Gfx ((const u32 *)UI_Get("emerald:ui/pokedex/gpokedexareascreenareaunknown_gfx"))
#define gPokedexAreaScreenAreaUnknown_Gfx_SIZE 1536u
#define gPokedexAreaScreenAreaUnknown_Pal ((const u16 *)UI_Get("emerald:ui/pokedex/gpokedexareascreenareaunknown_pal"))
#define gPokedexAreaScreenAreaUnknown_Pal_SIZE 32u
#define gPokedexBgNational_Pal ((const u16 *)UI_Get("emerald:ui/pokedex/gpokedexbgnational_pal"))
#define gPokedexBgNational_Pal_SIZE 192u
#define gPokedexCryScreen_Tilemap ((const u32 *)UI_Get("emerald:ui/pokedex/gpokedexcryscreen_tilemap"))
#define gPokedexCryScreen_Tilemap_SIZE 1280u
#define gPokedexInfoScreen_Tilemap ((const u32 *)UI_Get("emerald:ui/pokedex/gpokedexinfoscreen_tilemap"))
#define gPokedexInfoScreen_Tilemap_SIZE 1280u
#define gPokedexInterface_Gfx ((const u32 *)UI_Get("emerald:ui/pokedex/gpokedexinterface_gfx"))
#define gPokedexInterface_Gfx_SIZE 8192u
#define gPokedexListUnderlay_Tilemap ((const u32 *)UI_Get("emerald:ui/pokedex/gpokedexlistunderlay_tilemap"))
#define gPokedexListUnderlay_Tilemap_SIZE 1280u
#define gPokedexList_Tilemap ((const u32 *)UI_Get("emerald:ui/pokedex/gpokedexlist_tilemap"))
#define gPokedexList_Tilemap_SIZE 1280u
#define gPokedexMenu_Gfx ((const u32 *)UI_Get("emerald:ui/pokedex/gpokedexmenu_gfx"))
#define gPokedexMenu_Gfx_SIZE 8192u
#define gPokedexScreenSelectBarMain_Tilemap ((const u32 *)UI_Get("emerald:ui/pokedex/gpokedexscreenselectbarmain_tilemap"))
#define gPokedexScreenSelectBarMain_Tilemap_SIZE 192u
#define gPokedexScreenSelectBarSubmenu_Tilemap ((const u32 *)UI_Get("emerald:ui/pokedex/gpokedexscreenselectbarsubmenu_tilemap"))
#define gPokedexScreenSelectBarSubmenu_Tilemap_SIZE 192u
#define gPokedexSearchMenuHoenn_Tilemap ((const u32 *)UI_Get("emerald:ui/pokedex/gpokedexsearchmenuhoenn_tilemap"))
#define gPokedexSearchMenuHoenn_Tilemap_SIZE 1280u
#define gPokedexSearchMenuNational_Tilemap ((const u32 *)UI_Get("emerald:ui/pokedex/gpokedexsearchmenunational_tilemap"))
#define gPokedexSearchMenuNational_Tilemap_SIZE 1280u
#define gPokedexSearchMenu_Gfx ((const u32 *)UI_Get("emerald:ui/pokedex/gpokedexsearchmenu_gfx"))
#define gPokedexSearchMenu_Gfx_SIZE 4096u
#define gPokedexSearchMenu_Pal ((const u16 *)UI_Get("emerald:ui/pokedex/gpokedexsearchmenu_pal"))
#define gPokedexSearchMenu_Pal_SIZE 128u
#define gPokedexSearchResults_Pal ((const u16 *)UI_Get("emerald:ui/pokedex/gpokedexsearchresults_pal"))
#define gPokedexSearchResults_Pal_SIZE 192u
#define gPokedexSizeScreen_Tilemap ((const u32 *)UI_Get("emerald:ui/pokedex/gpokedexsizescreen_tilemap"))
#define gPokedexSizeScreen_Tilemap_SIZE 1280u
#define gPokedexStartMenuMain_Tilemap ((const u32 *)UI_Get("emerald:ui/pokedex/gpokedexstartmenumain_tilemap"))
#define gPokedexStartMenuMain_Tilemap_SIZE 768u
#define gPokedexStartMenuSearchResults_Tilemap ((const u32 *)UI_Get("emerald:ui/pokedex/gpokedexstartmenusearchresults_tilemap"))
#define gPokedexStartMenuSearchResults_Tilemap_SIZE 768u
#define gUnused_PokedexNoBall ((const u32 *)UI_Get("emerald:ui/pokedex/gunused_pokedexnoball"))
#define gUnused_PokedexNoBall_SIZE 128u
#define gMonUnusedGarbage ((const u16 *)UI_Get("emerald:ui/pokemon/gmonunusedgarbage"))
#define gMonUnusedGarbage_SIZE 1024u
#define gStorageSystemMenu_Gfx ((const u32 *)UI_Get("emerald:ui/pokemon_storage/gstoragesystemmenu_gfx"))
#define gStorageSystemMenu_Gfx_SIZE 4608u
#define gStorageSystemPartyMenu_Pal ((const u16 *)UI_Get("emerald:ui/pokemon_storage/gstoragesystempartymenu_pal"))
#define gStorageSystemPartyMenu_Pal_SIZE 32u
#define gStorageSystemPartyMenu_Tilemap ((const u32 *)UI_Get("emerald:ui/pokemon_storage/gstoragesystempartymenu_tilemap"))
#define gStorageSystemPartyMenu_Tilemap_SIZE 528u
#define gPokenavConditionCancel_Gfx ((const u8 *)UI_Get("emerald:ui/pokenav/gpokenavconditioncancel_gfx"))
#define gPokenavConditionCancel_Gfx_SIZE 256u
#define gPokenavConditionCancel_Pal ((const u16 *)UI_Get("emerald:ui/pokenav/gpokenavconditioncancel_pal"))
#define gPokenavConditionCancel_Pal_SIZE 64u
#define gPokenavCondition_Gfx ((const u32 *)UI_Get("emerald:ui/pokenav/gpokenavcondition_gfx"))
#define gPokenavCondition_Gfx_SIZE 6656u
#define gPokenavCondition_Pal ((const u16 *)UI_Get("emerald:ui/pokenav/gpokenavcondition_pal"))
#define gPokenavCondition_Pal_SIZE 32u
#define gPokenavCondition_Tilemap ((const u32 *)UI_Get("emerald:ui/pokenav/gpokenavcondition_tilemap"))
#define gPokenavCondition_Tilemap_SIZE 2048u
#define gPokenavHeader_Gfx ((const u32 *)UI_Get("emerald:ui/pokenav/gpokenavheader_gfx"))
#define gPokenavHeader_Gfx_SIZE 1696u
#define gPokenavHeader_Pal ((const u16 *)UI_Get("emerald:ui/pokenav/gpokenavheader_pal"))
#define gPokenavHeader_Pal_SIZE 32u
#define gPokenavHeader_Tilemap ((const u32 *)UI_Get("emerald:ui/pokenav/gpokenavheader_tilemap"))
#define gPokenavHeader_Tilemap_SIZE 2048u
#define gPokenavLeftHeaderBeauty_Gfx ((const u32 *)UI_Get("emerald:ui/pokenav/gpokenavleftheaderbeauty_gfx"))
#define gPokenavLeftHeaderBeauty_Gfx_SIZE 1024u
#define gPokenavLeftHeaderCondition_Gfx ((const u32 *)UI_Get("emerald:ui/pokenav/gpokenavleftheadercondition_gfx"))
#define gPokenavLeftHeaderCondition_Gfx_SIZE 2048u
#define gPokenavLeftHeaderCool_Gfx ((const u32 *)UI_Get("emerald:ui/pokenav/gpokenavleftheadercool_gfx"))
#define gPokenavLeftHeaderCool_Gfx_SIZE 1024u
#define gPokenavLeftHeaderCute_Gfx ((const u32 *)UI_Get("emerald:ui/pokenav/gpokenavleftheadercute_gfx"))
#define gPokenavLeftHeaderCute_Gfx_SIZE 1024u
#define gPokenavLeftHeaderHoennMap_Gfx ((const u32 *)UI_Get("emerald:ui/pokenav/gpokenavleftheaderhoennmap_gfx"))
#define gPokenavLeftHeaderHoennMap_Gfx_SIZE 3072u
#define gPokenavLeftHeaderMainMenu_Gfx ((const u32 *)UI_Get("emerald:ui/pokenav/gpokenavleftheadermainmenu_gfx"))
#define gPokenavLeftHeaderMainMenu_Gfx_SIZE 2048u
#define gPokenavLeftHeaderMatchCall_Gfx ((const u32 *)UI_Get("emerald:ui/pokenav/gpokenavleftheadermatchcall_gfx"))
#define gPokenavLeftHeaderMatchCall_Gfx_SIZE 2048u
#define gPokenavLeftHeaderParty_Gfx ((const u32 *)UI_Get("emerald:ui/pokenav/gpokenavleftheaderparty_gfx"))
#define gPokenavLeftHeaderParty_Gfx_SIZE 1024u
#define gPokenavLeftHeaderRibbons_Gfx ((const u32 *)UI_Get("emerald:ui/pokenav/gpokenavleftheaderribbons_gfx"))
#define gPokenavLeftHeaderRibbons_Gfx_SIZE 2048u
#define gPokenavLeftHeaderSearch_Gfx ((const u32 *)UI_Get("emerald:ui/pokenav/gpokenavleftheadersearch_gfx"))
#define gPokenavLeftHeaderSearch_Gfx_SIZE 1024u
#define gPokenavLeftHeaderSmart_Gfx ((const u32 *)UI_Get("emerald:ui/pokenav/gpokenavleftheadersmart_gfx"))
#define gPokenavLeftHeaderSmart_Gfx_SIZE 1024u
#define gPokenavLeftHeaderTough_Gfx ((const u32 *)UI_Get("emerald:ui/pokenav/gpokenavleftheadertough_gfx"))
#define gPokenavLeftHeaderTough_Gfx_SIZE 1024u
#define gPokenavLeftHeader_Pal ((const u16 *)UI_Get("emerald:ui/pokenav/gpokenavleftheader_pal"))
#define gPokenavLeftHeader_Pal_SIZE 160u
#define gPokenavMessageBox_Gfx ((const u32 *)UI_Get("emerald:ui/pokenav/gpokenavmessagebox_gfx"))
#define gPokenavMessageBox_Gfx_SIZE 224u
#define gPokenavMessageBox_Pal ((const u16 *)UI_Get("emerald:ui/pokenav/gpokenavmessagebox_pal"))
#define gPokenavMessageBox_Pal_SIZE 32u
#define gPokenavMessageBox_Tilemap ((const u32 *)UI_Get("emerald:ui/pokenav/gpokenavmessagebox_tilemap"))
#define gPokenavMessageBox_Tilemap_SIZE 1280u
#define gPokenavOptions_Gfx ((const u32 *)UI_Get("emerald:ui/pokenav/gpokenavoptions_gfx"))
#define gPokenavOptions_Gfx_SIZE 13312u
#define gPokenavOptions_Pal ((const u16 *)UI_Get("emerald:ui/pokenav/gpokenavoptions_pal"))
#define gPokenavOptions_Pal_SIZE 160u
#define gPokenavOptions_Tilemap ((const u16 *)UI_Get("emerald:ui/pokenav/gpokenavoptions_tilemap"))
#define gPokenavOptions_Tilemap_SIZE 72u
#define gPokenavRibbonsSummaryBg_Gfx ((const u32 *)UI_Get("emerald:ui/pokenav/gpokenavribbonssummarybg_gfx"))
#define gPokenavRibbonsSummaryBg_Gfx_SIZE 608u
#define gPokenavRibbonsSummaryBg_Pal ((const u16 *)UI_Get("emerald:ui/pokenav/gpokenavribbonssummarybg_pal"))
#define gPokenavRibbonsSummaryBg_Pal_SIZE 32u
#define gPokenavRibbonsSummaryBg_Tilemap ((const u32 *)UI_Get("emerald:ui/pokenav/gpokenavribbonssummarybg_tilemap"))
#define gPokenavRibbonsSummaryBg_Tilemap_SIZE 1280u
#define gRegionMapCityZoomText_Gfx ((const u32 *)UI_Get("emerald:ui/pokenav/gregionmapcityzoomtext_gfx"))
#define gRegionMapCityZoomText_Gfx_SIZE 2048u
#define gRegionMapCityZoomTiles_Pal ((const u16 *)UI_Get("emerald:ui/pokenav/gregionmapcityzoomtiles_pal"))
#define gRegionMapCityZoomTiles_Pal_SIZE 32u
#define gRouletteCenter_Gfx ((const u32 *)UI_Get("emerald:ui/roulette/groulettecenter_gfx"))
#define gRouletteCenter_Gfx_SIZE 2048u
#define gRouletteCredit_Gfx ((const u32 *)UI_Get("emerald:ui/roulette/groulettecredit_gfx"))
#define gRouletteCredit_Gfx_SIZE 1024u
#define gRouletteHeaders_Gfx ((const u32 *)UI_Get("emerald:ui/roulette/grouletteheaders_gfx"))
#define gRouletteHeaders_Gfx_SIZE 5632u
#define gRouletteMenu_Gfx ((const u32 *)UI_Get("emerald:ui/roulette/groulettemenu_gfx"))
#define gRouletteMenu_Gfx_SIZE 8192u
#define gRouletteMultiplier_Gfx ((const u32 *)UI_Get("emerald:ui/roulette/groulettemultiplier_gfx"))
#define gRouletteMultiplier_Gfx_SIZE 1280u
#define gRouletteNumbers_Gfx ((const u32 *)UI_Get("emerald:ui/roulette/groulettenumbers_gfx"))
#define gRouletteNumbers_Gfx_SIZE 640u
#define gRouletteWheel_Gfx ((const u32 *)UI_Get("emerald:ui/roulette/groulettewheel_gfx"))
#define gRouletteWheel_Gfx_SIZE 16384u
#define gShopMenuMoney_Gfx ((const u32 *)UI_Get("emerald:ui/shop/gshopmenumoney_gfx"))
#define gShopMenuMoney_Gfx_SIZE 256u
#define gShopMenu_Gfx ((const u32 *)UI_Get("emerald:ui/shop/gshopmenu_gfx"))
#define gShopMenu_Gfx_SIZE 928u
#define gShopMenu_Pal ((const u32 *)UI_Get("emerald:ui/shop/gshopmenu_pal"))
#define gShopMenu_Pal_SIZE 32u
#define gShopMenu_Tilemap ((const u32 *)UI_Get("emerald:ui/shop/gshopmenu_tilemap"))
#define gShopMenu_Tilemap_SIZE 2048u
#define gSummaryMoveSelect_Gfx ((const u32 *)UI_Get("emerald:ui/summary_screen/gsummarymoveselect_gfx"))
#define gSummaryMoveSelect_Gfx_SIZE 1024u
#define gSummaryMoveSelect_Pal ((const u32 *)UI_Get("emerald:ui/summary_screen/gsummarymoveselect_pal"))
#define gSummaryMoveSelect_Pal_SIZE 32u
#define gSummaryPage_BattleMoves_Tilemap ((const u32 *)UI_Get("emerald:ui/summary_screen/gsummarypage_battlemoves_tilemap"))
#define gSummaryPage_BattleMoves_Tilemap_SIZE 2048u
#define gSummaryPage_ContestMoves_Tilemap ((const u32 *)UI_Get("emerald:ui/summary_screen/gsummarypage_contestmoves_tilemap"))
#define gSummaryPage_ContestMoves_Tilemap_SIZE 2048u
#define gSummaryPage_InfoEgg_Tilemap ((const u32 *)UI_Get("emerald:ui/summary_screen/gsummarypage_infoegg_tilemap"))
#define gSummaryPage_InfoEgg_Tilemap_SIZE 2048u
#define gSummaryPage_Info_Tilemap ((const u32 *)UI_Get("emerald:ui/summary_screen/gsummarypage_info_tilemap"))
#define gSummaryPage_Info_Tilemap_SIZE 2048u
#define gSummaryPage_Skills_Tilemap ((const u32 *)UI_Get("emerald:ui/summary_screen/gsummarypage_skills_tilemap"))
#define gSummaryPage_Skills_Tilemap_SIZE 2048u
#define gSummaryScreen_Gfx ((const u32 *)UI_Get("emerald:ui/summary_screen/gsummaryscreen_gfx"))
#define gSummaryScreen_Gfx_SIZE 7680u
#define gSummaryScreen_MoveEffect_Battle_Tilemap ((const u16 *)UI_Get("emerald:ui/summary_screen/gsummaryscreen_moveeffect_battle_tilemap"))
#define gSummaryScreen_MoveEffect_Battle_Tilemap_SIZE 160u
#define gSummaryScreen_MoveEffect_Cancel_Tilemap ((const u16 *)UI_Get("emerald:ui/summary_screen/gsummaryscreen_moveeffect_cancel_tilemap"))
#define gSummaryScreen_MoveEffect_Cancel_Tilemap_SIZE 128u
#define gSummaryScreen_MoveEffect_Contest_Tilemap ((const u16 *)UI_Get("emerald:ui/summary_screen/gsummaryscreen_moveeffect_contest_tilemap"))
#define gSummaryScreen_MoveEffect_Contest_Tilemap_SIZE 160u
#define gSummaryScreen_Pal ((const u32 *)UI_Get("emerald:ui/summary_screen/gsummaryscreen_pal"))
#define gSummaryScreen_Pal_SIZE 256u
#define gMessageBox_Gfx ((const u8 *)UI_Get("emerald:ui/text_window/gmessagebox_gfx"))
#define gMessageBox_Gfx_SIZE 448u
#define gMessageBox_Pal ((const u16 *)UI_Get("emerald:ui/text_window/gmessagebox_pal"))
#define gMessageBox_Pal_SIZE 32u
#define gTitleScreenCloudsTilemap ((const u32 *)UI_Get("emerald:ui/title_screen/gtitlescreencloudstilemap"))
#define gTitleScreenCloudsTilemap_SIZE 2048u
#define gTitleScreenEmeraldVersionGfx ((const u32 *)UI_Get("emerald:ui/title_screen/gtitlescreenemeraldversiongfx"))
#define gTitleScreenEmeraldVersionGfx_SIZE 4096u
#define gTitleScreenEmeraldVersionPal ((const u16 *)UI_Get("emerald:ui/title_screen/gtitlescreenemeraldversionpal"))
#define gTitleScreenEmeraldVersionPal_SIZE 32u
#define gTitleScreenPokemonLogoGfx ((const u32 *)UI_Get("emerald:ui/title_screen/gtitlescreenpokemonlogogfx"))
#define gTitleScreenPokemonLogoGfx_SIZE 16384u
#define gTitleScreenPokemonLogoTilemap ((const u32 *)UI_Get("emerald:ui/title_screen/gtitlescreenpokemonlogotilemap"))
#define gTitleScreenPokemonLogoTilemap_SIZE 1024u
#define gTitleScreenPressStartGfx ((const u32 *)UI_Get("emerald:ui/title_screen/gtitlescreenpressstartgfx"))
#define gTitleScreenPressStartGfx_SIZE 1536u
#define gTitleScreenPressStartPal ((const u16 *)UI_Get("emerald:ui/title_screen/gtitlescreenpressstartpal"))
#define gTitleScreenPressStartPal_SIZE 32u
#define gTradeCursor_Gfx ((const u8 *)UI_Get("emerald:ui/trade/gtradecursor_gfx"))
#define gTradeCursor_Gfx_SIZE 2048u
#define gTradeCursor_Pal ((const u16 *)UI_Get("emerald:ui/trade/gtradecursor_pal"))
#define gTradeCursor_Pal_SIZE 32u
#define gTradeGba2_Pal ((const u16 *)UI_Get("emerald:ui/trade/gtradegba2_pal"))
#define gTradeGba2_Pal_SIZE 96u
#define gTradeGba_Gfx ((const u8 *)UI_Get("emerald:ui/trade/gtradegba_gfx"))
#define gTradeGba_Gfx_SIZE 5120u
#define gTradeGba_Pal ((const u16 *)UI_Get("emerald:ui/trade/gtradegba_pal"))
#define gTradeGba_Pal_SIZE 32u
#define gTradeMenuMonBox_Tilemap ((const u16 *)UI_Get("emerald:ui/trade/gtrademenumonbox_tilemap"))
#define gTradeMenuMonBox_Tilemap_SIZE 36u
#define gTradeMenu_Gfx ((const u8 *)UI_Get("emerald:ui/trade/gtrademenu_gfx"))
#define gTradeMenu_Gfx_SIZE 4736u
#define gTradeMenu_Pal ((const u16 *)UI_Get("emerald:ui/trade/gtrademenu_pal"))
#define gTradeMenu_Pal_SIZE 96u
#define gTradeMenu_Tilemap ((const u16 *)UI_Get("emerald:ui/trade/gtrademenu_tilemap"))
#define gTradeMenu_Tilemap_SIZE 2048u
#define gTradeUnused_Tilemap ((const u16 *)UI_Get("emerald:ui/trade/gtradeunused_tilemap"))
#define gTradeUnused_Tilemap_SIZE 32u
#define gHoennTrainerCardBack_Tilemap ((const u32 *)UI_Get("emerald:ui/trainer_card/ghoenntrainercardback_tilemap"))
#define gHoennTrainerCardBack_Tilemap_SIZE 1200u
#define gHoennTrainerCardBg_Tilemap ((const u32 *)UI_Get("emerald:ui/trainer_card/ghoenntrainercardbg_tilemap"))
#define gHoennTrainerCardBg_Tilemap_SIZE 1200u
#define gHoennTrainerCardFrontLink_Tilemap ((const u32 *)UI_Get("emerald:ui/trainer_card/ghoenntrainercardfrontlink_tilemap"))
#define gHoennTrainerCardFrontLink_Tilemap_SIZE 1200u
#define gHoennTrainerCardFront_Tilemap ((const u32 *)UI_Get("emerald:ui/trainer_card/ghoenntrainercardfront_tilemap"))
#define gHoennTrainerCardFront_Tilemap_SIZE 1200u
#define gHoennTrainerCardGreen_Pal ((const u16 *)UI_Get("emerald:ui/trainer_card/ghoenntrainercardgreen_pal"))
#define gHoennTrainerCardGreen_Pal_SIZE 96u
#define gHoennTrainerCard_Gfx ((const u32 *)UI_Get("emerald:ui/trainer_card/ghoenntrainercard_gfx"))
#define gHoennTrainerCard_Gfx_SIZE 5120u
#define gKantoTrainerCardBack_Tilemap ((const u32 *)UI_Get("emerald:ui/trainer_card/gkantotrainercardback_tilemap"))
#define gKantoTrainerCardBack_Tilemap_SIZE 1200u
#define gKantoTrainerCardBg_Tilemap ((const u32 *)UI_Get("emerald:ui/trainer_card/gkantotrainercardbg_tilemap"))
#define gKantoTrainerCardBg_Tilemap_SIZE 1200u
#define gKantoTrainerCardBlue_Pal ((const u16 *)UI_Get("emerald:ui/trainer_card/gkantotrainercardblue_pal"))
#define gKantoTrainerCardBlue_Pal_SIZE 96u
#define gKantoTrainerCardFrontLink_Tilemap ((const u32 *)UI_Get("emerald:ui/trainer_card/gkantotrainercardfrontlink_tilemap"))
#define gKantoTrainerCardFrontLink_Tilemap_SIZE 1200u
#define gKantoTrainerCardFront_Tilemap ((const u32 *)UI_Get("emerald:ui/trainer_card/gkantotrainercardfront_tilemap"))
#define gKantoTrainerCardFront_Tilemap_SIZE 1200u
#define gKantoTrainerCard_Gfx ((const u32 *)UI_Get("emerald:ui/trainer_card/gkantotrainercard_gfx"))
#define gKantoTrainerCard_Gfx_SIZE 6144u
#define gMoveTypes_Gfx ((const u32 *)UI_Get("emerald:ui/types/gmovetypes_gfx"))
#define gMoveTypes_Gfx_SIZE 5888u
#define gMoveTypes_Pal ((const u32 *)UI_Get("emerald:ui/types/gmovetypes_pal"))
#define gMoveTypes_Pal_SIZE 96u
#define gUnionRoomChat_Background_Gfx ((const u32 *)UI_Get("emerald:ui/union_room_chat/gunionroomchat_background_gfx"))
#define gUnionRoomChat_Background_Gfx_SIZE 1248u
#define gUnionRoomChat_Background_Pal ((const u16 *)UI_Get("emerald:ui/union_room_chat/gunionroomchat_background_pal"))
#define gUnionRoomChat_Background_Pal_SIZE 32u
#define gUnionRoomChat_Background_Tilemap ((const u32 *)UI_Get("emerald:ui/union_room_chat/gunionroomchat_background_tilemap"))
#define gUnionRoomChat_Background_Tilemap_SIZE 1280u
#define gUnionRoomChat_InputText_Pal ((const u16 *)UI_Get("emerald:ui/union_room_chat/gunionroomchat_inputtext_pal"))
#define gUnionRoomChat_InputText_Pal_SIZE 32u
#define gUnionRoomChat_Keyboard_Gfx ((const u32 *)UI_Get("emerald:ui/union_room_chat/gunionroomchat_keyboard_gfx"))
#define gUnionRoomChat_Keyboard_Gfx_SIZE 288u
#define gUnionRoomChat_Keyboard_Pal ((const u16 *)UI_Get("emerald:ui/union_room_chat/gunionroomchat_keyboard_pal"))
#define gUnionRoomChat_Keyboard_Pal_SIZE 32u
#define gUnionRoomChat_Keyboard_Tilemap ((const u32 *)UI_Get("emerald:ui/union_room_chat/gunionroomchat_keyboard_tilemap"))
#define gUnionRoomChat_Keyboard_Tilemap_SIZE 1280u
#define gUnionRoomChat_RButtonLabels ((const u32 *)UI_Get("emerald:ui/union_room_chat/gunionroomchat_rbuttonlabels"))
#define gUnionRoomChat_RButtonLabels_SIZE 1024u
#define gOldBattleInterfaceGfx ((const u32 *)UI_Get("emerald:ui/unused/goldbattleinterfacegfx"))
#define gOldBattleInterfaceGfx_SIZE 2048u
#define gOldBattleInterfaceGfx2 ((const u32 *)UI_Get("emerald:ui/unused/goldbattleinterfacegfx2"))
#define gOldBattleInterfaceGfx2_SIZE 5120u
#define gOldBattleInterfacePal4 ((const u32 *)UI_Get("emerald:ui/unused/goldbattleinterfacepal4"))
#define gOldBattleInterfacePal4_SIZE 32u
#define gOldBattleInterfacePal_1_2_3 ((const u32 *)UI_Get("emerald:ui/unused/goldbattleinterfacepal_1_2_3"))
#define gOldBattleInterfacePal_1_2_3_SIZE 96u
#define gOldBattleInterfacePal_5_6_7 ((const u32 *)UI_Get("emerald:ui/unused/goldbattleinterfacepal_5_6_7"))
#define gOldBattleInterfacePal_5_6_7_SIZE 96u
#define gOldBattleInterfaceTilemap ((const u32 *)UI_Get("emerald:ui/unused/goldbattleinterfacetilemap"))
#define gOldBattleInterfaceTilemap_SIZE 2048u
#define gUnusedGfx_BasicFrame ((const u32 *)UI_Get("emerald:ui/unused/gunusedgfx_basicframe"))
#define gUnusedGfx_BasicFrame_SIZE 320u
#define gUnusedGfx_ColorFrames ((const u32 *)UI_Get("emerald:ui/unused/gunusedgfx_colorframes"))
#define gUnusedGfx_ColorFrames_SIZE 11296u
#define gUnusedGfx_OldCharmap ((const u32 *)UI_Get("emerald:ui/unused/gunusedgfx_oldcharmap"))
#define gUnusedGfx_OldCharmap_SIZE 8192u
#define gUnusedGfx_Shadow ((const u32 *)UI_Get("emerald:ui/unused/gunusedgfx_shadow"))
#define gUnusedGfx_Shadow_SIZE 256u
#define gUnusedPal_BasicFrame ((const u32 *)UI_Get("emerald:ui/unused/gunusedpal_basicframe"))
#define gUnusedPal_BasicFrame_SIZE 32u
#define gUnusedPal_ColorFrames ((const u32 *)UI_Get("emerald:ui/unused/gunusedpal_colorframes"))
#define gUnusedPal_ColorFrames_SIZE 32u
#define gUnusedPal_OldCharmap ((const u32 *)UI_Get("emerald:ui/unused/gunusedpal_oldcharmap"))
#define gUnusedPal_OldCharmap_SIZE 32u
#define gUnusedPal_Shadow ((const u32 *)UI_Get("emerald:ui/unused/gunusedpal_shadow"))
#define gUnusedPal_Shadow_SIZE 32u
#define gUnusedTilemap_BasicFrame ((const u32 *)UI_Get("emerald:ui/unused/gunusedtilemap_basicframe"))
#define gUnusedTilemap_BasicFrame_SIZE 2048u
#define gUnusedTilemap_BlueFrame ((const u32 *)UI_Get("emerald:ui/unused/gunusedtilemap_blueframe"))
#define gUnusedTilemap_BlueFrame_SIZE 2048u
#define gUnusedTilemap_RedYellowGreenFrame ((const u32 *)UI_Get("emerald:ui/unused/gunusedtilemap_redyellowgreenframe"))
#define gUnusedTilemap_RedYellowGreenFrame_SIZE 8192u
#define gUnusedTimemap_OldCharmap ((const u32 *)UI_Get("emerald:ui/unused/gunusedtimemap_oldcharmap"))
#define gUnusedTimemap_OldCharmap_SIZE 4096u
#define gWallClockFemale_Pal ((const u16 *)UI_Get("emerald:ui/wallclock/gwallclockfemale_pal"))
#define gWallClockFemale_Pal_SIZE 32u
#define gWallClockMale_Pal ((const u16 *)UI_Get("emerald:ui/wallclock/gwallclockmale_pal"))
#define gWallClockMale_Pal_SIZE 32u
#define gWallClockStart_Tilemap ((const u32 *)UI_Get("emerald:ui/wallclock/gwallclockstart_tilemap"))
#define gWallClockStart_Tilemap_SIZE 1280u
#define gWallClockView_Tilemap ((const u32 *)UI_Get("emerald:ui/wallclock/gwallclockview_tilemap"))
#define gWallClockView_Tilemap_SIZE 1280u
#define gWallClock_Gfx ((const u32 *)UI_Get("emerald:ui/wallclock/gwallclock_gfx"))
#define gWallClock_Gfx_SIZE 4096u
#endif
