/* Generated by R15 UI family generator (gen_ui_populate.py)
 * Do not edit by hand.
 *
 * Extern declarations for the mutable native UI structs published
 * from the pack by EmeraldUICompat_PopulateStructs(). */
#ifndef EMERALD_RESOURCES_UI_STRUCT_POPULATION_H
#define EMERALD_RESOURCES_UI_STRUCT_POPULATION_H

#if defined(NATIVE_LINUX)
#include "sprite.h"
#include "bg.h"
extern struct CompressedSpriteSheet sSmokescreenImpactSpriteSheet;
extern struct CompressedSpritePalette sSmokescreenImpactSpritePalette;
extern struct CompressedSpriteSheet gSpriteSheet_EnemyShadow;
extern struct CompressedSpriteSheet sBattleArenaJudgmentSymbolsSpriteSheet[];
extern struct CompressedSpriteSheet sVsLettersSpriteSheet;
extern struct CompressedSpriteSheet sTourneyTreeButtonsSpriteSheet[];
extern struct CompressedSpritePalette sTourneyTreeButtonsSpritePal[];
extern struct CompressedSpriteSheet sSpriteSheet_SinglesPlayerHealthbox;
extern struct CompressedSpriteSheet sSpriteSheet_SinglesOpponentHealthbox;
extern struct CompressedSpriteSheet sSpriteSheets_DoublesOpponentHealthbox[];
extern struct CompressedSpriteSheet sSpriteSheet_SafariHealthbox;
extern struct CompressedSpriteSheet sSpriteSheets_HealthBar[];
extern struct SpritePalette sSpritePalettes_HealthBoxHealthBar[];
extern struct CompressedSpriteSheet sStatusSummaryBarSpriteSheet;
extern struct SpritePalette sStatusSummaryBarSpritePal;
extern struct SpritePalette sStatusSummaryBallsSpritePal;
extern struct CompressedSpriteSheet sSpriteSheet_PyramidBag;
extern struct SpriteSheet sSpriteSheet_PlayerArrow;
extern struct SpritePalette sSpritePal_BlenderMisc;
extern struct SpritePalette sSpritePal_PlayerArrow;
extern struct SpriteSheet sSpriteSheet_ScoreSymbols;
extern struct SpriteSheet sSpriteSheet_Particles;
extern struct SpriteSheet sSpriteSheet_CountdownNumbers;
extern struct SpriteSheet sSpriteSheet_Start;
extern struct CompressedSpriteSheet sCableCarSpriteSheets[];
extern struct SpritePalette sCableCarSpritePalettes[];
extern struct SpriteSheet sSpriteSheet_SliderHeart;
extern struct CompressedSpriteSheet sSpriteSheet_NextTurn[];
extern struct SpritePalette sSpritePalette_NextTurn;
extern struct CompressedSpriteSheet sSpriteSheet_Faces;
extern struct CompressedSpriteSheet sSpriteSheet_ApplauseMeter;
extern struct SpritePalette sSpritePalette_ApplauseMeter;
extern struct CompressedSpriteSheet sSpriteSheet_Judge;
extern struct CompressedSpriteSheet sSpriteSheet_JudgeSymbols;
extern struct CompressedSpritePalette sSpritePalette_JudgeSymbols;
extern struct CompressedSpriteSheet sSpriteSheets_ContestantsTurnBlinkEffect[];
extern struct CompressedSpriteSheet sContestConfettiSpriteSheet;
extern struct CompressedSpritePalette sContestConfettiSpritePalette;
extern struct CompressedSpriteSheet sSpriteSheet_MenuPokeball;
extern struct CompressedSpritePalette sSpritePalette_MenuPokeball;
extern struct CompressedSpriteSheet sSpriteSheet_MenuPokeballSmall;
extern struct CompressedSpriteSheet sSpriteSheet_StatusIcons;
extern struct CompressedSpritePalette sSpritePalette_StatusIcons;
extern struct SpriteSheet sCursor_SpriteSheet;
extern struct SpritePalette sCursor_SpritePalette;
extern struct SpritePalette sEasyChatSpritePalettes[];
extern struct CompressedSpriteSheet sEasyChatCompressedSpriteSheets[];
extern struct CompressedSpriteSheet sCursorSpriteSheets[];
extern struct SpritePalette sFrontierPassSpritePalettes[];
extern struct CompressedSpriteSheet sHoFConfettiSpriteSheets[];
extern struct CompressedSpritePalette sHoFConfettiSpritePalettes[];
extern struct CompressedSpriteSheet gBagMaleSpriteSheet;
extern struct CompressedSpriteSheet gBagFemaleSpriteSheet;
extern struct CompressedSpritePalette gBagPaletteTable;
extern struct CompressedSpriteSheet sSpriteSheet_SwapLine;
extern struct CompressedSpritePalette sSpritePalette_SwapLine;
extern struct CompressedSpriteSheet sSpriteSheet_MoneyLabel;
extern struct CompressedSpritePalette sSpritePalette_MoneyLabel;
extern const const u32 *sNextKeyboardPageTilemaps[];
extern struct SpriteSheet sNamingScreenSpriteSheets[];
extern struct CompressedSpriteSheet gPokeblockCase_SpriteSheet;
extern struct CompressedSpritePalette gPokeblockCase_SpritePal;
extern const u32 *sPokeblocksPals[];
extern struct CompressedSpriteSheet sSpriteSheet_Pokeblock;
extern struct CompressedSpriteSheet sInterfaceSpriteSheet[];
extern struct SpritePalette sAreaUnknownSpritePalette;
/* file-local struct kind, definition mirrored from /home/tristen/work/pokeemerald-recomp/src/pokemon_summary_screen.c */
struct TilemapCtrl
{
    const u16 *gfx;
    u16 field_4;
    u8 field_6;
    u8 field_7;
    u8 field_8;
    u8 field_9;
};

extern struct TilemapCtrl sBattleMoveTilemapCtrl;
extern struct TilemapCtrl sContestMoveTilemapCtrl;
extern struct CompressedSpriteSheet sSpriteSheet_MoveTypes;
extern struct CompressedSpriteSheet sMoveSelectorSpriteSheet;
extern struct CompressedSpritePalette sMoveSelectorSpritePal;
extern struct CompressedSpriteSheet sStatusIconsSpriteSheet;
extern struct CompressedSpritePalette sStatusIconsSpritePalette;
extern struct CompressedSpriteSheet sMenuLeftHeaderSpriteSheet;
extern struct CompressedSpriteSheet sMenuLeftHeaderSpriteSheets[];
/* file-local struct kind, definition mirrored from /home/tristen/work/pokeemerald-recomp/src/pokenav_main_menu.c */
struct CompressedSpriteSheetNoSize
{
    const u32 *data;  // LZ77 compressed palette data
    u32 tag;
};

extern struct CompressedSpriteSheetNoSize sPokenavSubMenuLeftHeaderSpriteSheets[];
extern struct CompressedSpriteSheet sPokenavOptionsSpriteSheets[];
extern struct SpritePalette sPokenavOptionsSpritePalettes[];
extern struct CompressedSpriteSheet sCityZoomTextSpriteSheet[];
extern struct SpritePalette sCityZoomTilesSpritePalette[];
extern struct CompressedSpriteSheet sSpriteSheet_Headers;
extern struct CompressedSpriteSheet sRouletteInterfaceSpriteSheets[];
extern struct CompressedSpriteSheet sSpriteSheet_WheelCenter;
extern struct CompressedSpriteSheet sSpriteSheet_EmeraldVersion[];
extern struct CompressedSpriteSheet sSpriteSheet_PressStart[];
extern struct SpritePalette sSpritePalette_PressStart[];
extern const const u16 *sHoennTrainerCardPals[];
extern const const u16 *sKantoTrainerCardPals[];
extern struct CompressedSpriteSheet sUnionRoomChatSpriteSheets[];
extern struct SpriteSheet sSpriteSheet_UpDown;
extern struct SpritePalette sSpritePalette_UpDown;
extern struct SpritePalette sSpritePalette_Condition;
extern struct SpritePalette sSpritePalettes_Clock[];

void EmeraldUICompat_PopulateStructs(void);
void EmeraldUICompat_ClearStructPointers(void);
#endif
#endif
