#ifndef GEN3_RESOURCES_RESOURCE_VERSION_H
#define GEN3_RESOURCES_RESOURCE_VERSION_H

#define RESOURCE_API_VERSION_MAJOR 1
#define RESOURCE_API_VERSION_MINOR 0
#define RESOURCE_API_VERSION_PATCH 0

#define MOD_MANIFEST_VERSION 1
#define MOD_PACK_VERSION 1
#define RESOURCE_PACK_FORMAT_VERSION 1

#endif
