/* Stage 7: production compatibility / linker-load proof (family-wide, R7B/R8).
 *
 * Reuses the ENTIRE Stage R7B/R8 harness (tests/emerald_trainer_native_compat_test.c)
 * - the REAL Emerald decompressor (src/platform/bios.c LZ77UnCompWram), the REAL
 * native trainer front/back tables (front_pic_tables.h + back_pic_tables.h,
 * native non-const branches), the REAL load-path functions (src/decompress.c
 * DecompressPicFromTable_2 / LoadCompressedSpritePalette), the family fixture
 * loaders (descriptor-driven, committed .lz assets decoded by the real
 * decompressor, plus the R8 back-family RAW sheets), the table-state capture +
 * "only the migrated slots changed" assertions, and the R7B/R8 compat seam -
 * but drives the seam with the REAL PRODUCTION ROM_BASE snapshot built from the
 * REAL installed production pack, for the FULL trainer family: 93 front sheets
 * + 93 front palettes + 6 shared back-pic palette consumers (R7B), the 8 back
 * sheets + 2 back-only Red/Leaf palettes (R8), and the 1608-resource Pokémon
 * battle family (R9 §5: 1759 published table slots + the external back-EGG
 * row; every published stream decoded by the real decompressor must equal
 * the pack's canonical decoded bytes):
 *
 *   retail ROM -> production-qualified manifest -> emerald-bpee01-v1.rpack
 *     -> EmeraldResourceSession_BuildRomBaseCandidate (provider id
 *        "emerald.rom-base.bpee01", precedence 300, 1804 entries;
 *        186 trainer-front + 10 trainer-back (R8) + 1608 Pokémon battle (R9))
 *     -> Gen3ResourceCandidate_Build (1804-resource ROM_BASE snapshot;
 *        front+back family contract checks below)
 *     -> EmeraldResourceCompat_InitializeFromSnapshot
 *     -> EmeraldResourceCompatibilityImage (literal-only LZ77 streams)
 *     -> live native trainer tables
 *     -> existing Emerald decompression/load consumers
 *
 * This closes the full production chain in one process: retail bytes -> pack ->
 * snapshot -> compatibility image -> the exact same trainer tables and loaders
 * the running game uses.
 *
 * The family descriptor (resources/extraction/emerald/bpee01/
 * trainer_front_family.toml) drives BOTH sides, so the production chain is
 * verified against the same canonical source artifacts the R7B unit regression
 * pins:
 *   - the 186 canonical payloads are derived from its slug/palette_dir fields
 *     (graphics/trainers/front_pics/<slug>.4bpp.lz + graphics/trainers/
 *     <palette_dir>/<slug>.gbapal.lz, decoded by the REAL decompressor);
 *   - every one of the 186 contracts must resolve through the production
 *     snapshot with a stable key, type/schema, ROM_BASE winner and payload
 *     byte-identical to that canonical payload;
 *   - the seam's resource-id -> table-slot mapping is cross-checked via the
 *     descriptor's index/back_palette_index fields: every published stream
 *     must decode to the canonical payload of the trainer the descriptor
 *     places at that slot.
 *
 * "Byte-for-byte vs canonical" is proven two independent ways:
 *   1. the ROM_BASE snapshot's payloads are byte-identical to the canonical
 *      decoded artifacts, for all 186 resources;
 *   2. the published compatibility streams, decoded by the REAL decompressor
 *      and the REAL DecompressPicFromTable_2 / LoadCompressedSpritePalette
 *      load path, equal those same canonical bytes at the descriptor's table
 *      index.
 *
 * Usage:
 *   emerald_trainer_native_compat_production \
 *     <pack.rpack> --catalog <catalog.toml>... --descriptor <family-descriptor.toml>
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Rename the included R7B harness's main() so it is linkable here but never
 * called; every harness helper (CHECK, LoadFamilyFixturesFrom, FixtureForIndex,
 * BuildFamilyId, Capture*Table, AssertOnlyMigratedChanged, IsMigratedBackPaletteSlot,
 * the load-path functions, the stubs) lands in this translation unit and is
 * reused as-is. The harness's own six tests do NOT run here; the production
 * chain gets its own family-wide sequence below. */
#define main emerald_compat_production_r6_main
#include "emerald_trainer_native_compat_test.c"
#undef main

/* Resource-pack / catalog / session / id headers the R7B harness does not
 * include (or includes only transitively). */
#include "gen3/resources/resource_pack.h"
#include "gen3/resources/resource_id.h"
#include "gen3/resources/toml.h"
#include "gen3/resources/util.h"
#include "emerald/resources/emerald_resource_session.h"
#include "emerald/resources/pokemon_battle_slots.generated.h"

static enum Gen3ResourceType CatalogTypeForName(const char *name)
{
    /* Same vocabulary as the importer's ParseTypeName (the catalog files are
     * generated by the same family generators, so the test loader must accept
     * every type the generated catalogs emit - tileset included). */
    if (name == NULL)
        return GEN3_RESOURCE_TYPE_INVALID;
    if (strcmp(name, "bitmap") == 0)
        return GEN3_RESOURCE_TYPE_BITMAP;
    if (strcmp(name, "tile-graphics") == 0)
        return GEN3_RESOURCE_TYPE_TILE_GRAPHICS;
    if (strcmp(name, "palette") == 0)
        return GEN3_RESOURCE_TYPE_PALETTE;
    if (strcmp(name, "sprite-sheet") == 0)
        return GEN3_RESOURCE_TYPE_SPRITE_SHEET;
    if (strcmp(name, "sprite-metadata") == 0)
        return GEN3_RESOURCE_TYPE_SPRITE_METADATA;
    if (strcmp(name, "tileset") == 0)
        return GEN3_RESOURCE_TYPE_TILESET;
    if (strcmp(name, "tilemap") == 0)
        return GEN3_RESOURCE_TYPE_TILEMAP;
    if (strcmp(name, "font") == 0)
        return GEN3_RESOURCE_TYPE_FONT;
    if (strcmp(name, "text") == 0)
        return GEN3_RESOURCE_TYPE_TEXT;
    if (strcmp(name, "audio-sample") == 0)
        return GEN3_RESOURCE_TYPE_AUDIO_SAMPLE;
    if (strcmp(name, "music-sequence") == 0)
        return GEN3_RESOURCE_TYPE_MUSIC_SEQUENCE;
    if (strcmp(name, "sound-effect") == 0)
        return GEN3_RESOURCE_TYPE_SOUND_EFFECT;
    if (strcmp(name, "cry") == 0)
        return GEN3_RESOURCE_TYPE_CRY;
    if (strcmp(name, "binary") == 0)
        return GEN3_RESOURCE_TYPE_BINARY;
    if (strcmp(name, "instrument-bank") == 0)
        return GEN3_RESOURCE_TYPE_INSTRUMENT_BANK;
    if (strcmp(name, "structured-data") == 0)
        return GEN3_RESOURCE_TYPE_STRUCTURED_DATA;
    return GEN3_RESOURCE_TYPE_INVALID;
}

/* Append every resource of one catalog TOML file to `catalog` (R9 Stage 4:
 * the real pack contract spans several family catalogs). Duplicate ids are
 * rejected by Gen3ResourceCatalog_Add, matching the importer's fail-closed
 * merge. */
static bool AddCatalogFile(struct Gen3ResourceCatalog *catalog, const char *path)
{
    struct Gen3Buffer buf;
    struct Gen3TomlDocument doc;
    struct Gen3ResourceDiagnosticList diag;
    char errbuf[512];
    size_t i;
    bool ok = false;

    if (!Gen3Util_ReadFile(path, &buf, errbuf, sizeof(errbuf)))
    {
        fprintf(stderr, "catalog read: %s\n", errbuf);
        return false;
    }
    if (!Gen3Toml_Parse(buf.data, buf.length, &doc, errbuf, sizeof(errbuf)))
    {
        fprintf(stderr, "catalog parse: %s\n", errbuf);
        Gen3Buffer_Destroy(&buf);
        return false;
    }
    Gen3ResourceDiagnostics_Init(&diag);
    for (i = 0; i < Gen3Toml_GetArrayCount(&doc.root, "resources"); i++)
    {
        const struct Gen3TomlMap *item =
            Gen3Toml_GetArrayItem(&doc.root, "resources", i);
        const char *id, *type;
        long long schema;
        bool required = false;
        if (!Gen3Toml_GetString(item, "id", &id)
         || !Gen3Toml_GetString(item, "type", &type)
         || !Gen3Toml_GetInteger(item, "schema", &schema))
        {
            fprintf(stderr, "catalog record %zu missing id/type/schema\n", i);
            goto done;
        }
        Gen3Toml_GetBool(item, "required_for_base", &required);
        if (!Gen3ResourceCatalog_Add(catalog, id, CatalogTypeForName(type),
                                     (uint32_t)schema, required, &diag))
        {
            fprintf(stderr, "catalog add failed for %s\n", id);
            goto done;
        }
    }
    ok = true;
done:
    Gen3ResourceDiagnostics_Destroy(&diag);
    Gen3Toml_Destroy(&doc);
    Gen3Buffer_Destroy(&buf);
    return ok;
}

/* Resolve ONE family contract through the production snapshot and verify it
 * byte-for-byte against the canonical fixture (itself the committed-.lz decode
 * the R7B unit regression pins). Runs its own CHECKs. */
static void CheckFamilyContract(struct Gen3ResourceSnapshot *snapshot,
                                const char *name,
                                enum Gen3ResourceType type,
                                const u8 *canonical, u32 canonicalSize,
                                const char *what)
{
    struct Gen3ResourceView view;
    Gen3ResourceHandle handle;
    Gen3ResourceKey derivedKey;
    char label[160];

    CHECK("find handle",
          Gen3ResourceSnapshot_FindHandle(snapshot, name, &handle) == GEN3_RESOURCE_OK);
    snprintf(label, sizeof(label), "%s resolves", what);
    CHECK(label, Gen3ResourceSnapshot_Resolve(snapshot, handle, type, 1u, &view)
                     == GEN3_RESOURCE_OK);
    Gen3ResourceId_DeriveKey(name, &derivedKey);
    snprintf(label, sizeof(label), "%s key is the derived stable key", what);
    CHECK(label, memcmp(view.key.bytes, derivedKey.bytes, GEN3_RESOURCE_KEY_SIZE) == 0);
    snprintf(label, sizeof(label), "%s type/schema", what);
    CHECK(label, view.type == type && view.schema == 1u);
    snprintf(label, sizeof(label), "%s winner is ROM_BASE", what);
    CHECK(label, view.winningProviderId != NULL
                     && strcmp(view.winningProviderId, EMERALD_ROM_BASE_PROVIDER_ID) == 0
                     && view.winningProviderPrecedence == EMERALD_ROM_BASE_PRECEDENCE);
    snprintf(label, sizeof(label), "%s payload == canonical (%zu bytes)", what,
             (size_t)canonicalSize);
    CHECK(label, view.payloadSize == canonicalSize
                     && memcmp(view.payload, canonical, canonicalSize) == 0);
}

/* The data.c metadata the Pokémon tables are stamped with pre-publish: sheets
 * carry MON_PIC_SIZE (2048, decoded sheet bytes) with the slot index as tag;
 * palettes carry size 0 with the slot index as tag (CompressedSpritePalette
 * consumers key on tag; sizes are only meaningful for sheets). */
#define MON_SHEET_STAMP_SIZE 2048u

/* R9 §5: verify the published Pokémon battle family against the production
 * pack. For every one of the 1760 slots: the size/tag stamp is retained (only
 * .data changes); external slots (the back-EGG row) stay NULL; every published
 * slot holds exactly its mapping resource's pack payload - the retail GBA LZ77
 * stream served verbatim - with the stream header declaring the mapping's
 * decoded size. */
static void VerifyPokemonPublished(const struct Gen3ResourcePack *pack)
{
    size_t kind;
    size_t idx;
    char label[96];

    for (kind = 0u; kind < 4u; kind++)
    {
        const struct CompressedSpriteSheet *sheet =
            kind <= 1u ? (kind == 0u ? gMonFrontPicTable : gMonBackPicTable)
                       : NULL;
        const struct CompressedSpritePalette *pal =
            kind >= 2u ? (kind == 2u ? gMonPaletteTable : gMonShinyPaletteTable)
                       : NULL;

        for (idx = 0u; idx < POKEMON_BATTLE_SLOTS_PER_TABLE; idx++)
        {
            const void *data = sheet != NULL ? (const void *)sheet[idx].data
                                             : (const void *)pal[idx].data;
            /* CompressedSpritePalette carries no size - only tag. */
            const u32 size = sheet != NULL ? sheet[idx].size : 0u;
            const u16 tag = sheet != NULL ? sheet[idx].tag : pal[idx].tag;
            const int32_t ri = kPokemonBattleCompatSlots[
                kind * POKEMON_BATTLE_SLOTS_PER_TABLE + idx];
            const struct Gen3ResourcePackEntry *entry;

            snprintf(label, sizeof(label),
                     "mon table %zu slot %zu size/tag retained", kind, idx);
            CHECK(label, size == (sheet != NULL ? MON_SHEET_STAMP_SIZE : 0u)
                             && tag == idx);
            if (ri == POKEMON_BATTLE_EXTERNAL_SLOT)
            {
                snprintf(label, sizeof(label),
                         "mon table %zu slot %zu external stays compiled",
                         kind, idx);
                CHECK(label, data == NULL);
                continue;
            }
            snprintf(label, sizeof(label),
                     "mon table %zu slot %zu published", kind, idx);
            CHECK(label, data != NULL);
            if (data == NULL)
                continue;
            entry = Gen3ResourcePack_FindByCanonicalName(
                pack, kPokemonBattleCompatResources[ri].id);
            snprintf(label, sizeof(label),
                     "mon table %zu slot %zu resolves in pack", kind, idx);
            CHECK(label, entry != NULL);
            if (entry == NULL)
                continue;
            /* The pack stores the DECODED representation; the published
             * stream is the seam's re-encoded GBA LZ77 stream. Decode it
             * with the REAL consumer decompressor and prove it equals the
             * pack's canonical decoded bytes - the strongest form of the
             * Stage 3 three-way equality, exercised through the live table. */
            {
                u8 *decoded = (u8 *)malloc(entry->payloadSize);
                snprintf(label, sizeof(label),
                         "mon table %zu slot %zu stream decodes to pack bytes",
                         kind, idx);
                CHECK(label, decoded != NULL);
                if (decoded == NULL)
                    continue;
                memset(decoded, 0, entry->payloadSize);
                LZ77UnCompWram((const u32 *)(const void *)data, decoded);
                CHECK(label, memcmp(decoded, entry->payload,
                                    entry->payloadSize) == 0);
                snprintf(label, sizeof(label),
                         "mon table %zu slot %zu stream header == mapping size",
                         kind, idx);
                CHECK(label, ((const u8 *)data)[0] == 0x10u
                         && ((const u8 *)data)[1]
                                == (u8)(kPokemonBattleCompatResources[ri].expectedSize & 0xFFu)
                         && ((const u8 *)data)[2]
                                == (u8)((kPokemonBattleCompatResources[ri].expectedSize >> 8) & 0xFFu));
                free(decoded);
            }
        }
    }
}

/* ClearMigratedEntries leaves exactly the published slots NULL (external slot
 * untouched) and retains the size/tag stamp. */
static void VerifyPokemonCleared(void)
{
    size_t kind;
    size_t idx;
    char label[96];

    for (kind = 0u; kind < 4u; kind++)
    {
        const struct CompressedSpriteSheet *sheet =
            kind <= 1u ? (kind == 0u ? gMonFrontPicTable : gMonBackPicTable)
                       : NULL;
        const struct CompressedSpritePalette *pal =
            kind >= 2u ? (kind == 2u ? gMonPaletteTable : gMonShinyPaletteTable)
                       : NULL;

        for (idx = 0u; idx < POKEMON_BATTLE_SLOTS_PER_TABLE; idx++)
        {
            const void *data = sheet != NULL ? (const void *)sheet[idx].data
                                             : (const void *)pal[idx].data;
            /* CompressedSpritePalette carries no size - only tag. */
            const u32 size = sheet != NULL ? sheet[idx].size : 0u;
            const u16 tag = sheet != NULL ? sheet[idx].tag : pal[idx].tag;

            snprintf(label, sizeof(label),
                     "mon table %zu slot %zu cleared", kind, idx);
            CHECK(label, data == NULL && size
                     == (sheet != NULL ? MON_SHEET_STAMP_SIZE : 0u)
                     && tag == idx);
        }
    }
}

/* R9 §6/§8e: special-case pins on the PUBLISHED tables. The policy makes
 * every special case mapping data (kPokemonBattleCompatSlots); these checks
 * prove the seam serves the aliasing and size classes exactly: shared-ri
 * slots publish THE SAME stream pointer, the egg shiny slot reuses the
 * normal-palette stream, the old-unown rows are the question-mark/double
 * family, the multi-frame sheets decode to their declared classes, and the
 * Deoxys front stream is fixup-compatible with the game's
 * DuplicateDeoxysTiles. */
static void VerifyPokemonSpecialCases(void)
{
    size_t s;
    char label[96];

    /* 1. Unown family shared palettes: species 201 + the 27 form slots
     * (413..439) all publish one normal-palette stream and one shiny-palette
     * stream (kPokemonBattleCompatResources[1422]/[1423] - one payload for
     * the whole family, exactly like data.c's shared palette entry). */
    for (s = 413u; s <= 439u; s++)
    {
        snprintf(label, sizeof(label),
                 "unown pal slot %zu shares species-201 stream", s);
        CHECK(label, gMonPaletteTable[s].data
                         == gMonPaletteTable[SPECIES_UNOWN].data);
        snprintf(label, sizeof(label),
                 "unown shiny slot %zu shares species-201 stream", s);
        CHECK(label, gMonShinyPaletteTable[s].data
                         == gMonShinyPaletteTable[SPECIES_UNOWN].data);
    }

    /* 2. Egg shiny aliases the egg NORMAL palette stream (no shiny egg -
     * both slots map kPokemonBattleCompatResources[329]). */
    CHECK("egg shiny slot reuses egg normal stream",
          gMonShinyPaletteTable[SPECIES_EGG].data
              == gMonPaletteTable[SPECIES_EGG].data);

    /* 3. Old-unown rows (252..276) are the question-mark/double family: every
     * one of the 25 rows publishes the same front sheet stream, the same back
     * sheet stream, the same normal-palette stream and the same shiny-palette
     * stream (ri 1039/1038/1040/1041 - one payload per kind). */
    for (s = 253u; s <= 276u; s++)
    {
        snprintf(label, sizeof(label),
                 "old-unown front slot %zu shares 252 stream", s);
        CHECK(label, gMonFrontPicTable[s].data
                         == gMonFrontPicTable[SPECIES_OLD_UNOWN_B].data);
        snprintf(label, sizeof(label),
                 "old-unown back slot %zu shares 252 stream", s);
        CHECK(label, gMonBackPicTable[s].data
                         == gMonBackPicTable[SPECIES_OLD_UNOWN_B].data);
        snprintf(label, sizeof(label),
                 "old-unown pal slot %zu shares 252 stream", s);
        CHECK(label, gMonPaletteTable[s].data
                         == gMonPaletteTable[SPECIES_OLD_UNOWN_B].data);
        snprintf(label, sizeof(label),
                 "old-unown shiny slot %zu shares 252 stream", s);
        CHECK(label, gMonShinyPaletteTable[s].data
                         == gMonShinyPaletteTable[SPECIES_OLD_UNOWN_B].data);
    }

    /* 4. Slot 0 fallback identity: the four kinds publish the
     * question_mark/circled family (ri 1035/1034/1036/1037) - published, and
     * DISTINCT from the old-unown double family (different resources). */
    CHECK("slot 0 front published", gMonFrontPicTable[0].data != NULL);
    CHECK("slot 0 back published", gMonBackPicTable[0].data != NULL);
    CHECK("slot 0 pal published", gMonPaletteTable[0].data != NULL);
    CHECK("slot 0 shiny published", gMonShinyPaletteTable[0].data != NULL);
    CHECK("slot 0 front != old-unown front (circled vs double)",
          gMonFrontPicTable[0].data != gMonFrontPicTable[SPECIES_OLD_UNOWN_B].data);

    /* 5. Multi-frame / multi-palette size classes: decode each published
     * stream into a guarded buffer and prove the header declares the class
     * and the decode stays inside it (spot classes: Castform 8192/128,
     * Deoxys 4096, Spinda front 4096, Egg front 4096, Unown front 4096). */
    {
        enum SizeClassKind
        {
            KIND_FRONT,
            KIND_BACK,
            KIND_PAL,
            KIND_SHINY,
        };
        static const struct
        {
            u16 species;
            enum SizeClassKind kind;
            u32 size;
            const char *what;
        } kSizeClass[] = {
            { SPECIES_CASTFORM, KIND_FRONT, 8192u, "castform front" },
            { SPECIES_CASTFORM, KIND_BACK,  8192u, "castform back" },
            { SPECIES_CASTFORM, KIND_PAL,   128u,  "castform palette" },
            { SPECIES_CASTFORM, KIND_SHINY, 128u,  "castform shiny" },
            { SPECIES_DEOXYS,   KIND_FRONT, 4096u, "deoxys front" },
            { SPECIES_DEOXYS,   KIND_BACK,  4096u, "deoxys back" },
            { SPECIES_SPINDA,   KIND_FRONT, 4096u, "spinda front" },
            { SPECIES_EGG,      KIND_FRONT, 4096u, "egg front" },
            { SPECIES_UNOWN,    KIND_FRONT, 4096u, "unown front" },
        };
        size_t c;

        for (c = 0u; c < sizeof(kSizeClass) / sizeof(kSizeClass[0]); c++)
        {
            const struct CompressedSpriteSheet *sheet;
            const struct CompressedSpritePalette *pal;
            const void *stream;
            u8 *buf;

            if (kSizeClass[c].kind == KIND_FRONT)
                sheet = &gMonFrontPicTable[kSizeClass[c].species];
            else if (kSizeClass[c].kind == KIND_BACK)
                sheet = &gMonBackPicTable[kSizeClass[c].species];
            else if (kSizeClass[c].kind == KIND_PAL)
                pal = &gMonPaletteTable[kSizeClass[c].species];
            else
                pal = &gMonShinyPaletteTable[kSizeClass[c].species];
            stream = kSizeClass[c].kind <= KIND_BACK
                         ? (const void *)sheet->data
                         : (const void *)pal->data;
            buf = (u8 *)malloc(kSizeClass[c].size + 4u);
            snprintf(label, sizeof(label), "%s stream present",
                     kSizeClass[c].what);
            CHECK(label, stream != NULL && buf != NULL);
            if (stream == NULL || buf == NULL)
            {
                free(buf);
                continue;
            }
            memset(buf, 0xA5, kSizeClass[c].size + 4u);
            LZ77UnCompWram((const u32 *)(const void *)stream, buf);
            snprintf(label, sizeof(label), "%s header declares %u",
                     kSizeClass[c].what, kSizeClass[c].size);
            CHECK(label, ((const u8 *)stream)[0] == 0x10u
                     && ((const u8 *)stream)[1] == (u8)(kSizeClass[c].size & 0xFFu)
                     && ((const u8 *)stream)[2] == (u8)((kSizeClass[c].size >> 8) & 0xFFu));
            snprintf(label, sizeof(label), "%s decodes inside %u (no overrun)",
                     kSizeClass[c].what, kSizeClass[c].size);
            CHECK(label, buf[kSizeClass[c].size] == 0xA5u
                     && buf[kSizeClass[c].size + 1u] == 0xA5u
                     && buf[kSizeClass[c].size + 2u] == 0xA5u
                     && buf[kSizeClass[c].size + 3u] == 0xA5u);
            free(buf);
        }
    }

    /* 6. Deoxys fixup compatibility: the game's DuplicateDeoxysTiles copies
     * frame 1 over frame 0 on the DECODED front sheet (CpuCopy32(src=frame1,
     * dest=frame0); battle_controller / DecompressPicFromTable_2 path). Run
     * it on the published stream's decode and prove frame 0 becomes frame
     * 1's content with frame 1 untouched (pure-memory, no tables). */
    {
        u8 deoxys[4096u];
        u8 before1[2048u];

        LZ77UnCompWram((const u32 *)(const void *)
                           gMonFrontPicTable[SPECIES_DEOXYS].data,
                       deoxys);
        memcpy(before1, deoxys + 2048u, sizeof(before1));
        DuplicateDeoxysTiles(deoxys, SPECIES_DEOXYS);
        CHECK("deoxys duplication makes frame 0 == original frame 1",
              memcmp(deoxys, before1, sizeof(before1)) == 0);
        CHECK("deoxys duplication leaves frame 1 unchanged",
              memcmp(deoxys + 2048u, before1, sizeof(before1)) == 0);
    }
}

static void VerifySpotDecode(const char *table, u16 species, int32_t ri,
                             const void *stream);

/* Real-decompressor acceptance on published retail streams, spot species: the
 * FULL byte-level canonical decode is the Stage 8 family test; here the point
 * is that the REAL consumer codec (bios.c LZ77UnCompWram) accepts each
 * published stream and honors its header-declared length - decode into a
 * guarded buffer and prove no overrun (guard intact) and non-degenerate
 * output. */
static void VerifyPokemonSpotDecodes(void)
{
    static const u16 kSpot[] = {
        SPECIES_BULBASAUR, SPECIES_CHARIZARD, SPECIES_UNOWN_Z,
        SPECIES_CASTFORM, SPECIES_DEOXYS, SPECIES_SPINDA, SPECIES_EGG,
    };
    size_t s;

    for (s = 0u; s < sizeof(kSpot) / sizeof(kSpot[0]); s++)
    {
        const u16 species = kSpot[s];
        int32_t front = kPokemonBattleCompatSlots[species];
        int32_t back = kPokemonBattleCompatSlots[
            POKEMON_BATTLE_SLOTS_PER_TABLE + species];
        VerifySpotDecode("front", species, front, gMonFrontPicTable[species].data);
        VerifySpotDecode("back", species, back, gMonBackPicTable[species].data);
    }
}

static void VerifySpotDecode(const char *table, u16 species, int32_t ri,
                             const void *stream)
{
    u32 expected;
    u8 *buf;
    u32 sum = 0u;
    u32 k;
    char label[96];

    if (ri == POKEMON_BATTLE_EXTERNAL_SLOT)
    {
        /* back EGG: no canonical - the slot is the compiled
         * gMonStillFrontPic_Egg and is never part of this family. */
        snprintf(label, sizeof(label), "spot %s %u external stays compiled",
                 table, species);
        CHECK(label, stream == NULL);
        return;
    }
    expected = kPokemonBattleCompatResources[ri].expectedSize;
    buf = (u8 *)malloc(expected + 4u);
    if (buf == NULL)
    {
        printf("FAIL: out of memory decoding spot %u\n", species);
        gFailures++;
        return;
    }
    memset(buf, 0xA5, expected + 4u);
    LZ77UnCompWram((const u32 *)(const void *)stream, buf);
    snprintf(label, sizeof(label),
             "spot %s %u decodes within declared size", table, species);
    CHECK(label, buf[expected] == 0xA5u && buf[expected + 1u] == 0xA5u
              && buf[expected + 2u] == 0xA5u && buf[expected + 3u] == 0xA5u);
    for (k = 0u; k < expected; k++)
        sum += buf[k];
    snprintf(label, sizeof(label), "spot %s %u decodes to data", table, species);
    CHECK(label, sum != 0u);
    free(buf);
}

int main(int argc, char **argv)
{
    struct Gen3ResourcePack *pack = NULL;
    struct Gen3ResourcePackDiagnosticList packDiag;
    struct Gen3ResourceCatalog *catalog = NULL;
    struct Gen3ResourceCandidate *candidate = NULL;
    struct Gen3ResourceSnapshot *snapshot = NULL;
    struct Gen3ResourceDiagnosticList gdiag;
    struct EmeraldResourceSessionInfo info;
    struct EmeraldResourceCompatDiagnostics cdiag;
    enum EmeraldResourceSessionError sessionError;
    enum EmeraldResourceCompatStatus status;
    struct CompressedSpriteSheet beforeSheet[ARRAY_COUNT(gTrainerFrontPicTable)];
    struct CompressedSpritePalette beforePal[ARRAY_COUNT(gTrainerFrontPicPaletteTable)];
    struct CompressedSpritePalette beforeBackPal[ARRAY_COUNT(gTrainerBackPicPaletteTable)];
    struct CompressedSpriteSheet beforeBackSheet[ARRAY_COUNT(gTrainerBackPicTable)];
    struct BackFrameCapture beforeBackFrames;
    u8 decodedSheet[EMERALD_TRAINER_SHEET_SIZE];
    u8 decodedPalette[EMERALD_TRAINER_PALETTE_SIZE];
    u8 decodedBackSheet[10240]; /* largest back sheet: red/leaf, 5 frames */
    char id[128];
    char label[160];
    size_t i;
    const char *descriptor = NULL;

    {
        const char *catalogPaths[16];
        size_t catalogCount = 0u;
        int arg;
        for (arg = 2; arg < argc; arg++)
        {
            if (strcmp(argv[arg], "--catalog") == 0 && arg + 1 < argc
             && catalogCount < sizeof(catalogPaths) / sizeof(catalogPaths[0]))
            {
                catalogPaths[catalogCount++] = argv[++arg];
            }
            else if (strcmp(argv[arg], "--descriptor") == 0 && arg + 1 < argc)
            {
                descriptor = argv[++arg];
            }
            else
            {
                fprintf(stderr, "usage: %s <pack.rpack> --catalog <catalog.toml>... "
                                "--descriptor <family-descriptor.toml>\n", argv[0]);
                return 2;
            }
        }
        if (catalogCount == 0u || descriptor == NULL)
        {
            fprintf(stderr, "usage: %s <pack.rpack> --catalog <catalog.toml>... "
                            "--descriptor <family-descriptor.toml>\n", argv[0]);
            return 2;
        }
        catalog = Gen3ResourceCatalog_Create();
        if (catalog == NULL)
        {
            fprintf(stderr, "out of memory creating catalog\n");
            return 1;
        }
        for (arg = 0; (size_t)arg < catalogCount; arg++)
        {
            if (!AddCatalogFile(catalog, catalogPaths[arg]))
            {
                Gen3ResourceCatalog_Destroy(catalog);
                return 1;
            }
        }
        Gen3ResourceDiagnostics_Init(&gdiag);
        if (!Gen3ResourceCatalog_Finalize(catalog, &gdiag))
        {
            fprintf(stderr, "catalog finalize failed\n");
            Gen3ResourceDiagnostics_Destroy(&gdiag);
            Gen3ResourceCatalog_Destroy(catalog);
            return 1;
        }
        Gen3ResourceDiagnostics_Destroy(&gdiag);
    }

    printf("== Stage 7: production compatibility / linker-load proof "
           "(family-wide) ==\n");

    /* 0. Canonical payloads: the descriptor-driven fixture load. Each fixture
     * is the REAL committed .lz artifact (graphics/trainers/front_pics/<slug>
     * .4bpp.lz + graphics/trainers/<palette_dir>/<slug>.gbapal.lz) decoded by
     * the REAL decompressor - exactly the bytes the R7B unit regression pins,
     * so the production chain demonstrably serves the same canonical content. */
    CHECK("family fixtures load from production descriptor",
          LoadFamilyFixturesFrom(descriptor));
    CHECK("back fixtures load (committed R8 descriptor)",
          LoadBackFamilyFixtures());
    if (gFailures != 0)
        return 1;

    /* 1. Open the REAL installed production pack. */
    Gen3ResourcePackDiagnostics_Init(&packDiag);
    if (Gen3ResourcePack_OpenFile(argv[1], &pack, &packDiag) != GEN3_PACK_OK
     || pack == NULL)
    {
        printf("FAIL: cannot open pack '%s'\n", argv[1]);
        Gen3ResourcePackDiagnostics_Destroy(&packDiag);
        Gen3ResourceCatalog_Destroy(catalog);
        return 1;
    }
    Gen3ResourcePackDiagnostics_Destroy(&packDiag);
    printf("opened production pack : %zu entries\n", Gen3ResourcePack_GetEntryCount(pack));
    CHECK("production pack has 20501 entries (196 trainer + 1608 Pokémon "
          "battle + 288 object-event + 1544 tileset + 882 layout + 771 audio + 530 song graphs + 1057 leaf + 5187 text + 3310 D1 + 377 items + 1775 E1 + 210 E2 + 786 E3a-1)",
          Gen3ResourcePack_GetEntryCount(pack) == 20501u);
    printf("loaded catalog          : %zu resources\n", Gen3ResourceCatalog_Count(catalog));
    CHECK("catalog has 20501 resources (196 trainer + 1608 Pokémon battle + "
          "288 object-event + 1544 tileset + 882 layout + 771 audio + 530 song graphs + 1057 leaf + 5187 text + 3310 D1 + 377 items + 1775 E1 + 210 E2 + 786 E3a-1)",
          Gen3ResourceCatalog_Count(catalog) == 20501u);

    /* 3. Build the production ROM_BASE candidate + snapshot from the real pack. */
    Gen3ResourceDiagnostics_Init(&gdiag);
    memset(&info, 0, sizeof(info));
    sessionError = EmeraldResourceSession_BuildRomBaseCandidate(
        pack, catalog, &candidate, &info, &gdiag);
    CHECK("BuildRomBaseCandidate ok",
          sessionError == EMERALD_SESSION_OK && candidate != NULL);
    if (sessionError != EMERALD_SESSION_OK || candidate == NULL)
    {
        printf("FAIL: BuildRomBaseCandidate (%d)\n", (int)sessionError);
        for (i = 0; i < gdiag.count; i++)
        {
            printf("  diag %zu: reason=%s resource='%s' provider='%s' "
                   "expectedType=%d actualType=%d expectedSchema=%u actualSchema=%u\n",
                   i, Gen3ResourceReason_Describe(gdiag.items[i].reason),
                   gdiag.items[i].resourceName, gdiag.items[i].providerId,
                   (int)gdiag.items[i].expectedType, (int)gdiag.items[i].actualType,
                   gdiag.items[i].expectedSchema, gdiag.items[i].actualSchema);
        }
        Gen3ResourceDiagnostics_Destroy(&gdiag);
        Gen3ResourceCatalog_Destroy(catalog);
        Gen3ResourcePack_Destroy(pack);
        return 1;
    }
    printf("ROM_BASE provider       : %s %s kind=%d precedence=%u entryCount=%zu\n",
           info.providerId, info.providerVersion, (int)info.kind,
           info.precedence, info.entryCount);
    CHECK("provider id is emerald.rom-base.bpee01",
          strcmp(info.providerId, EMERALD_ROM_BASE_PROVIDER_ID) == 0);
    CHECK("provider precedence 300", info.precedence == EMERALD_ROM_BASE_PRECEDENCE);
    CHECK("provider version v1", strcmp(info.providerVersion, "v1") == 0);
    CHECK("provider entryCount 20501 (196 trainer + 1608 Pokémon + 288 object-event + 1544 tileset + 882 layout + 771 audio + 530 song graphs + 1057 leaf + 5187 text + 3310 D1 + 377 items + 1775 E1 + 210 E2 + 786 E3a-1)",
          info.entryCount == 20501u);

    CHECK("snapshot builds",
          Gen3ResourceCandidate_Build(candidate, &snapshot, &gdiag) && snapshot != NULL);
    Gen3ResourceDiagnostics_Destroy(&gdiag);
    if (snapshot == NULL)
    {
        printf("FAIL: candidate build\n");
        Gen3ResourceCandidate_Destroy(candidate);
        Gen3ResourceCatalog_Destroy(catalog);
        Gen3ResourcePack_Destroy(pack);
        return 1;
    }

    /* 4. Production snapshot content == canonical artifacts for ALL 186
     * contracts (independent of the intermediate pack entry checks). */
    for (i = 0; i < EMERALD_TRAINER_FRONT_COUNT; i++)
    {
        const struct FamilyTrainerFixture *fix = FixtureForIndex((int)i);
        BuildFamilyId(id, sizeof(id), fix->canonical, false);
        snprintf(label, sizeof(label), "sheet %zu (%s)", i, fix->canonical);
        CheckFamilyContract(snapshot, id, GEN3_RESOURCE_TYPE_TILE_GRAPHICS,
                            fix->sheet, EMERALD_TRAINER_SHEET_SIZE, label);
        BuildFamilyId(id, sizeof(id), fix->canonical, true);
        snprintf(label, sizeof(label), "palette %zu (%s)", i, fix->canonical);
        CheckFamilyContract(snapshot, id, GEN3_RESOURCE_TYPE_PALETTE,
                            fix->palette, EMERALD_TRAINER_PALETTE_SIZE, label);
    }

    /* 5. Pristine pre-publish baseline: fresh process, no prior publish, so
     * every migrated slot starts at the NULL sentinel (no legacy leaf symbols
     * linked on native, R7B §4/§14-A; R8 removes the Red/Leaf compiled pointers
     * too - all 8 back-palette slots, all 8 back SHEET table slots and all 34
     * back SpriteFrameImage slots start NULL). */
    for (i = 0; i < ARRAY_COUNT(gTrainerFrontPicTable); i++)
        CHECK("front sheet slot starts NULL (no legacy dep)",
              gTrainerFrontPicTable[i].data == NULL);
    for (i = 0; i < ARRAY_COUNT(gTrainerFrontPicPaletteTable); i++)
        CHECK("front palette slot starts NULL (no legacy dep)",
              gTrainerFrontPicPaletteTable[i].data == NULL);
    for (i = 0; i < ARRAY_COUNT(gTrainerBackPicPaletteTable); i++)
        CHECK("back-pal slot starts NULL (no legacy dep)",
              gTrainerBackPicPaletteTable[i].data == NULL);
    for (i = 0; i < ARRAY_COUNT(gTrainerBackPicTable); i++)
        CHECK("back sheet slot starts NULL (no legacy dep)",
              gTrainerBackPicTable[i].data == NULL);
    for (i = 0; i < ARRAY_COUNT(gTrainerBackPicTable); i++)
    {
        size_t f;
        for (f = 0; f < sBackFixtures[i].frames; f++)
            CHECK("back frame slot starts NULL (no legacy dep)",
                  kBackFrameArrays[i][f].data == NULL);
    }
    CaptureSheetTable(beforeSheet);
    CapturePaletteTable(beforePal);
    CaptureBackPaletteTable(beforeBackPal);
    CaptureBackSheetTable(beforeBackSheet);
    CaptureBackFrames(&beforeBackFrames);

    /* 5c. R9 §5: the four Pokémon battle tables start at the NULL sentinel in
     * every one of the 1760 slots, and are stamped so publication can be
     * proven to touch ONLY .data: sheets get MON_PIC_SIZE (2048) with the slot
     * index as tag, palettes keep size 0 with the slot index as tag - the same
     * metadata shape data.c gives them, retained after init. */
    for (i = 0; i < POKEMON_BATTLE_SLOTS_PER_TABLE; i++)
    {
        CHECK("mon front slot starts NULL", gMonFrontPicTable[i].data == NULL);
        CHECK("mon back slot starts NULL", gMonBackPicTable[i].data == NULL);
        CHECK("mon palette slot starts NULL", gMonPaletteTable[i].data == NULL);
        CHECK("mon shiny slot starts NULL", gMonShinyPaletteTable[i].data == NULL);
        gMonFrontPicTable[i].size = MON_SHEET_STAMP_SIZE;
        gMonFrontPicTable[i].tag = (u16)i;
        gMonBackPicTable[i].size = MON_SHEET_STAMP_SIZE;
        gMonBackPicTable[i].tag = (u16)i;
        gMonPaletteTable[i].tag = (u16)i;
        gMonShinyPaletteTable[i].tag = (u16)i;
    }

    /* 6. Publish through the R7B compatibility seam with the production
     * snapshot. */
    status = EmeraldResourceCompat_InitializeFromSnapshot(snapshot, &cdiag);
    CHECK("initialize ok", status == EMERALD_COMPAT_OK);
    CHECK("success diagnostics empty", cdiag.stage[0] == '\0');

    /* 7. Only the migrated data slots changed (236: 186 front + 6 shared
     * back-pal + 2 Red/Leaf back-pal + 8 back sheets + 34 back frames); every
     * other entry of the five live tables is byte-identical - size/tag
     * included (R7B §4/§7, R8). */
    AssertOnlyMigratedChanged(beforeSheet, beforePal, beforeBackPal,
                              beforeBackSheet, &beforeBackFrames);

    /* 8. Shared back-pic palette consumers: the six gTrainerBackPicPaletteTable
     * slots publish the SAME normal-palette stream as their owner trainer's
     * front palette (battle_controller_player.c indexes it by player gender),
     * and each decodes to the owner's canonical palette. */
    for (i = 0; i < EMERALD_TRAINER_FRONT_COUNT; i++)
    {
        const struct FamilyTrainerFixture *fix = FixtureForIndex((int)i);
        if (fix->backPaletteIndex < 0)
            continue;
        snprintf(label, sizeof(label), "shared back %d reuses %s's front stream",
                 fix->backPaletteIndex, fix->canonical);
        CHECK(label, gTrainerBackPicPaletteTable[fix->backPaletteIndex].data
                         == gTrainerFrontPicPaletteTable[i].data);
        LZ77UnCompWram((const u32 *)(const void *)
                           gTrainerBackPicPaletteTable[fix->backPaletteIndex].data,
                       decodedPalette);
        snprintf(label, sizeof(label), "shared back %d decodes to owner palette",
                 fix->backPaletteIndex);
        CHECK(label, memcmp(decodedPalette, fix->palette,
                            EMERALD_TRAINER_PALETTE_SIZE) == 0);
    }

    /* 9. Real decompressor on the published compat streams == canonical, for
     * all 93 sheets + 93 palettes, at the descriptor's table index. */
    for (i = 0; i < ARRAY_COUNT(gTrainerFrontPicTable); i++)
    {
        const struct FamilyTrainerFixture *fix = FixtureForIndex((int)i);
        LZ77UnCompWram((const u32 *)(const void *)gTrainerFrontPicTable[i].data,
                       decodedSheet);
        snprintf(label, sizeof(label), "compat sheet %zu decodes to canonical", i);
        CHECK(label, memcmp(decodedSheet, fix->sheet,
                            EMERALD_TRAINER_SHEET_SIZE) == 0);
        LZ77UnCompWram((const u32 *)(const void *)gTrainerFrontPicPaletteTable[i].data,
                       decodedPalette);
        snprintf(label, sizeof(label), "compat palette %zu decodes to canonical", i);
        CHECK(label, memcmp(decodedPalette, fix->palette,
                            EMERALD_TRAINER_PALETTE_SIZE) == 0);
    }

    /* 9b. R8: the back family through the PRODUCTION chain. The 10 back
     * contracts (8 raw sheets + 2 Red/Leaf palettes) must resolve through the
     * production snapshot byte-identical to the committed artifacts, and the
     * published live tables must expose them exactly as the GBA runtime
     * consumes them: RAW sheet streams verbatim (the sprite pipeline copies
     * images[frame].data into OBJ VRAM; DecompressTrainerBackPic LZ77-decodes
     * these same bytes), the 34 frame slots pointing into the sheet stream at
     * per-frame offsets, and the Red/Leaf palette slots decoding to canonical. */
    for (i = 0; i < ARRAY_COUNT(gTrainerBackPicTable); i++)
    {
        const struct FamilyBackFixture *fix = &sBackFixtures[i];
        BuildBackFamilyId(id, sizeof(id), fix->canonical, false);
        snprintf(label, sizeof(label), "back sheet %zu (%s) contract",
                 i, fix->canonical);
        CheckFamilyContract(snapshot, id, GEN3_RESOURCE_TYPE_TILE_GRAPHICS,
                            fix->sheet, fix->sheetSize, label);
        if (fix->palette != NULL)
        {
            BuildBackFamilyId(id, sizeof(id), fix->canonical, true);
            snprintf(label, sizeof(label), "back palette %zu (%s) contract",
                     i, fix->canonical);
            CheckFamilyContract(snapshot, id, GEN3_RESOURCE_TYPE_PALETTE,
                                fix->palette, EMERALD_TRAINER_PALETTE_SIZE, label);
        }
    }
    for (i = 0; i < ARRAY_COUNT(gTrainerBackPicPaletteTable); i++)
        CHECK("every back-pal slot migrated (R8)", IsMigratedBackPaletteSlot(i));
    for (i = 0; i < ARRAY_COUNT(gTrainerBackPicTable); i++)
    {
        const struct FamilyBackFixture *fix = &sBackFixtures[i];
        size_t f;
        snprintf(label, sizeof(label), "back sheet %zu stream == raw canonical",
                 i);
        CHECK(label, memcmp(gTrainerBackPicTable[i].data, fix->sheet,
                            fix->sheetSize) == 0);
        snprintf(label, sizeof(label), "back sheet %zu size metadata", i);
        CHECK(label, gTrainerBackPicTable[i].size == fix->sheetSize);
        snprintf(label, sizeof(label), "back sheet %zu tag metadata", i);
        CHECK(label, gTrainerBackPicTable[i].tag == i);
        for (f = 0; f < fix->frames; f++)
        {
            snprintf(label, sizeof(label), "back frame %zu/%u in stream (%s)",
                     f, fix->frames, fix->canonical);
            CHECK(label,
                  (const u8 *)(const void *)kBackFrameArrays[i][f].data
                      == (const u8 *)(const void *)gTrainerBackPicTable[i].data
                             + TRAINER_PIC_SIZE * f);
            snprintf(label, sizeof(label), "back frame %zu/%u decodes raw (%s)",
                     f, fix->frames, fix->canonical);
            CHECK(label,
                  memcmp(kBackFrameArrays[i][f].data,
                         fix->sheet + TRAINER_PIC_SIZE * f, TRAINER_PIC_SIZE) == 0);
            CHECK("back frame size metadata",
                  kBackFrameArrays[i][f].size == TRAINER_PIC_SIZE);
        }
        if (fix->palette != NULL)
        {
            LoadCompressedSpritePalette(&gTrainerBackPicPaletteTable[fix->index]);
            snprintf(label, sizeof(label), "load path back palette == canonical (%s)",
                     fix->canonical);
            CHECK(label, memcmp(sLastLoadedPalette, fix->palette,
                                EMERALD_TRAINER_PALETTE_SIZE) == 0);
            CHECK("back palette tag metadata",
                  gTrainerBackPicPaletteTable[fix->index].tag == fix->index);
        }
    }

    /* 10. The actual native load path the game uses, for the full family. */
    for (i = 0; i < ARRAY_COUNT(gTrainerFrontPicTable); i++)
    {
        const struct FamilyTrainerFixture *fix = FixtureForIndex((int)i);
        DecompressPicFromTable_2(&gTrainerFrontPicTable[i], decodedSheet, SPECIES_NONE);
        snprintf(label, sizeof(label), "load path sheet %zu == canonical", i);
        CHECK(label, memcmp(decodedSheet, fix->sheet,
                            EMERALD_TRAINER_SHEET_SIZE) == 0);
        LoadCompressedSpritePalette(&gTrainerFrontPicPaletteTable[i]);
        snprintf(label, sizeof(label), "load path palette %zu == canonical", i);
        CHECK(label, memcmp(sLastLoadedPalette, fix->palette,
                            EMERALD_TRAINER_PALETTE_SIZE) == 0);
    }

    /* 11. Cross-check: the canonical fixtures are the committed-.lz decodes the
     * R7B unit regression pins (and the R8 back RAW sheets are the committed
     * .4bpp files verbatim), so steps 4/9/9b already prove the production chain
     * serves exactly those bytes (pack payload == legacy decoded). */

    /* 12. R9 §5: the Pokémon battle family published through the production
     * chain. All 1760 slots verified against the pack: 1759 published streams
     * (the seam's re-encoded GBA LZ77) decode through the REAL decompressor
     * to exactly the pack's canonical decoded bytes, with the stream header
     * declaring the mapping's decoded size; the external back-EGG slot
     * untouched; the size/tag stamp retained everywhere (only .data changes).
     * Then the lifecycle: Republish is idempotent (state-load re-derivation),
     * ClearMigratedEntries NULLs exactly the published slots, a second
     * Republish restores them. Finally, guarded spot decodes on chosen
     * species. */
    VerifyPokemonPublished(pack);
    VerifyPokemonSpotDecodes();
    VerifyPokemonSpecialCases();
    status = EmeraldResourceCompat_Republish(&cdiag);
    CHECK("republish ok", status == EMERALD_COMPAT_OK);
    VerifyPokemonPublished(pack);
    EmeraldResourceCompat_ClearMigratedEntries();
    VerifyPokemonCleared();
    status = EmeraldResourceCompat_Republish(&cdiag);
    CHECK("republish after clear ok", status == EMERALD_COMPAT_OK);
    VerifyPokemonPublished(pack);

    /* Report. */
    if (gFailures != 0)
    {
        printf("PRODUCTION COMPAT/LINKER-LOAD PROOF: FAIL (%d/%d checks)\n",
               gFailures, gChecks);
        Gen3ResourceSnapshot_Destroy(snapshot);
        Gen3ResourceCandidate_Destroy(candidate);
        Gen3ResourceCatalog_Destroy(catalog);
        Gen3ResourcePack_Destroy(pack);
        FreeFamilyFixtures();
        return 1;
    }
    printf("PRODUCTION COMPAT/LINKER-LOAD PROOF: PASS (%d checks)\n", gChecks);
    printf("  production pack  : %s (%zu entries)\n", argv[1],
           Gen3ResourcePack_GetEntryCount(pack));
    printf("  provider         : %s %s kind=%d precedence=%u\n",
           info.providerId, info.providerVersion, (int)info.kind, info.precedence);
    printf("  family           : 186 front + 44 back published slots (236 total), "
           "all byte-identical to canonical\n");
    printf("  pokemon battle   : 1759 published slots + 1 external (back EGG), "
           "streams decode to pack bytes (real decompressor), size/tag "
           "retained, lifecycle republish/clear verified\n");

    Gen3ResourceSnapshot_Destroy(snapshot);
    Gen3ResourceCandidate_Destroy(candidate);
    Gen3ResourceCatalog_Destroy(catalog);
    Gen3ResourcePack_Destroy(pack);
    FreeFamilyFixtures();
    return 0;
}
