#!/usr/bin/env bash
#
# R11-E/F Harness B: the neighborhood module against the REAL qualified
# Emerald data + the REAL production pack
# (tests/emerald_native_world_real_test.c).
#
# Link set: the production-runner link set (gen3 core + all compat seams +
# umbrella + session, as run_emerald_trainer_native_compat_production.sh)
# PLUS maps.o (the REAL compiled map headers + connection lists + gMapGroups)
# + a GENERATED stub object resolving maps.o's <Map>_MapScripts and
# <Map>_MapEvents relocations + host_memory.c (HostResolveGbaAddr /
# HostResolveGbaTableEntry / HostPointerToGbaAddr) + the neighborhood module
# + the tileset-anim stubs + the native-table stubs
# (emerald_native_world_tables_stub.c) + the Overworld accessor stub
# (emerald_native_world_overworld_stub.c: the verbatim PORTABLE branch,
# overworld.c:595-603, over maps.o's real gMapGroups table + a real
# `struct SaveBlock1` fixture).
#
# NOTE on the link set (plan §10 audit correction): the plan's "mutually
# self-contained closure" (maps.o + map_events.o + event_scripts.o) does not
# hold. maps.o is clean apart from <Map>_Layout (the R11-D seam), <Map>_MapEvents
# and <Map>_MapScripts pointers (518+518 relocations) -- but map_events.o
# carries 2260 undefined refs into event scripts AND game functions, and
# event_scripts.o carries 769 (gScriptCmdTable + the script bytecode). The
# module never dereferences mapScripts or the events record fields (it reads
# only mapLayout + connections; events only for objectEventCount in
# GetObjectEventsAt, which no Harness B test pins to a real value), so the
# stub object is an inert pointer target: real headers, layouts, connections,
# blockdata and tilesets stay canonical, and the script/event pointers are
# never read. The stubs are generated from data/maps/map_groups.json (the
# same source that names the relocation targets).
#
# Session: pack + 6 family catalogs (the R12-B audio catalog included - the
# ROM_BASE candidate covers every pack entry, 5087 incl. the 569 audio
# leaves) -> BuildRomBaseCandidate (5087 entries, provider
# emerald.rom-base.bpee01 precedence 300) -> snapshot ->
# EmeraldResourceCompat_InitializeFromSnapshot (publishes the R11-C tilesets
# + R11-D layouts) -> NativeWorldNeighborhood_Init -> tests 1/9/10/11/14/
# 17/18/19/20 (plan §11 Harness B, lines 528-550).
#
# Non-PIE link (-no-pie, as Makefile_pc:104/449): HostPointerToGbaAddr's
# identity conversion stays valid below 4 GiB.
#
# Usage: run_emerald_native_world_real.sh [sanitize]
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$here/.." && pwd)"
core_dir="$root/src/gen3/resources"
emerald_dir="$root/src/emerald/resources"
data_dir="$root/build/linux64/data"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

mode="${1:-}"
sanitize_flags=""
if [ "$mode" = "sanitize" ]; then
    sanitize_flags="-fsanitize=address,undefined -fno-omit-frame-pointer -g"
fi

echo "== generating map script/event stub symbols =="
# Source the exact undefined set from maps.o itself (nm -u), not the JSON:
# the secret-base maps (SecretBase_*Cave*, SecretBase_Tree*, ...) are
# generated by the build and exist in maps.o but not in map_groups.json.
nm -u "$data_dir/maps.o" | awk '/_(MapScripts|MapEvents)$/ {print $2}' | sort -u > "$tmp/stub_names.txt"
python3 - "$tmp" <<'EOF'
import sys
tmp = sys.argv[1]
names = [line.strip() for line in open(tmp + "/stub_names.txt") if line.strip()]
assert names, "no <Map>_MapScripts/_MapEvents symbols found in maps.o"
with open(tmp + "/map_script_stubs.s", "w") as f:
    f.write("# R11-E/F Harness B: inert <Map>_MapScripts / <Map>_MapEvents\n")
    f.write("# pointer targets for maps.o's relocations (from nm -u maps.o;\n")
    f.write("# never dereferenced by the module).\n")
    for name in sorted(names):
        f.write("    .balign 8\n")
        f.write("    .globl %s\n%s:\n" % (name, name))
        f.write("    .quad 0\n")
EOF
gcc -c "$tmp/map_script_stubs.s" -o "$tmp/map_script_stubs.o"
printf -- "-- stubbed %s symbols (nm -u maps.o)\n" "$(wc -l < "$tmp/stub_names.txt")"

echo "== compiling harness B (real data + production pack) =="
cd "$root"
gcc -std=gnu99 -O2 -ffunction-sections -fdata-sections -Wl,--gc-sections \
    -Wall -Wextra $sanitize_flags -no-pie \
    -iquote include -iquote "$core_dir" \
    -DPORTABLE -DNONMATCHING -DUBFIX -DMODERN=1 \
    -DPLATFORM_SDL2 -DNATIVE_LINUX -DLINUX64=1 \
    "$core_dir/sha256.c" \
    "$core_dir/sha1.c" \
    "$core_dir/resource_lz.c" \
    "$core_dir/resource_id.c" \
    "$core_dir/resource_core.c" \
    "$core_dir/resource_resolver.c" \
    "$core_dir/resource_content_digest.c" \
    "$core_dir/resource_pack.c" \
    "$core_dir/resource_pack_writer.c" \
    "$core_dir/resource_pack_provider.c" \
    "$core_dir/toml.c" \
    "$core_dir/util.c" \
    "$core_dir/lz77.c" \
    "$emerald_dir/emerald_rom_profile.c" \
    "$emerald_dir/emerald_resource_compat.c" \
    "$emerald_dir/emerald_resource_ranges.c" \
    "$emerald_dir/emerald_trainer_native_compat.c" \
    "$emerald_dir/emerald_pokemon_native_compat.c" \
    "$emerald_dir/emerald_object_event_compat.c" \
    "$emerald_dir/emerald_tileset_compat.c" \
    "$emerald_dir/emerald_layout_compat.c" \
    "$emerald_dir/emerald_audio_compat.c" \
    "$here/emerald_tileset_compat_stubs.c" \
    "$emerald_dir/emerald_resource_session.c" \
    src/platform/host_memory.c \
    src/platform/native_world_neighborhood.c \
    "$data_dir/maps.o" \
    "$tmp/map_script_stubs.o" \
    "$here/emerald_native_world_tables_stub.c" \
    "$here/emerald_native_world_overworld_stub.c" \
    "$here/emerald_native_world_real_test.c" \
    -o "$tmp/emerald_native_world_real_test"

echo "== running =="
"$tmp/emerald_native_world_real_test" \
    "$root/games/emerald/base/emerald-bpee01-v1.rpack" \
    --catalog "$root/resources/catalogs/emerald/catalog.toml" \
    --catalog "$root/resources/extraction/emerald/bpee01/pokemon_battle/catalog.generated.toml" \
    --catalog "$root/resources/extraction/emerald/bpee01/object_event/catalog.generated.toml" \
    --catalog "$root/resources/extraction/emerald/bpee01/tileset/catalog.generated.toml" \
    --catalog "$root/resources/extraction/emerald/bpee01/layout/catalog.generated.toml" \
    --catalog "$root/resources/extraction/emerald/bpee01/audio/catalog.generated.toml" \
    --catalog "$root/resources/extraction/emerald/bpee01/movement/catalog.generated.toml" \
    --catalog "$root/resources/extraction/emerald/bpee01/text/catalog.generated.toml" \
    --catalog "$root/resources/extraction/emerald/bpee01/multiboot/catalog.generated.toml"
