#!/usr/bin/env bash
#
# R11-F Harness D: the renderer-facing offscreen proof
# (tests/emerald_native_world_render_proof.c) against the REAL qualified
# Emerald data + the REAL production pack.
#
# Link set: identical to Harness B (run_emerald_native_world_real.sh) —
# the production-runner link set (gen3 core + all compat seams + umbrella +
# session) PLUS maps.o (real compiled map headers + connection lists +
# gMapGroups) + the generated <Map>_MapScripts/<Map>_MapEvents stub object
# + host_memory.c + the neighborhood module + the tileset-anim stubs
# (emerald_tileset_compat_stubs.c) + the native-table stubs
# (emerald_native_world_tables_stub.c) + the Overworld accessor stub
# (emerald_native_world_overworld_stub.c). See the Harness B header comment
# for the plan §10 link-set audit correction (map_events.o/event_scripts.o
# are NOT self-contained; the module never dereferences the stub targets).
#
# Session: pack + 6 family catalogs (the R12-B audio catalog included - the
# ROM_BASE candidate covers every pack entry, 5087 incl. the 569 audio
# leaves) -> BuildRomBaseCandidate (5087 entries, provider
# emerald.rom-base.bpee01 precedence 300) -> snapshot ->
# EmeraldResourceCompat_InitializeFromSnapshot (publishes the R11-C tilesets
# + R11-D layouts) -> NativeWorldNeighborhood_Init -> set location
# Littleroot Town -> offscreen tilemap-entry render of the world block rect
# x in [0,20), y in [-10,10) across the real Littleroot<->Route101 north
# connection, byte-compared against an independent oracle (plan §11
# Harness D assertions i-v).
#
# Non-PIE link (-no-pie, as Makefile_pc:104/449): HostPointerToGbaAddr's
# identity conversion stays valid below 4 GiB.
#
# Usage: run_emerald_native_world_render_proof.sh [sanitize]
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$here/.." && pwd)"
core_dir="$root/src/gen3/resources"
emerald_dir="$root/src/emerald/resources"
data_dir="$root/build/linux64/data"

tmp="$(mktemp -d)"
export ROOT="$root"
# R13-G2 script catalog declares 523 identities; 56 routing-only ids have
# no pack entry. The session's construction catalog must match the pack's
# provider surface, so this harness passes the 467 embedded ids only.
python3 - <<PYFILT > "$tmp/script_embedded_catalog.toml"
import re, os
cat = open(os.environ["ROOT"] + "/resources/extraction/emerald/bpee01/script/modules/catalog.generated.toml").read()
man = open(os.environ["ROOT"] + "/resources/extraction/emerald/bpee01/script/modules/manifest.production.toml").read()
ids = set(re.findall(r'^id = "([^"]+)"$', man, re.M))
header, rest = cat.split("[[resources]]", 1)
print(header, end="")
for block in rest.split("[[resources]]"):
    i = re.search(r'id = "([^"]+)"', block)
    if i and i.group(1) in ids:
        print("[[resources]]" + block, end="")
PYFILT

trap 'rm -rf "$tmp"' EXIT

mode="${1:-}"
sanitize_flags=""
if [ "$mode" = "sanitize" ]; then
    sanitize_flags="-fsanitize=address,undefined -fno-omit-frame-pointer -g"
fi

echo "== generating map script/event stub symbols =="
# Source the exact undefined set from maps.o itself (nm -u), not the JSON:
# the secret-base maps (SecretBase_*Cave*, SecretBase_Tree*, ...) are
# generated by the build and exist in maps.o but not in map_groups.json.
nm -u "$data_dir/maps.o" | awk '/_(MapScripts|MapEvents)$/ {print $2}' | sort -u > "$tmp/stub_names.txt"
python3 - "$tmp" <<'EOF'
import sys
tmp = sys.argv[1]
names = [line.strip() for line in open(tmp + "/stub_names.txt") if line.strip()]
assert names, "no <Map>_MapScripts/_MapEvents symbols found in maps.o"
with open(tmp + "/map_script_stubs.s", "w") as f:
    f.write("# R11-F Harness D: inert <Map>_MapScripts / <Map>_MapEvents\n")
    f.write("# pointer targets for maps.o's relocations (from nm -u maps.o;\n")
    f.write("# never dereferenced by the module).\n")
    for name in sorted(names):
        f.write("    .balign 8\n")
        f.write("    .globl %s\n%s:\n" % (name, name))
        f.write("    .quad 0\n")
EOF
gcc -c "$tmp/map_script_stubs.s" -o "$tmp/map_script_stubs.o"
printf -- "-- stubbed %s symbols (nm -u maps.o)\n" "$(wc -l < "$tmp/stub_names.txt")"

echo "== compiling harness D (offscreen render proof, real data + pack) =="
cd "$root"
gcc -std=gnu99 -O2 -ffunction-sections -fdata-sections -Wl,--gc-sections \
    -Wall -Wextra $sanitize_flags -no-pie \
    -iquote include -iquote "$core_dir" \
    -DPORTABLE -DNONMATCHING -DUBFIX -DMODERN=1 \
    -DPLATFORM_SDL2 -DNATIVE_LINUX -DLINUX64=1 \
    "$core_dir/sha256.c" \
    "$core_dir/sha1.c" \
    "$core_dir/resource_lz.c" \
    "$core_dir/resource_id.c" \
    "$core_dir/resource_core.c" \
    "$core_dir/resource_resolver.c" \
    "$core_dir/resource_content_digest.c" \
    "$core_dir/resource_pack.c" \
    "$core_dir/resource_pack_writer.c" \
    "$core_dir/resource_pack_provider.c" \
    "$core_dir/toml.c" \
    "$core_dir/util.c" \
    "$core_dir/lz77.c" \
    "$emerald_dir/emerald_rom_profile.c" \
    "$emerald_dir/emerald_resource_compat.c" \
    "$emerald_dir/emerald_resource_ranges.c" \
    "$emerald_dir/emerald_trainer_native_compat.c" \
    "$emerald_dir/emerald_pokemon_native_compat.c" \
    "$emerald_dir/emerald_object_event_compat.c" \
    "$emerald_dir/emerald_tileset_compat.c" \
    "$emerald_dir/emerald_layout_compat.c" \
    "$here/emerald_tileset_compat_stubs.c" \
    "$emerald_dir/emerald_resource_session.c" \
    src/platform/host_memory.c \
    src/platform/native_world_neighborhood.c \
    "$data_dir/maps.o" \
    "$tmp/map_script_stubs.o" \
    "$here/emerald_native_world_tables_stub.c" \
    "$here/emerald_native_world_overworld_stub.c" \
    "$here/emerald_native_world_render_proof.c" \
    -o "$tmp/emerald_native_world_render_proof"

echo "== running =="
"$tmp/emerald_native_world_render_proof" \
    "$root/games/emerald/base/emerald-bpee01-v1.rpack" \
    --catalog "$root/resources/catalogs/emerald/catalog.toml" \
    --catalog "$root/resources/extraction/emerald/bpee01/pokemon_battle/catalog.generated.toml" \
    --catalog "$root/resources/extraction/emerald/bpee01/object_event/catalog.generated.toml" \
    --catalog "$root/resources/extraction/emerald/bpee01/tileset/catalog.generated.toml" \
    --catalog "$root/resources/extraction/emerald/bpee01/layout/catalog.generated.toml" \
    --catalog "$root/resources/extraction/emerald/bpee01/audio/catalog.generated.toml" \
    --catalog "$root/resources/extraction/emerald/bpee01/movement/catalog.generated.toml" \
    --catalog "$root/resources/extraction/emerald/bpee01/text/catalog.generated.toml" \
    --catalog "$root/resources/extraction/emerald/bpee01/gameplay/catalog.generated.toml" \
    --catalog "$root/resources/extraction/emerald/bpee01/multiboot/catalog.generated.toml" \
    --catalog "$tmp/script_embedded_catalog.toml"
