#!/usr/bin/env python3
"""R11-L: machine-readable object-event graphics inventory.

Parses the checked-in sources of truth and emits
resources/extraction/emerald/bpee01/object_event/inventory.generated.toml:

  * src/data/object_events/object_event_graphics.h
      -> gObjectEventPic_* raw 4bpp sheet symbols + INCBIN artifact paths
      -> gObjectEventPal_* gbapal palette symbols + INCBIN artifact paths
         (null placeholders classified separately; field-effect leaves and
         gUnusedObjectEventPalette are NOT part of this family)
  * src/data/object_events/object_event_pic_tables.h
  * src/data/object_events/berry_tree_graphics_tables.h
      -> SpriteFrameImage arrays and every overworld_frame(...) consumer:
         the frame macro names the sheet symbol directly, so the sheet
         relation is derived textually from source provenance - no ELF
         walking.

Deterministic: resources bytewise by symbol, frame arrays bytewise by
symbol, consumers bytewise by (array, index). Regeneration must be a
no-op diff; --check enforces that.

Usage: python3 gen_object_event_inventory.py [repo-root] [output-path] [--check]
"""
import re
import sys
from collections import OrderedDict

SHEET_RE = re.compile(r'const u32 (gObjectEventPic_\w+)\[\] = INCBIN_U32\("([^"]+)"\);')
PAL_RE = re.compile(r'const u16 (gObjectEventPal_\w+)\[\] = INCBIN_U16\("([^"]+)"\);')
NULL_PAL_RE = re.compile(r'const u16 (gObjectEventPal_\w+)\[16\] = \{\};')
FRAME_ARRAY_RE = re.compile(r'static const struct SpriteFrameImage (sPicTable_\w+)\[\] = \{')
FRAME_RE = re.compile(r'overworld_frame\((\w+),\s*(\d+),\s*(\d+),\s*(\d+)\)')
# obj_frame_tiles(ptr): one whole-sheet frame (offset 0, size = sizeof ptr).
OBJ_FRAME_RE = re.compile(r'obj_frame_tiles\((\w+)\)')

GRAPHICS_H = "src/data/object_events/object_event_graphics.h"
PIC_TABLES_H = "src/data/object_events/object_event_pic_tables.h"
BERRY_TABLES_H = "src/data/object_events/berry_tree_graphics_tables.h"


def parse_graphics(path):
    sheets = OrderedDict()
    pals = OrderedDict()
    nulls = []
    for i, line in enumerate(open(path)):
        m = SHEET_RE.match(line.strip())
        if m:
            if m.group(1) in sheets:
                sys.exit(f"FAIL: duplicate sheet symbol {m.group(1)} (line {i + 1})")
            sheets[m.group(1)] = m.group(2)
            continue
        m = PAL_RE.match(line.strip())
        if m:
            if m.group(1) in pals:
                sys.exit(f"FAIL: duplicate palette symbol {m.group(1)} (line {i + 1})")
            pals[m.group(1)] = m.group(2)
            continue
        m = NULL_PAL_RE.match(line.strip())
        if m:
            nulls.append(m.group(1))
    return sheets, pals, nulls


def parse_frame_arrays(paths):
    arrays = OrderedDict()
    current = None
    pending = []  # (line_no, entry) rows since the last array header
    for path in paths:
        for i, line in enumerate(open(path)):
            stripped = line.strip()
            m = FRAME_ARRAY_RE.match(stripped)
            if m:
                if current is not None and pending:
                    arrays[current] = pending
                name = m.group(1)
                if name in arrays:
                    sys.exit(f"FAIL: duplicate frame array {name} in {path} (line {i + 1})")
                current = name
                pending = []
                continue
            m = FRAME_RE.search(stripped)
            if m:
                if current is None:
                    sys.exit(f"FAIL: {path} line {i + 1}: overworld_frame before any array header")
                pending.append((m.group(1), int(m.group(2)), int(m.group(3)), int(m.group(4)), False))
                continue
            m = OBJ_FRAME_RE.search(stripped)
            if m:
                if current is None:
                    sys.exit(f"FAIL: {path} line {i + 1}: obj_frame_tiles before any array header")
                pending.append((m.group(1), 0, 0, 0, True))
    if current is not None and pending:
        arrays[current] = pending
    return arrays


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    check = "--check" in sys.argv
    root = args[0] if len(args) > 0 else "."
    out = args[1] if len(args) > 1 else \
        "resources/extraction/emerald/bpee01/object_event/inventory.generated.toml"

    sheets, pals, nulls = parse_graphics(f"{root}/{GRAPHICS_H}")
    arrays = parse_frame_arrays([f"{root}/{PIC_TABLES_H}", f"{root}/{BERRY_TABLES_H}"])

    lines = []
    lines.append("# Generated by tools/gen3_resources/object_event_family/gen_object_event_inventory.py")
    lines.append("# Do not edit by hand; edit the checked-in object-event data headers")
    lines.append("# and re-run the generator (regeneration must be a no-op diff).")
    lines.append("inventory_version = 1")
    lines.append('family = "object_event"')
    lines.append('game = "emerald"')
    lines.append('rom_profile = "bpee01"')
    lines.append("")

    for kind, count in (("sheet", len(sheets)), ("palette", len(pals))):
        lines.append(f"[[families]]")
        lines.append(f'kind = "{kind}"')
        lines.append(f"symbol_count = {count}")
        lines.append("")

    for symbol in sorted(sheets):
        lines.append("[[resources]]")
        lines.append(f'symbol = "{symbol}"')
        lines.append('kind = "sheet"')
        lines.append(f'source_artifact = "{sheets[symbol]}"')
        lines.append("")

    for symbol in sorted(pals):
        lines.append("[[resources]]")
        lines.append(f'symbol = "{symbol}"')
        lines.append('kind = "palette"')
        lines.append(f'source_artifact = "{pals[symbol]}"')
        lines.append(f'reflection = {"true" if symbol.endswith("Reflection") else "false"}')
        lines.append("")

    for symbol in sorted(nulls):
        lines.append("[[null_palettes]]")
        lines.append(f'symbol = "{symbol}"')
        lines.append("")

    # Validate consumers before emitting: every referenced sheet exists.
    for array, entries in arrays.items():
        for (sheet, w, h, f, whole) in entries:
            if sheet not in sheets:
                sys.exit(f"FAIL: frame array {array} references unknown sheet {sheet}")
            if not whole and (w <= 0 or h <= 0 or f < 0):
                sys.exit(f"FAIL: frame array {array} has invalid frame geometry {w}x{h}#{f}")

    for array in sorted(arrays):
        lines.append("[[frame_arrays]]")
        lines.append(f'symbol = "{array}"')
        lines.append(f"frame_count = {len(arrays[array])}")
        lines.append("")

    for array in sorted(arrays):
        for idx, (sheet, w, h, f, whole) in enumerate(arrays[array]):
            lines.append("[[consumers]]")
            lines.append(f'array = "{array}"')
            lines.append(f"index = {idx}")
            lines.append(f'sheet = "{sheet}"')
            lines.append(f"width = {w}")
            lines.append(f"height = {h}")
            lines.append(f"frame = {f}")
            lines.append(f'whole_sheet = {"true" if whole else "false"}')
            lines.append("")

    text = "\n".join(lines)
    if check:
        try:
            existing = open(out).read()
        except FileNotFoundError:
            sys.exit(f"FAIL: --check: {out} does not exist")
        if existing != text:
            sys.exit(f"FAIL: --check: {out} is not up to date with the sources")
        print(f"{out}: up to date ({len(sheets)} sheets, {len(pals)} palettes, "
              f"{len(arrays)} frame arrays, {sum(len(e) for e in arrays.values())} frames)")
        return 0
    with open(out, "w") as f:
        f.write(text)
    print(f"{out}: wrote {len(sheets)} sheets, {len(pals)} palettes, "
          f"{len(nulls)} null palettes, {len(arrays)} frame arrays, "
          f"{sum(len(e) for e in arrays.values())} frames")
    return 0


if __name__ == "__main__":
    sys.exit(main())
