#!/usr/bin/env python3
"""R9 Stage 1/2: machine-readable Pokémon battle graphics inventory.

Parses the checked-in sources of truth and emits
resources/extraction/emerald/bpee01/pokemon_battle/inventory.generated.toml:

  * include/constants/species.h            -> species token -> species id
  * src/data/pokemon_graphics/{front_pic_table.h,back_pic_table.h,
    palette_table.h,shiny_palette_table.h} -> (table, index, token, symbol)
  * src/anim_mon_front_pics.c,
    src/data/graphics/pokemon.h,
    src/data/graphics/pokemon_battle_payload.c,
    src/graphics.c                          -> symbol -> INCBIN artifact path

The four tables use designated initializers [SPECIES_##token] == species id,
so index is the species value (verified per slot). The table headers are the
authoritative alias map (OLD_UNOWN_B..Z share *_DoubleQuestionMark; the unown
form slots share gMonPalette_Unown/gMonShinyPalette_Unown; the back EGG slot
references gMonStillFrontPic_Egg; the shiny EGG slot references gMonPalette_Egg)
-- no per-species logic anywhere. Deterministic: regeneration must be a no-op
diff (the generator test asserts this).

Usage: python3 gen_pokemon_inventory.py [repo-root] [output-path]
"""
import re
import sys
from collections import OrderedDict

SPECIES_RE = re.compile(r"#define (SPECIES_\w+) (\d+)")
SPECIES_EXPR_RE = re.compile(r"#define (SPECIES_\w+) \((\w+) \+ (\d+)\)")
# SPECIES_UNOWN_B..QMARK are (NUM_SPECIES + N); NUM_SPECIES == SPECIES_EGG.
SPECIES_ALIAS_RE = re.compile(r"#define (\w+) (SPECIES_\w+)")

FAMILIES = [
    # R9 §7 renamed the four battle tables' row macros to SPECIES_BATTLE_*
    # (data.c); the one back-EGG external row keeps the original
    # SPECIES_SPRITE on every target, so the sheet pattern matches both.
    ("front_sheet", "gMonFrontPicTable", "SPECIES_BATTLE_SPRITE",
     r"(?:SPECIES_BATTLE_SPRITE|SPECIES_SPRITE)\((\w+), (gMon\w+)\)"),
    ("back_sheet", "gMonBackPicTable", "SPECIES_BATTLE_SPRITE",
     r"(?:SPECIES_BATTLE_SPRITE|SPECIES_SPRITE)\((\w+), (gMon\w+)\)"),
    ("normal_palette", "gMonPaletteTable", "SPECIES_BATTLE_PAL",
     r"SPECIES_BATTLE_PAL\((\w+), (gMon\w+)\)"),
    ("shiny_palette", "gMonShinyPaletteTable", "SPECIES_BATTLE_SHINY_PAL",
     r"SPECIES_BATTLE_SHINY_PAL\((\w+), (gMon\w+)\)"),
    # R15 Phase 2: the three remaining pokemon graphics sub-families.
    # still_front uses the SPECIES_SPRITE macro (same shape as the sheets);
    # icon/footprint tables are designated-initializer arrays (the icon
    # table lives in src/pokemon_icon.c, not under pokemon_graphics/).
    ("still_front", "gMonStillFrontPicTable", "SPECIES_STILL_SPRITE",
     r"(?:SPECIES_STILL_SPRITE|SPECIES_BATTLE_SPRITE|SPECIES_SPRITE)\((\w+),\s+(gMon\w+)\)"),
    ("icon", "gMonIconTable", None,
     r"SPECIES_ICON\((\w+),\s*(gMon\w+)\)"),
    ("footprint", "gMonFootprintTable", None,
     r"SPECIES_FOOTPRINT\((\w+),\s*(gMon\w+)\)"),
]

INCBIN_FILES = [
    "src/anim_mon_front_pics.c",
    "src/data/graphics/pokemon.h",
    "src/data/graphics/pokemon_battle_payload.c",
    "src/graphics.c",
]

def parse_species(path):
    tokens = {}
    aliases = {}
    for line in open(path):
        m = SPECIES_RE.match(line)
        if m and m.group(1) != "SPECIES_TOTAL":
            tokens[m.group(1)] = int(m.group(2))
    # alias defines: NUM_SPECIES SPECIES_EGG (plain value-to-token aliases).
    resolved = True
    while resolved:
        resolved = False
        for line in open(path):
            m = SPECIES_ALIAS_RE.match(line)
            if m and m.group(2) in tokens and m.group(1) not in tokens:
                tokens[m.group(1)] = tokens[m.group(2)]
                resolved = True
    # arithmetic defines: SPECIES_UNOWN_B (NUM_SPECIES + 1) and friends.
    resolved = True
    while resolved:
        resolved = False
        for line in open(path):
            m = SPECIES_EXPR_RE.match(line)
            if m and m.group(1) not in tokens and m.group(2) in tokens:
                tokens[m.group(1)] = tokens[m.group(2)] + int(m.group(3))
                resolved = True
    return tokens

def parse_incbins(path):
    symbols = {}
    for line in open(path):
        m = re.match(r'const u(?:8|16|32) (gMon\w+)\[\] = INCBIN_U(?:8|16|32)\(\s*"([^"]+)"\);', line.strip())
        if m:
            symbols[m.group(1)] = m.group(2)
    return symbols

def main():
    root = sys.argv[1] if len(sys.argv) > 1 else "."
    out = sys.argv[2] if len(sys.argv) > 2 else "resources/extraction/emerald/bpee01/pokemon_battle/inventory.generated.toml"

    species = parse_species(f"{root}/include/constants/species.h")
    incbins = OrderedDict()
    for f in INCBIN_FILES:
        incbins.update(parse_incbins(f"{root}/{f}"))

    lines = []
    lines.append("# Generated by tools/gen3_resources/pokemon_family/gen_pokemon_inventory.py")
    lines.append("# Do not edit by hand; edit the checked-in table headers / INCBIN sources")
    lines.append("# and re-run the generator (regeneration must be a no-op diff).")
    lines.append("inventory_version = 1")
    lines.append('family = "pokemon_battle"')
    lines.append('game = "emerald"')
    lines.append('rom_profile = "bpee01"')
    lines.append("")

    slot_rows = []  # (kind, symbol, index, species) in resource emission order
    for kind, table, macro, pat in FAMILIES:
        slots = []
        for i, line in enumerate(open(f"{root}/" + {
            "front_sheet": "src/data/pokemon_graphics/front_pic_table.h",
            "back_sheet": "src/data/pokemon_graphics/back_pic_table.h",
            "normal_palette": "src/data/pokemon_graphics/palette_table.h",
            "shiny_palette": "src/data/pokemon_graphics/shiny_palette_table.h",
            "still_front": "src/data/pokemon_graphics/still_front_pic_table.h",
            "icon": "src/pokemon_icon.c",
            "footprint": "src/data/pokemon_graphics/footprint_table.h",
        }[kind])):
            m = re.search(pat, line)
            if m:
                token, symbol = m.groups()
                # table macros expand [SPECIES_##token]; species.h keys are
                # "SPECIES_<token>", so map the bare token through the prefix
                # (the designated-initializer patterns capture it already).
                key = token if token.startswith("SPECIES_") else "SPECIES_" + token
                if key not in species:
                    sys.exit(f"FAIL: table {table} line {i + 1}: species token '{token}' not in species.h")
                idx = species[key]
                # species_mapping rows carry bare tokens (macro kinds emit bare);
                # strip the prefix the designated-initializer pattern captured.
                bare = token[len("SPECIES_"):] if token.startswith("SPECIES_") else token
                slots.append((idx, bare, symbol))
        # designated initializers: index must equal species value and be unique
        seen = set()
        for idx, token, _ in slots:
            if idx in seen:
                sys.exit(f"FAIL: duplicate index {idx} in {table}")
            seen.add(idx)
        for idx, (i, _, _) in enumerate(slots):
            if i != idx:
                sys.exit(f"FAIL: {table} slot {idx} has species value {i} (designated-initializer mismatch)")

        unique = OrderedDict()
        for idx, token, symbol in slots:
            unique.setdefault(symbol, []).append(idx)
        for symbol in unique:
            if symbol not in incbins:
                sys.exit(f"FAIL: {table} references {symbol}, not defined by any INCBIN")

        lines.append(f"# {kind}: {table} -- {len(slots)} slots, {len(unique)} unique symbols")
        lines.append(f"[[families]]")
        lines.append(f'kind = "{kind}"')
        lines.append(f'table = "{table}"')
        lines.append(f"slot_count = {len(slots)}")
        lines.append(f"unique_symbol_count = {len(unique)}")
        lines.append("")
        # Slots live in a flat top-level [[slots]] array (the shared TOML
        # subset has no nested table headers); the family generator joins by
        # symbol and re-verifies coverage.
        for symbol, idxs in unique.items():
            artifact = incbins[symbol]
            lines.append("[[resources]]")
            lines.append(f'symbol = "{symbol}"')
            lines.append(f'kind = "{kind}"')
            lines.append(f'source_artifact = "{artifact}"')
            lines.append(f"slot_count = {len(idxs)}")
            lines.append("")
            for idx in idxs:
                tok = dict((i, t) for i, t, _ in slots)[idx]
                slot_rows.append((kind, symbol, idx, tok))

    for kind, symbol, idx, tok in slot_rows:
        lines.append("[[slots]]")
        lines.append(f'symbol = "{symbol}"')
        lines.append(f'kind = "{kind}"')
        lines.append(f"index = {idx}")
        lines.append(f'species = "{tok}"')
    lines.append("")

    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {out}")

if __name__ == "__main__":
    main()
