/* Generated by tools/gen3_resources/battle_family/h4_generate.py.
 * Do not edit by hand; re-run the generator (regeneration must
 * be a no-op diff).
 */

/* Native-typed address table for the R13-H5 battle bindings
 * (A EWRAM + battle B string-ID tables) and the compiled-label
 * map. Every symbol below is ADDRESSED (never dereferenced) in
 * this TU, so the uniform scalar declarations bind the linker
 * symbol regardless of the defining TU's real type; the real
 * type stays where it is defined. Missing symbols fail the
 * link (build-time coverage proof).
 *
 * R13-H7: on linux64 the compiled battle labels are REMOVED
 * from the link (brief sec 3/§4); the label externs and the
 * host-address table below exist only off-linux64, and
 * LabelAddress returns the canonical GBA word instead (the
 * label map stays queryable; ResolveCompiledLabel compares
 * words on linux64). The engine binding symbols stay on all
 * targets (brief sec 12/§26). */

#include <stdint.h>
#include "emerald/resources/battle_live.generated.h"

extern uint8_t gAbsorbDrainStringIds;
extern uint8_t gBRNPreventionStringIds;
extern uint8_t gBallEscapeStringIds;
extern uint8_t gBattleCommunication;
extern uint8_t gBattleMoveDamage;
extern uint8_t gBattleOutcome;
extern uint8_t gBattlePalaceFlavorTextTable;
extern uint8_t gBattleScripting;
extern uint8_t gBattleTextBuff1;
extern uint8_t gBattleTypeFlags;
extern uint8_t gBattleWeather;
extern uint8_t gBattlerAttacker;
extern uint8_t gBattlerByTurnOrder;
extern uint8_t gBattlerFainted;
extern uint8_t gBattlerTarget;
extern uint8_t gBattlersCount;
extern uint8_t gBerryEffectStringIds;
extern uint8_t gCaughtMonStringIds;
extern uint8_t gChosenMove;
extern uint8_t gCritMultiplier;
extern uint8_t gCurrentMove;
extern uint8_t gDynamicBasePower;
extern uint8_t gEffectBattler;
extern uint8_t gFellAsleepStringIds;
extern uint8_t gFirstTurnOfTwoStringIds;
extern uint8_t gFlashFireStringIds;
extern uint8_t gFocusEnergyUsedStringIds;
extern uint8_t gFutureMoveUsedStringIds;
extern uint8_t gGotBurnedStringIds;
extern uint8_t gGotDefrostedStringIds;
extern uint8_t gGotFrozenStringIds;
extern uint8_t gGotParalyzedStringIds;
extern uint8_t gGotPoisonedStringIds;
extern uint8_t gHitMarker;
extern uint8_t gHpDealt;
extern uint8_t gInobedientStringIds;
extern uint8_t gItemSwapStringIds;
extern uint8_t gKOFailedStringIds;
extern uint8_t gLastUsedItem;
extern uint8_t gLeechSeedStringIds;
extern uint8_t gMistUsedStringIds;
extern uint8_t gMoveResultFlags;
extern uint8_t gMoveWeatherChangeStringIds;
extern uint8_t gNoEscapeStringIds;
extern uint8_t gNumSafariBalls;
extern uint8_t gPRLZPreventionStringIds;
extern uint8_t gPSNPreventionStringIds;
extern uint8_t gPartyStatusHealStringIds;
extern uint8_t gProtectLikeUsedStringIds;
extern uint8_t gRainContinuesStringIds;
extern uint8_t gReflectLightScreenSafeguardStringIds;
extern uint8_t gRestUsedStringIds;
extern uint8_t gSafariGetNearStringIds;
extern uint8_t gSafariPokeblockResultStringIds;
extern uint8_t gSandStormHailContinuesStringIds;
extern uint8_t gSandStormHailDmgStringIds;
extern uint8_t gSandStormHailEndStringIds;
extern uint8_t gSportsUsedStringIds;
extern uint8_t gStatDownStringIds;
extern uint8_t gStatUpStringIds;
extern uint8_t gStockpileUsedStringIds;
extern uint8_t gSubstituteUsedStringIds;
extern uint8_t gSwallowFailStringIds;
extern uint8_t gTrainerBattleOpponent_A;
extern uint8_t gTrainerItemCuredStatusStringIds;
extern uint8_t gTransformUsedStringIds;
extern uint8_t gUproarAwakeStringIds;
extern uint8_t gUproarOverTurnStringIds;
extern uint8_t gWeatherStartsStringIds;
extern uint8_t gWokeUpStringIds;
extern uint8_t gWrappedStringIds;

static const uintptr_t sNativeBindingAddresses[] = {
    (uintptr_t)&gBattleTextBuff1, /* gBattleTextBuff1 */
    (uintptr_t)&gBattleTypeFlags, /* gBattleTypeFlags */
    (uintptr_t)&gBattlersCount, /* gBattlersCount */
    (uintptr_t)&gBattlerByTurnOrder, /* gBattlerByTurnOrder */
    (uintptr_t)&gCurrentMove, /* gCurrentMove */
    (uintptr_t)&gChosenMove, /* gChosenMove */
    (uintptr_t)&gBattleMoveDamage, /* gBattleMoveDamage */
    (uintptr_t)&gBattleMoveDamage, /* gBattleMoveDamage */
    (uintptr_t)&gBattleMoveDamage, /* gBattleMoveDamage */
    (uintptr_t)&gBattleMoveDamage, /* gBattleMoveDamage */
    (uintptr_t)&gHpDealt, /* gHpDealt */
    (uintptr_t)&gLastUsedItem, /* gLastUsedItem */
    (uintptr_t)&gBattlerAttacker, /* gBattlerAttacker */
    (uintptr_t)&gBattlerTarget, /* gBattlerTarget */
    (uintptr_t)&gBattlerFainted, /* gBattlerFainted */
    (uintptr_t)&gEffectBattler, /* gEffectBattler */
    (uintptr_t)&gCritMultiplier, /* gCritMultiplier */
    (uintptr_t)&gMoveResultFlags, /* gMoveResultFlags */
    (uintptr_t)&gHitMarker, /* gHitMarker */
    (uintptr_t)&gBattleCommunication, /* gBattleCommunication */
    (uintptr_t)&gBattleCommunication, /* gBattleCommunication */
    (uintptr_t)&gBattleCommunication, /* gBattleCommunication */
    (uintptr_t)&gBattleCommunication, /* gBattleCommunication */
    (uintptr_t)&gBattleCommunication, /* gBattleCommunication */
    (uintptr_t)&gBattleOutcome, /* gBattleOutcome */
    (uintptr_t)&gBattleWeather, /* gBattleWeather */
    (uintptr_t)&gDynamicBasePower, /* gDynamicBasePower */
    (uintptr_t)&gBattleScripting, /* gBattleScripting */
    (uintptr_t)&gBattleScripting, /* gBattleScripting */
    (uintptr_t)&gBattleScripting, /* gBattleScripting */
    (uintptr_t)&gBattleScripting, /* gBattleScripting */
    (uintptr_t)&gBattleScripting, /* gBattleScripting */
    (uintptr_t)&gBattleScripting, /* gBattleScripting */
    (uintptr_t)&gBattleScripting, /* gBattleScripting */
    (uintptr_t)&gBattleScripting, /* gBattleScripting */
    (uintptr_t)&gBattleScripting, /* gBattleScripting */
    (uintptr_t)&gBattleScripting, /* gBattleScripting */
    (uintptr_t)&gBattleScripting, /* gBattleScripting */
    (uintptr_t)&gBattleScripting, /* gBattleScripting */
    (uintptr_t)&gBattleScripting, /* gBattleScripting */
    (uintptr_t)&gBattleScripting, /* gBattleScripting */
    (uintptr_t)&gBattleScripting, /* gBattleScripting */
    (uintptr_t)&gBattleScripting, /* gBattleScripting */
    (uintptr_t)&gBattleScripting, /* gBattleScripting */
    (uintptr_t)&gBattleScripting, /* gBattleScripting */
    (uintptr_t)&gBattleScripting, /* gBattleScripting */
    (uintptr_t)&gBattleScripting, /* gBattleScripting */
    (uintptr_t)&gBattleScripting, /* gBattleScripting */
    (uintptr_t)&gTrainerBattleOpponent_A, /* gTrainerBattleOpponent_A */
    (uintptr_t)&gNumSafariBalls, /* gNumSafariBalls */
    0u,
    0u,
    (uintptr_t)&gNoEscapeStringIds, /* gNoEscapeStringIds */
    (uintptr_t)&gMoveWeatherChangeStringIds, /* gMoveWeatherChangeStringIds */
    (uintptr_t)&gSandStormHailContinuesStringIds, /* gSandStormHailContinuesStringIds */
    (uintptr_t)&gSandStormHailDmgStringIds, /* gSandStormHailDmgStringIds */
    (uintptr_t)&gSandStormHailEndStringIds, /* gSandStormHailEndStringIds */
    (uintptr_t)&gRainContinuesStringIds, /* gRainContinuesStringIds */
    (uintptr_t)&gProtectLikeUsedStringIds, /* gProtectLikeUsedStringIds */
    (uintptr_t)&gReflectLightScreenSafeguardStringIds, /* gReflectLightScreenSafeguardStringIds */
    (uintptr_t)&gLeechSeedStringIds, /* gLeechSeedStringIds */
    (uintptr_t)&gRestUsedStringIds, /* gRestUsedStringIds */
    (uintptr_t)&gUproarOverTurnStringIds, /* gUproarOverTurnStringIds */
    (uintptr_t)&gStockpileUsedStringIds, /* gStockpileUsedStringIds */
    (uintptr_t)&gWokeUpStringIds, /* gWokeUpStringIds */
    (uintptr_t)&gSwallowFailStringIds, /* gSwallowFailStringIds */
    (uintptr_t)&gUproarAwakeStringIds, /* gUproarAwakeStringIds */
    (uintptr_t)&gStatUpStringIds, /* gStatUpStringIds */
    (uintptr_t)&gStatDownStringIds, /* gStatDownStringIds */
    (uintptr_t)&gFirstTurnOfTwoStringIds, /* gFirstTurnOfTwoStringIds */
    (uintptr_t)&gWrappedStringIds, /* gWrappedStringIds */
    (uintptr_t)&gMistUsedStringIds, /* gMistUsedStringIds */
    (uintptr_t)&gFocusEnergyUsedStringIds, /* gFocusEnergyUsedStringIds */
    (uintptr_t)&gTransformUsedStringIds, /* gTransformUsedStringIds */
    (uintptr_t)&gSubstituteUsedStringIds, /* gSubstituteUsedStringIds */
    (uintptr_t)&gGotPoisonedStringIds, /* gGotPoisonedStringIds */
    (uintptr_t)&gGotParalyzedStringIds, /* gGotParalyzedStringIds */
    (uintptr_t)&gFellAsleepStringIds, /* gFellAsleepStringIds */
    (uintptr_t)&gGotBurnedStringIds, /* gGotBurnedStringIds */
    (uintptr_t)&gGotFrozenStringIds, /* gGotFrozenStringIds */
    (uintptr_t)&gGotDefrostedStringIds, /* gGotDefrostedStringIds */
    (uintptr_t)&gKOFailedStringIds, /* gKOFailedStringIds */
    (uintptr_t)&gAbsorbDrainStringIds, /* gAbsorbDrainStringIds */
    (uintptr_t)&gSportsUsedStringIds, /* gSportsUsedStringIds */
    (uintptr_t)&gPartyStatusHealStringIds, /* gPartyStatusHealStringIds */
    (uintptr_t)&gFutureMoveUsedStringIds, /* gFutureMoveUsedStringIds */
    (uintptr_t)&gBallEscapeStringIds, /* gBallEscapeStringIds */
    (uintptr_t)&gWeatherStartsStringIds, /* gWeatherStartsStringIds */
    (uintptr_t)&gInobedientStringIds, /* gInobedientStringIds */
    (uintptr_t)&gSafariGetNearStringIds, /* gSafariGetNearStringIds */
    (uintptr_t)&gSafariPokeblockResultStringIds, /* gSafariPokeblockResultStringIds */
    (uintptr_t)&gTrainerItemCuredStatusStringIds, /* gTrainerItemCuredStatusStringIds */
    (uintptr_t)&gBerryEffectStringIds, /* gBerryEffectStringIds */
    (uintptr_t)&gBRNPreventionStringIds, /* gBRNPreventionStringIds */
    (uintptr_t)&gPRLZPreventionStringIds, /* gPRLZPreventionStringIds */
    (uintptr_t)&gPSNPreventionStringIds, /* gPSNPreventionStringIds */
    (uintptr_t)&gItemSwapStringIds, /* gItemSwapStringIds */
    (uintptr_t)&gFlashFireStringIds, /* gFlashFireStringIds */
    (uintptr_t)&gCaughtMonStringIds, /* gCaughtMonStringIds */
    (uintptr_t)&gBattlePalaceFlavorTextTable, /* gBattlePalaceFlavorTextTable */
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
    0u,
};

#if !(defined(NATIVE_LINUX) && defined(LINUX64) && (LINUX64 == 1))
/* Compiled-label host-address table (off-linux64 only). */
extern uint8_t BattleScript_AbilityCuredStatus;
extern uint8_t BattleScript_AbilityNoSpecificStatLoss;
extern uint8_t BattleScript_AbilityNoStatLoss;
extern uint8_t BattleScript_ActionSelectionItemsCantBeUsed;
extern uint8_t BattleScript_ActionSwitch;
extern uint8_t BattleScript_AllStatsUp;
extern uint8_t BattleScript_AlreadyAtFullHp;
extern uint8_t BattleScript_ApplySecondaryEffect;
extern uint8_t BattleScript_ArenaDoJudgment;
extern uint8_t BattleScript_ArenaTurnBeginning;
extern uint8_t BattleScript_AskIfWantsToForfeitMatch;
extern uint8_t BattleScript_AtkDefDown;
extern uint8_t BattleScript_BRNPrevention;
extern uint8_t BattleScript_BerryConfuseHealEnd2;
extern uint8_t BattleScript_BerryCureBrnEnd2;
extern uint8_t BattleScript_BerryCureBrnRet;
extern uint8_t BattleScript_BerryCureChosenStatusEnd2;
extern uint8_t BattleScript_BerryCureChosenStatusRet;
extern uint8_t BattleScript_BerryCureConfusionEnd2;
extern uint8_t BattleScript_BerryCureConfusionRet;
extern uint8_t BattleScript_BerryCureFrzEnd2;
extern uint8_t BattleScript_BerryCureFrzRet;
extern uint8_t BattleScript_BerryCureParRet;
extern uint8_t BattleScript_BerryCurePrlzEnd2;
extern uint8_t BattleScript_BerryCurePsnEnd2;
extern uint8_t BattleScript_BerryCurePsnRet;
extern uint8_t BattleScript_BerryCureSlpEnd2;
extern uint8_t BattleScript_BerryCureSlpRet;
extern uint8_t BattleScript_BerryFocusEnergyEnd2;
extern uint8_t BattleScript_BerryPPHealEnd2;
extern uint8_t BattleScript_BerryStatRaiseEnd2;
extern uint8_t BattleScript_BideAttack;
extern uint8_t BattleScript_BideNoEnergyToAttack;
extern uint8_t BattleScript_BideStoringEnergy;
extern uint8_t BattleScript_BurnTurnDmg;
extern uint8_t BattleScript_ButItFailed;
extern uint8_t BattleScript_CastformChange;
extern uint8_t BattleScript_ColorChangeActivates;
extern uint8_t BattleScript_CurseTurnDmg;
extern uint8_t BattleScript_CuteCharmActivates;
extern uint8_t BattleScript_DamagingWeatherContinues;
extern uint8_t BattleScript_DampStopsExplosion;
extern uint8_t BattleScript_DefrostedViaFireMove;
extern uint8_t BattleScript_DestinyBondTakesLife;
extern uint8_t BattleScript_DisabledNoMore;
extern uint8_t BattleScript_DrizzleActivates;
extern uint8_t BattleScript_DroughtActivates;
extern uint8_t BattleScript_EncoredNoMore;
extern uint8_t BattleScript_EnduredMsg;
extern uint8_t BattleScript_FaintAttacker;
extern uint8_t BattleScript_FaintTarget;
extern uint8_t BattleScript_FlashFireBoost;
extern uint8_t BattleScript_FlashFireBoost_PPLoss;
extern uint8_t BattleScript_FlinchPrevention;
extern uint8_t BattleScript_FlushMessageBox;
extern uint8_t BattleScript_FocusBandActivates;
extern uint8_t BattleScript_FocusPunchSetUp;
extern uint8_t BattleScript_FrontierLinkBattleLost;
extern uint8_t BattleScript_FrontierTrainerBattleWon;
extern uint8_t BattleScript_GiveExp;
extern uint8_t BattleScript_GotAwaySafely;
extern uint8_t BattleScript_GrudgeTakesPp;
extern uint8_t BattleScript_HandleFaintedMon;
extern uint8_t BattleScript_HitFromCritCalc;
extern uint8_t BattleScript_IgnoresAndFallsAsleep;
extern uint8_t BattleScript_IgnoresAndHitsItself;
extern uint8_t BattleScript_IgnoresAndUsesRandomMove;
extern uint8_t BattleScript_IgnoresWhileAsleep;
extern uint8_t BattleScript_IngrainTurnHeal;
extern uint8_t BattleScript_IntimidateActivates;
extern uint8_t BattleScript_IntimidateActivatesEnd3;
extern uint8_t BattleScript_ItemHealHP_End2;
extern uint8_t BattleScript_ItemHealHP_RemoveItem;
extern uint8_t BattleScript_ItemHealHP_Ret;
extern uint8_t BattleScript_ItemSteal;
extern uint8_t BattleScript_KnockedOff;
extern uint8_t BattleScript_LeechSeedFree;
extern uint8_t BattleScript_LeechSeedTurnDrain;
extern uint8_t BattleScript_LevelUp;
extern uint8_t BattleScript_LinkBattleWonOrLost;
extern uint8_t BattleScript_LocalBattleLost;
extern uint8_t BattleScript_LocalTrainerBattleWon;
extern uint8_t BattleScript_MagicCoatBounce;
extern uint8_t BattleScript_MistProtected;
extern uint8_t BattleScript_MonMadeMoveUseless;
extern uint8_t BattleScript_MonMadeMoveUseless_PPLoss;
extern uint8_t BattleScript_MonTookFutureAttack;
extern uint8_t BattleScript_MonWokeUpInUproar;
extern uint8_t BattleScript_MoveEffectBurn;
extern uint8_t BattleScript_MoveEffectConfusion;
extern uint8_t BattleScript_MoveEffectFreeze;
extern uint8_t BattleScript_MoveEffectParalysis;
extern uint8_t BattleScript_MoveEffectPayDay;
extern uint8_t BattleScript_MoveEffectPoison;
extern uint8_t BattleScript_MoveEffectRecoil;
extern uint8_t BattleScript_MoveEffectSleep;
extern uint8_t BattleScript_MoveEffectToxic;
extern uint8_t BattleScript_MoveEffectUproar;
extern uint8_t BattleScript_MoveEffectWrap;
extern uint8_t BattleScript_MoveEnd;
extern uint8_t BattleScript_MoveHPDrain;
extern uint8_t BattleScript_MoveHPDrain_PPLoss;
extern uint8_t BattleScript_MoveMissedPause;
extern uint8_t BattleScript_MoveUsedFlinched;
extern uint8_t BattleScript_MoveUsedIsAsleep;
extern uint8_t BattleScript_MoveUsedIsConfused;
extern uint8_t BattleScript_MoveUsedIsConfusedNoMore;
extern uint8_t BattleScript_MoveUsedIsDisabled;
extern uint8_t BattleScript_MoveUsedIsFrozen;
extern uint8_t BattleScript_MoveUsedIsImprisoned;
extern uint8_t BattleScript_MoveUsedIsInLove;
extern uint8_t BattleScript_MoveUsedIsInLoveCantAttack;
extern uint8_t BattleScript_MoveUsedIsParalyzed;
extern uint8_t BattleScript_MoveUsedIsTaunted;
extern uint8_t BattleScript_MoveUsedLoafingAround;
extern uint8_t BattleScript_MoveUsedMustRecharge;
extern uint8_t BattleScript_MoveUsedUnfroze;
extern uint8_t BattleScript_MoveUsedWokeUp;
extern uint8_t BattleScript_NightmareTurnDmg;
extern uint8_t BattleScript_NoItemSteal;
extern uint8_t BattleScript_NoMovesLeft;
extern uint8_t BattleScript_NoPPForMove;
extern uint8_t BattleScript_ObliviousPreventsAttraction;
extern uint8_t BattleScript_OneHitKOMsg;
extern uint8_t BattleScript_OverworldWeatherStarts;
extern uint8_t BattleScript_PRLZPrevention;
extern uint8_t BattleScript_PSNPrevention;
extern uint8_t BattleScript_PalacePrintFlavorText;
extern uint8_t BattleScript_Pausex20;
extern uint8_t BattleScript_PayDayMoneyAndPickUpItems;
extern uint8_t BattleScript_PerishSongCountGoesDown;
extern uint8_t BattleScript_PerishSongTakesLife;
extern uint8_t BattleScript_PlayerUsesItem;
extern uint8_t BattleScript_PoisonTurnDmg;
extern uint8_t BattleScript_PresentHealTarget;
extern uint8_t BattleScript_PrintCantEscapeFromBattle;
extern uint8_t BattleScript_PrintCantRunFromTrainer;
extern uint8_t BattleScript_PrintFailedToRunString;
extern uint8_t BattleScript_PrintFullBox;
extern uint8_t BattleScript_PrintPayDayMoneyString;
extern uint8_t BattleScript_PrintPlayerForfeited;
extern uint8_t BattleScript_PrintPlayerForfeitedLinkBattle;
extern uint8_t BattleScript_PrintUproarOverTurns;
extern uint8_t BattleScript_RageIsBuilding;
extern uint8_t BattleScript_RainContinuesOrEnds;
extern uint8_t BattleScript_RainDishActivates;
extern uint8_t BattleScript_RanAwayUsingMonAbility;
extern uint8_t BattleScript_RapidSpinAway;
extern uint8_t BattleScript_RoughSkinActivates;
extern uint8_t BattleScript_RunByUsingItem;
extern uint8_t BattleScript_SAtkDown2;
extern uint8_t BattleScript_SafeguardEnds;
extern uint8_t BattleScript_SandStormHailEnds;
extern uint8_t BattleScript_SandstreamActivates;
extern uint8_t BattleScript_SelectingDisabledMove;
extern uint8_t BattleScript_SelectingDisabledMoveInPalace;
extern uint8_t BattleScript_SelectingImprisonedMove;
extern uint8_t BattleScript_SelectingImprisonedMoveInPalace;
extern uint8_t BattleScript_SelectingMoveWithNoPP;
extern uint8_t BattleScript_SelectingNotAllowedMoveChoiceItem;
extern uint8_t BattleScript_SelectingNotAllowedMoveTaunt;
extern uint8_t BattleScript_SelectingNotAllowedMoveTauntInPalace;
extern uint8_t BattleScript_SelectingTormentedMove;
extern uint8_t BattleScript_SelectingTormentedMoveInPalace;
extern uint8_t BattleScript_ShakeBallThrow;
extern uint8_t BattleScript_ShedSkinActivates;
extern uint8_t BattleScript_SideStatusWoreOff;
extern uint8_t BattleScript_SmokeBallEscape;
extern uint8_t BattleScript_SnatchedMove;
extern uint8_t BattleScript_SoundproofProtected;
extern uint8_t BattleScript_SpeedBoostActivates;
extern uint8_t BattleScript_SpikesFree;
extern uint8_t BattleScript_SpikesOnAttacker;
extern uint8_t BattleScript_SpikesOnFaintedBattler;
extern uint8_t BattleScript_SpikesOnTarget;
extern uint8_t BattleScript_StatDown;
extern uint8_t BattleScript_StatUp;
extern uint8_t BattleScript_StickyHoldActivates;
extern uint8_t BattleScript_SturdyPreventsOHKO;
extern uint8_t BattleScript_SubstituteFade;
extern uint8_t BattleScript_SuccessBallThrow;
extern uint8_t BattleScript_SuccessForceOut;
extern uint8_t BattleScript_SunlightContinues;
extern uint8_t BattleScript_SunlightFaded;
extern uint8_t BattleScript_SynchronizeActivates;
extern uint8_t BattleScript_TargetPRLZHeal;
extern uint8_t BattleScript_ThrashConfuses;
extern uint8_t BattleScript_TookAttack;
extern uint8_t BattleScript_TraceActivates;
extern uint8_t BattleScript_TrainerBallBlock;
extern uint8_t BattleScript_WallyBallThrow;
extern uint8_t BattleScript_WhiteHerbEnd2;
extern uint8_t BattleScript_WhiteHerbRet;
extern uint8_t BattleScript_WildMonFled;
extern uint8_t BattleScript_WishComesTrue;
extern uint8_t BattleScript_WrapEnds;
extern uint8_t BattleScript_WrapFree;
extern uint8_t BattleScript_WrapTurnDmg;
extern uint8_t BattleScript_YawnMakesAsleep;

static const uintptr_t sLabelAddresses[] = {
    (uintptr_t)&BattleScript_AbilityCuredStatus, /* BattleScript_AbilityCuredStatus */
    (uintptr_t)&BattleScript_AbilityNoSpecificStatLoss, /* BattleScript_AbilityNoSpecificStatLoss */
    (uintptr_t)&BattleScript_AbilityNoStatLoss, /* BattleScript_AbilityNoStatLoss */
    (uintptr_t)&BattleScript_ActionSelectionItemsCantBeUsed, /* BattleScript_ActionSelectionItemsCantBeUsed */
    (uintptr_t)&BattleScript_ActionSwitch, /* BattleScript_ActionSwitch */
    (uintptr_t)&BattleScript_AllStatsUp, /* BattleScript_AllStatsUp */
    (uintptr_t)&BattleScript_AlreadyAtFullHp, /* BattleScript_AlreadyAtFullHp */
    (uintptr_t)&BattleScript_ApplySecondaryEffect, /* BattleScript_ApplySecondaryEffect */
    (uintptr_t)&BattleScript_ArenaDoJudgment, /* BattleScript_ArenaDoJudgment */
    (uintptr_t)&BattleScript_ArenaTurnBeginning, /* BattleScript_ArenaTurnBeginning */
    (uintptr_t)&BattleScript_AskIfWantsToForfeitMatch, /* BattleScript_AskIfWantsToForfeitMatch */
    (uintptr_t)&BattleScript_AtkDefDown, /* BattleScript_AtkDefDown */
    (uintptr_t)&BattleScript_BRNPrevention, /* BattleScript_BRNPrevention */
    (uintptr_t)&BattleScript_BerryConfuseHealEnd2, /* BattleScript_BerryConfuseHealEnd2 */
    (uintptr_t)&BattleScript_BerryCureBrnEnd2, /* BattleScript_BerryCureBrnEnd2 */
    (uintptr_t)&BattleScript_BerryCureBrnRet, /* BattleScript_BerryCureBrnRet */
    (uintptr_t)&BattleScript_BerryCureChosenStatusEnd2, /* BattleScript_BerryCureChosenStatusEnd2 */
    (uintptr_t)&BattleScript_BerryCureChosenStatusRet, /* BattleScript_BerryCureChosenStatusRet */
    (uintptr_t)&BattleScript_BerryCureConfusionEnd2, /* BattleScript_BerryCureConfusionEnd2 */
    (uintptr_t)&BattleScript_BerryCureConfusionRet, /* BattleScript_BerryCureConfusionRet */
    (uintptr_t)&BattleScript_BerryCureFrzEnd2, /* BattleScript_BerryCureFrzEnd2 */
    (uintptr_t)&BattleScript_BerryCureFrzRet, /* BattleScript_BerryCureFrzRet */
    (uintptr_t)&BattleScript_BerryCureParRet, /* BattleScript_BerryCureParRet */
    (uintptr_t)&BattleScript_BerryCurePrlzEnd2, /* BattleScript_BerryCurePrlzEnd2 */
    (uintptr_t)&BattleScript_BerryCurePsnEnd2, /* BattleScript_BerryCurePsnEnd2 */
    (uintptr_t)&BattleScript_BerryCurePsnRet, /* BattleScript_BerryCurePsnRet */
    (uintptr_t)&BattleScript_BerryCureSlpEnd2, /* BattleScript_BerryCureSlpEnd2 */
    (uintptr_t)&BattleScript_BerryCureSlpRet, /* BattleScript_BerryCureSlpRet */
    (uintptr_t)&BattleScript_BerryFocusEnergyEnd2, /* BattleScript_BerryFocusEnergyEnd2 */
    (uintptr_t)&BattleScript_BerryPPHealEnd2, /* BattleScript_BerryPPHealEnd2 */
    (uintptr_t)&BattleScript_BerryStatRaiseEnd2, /* BattleScript_BerryStatRaiseEnd2 */
    (uintptr_t)&BattleScript_BideAttack, /* BattleScript_BideAttack */
    (uintptr_t)&BattleScript_BideNoEnergyToAttack, /* BattleScript_BideNoEnergyToAttack */
    (uintptr_t)&BattleScript_BideStoringEnergy, /* BattleScript_BideStoringEnergy */
    (uintptr_t)&BattleScript_BurnTurnDmg, /* BattleScript_BurnTurnDmg */
    (uintptr_t)&BattleScript_ButItFailed, /* BattleScript_ButItFailed */
    (uintptr_t)&BattleScript_CastformChange, /* BattleScript_CastformChange */
    (uintptr_t)&BattleScript_ColorChangeActivates, /* BattleScript_ColorChangeActivates */
    (uintptr_t)&BattleScript_CurseTurnDmg, /* BattleScript_CurseTurnDmg */
    (uintptr_t)&BattleScript_CuteCharmActivates, /* BattleScript_CuteCharmActivates */
    (uintptr_t)&BattleScript_DamagingWeatherContinues, /* BattleScript_DamagingWeatherContinues */
    (uintptr_t)&BattleScript_DampStopsExplosion, /* BattleScript_DampStopsExplosion */
    (uintptr_t)&BattleScript_DefrostedViaFireMove, /* BattleScript_DefrostedViaFireMove */
    (uintptr_t)&BattleScript_DestinyBondTakesLife, /* BattleScript_DestinyBondTakesLife */
    (uintptr_t)&BattleScript_DisabledNoMore, /* BattleScript_DisabledNoMore */
    (uintptr_t)&BattleScript_DrizzleActivates, /* BattleScript_DrizzleActivates */
    (uintptr_t)&BattleScript_DroughtActivates, /* BattleScript_DroughtActivates */
    (uintptr_t)&BattleScript_EncoredNoMore, /* BattleScript_EncoredNoMore */
    (uintptr_t)&BattleScript_EnduredMsg, /* BattleScript_EnduredMsg */
    (uintptr_t)&BattleScript_FaintAttacker, /* BattleScript_FaintAttacker */
    (uintptr_t)&BattleScript_FaintTarget, /* BattleScript_FaintTarget */
    (uintptr_t)&BattleScript_FlashFireBoost, /* BattleScript_FlashFireBoost */
    (uintptr_t)&BattleScript_FlashFireBoost_PPLoss, /* BattleScript_FlashFireBoost_PPLoss */
    (uintptr_t)&BattleScript_FlinchPrevention, /* BattleScript_FlinchPrevention */
    (uintptr_t)&BattleScript_FlushMessageBox, /* BattleScript_FlushMessageBox */
    (uintptr_t)&BattleScript_FocusBandActivates, /* BattleScript_FocusBandActivates */
    (uintptr_t)&BattleScript_FocusPunchSetUp, /* BattleScript_FocusPunchSetUp */
    (uintptr_t)&BattleScript_FrontierLinkBattleLost, /* BattleScript_FrontierLinkBattleLost */
    (uintptr_t)&BattleScript_FrontierTrainerBattleWon, /* BattleScript_FrontierTrainerBattleWon */
    (uintptr_t)&BattleScript_GiveExp, /* BattleScript_GiveExp */
    (uintptr_t)&BattleScript_GotAwaySafely, /* BattleScript_GotAwaySafely */
    (uintptr_t)&BattleScript_GrudgeTakesPp, /* BattleScript_GrudgeTakesPp */
    (uintptr_t)&BattleScript_HandleFaintedMon, /* BattleScript_HandleFaintedMon */
    (uintptr_t)&BattleScript_HitFromCritCalc, /* BattleScript_HitFromCritCalc */
    (uintptr_t)&BattleScript_IgnoresAndFallsAsleep, /* BattleScript_IgnoresAndFallsAsleep */
    (uintptr_t)&BattleScript_IgnoresAndHitsItself, /* BattleScript_IgnoresAndHitsItself */
    (uintptr_t)&BattleScript_IgnoresAndUsesRandomMove, /* BattleScript_IgnoresAndUsesRandomMove */
    (uintptr_t)&BattleScript_IgnoresWhileAsleep, /* BattleScript_IgnoresWhileAsleep */
    (uintptr_t)&BattleScript_IngrainTurnHeal, /* BattleScript_IngrainTurnHeal */
    (uintptr_t)&BattleScript_IntimidateActivates, /* BattleScript_IntimidateActivates */
    (uintptr_t)&BattleScript_IntimidateActivatesEnd3, /* BattleScript_IntimidateActivatesEnd3 */
    (uintptr_t)&BattleScript_ItemHealHP_End2, /* BattleScript_ItemHealHP_End2 */
    (uintptr_t)&BattleScript_ItemHealHP_RemoveItem, /* BattleScript_ItemHealHP_RemoveItem */
    (uintptr_t)&BattleScript_ItemHealHP_Ret, /* BattleScript_ItemHealHP_Ret */
    (uintptr_t)&BattleScript_ItemSteal, /* BattleScript_ItemSteal */
    (uintptr_t)&BattleScript_KnockedOff, /* BattleScript_KnockedOff */
    (uintptr_t)&BattleScript_LeechSeedFree, /* BattleScript_LeechSeedFree */
    (uintptr_t)&BattleScript_LeechSeedTurnDrain, /* BattleScript_LeechSeedTurnDrain */
    (uintptr_t)&BattleScript_LevelUp, /* BattleScript_LevelUp */
    (uintptr_t)&BattleScript_LinkBattleWonOrLost, /* BattleScript_LinkBattleWonOrLost */
    (uintptr_t)&BattleScript_LocalBattleLost, /* BattleScript_LocalBattleLost */
    (uintptr_t)&BattleScript_LocalTrainerBattleWon, /* BattleScript_LocalTrainerBattleWon */
    (uintptr_t)&BattleScript_MagicCoatBounce, /* BattleScript_MagicCoatBounce */
    (uintptr_t)&BattleScript_MistProtected, /* BattleScript_MistProtected */
    (uintptr_t)&BattleScript_MonMadeMoveUseless, /* BattleScript_MonMadeMoveUseless */
    (uintptr_t)&BattleScript_MonMadeMoveUseless_PPLoss, /* BattleScript_MonMadeMoveUseless_PPLoss */
    (uintptr_t)&BattleScript_MonTookFutureAttack, /* BattleScript_MonTookFutureAttack */
    (uintptr_t)&BattleScript_MonWokeUpInUproar, /* BattleScript_MonWokeUpInUproar */
    (uintptr_t)&BattleScript_MoveEffectBurn, /* BattleScript_MoveEffectBurn */
    (uintptr_t)&BattleScript_MoveEffectConfusion, /* BattleScript_MoveEffectConfusion */
    (uintptr_t)&BattleScript_MoveEffectFreeze, /* BattleScript_MoveEffectFreeze */
    (uintptr_t)&BattleScript_MoveEffectParalysis, /* BattleScript_MoveEffectParalysis */
    (uintptr_t)&BattleScript_MoveEffectPayDay, /* BattleScript_MoveEffectPayDay */
    (uintptr_t)&BattleScript_MoveEffectPoison, /* BattleScript_MoveEffectPoison */
    (uintptr_t)&BattleScript_MoveEffectRecoil, /* BattleScript_MoveEffectRecoil */
    (uintptr_t)&BattleScript_MoveEffectSleep, /* BattleScript_MoveEffectSleep */
    (uintptr_t)&BattleScript_MoveEffectToxic, /* BattleScript_MoveEffectToxic */
    (uintptr_t)&BattleScript_MoveEffectUproar, /* BattleScript_MoveEffectUproar */
    (uintptr_t)&BattleScript_MoveEffectWrap, /* BattleScript_MoveEffectWrap */
    (uintptr_t)&BattleScript_MoveEnd, /* BattleScript_MoveEnd */
    (uintptr_t)&BattleScript_MoveHPDrain, /* BattleScript_MoveHPDrain */
    (uintptr_t)&BattleScript_MoveHPDrain_PPLoss, /* BattleScript_MoveHPDrain_PPLoss */
    (uintptr_t)&BattleScript_MoveMissedPause, /* BattleScript_MoveMissedPause */
    (uintptr_t)&BattleScript_MoveUsedFlinched, /* BattleScript_MoveUsedFlinched */
    (uintptr_t)&BattleScript_MoveUsedIsAsleep, /* BattleScript_MoveUsedIsAsleep */
    (uintptr_t)&BattleScript_MoveUsedIsConfused, /* BattleScript_MoveUsedIsConfused */
    (uintptr_t)&BattleScript_MoveUsedIsConfusedNoMore, /* BattleScript_MoveUsedIsConfusedNoMore */
    (uintptr_t)&BattleScript_MoveUsedIsDisabled, /* BattleScript_MoveUsedIsDisabled */
    (uintptr_t)&BattleScript_MoveUsedIsFrozen, /* BattleScript_MoveUsedIsFrozen */
    (uintptr_t)&BattleScript_MoveUsedIsImprisoned, /* BattleScript_MoveUsedIsImprisoned */
    (uintptr_t)&BattleScript_MoveUsedIsInLove, /* BattleScript_MoveUsedIsInLove */
    (uintptr_t)&BattleScript_MoveUsedIsInLoveCantAttack, /* BattleScript_MoveUsedIsInLoveCantAttack */
    (uintptr_t)&BattleScript_MoveUsedIsParalyzed, /* BattleScript_MoveUsedIsParalyzed */
    (uintptr_t)&BattleScript_MoveUsedIsTaunted, /* BattleScript_MoveUsedIsTaunted */
    (uintptr_t)&BattleScript_MoveUsedLoafingAround, /* BattleScript_MoveUsedLoafingAround */
    (uintptr_t)&BattleScript_MoveUsedMustRecharge, /* BattleScript_MoveUsedMustRecharge */
    (uintptr_t)&BattleScript_MoveUsedUnfroze, /* BattleScript_MoveUsedUnfroze */
    (uintptr_t)&BattleScript_MoveUsedWokeUp, /* BattleScript_MoveUsedWokeUp */
    (uintptr_t)&BattleScript_NightmareTurnDmg, /* BattleScript_NightmareTurnDmg */
    (uintptr_t)&BattleScript_NoItemSteal, /* BattleScript_NoItemSteal */
    (uintptr_t)&BattleScript_NoMovesLeft, /* BattleScript_NoMovesLeft */
    (uintptr_t)&BattleScript_NoPPForMove, /* BattleScript_NoPPForMove */
    (uintptr_t)&BattleScript_ObliviousPreventsAttraction, /* BattleScript_ObliviousPreventsAttraction */
    (uintptr_t)&BattleScript_OneHitKOMsg, /* BattleScript_OneHitKOMsg */
    (uintptr_t)&BattleScript_OverworldWeatherStarts, /* BattleScript_OverworldWeatherStarts */
    (uintptr_t)&BattleScript_PRLZPrevention, /* BattleScript_PRLZPrevention */
    (uintptr_t)&BattleScript_PSNPrevention, /* BattleScript_PSNPrevention */
    (uintptr_t)&BattleScript_PalacePrintFlavorText, /* BattleScript_PalacePrintFlavorText */
    (uintptr_t)&BattleScript_Pausex20, /* BattleScript_Pausex20 */
    (uintptr_t)&BattleScript_PayDayMoneyAndPickUpItems, /* BattleScript_PayDayMoneyAndPickUpItems */
    (uintptr_t)&BattleScript_PerishSongCountGoesDown, /* BattleScript_PerishSongCountGoesDown */
    (uintptr_t)&BattleScript_PerishSongTakesLife, /* BattleScript_PerishSongTakesLife */
    (uintptr_t)&BattleScript_PlayerUsesItem, /* BattleScript_PlayerUsesItem */
    (uintptr_t)&BattleScript_PoisonTurnDmg, /* BattleScript_PoisonTurnDmg */
    (uintptr_t)&BattleScript_PresentHealTarget, /* BattleScript_PresentHealTarget */
    (uintptr_t)&BattleScript_PrintCantEscapeFromBattle, /* BattleScript_PrintCantEscapeFromBattle */
    (uintptr_t)&BattleScript_PrintCantRunFromTrainer, /* BattleScript_PrintCantRunFromTrainer */
    (uintptr_t)&BattleScript_PrintFailedToRunString, /* BattleScript_PrintFailedToRunString */
    (uintptr_t)&BattleScript_PrintFullBox, /* BattleScript_PrintFullBox */
    (uintptr_t)&BattleScript_PrintPayDayMoneyString, /* BattleScript_PrintPayDayMoneyString */
    (uintptr_t)&BattleScript_PrintPlayerForfeited, /* BattleScript_PrintPlayerForfeited */
    (uintptr_t)&BattleScript_PrintPlayerForfeitedLinkBattle, /* BattleScript_PrintPlayerForfeitedLinkBattle */
    (uintptr_t)&BattleScript_PrintUproarOverTurns, /* BattleScript_PrintUproarOverTurns */
    (uintptr_t)&BattleScript_RageIsBuilding, /* BattleScript_RageIsBuilding */
    (uintptr_t)&BattleScript_RainContinuesOrEnds, /* BattleScript_RainContinuesOrEnds */
    (uintptr_t)&BattleScript_RainDishActivates, /* BattleScript_RainDishActivates */
    (uintptr_t)&BattleScript_RanAwayUsingMonAbility, /* BattleScript_RanAwayUsingMonAbility */
    (uintptr_t)&BattleScript_RapidSpinAway, /* BattleScript_RapidSpinAway */
    (uintptr_t)&BattleScript_RoughSkinActivates, /* BattleScript_RoughSkinActivates */
    (uintptr_t)&BattleScript_RunByUsingItem, /* BattleScript_RunByUsingItem */
    (uintptr_t)&BattleScript_SAtkDown2, /* BattleScript_SAtkDown2 */
    (uintptr_t)&BattleScript_SafeguardEnds, /* BattleScript_SafeguardEnds */
    (uintptr_t)&BattleScript_SandStormHailEnds, /* BattleScript_SandStormHailEnds */
    (uintptr_t)&BattleScript_SandstreamActivates, /* BattleScript_SandstreamActivates */
    (uintptr_t)&BattleScript_SelectingDisabledMove, /* BattleScript_SelectingDisabledMove */
    (uintptr_t)&BattleScript_SelectingDisabledMoveInPalace, /* BattleScript_SelectingDisabledMoveInPalace */
    (uintptr_t)&BattleScript_SelectingImprisonedMove, /* BattleScript_SelectingImprisonedMove */
    (uintptr_t)&BattleScript_SelectingImprisonedMoveInPalace, /* BattleScript_SelectingImprisonedMoveInPalace */
    (uintptr_t)&BattleScript_SelectingMoveWithNoPP, /* BattleScript_SelectingMoveWithNoPP */
    (uintptr_t)&BattleScript_SelectingNotAllowedMoveChoiceItem, /* BattleScript_SelectingNotAllowedMoveChoiceItem */
    (uintptr_t)&BattleScript_SelectingNotAllowedMoveTaunt, /* BattleScript_SelectingNotAllowedMoveTaunt */
    (uintptr_t)&BattleScript_SelectingNotAllowedMoveTauntInPalace, /* BattleScript_SelectingNotAllowedMoveTauntInPalace */
    (uintptr_t)&BattleScript_SelectingTormentedMove, /* BattleScript_SelectingTormentedMove */
    (uintptr_t)&BattleScript_SelectingTormentedMoveInPalace, /* BattleScript_SelectingTormentedMoveInPalace */
    (uintptr_t)&BattleScript_ShakeBallThrow, /* BattleScript_ShakeBallThrow */
    (uintptr_t)&BattleScript_ShedSkinActivates, /* BattleScript_ShedSkinActivates */
    (uintptr_t)&BattleScript_SideStatusWoreOff, /* BattleScript_SideStatusWoreOff */
    (uintptr_t)&BattleScript_SmokeBallEscape, /* BattleScript_SmokeBallEscape */
    (uintptr_t)&BattleScript_SnatchedMove, /* BattleScript_SnatchedMove */
    (uintptr_t)&BattleScript_SoundproofProtected, /* BattleScript_SoundproofProtected */
    (uintptr_t)&BattleScript_SpeedBoostActivates, /* BattleScript_SpeedBoostActivates */
    (uintptr_t)&BattleScript_SpikesFree, /* BattleScript_SpikesFree */
    (uintptr_t)&BattleScript_SpikesOnAttacker, /* BattleScript_SpikesOnAttacker */
    (uintptr_t)&BattleScript_SpikesOnFaintedBattler, /* BattleScript_SpikesOnFaintedBattler */
    (uintptr_t)&BattleScript_SpikesOnTarget, /* BattleScript_SpikesOnTarget */
    (uintptr_t)&BattleScript_StatDown, /* BattleScript_StatDown */
    (uintptr_t)&BattleScript_StatUp, /* BattleScript_StatUp */
    (uintptr_t)&BattleScript_StickyHoldActivates, /* BattleScript_StickyHoldActivates */
    (uintptr_t)&BattleScript_SturdyPreventsOHKO, /* BattleScript_SturdyPreventsOHKO */
    (uintptr_t)&BattleScript_SubstituteFade, /* BattleScript_SubstituteFade */
    (uintptr_t)&BattleScript_SuccessBallThrow, /* BattleScript_SuccessBallThrow */
    (uintptr_t)&BattleScript_SuccessForceOut, /* BattleScript_SuccessForceOut */
    (uintptr_t)&BattleScript_SunlightContinues, /* BattleScript_SunlightContinues */
    (uintptr_t)&BattleScript_SunlightFaded, /* BattleScript_SunlightFaded */
    (uintptr_t)&BattleScript_SynchronizeActivates, /* BattleScript_SynchronizeActivates */
    (uintptr_t)&BattleScript_TargetPRLZHeal, /* BattleScript_TargetPRLZHeal */
    (uintptr_t)&BattleScript_ThrashConfuses, /* BattleScript_ThrashConfuses */
    (uintptr_t)&BattleScript_TookAttack, /* BattleScript_TookAttack */
    (uintptr_t)&BattleScript_TraceActivates, /* BattleScript_TraceActivates */
    (uintptr_t)&BattleScript_TrainerBallBlock, /* BattleScript_TrainerBallBlock */
    (uintptr_t)&BattleScript_WallyBallThrow, /* BattleScript_WallyBallThrow */
    (uintptr_t)&BattleScript_WhiteHerbEnd2, /* BattleScript_WhiteHerbEnd2 */
    (uintptr_t)&BattleScript_WhiteHerbRet, /* BattleScript_WhiteHerbRet */
    (uintptr_t)&BattleScript_WildMonFled, /* BattleScript_WildMonFled */
    (uintptr_t)&BattleScript_WishComesTrue, /* BattleScript_WishComesTrue */
    (uintptr_t)&BattleScript_WrapEnds, /* BattleScript_WrapEnds */
    (uintptr_t)&BattleScript_WrapFree, /* BattleScript_WrapFree */
    (uintptr_t)&BattleScript_WrapTurnDmg, /* BattleScript_WrapTurnDmg */
    (uintptr_t)&BattleScript_YawnMakesAsleep, /* BattleScript_YawnMakesAsleep */
};
#endif

uintptr_t EmeraldBattleLiveNative_BindingAddress(uint32_t index)
{
    if (index >= EMERALD_BATTLE_LIVE_BINDING_COUNT)
        return 0u;
    return sNativeBindingAddresses[index];
}

uintptr_t EmeraldBattleLiveNative_LabelAddress(uint32_t index)
{
#if defined(NATIVE_LINUX) && defined(LINUX64) && (LINUX64 == 1)
    /* R13-H7: the compiled symbols are removed - the accessor
     * yields the canonical GBA word so the label map stays
     * queryable (and ResolveCompiledLabel's linux64 branch
     * compares words). */
    if (index >= EMERALD_BATTLE_LIVE_LABEL_COUNT)
        return 0u;
    return (uintptr_t)kEmeraldBattleLiveTable.labels[index].word;
#else
    if (index >= EMERALD_BATTLE_LIVE_LABEL_COUNT)
        return 0u;
    return sLabelAddresses[index];
#endif
}
