/* Generated by R15 UI family generator (gen_ui_populate.py)
 * Do not edit by hand.
 *
 * Populates every mutable native UI struct's pointer fields from the
 * EmeraldUICompat image. The expressions below are the original GBA
 * initializer expressions; on NATIVE_LINUX the accessor macros in
 * ui_accessors.generated.h translate the legacy symbol names into
 * pack-backed UI_Get() pointers, including &gPal[0x10]-style
 * offsets. */
#include "global.h"
#include "graphics.h"
#include "pokeblock.h"
#include "emerald/resources/ui_struct_population.h"

#if defined(NATIVE_LINUX)

void EmeraldUICompat_PopulateStructs(void)
{
    /* /home/tristen/work/pokeemerald-recomp/src/battle_anim_smokescreen.c */
    sSmokescreenImpactSpriteSheet.data = gSmokescreenImpactTiles;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_anim_smokescreen.c */
    sSmokescreenImpactSpritePalette.data = gSmokescreenImpactPalette;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_anim_smokescreen.c */
    gSpriteSheet_EnemyShadow.data = gEnemyMonShadow_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_arena.c */
    sBattleArenaJudgmentSymbolsSpriteSheet[0].data = gBattleArenaJudgmentSymbolsGfx;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_bg.c */
    sVsLettersSpriteSheet.data = gVsLettersGfx;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_dome.c */
    sTourneyTreeButtonsSpriteSheet[0].data = gDomeTourneyTreeButtons_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_dome.c */
    sTourneyTreeButtonsSpritePal[0].data = gDomeTourneyTreeButtons_Pal;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_gfx_sfx_util.c */
    sSpriteSheet_SinglesPlayerHealthbox.data = gHealthboxSinglesPlayerGfx;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_gfx_sfx_util.c */
    sSpriteSheet_SinglesOpponentHealthbox.data = gHealthboxSinglesOpponentGfx;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_gfx_sfx_util.c */
    sSpriteSheets_DoublesOpponentHealthbox[0].data = gHealthboxDoublesOpponentGfx;
    sSpriteSheets_DoublesOpponentHealthbox[1].data = gHealthboxDoublesOpponentGfx;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_gfx_sfx_util.c */
    sSpriteSheet_SafariHealthbox.data = gHealthboxSafariGfx;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_gfx_sfx_util.c */
    sSpriteSheets_HealthBar[0].data = gBlankGfxCompressed;
    sSpriteSheets_HealthBar[1].data = gBlankGfxCompressed;
    sSpriteSheets_HealthBar[2].data = gBlankGfxCompressed;
    sSpriteSheets_HealthBar[3].data = gBlankGfxCompressed;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_gfx_sfx_util.c */
    sSpritePalettes_HealthBoxHealthBar[0].data = gBattleInterface_BallStatusBarPal;
    sSpritePalettes_HealthBoxHealthBar[1].data = gBattleInterface_BallDisplayPal;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_interface.c */
    sStatusSummaryBarSpriteSheet.data = gBattleInterface_BallStatusBarGfx;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_interface.c */
    sStatusSummaryBarSpritePal.data = gBattleInterface_BallStatusBarPal;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_interface.c */
    sStatusSummaryBallsSpritePal.data = gBattleInterface_BallDisplayPal;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_pyramid_bag.c */
    sSpriteSheet_PyramidBag.data = gBattlePyramidBag_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/berry_blender.c */
    sSpriteSheet_PlayerArrow.data = gBerryBlenderPlayerArrow_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/berry_blender.c */
    sSpritePal_BlenderMisc.data = gBerryBlenderMiscPalette;
    /* /home/tristen/work/pokeemerald-recomp/src/berry_blender.c */
    sSpritePal_PlayerArrow.data = gBerryBlenderArrowPalette;
    /* /home/tristen/work/pokeemerald-recomp/src/berry_blender.c */
    sSpriteSheet_ScoreSymbols.data = gBerryBlenderScoreSymbols_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/berry_blender.c */
    sSpriteSheet_Particles.data = gBerryBlenderParticles_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/berry_blender.c */
    sSpriteSheet_CountdownNumbers.data = gBerryBlenderCountdownNumbers_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/berry_blender.c */
    sSpriteSheet_Start.data = gBerryBlenderStart_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/cable_car.c */
    sCableCarSpriteSheets[0].data = gCableCar_Gfx;
    sCableCarSpriteSheets[1].data = gCableCarDoor_Gfx;
    sCableCarSpriteSheets[2].data = gCableCarCable_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/cable_car.c */
    sCableCarSpritePalettes[0].data = gCableCar_Pal;
    /* /home/tristen/work/pokeemerald-recomp/src/contest.c */
    sSpriteSheet_SliderHeart.data = gContestSliderHeart_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/contest.c */
    sSpriteSheet_NextTurn[0].data = gContestNextTurnGfx;
    sSpriteSheet_NextTurn[1].data = gContestNextTurnGfx;
    sSpriteSheet_NextTurn[2].data = gContestNextTurnGfx;
    sSpriteSheet_NextTurn[3].data = gContestNextTurnGfx;
    /* /home/tristen/work/pokeemerald-recomp/src/contest.c */
    sSpritePalette_NextTurn.data = gContestPal;
    /* /home/tristen/work/pokeemerald-recomp/src/contest.c */
    sSpriteSheet_Faces.data = gContestFaces_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/contest.c */
    sSpriteSheet_ApplauseMeter.data = gContestApplauseGfx;
    /* /home/tristen/work/pokeemerald-recomp/src/contest.c */
    sSpritePalette_ApplauseMeter.data = gContestPal;
    /* /home/tristen/work/pokeemerald-recomp/src/contest.c */
    sSpriteSheet_Judge.data = gContestJudgeGfx;
    /* /home/tristen/work/pokeemerald-recomp/src/contest.c */
    sSpriteSheet_JudgeSymbols.data = gContestJudgeSymbolsGfx;
    /* /home/tristen/work/pokeemerald-recomp/src/contest.c */
    sSpritePalette_JudgeSymbols.data = gContestJudgeSymbolsPal;
    /* /home/tristen/work/pokeemerald-recomp/src/contest.c */
    sSpriteSheets_ContestantsTurnBlinkEffect[0].data = gBlankGfxCompressed;
    sSpriteSheets_ContestantsTurnBlinkEffect[1].data = gBlankGfxCompressed;
    sSpriteSheets_ContestantsTurnBlinkEffect[2].data = gBlankGfxCompressed;
    sSpriteSheets_ContestantsTurnBlinkEffect[3].data = gBlankGfxCompressed;
    /* /home/tristen/work/pokeemerald-recomp/src/contest_util.c */
    sContestConfettiSpriteSheet.data = gConfetti_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/contest_util.c */
    sContestConfettiSpritePalette.data = gConfetti_Pal;
    /* /home/tristen/work/pokeemerald-recomp/src/data/party_menu.h */
    sSpriteSheet_MenuPokeball.data = gPartyMenuPokeball_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/data/party_menu.h */
    sSpritePalette_MenuPokeball.data = gPartyMenuPokeball_Pal;
    /* /home/tristen/work/pokeemerald-recomp/src/data/party_menu.h */
    sSpriteSheet_MenuPokeballSmall.data = gPartyMenuPokeballSmall_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/data/party_menu.h */
    sSpriteSheet_StatusIcons.data = gStatusGfx_Icons;
    /* /home/tristen/work/pokeemerald-recomp/src/data/party_menu.h */
    sSpritePalette_StatusIcons.data = gStatusPal_Icons;
    /* /home/tristen/work/pokeemerald-recomp/src/data/trade.h */
    sCursor_SpriteSheet.data = gTradeCursor_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/data/trade.h */
    sCursor_SpritePalette.data = gTradeCursor_Pal;
    /* /home/tristen/work/pokeemerald-recomp/src/easy_chat.c */
    sEasyChatSpritePalettes[1].data = gEasyChatRectangleCursor_Pal;
    sEasyChatSpritePalettes[2].data = gEasyChatButtonWindow_Pal;
    /* /home/tristen/work/pokeemerald-recomp/src/easy_chat.c */
    sEasyChatCompressedSpriteSheets[1].data = gEasyChatRectangleCursor_Gfx;
    sEasyChatCompressedSpriteSheets[2].data = gEasyChatButtonWindow_Gfx;
    sEasyChatCompressedSpriteSheets[3].data = gEasyChatMode_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/frontier_pass.c */
    sCursorSpriteSheets[2].data = gFrontierPassMedals_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/frontier_pass.c */
    sFrontierPassSpritePalettes[0].data = gFrontierPassCursor_Pal;
    sFrontierPassSpritePalettes[1].data = gFrontierPassMapCursor_Pal;
    sFrontierPassSpritePalettes[2].data = gFrontierPassMedalsSilver_Pal;
    sFrontierPassSpritePalettes[3].data = gFrontierPassMedalsGold_Pal;
    /* /home/tristen/work/pokeemerald-recomp/src/hall_of_fame.c */
    sHoFConfettiSpriteSheets[0].data = gConfetti_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/hall_of_fame.c */
    sHoFConfettiSpritePalettes[0].data = gConfetti_Pal;
    /* /home/tristen/work/pokeemerald-recomp/src/item_menu_icons.c */
    gBagMaleSpriteSheet.data = gBagMaleTiles;
    /* /home/tristen/work/pokeemerald-recomp/src/item_menu_icons.c */
    gBagFemaleSpriteSheet.data = gBagFemaleTiles;
    /* /home/tristen/work/pokeemerald-recomp/src/item_menu_icons.c */
    gBagPaletteTable.data = gBagPalette;
    /* /home/tristen/work/pokeemerald-recomp/src/menu_helpers.c */
    sSpriteSheet_SwapLine.data = gSwapLineGfx;
    /* /home/tristen/work/pokeemerald-recomp/src/menu_helpers.c */
    sSpritePalette_SwapLine.data = gSwapLinePal;
    /* /home/tristen/work/pokeemerald-recomp/src/money.c */
    sSpriteSheet_MoneyLabel.data = gShopMenuMoney_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/money.c */
    sSpritePalette_MoneyLabel.data = gShopMenu_Pal;
    /* /home/tristen/work/pokeemerald-recomp/src/naming_screen.c */
    sNextKeyboardPageTilemaps[0] = gNamingScreenKeyboardUpper_Tilemap; /* [KBPAGE_SYMBOLS] */
    sNextKeyboardPageTilemaps[1] = gNamingScreenKeyboardLower_Tilemap; /* [KBPAGE_LETTERS_UPPER] */
    sNextKeyboardPageTilemaps[2] = gNamingScreenKeyboardSymbols_Tilemap; /* [KBPAGE_LETTERS_LOWER] */
    /* /home/tristen/work/pokeemerald-recomp/src/naming_screen.c */
    sNamingScreenSpriteSheets[0].data = gNamingScreenBackButton_Gfx;
    sNamingScreenSpriteSheets[1].data = gNamingScreenOKButton_Gfx;
    sNamingScreenSpriteSheets[2].data = gNamingScreenPageSwapFrame_Gfx;
    sNamingScreenSpriteSheets[3].data = gNamingScreenPageSwapButton_Gfx;
    sNamingScreenSpriteSheets[4].data = gNamingScreenPageSwapUpper_Gfx;
    sNamingScreenSpriteSheets[5].data = gNamingScreenPageSwapLower_Gfx;
    sNamingScreenSpriteSheets[6].data = gNamingScreenPageSwapOthers_Gfx;
    sNamingScreenSpriteSheets[8].data = gNamingScreenCursorSquished_Gfx;
    sNamingScreenSpriteSheets[9].data = gNamingScreenCursorFilled_Gfx;
    sNamingScreenSpriteSheets[10].data = gNamingScreenInputArrow_Gfx;
    sNamingScreenSpriteSheets[11].data = gNamingScreenUnderscore_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/pokeblock.c */
    gPokeblockCase_SpriteSheet.data = gMenuPokeblockDevice_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/pokeblock.c */
    gPokeblockCase_SpritePal.data = gMenuPokeblockDevice_Pal;
    /* /home/tristen/work/pokeemerald-recomp/src/pokeblock_feed.c */
    sPokeblocksPals[PBLOCK_CLR_RED - 1] = gPokeblockRed_Pal;
    sPokeblocksPals[PBLOCK_CLR_BLUE - 1] = gPokeblockBlue_Pal;
    sPokeblocksPals[PBLOCK_CLR_PINK - 1] = gPokeblockPink_Pal;
    sPokeblocksPals[PBLOCK_CLR_GREEN - 1] = gPokeblockGreen_Pal;
    sPokeblocksPals[PBLOCK_CLR_YELLOW - 1] = gPokeblockYellow_Pal;
    sPokeblocksPals[PBLOCK_CLR_PURPLE - 1] = gPokeblockPurple_Pal;
    sPokeblocksPals[PBLOCK_CLR_INDIGO - 1] = gPokeblockIndigo_Pal;
    sPokeblocksPals[PBLOCK_CLR_BROWN - 1] = gPokeblockBrown_Pal;
    sPokeblocksPals[PBLOCK_CLR_LITE_BLUE - 1] = gPokeblockLiteBlue_Pal;
    sPokeblocksPals[PBLOCK_CLR_OLIVE - 1] = gPokeblockOlive_Pal;
    sPokeblocksPals[PBLOCK_CLR_GRAY - 1] = gPokeblockGray_Pal;
    sPokeblocksPals[PBLOCK_CLR_BLACK - 1] = gPokeblockBlack_Pal;
    sPokeblocksPals[PBLOCK_CLR_WHITE - 1] = gPokeblockWhite_Pal;
    sPokeblocksPals[PBLOCK_CLR_GOLD - 1] = gPokeblockGold_Pal;
    /* /home/tristen/work/pokeemerald-recomp/src/pokeblock_feed.c */
    sSpriteSheet_Pokeblock.data = gPokeblock_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/pokedex.c */
    sInterfaceSpriteSheet[0].data = gPokedexInterface_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/pokedex_area_screen.c */
    sAreaUnknownSpritePalette.data = gPokedexAreaScreenAreaUnknown_Pal;
    /* /home/tristen/work/pokeemerald-recomp/src/pokemon_summary_screen.c */
    sBattleMoveTilemapCtrl.gfx = gSummaryScreen_MoveEffect_Battle_Tilemap;
    /* /home/tristen/work/pokeemerald-recomp/src/pokemon_summary_screen.c */
    sContestMoveTilemapCtrl.gfx = gSummaryScreen_MoveEffect_Contest_Tilemap;
    /* /home/tristen/work/pokeemerald-recomp/src/pokemon_summary_screen.c */
    sSpriteSheet_MoveTypes.data = gMoveTypes_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/pokemon_summary_screen.c */
    sMoveSelectorSpriteSheet.data = gSummaryMoveSelect_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/pokemon_summary_screen.c */
    sMoveSelectorSpritePal.data = gSummaryMoveSelect_Pal;
    /* /home/tristen/work/pokeemerald-recomp/src/pokemon_summary_screen.c */
    sStatusIconsSpriteSheet.data = gStatusGfx_Icons;
    /* /home/tristen/work/pokeemerald-recomp/src/pokemon_summary_screen.c */
    sStatusIconsSpritePalette.data = gStatusPal_Icons;
    /* /home/tristen/work/pokeemerald-recomp/src/pokenav_main_menu.c */
    sMenuLeftHeaderSpriteSheet.data = gPokenavLeftHeaderHoennMap_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/pokenav_main_menu.c */
    sMenuLeftHeaderSpriteSheets[0].data = gPokenavLeftHeaderMainMenu_Gfx;
    sMenuLeftHeaderSpriteSheets[1].data = gPokenavLeftHeaderCondition_Gfx;
    sMenuLeftHeaderSpriteSheets[2].data = gPokenavLeftHeaderRibbons_Gfx;
    sMenuLeftHeaderSpriteSheets[3].data = gPokenavLeftHeaderMatchCall_Gfx;
    sMenuLeftHeaderSpriteSheets[4].data = gPokenavLeftHeaderHoennMap_Gfx;
    sMenuLeftHeaderSpriteSheets[5].data = gPokenavLeftHeaderHoennMap_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/pokenav_main_menu.c */
    sPokenavSubMenuLeftHeaderSpriteSheets[0].data = gPokenavLeftHeaderParty_Gfx;
    sPokenavSubMenuLeftHeaderSpriteSheets[1].data = gPokenavLeftHeaderSearch_Gfx;
    sPokenavSubMenuLeftHeaderSpriteSheets[2].data = gPokenavLeftHeaderCool_Gfx;
    sPokenavSubMenuLeftHeaderSpriteSheets[3].data = gPokenavLeftHeaderBeauty_Gfx;
    sPokenavSubMenuLeftHeaderSpriteSheets[4].data = gPokenavLeftHeaderCute_Gfx;
    sPokenavSubMenuLeftHeaderSpriteSheets[5].data = gPokenavLeftHeaderSmart_Gfx;
    sPokenavSubMenuLeftHeaderSpriteSheets[6].data = gPokenavLeftHeaderTough_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/pokenav_menu_handler_gfx.c */
    sPokenavOptionsSpriteSheets[0].data = gPokenavOptions_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/pokenav_menu_handler_gfx.c */
    sPokenavOptionsSpritePalettes[0].data = &gPokenavOptions_Pal[0x00];
    sPokenavOptionsSpritePalettes[1].data = &gPokenavOptions_Pal[0x10];
    sPokenavOptionsSpritePalettes[2].data = &gPokenavOptions_Pal[0x20];
    sPokenavOptionsSpritePalettes[3].data = &gPokenavOptions_Pal[0x30];
    sPokenavOptionsSpritePalettes[4].data = &gPokenavOptions_Pal[0x40];
    /* /home/tristen/work/pokeemerald-recomp/src/pokenav_region_map.c */
    sCityZoomTextSpriteSheet[0].data = gRegionMapCityZoomText_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/pokenav_region_map.c */
    sCityZoomTilesSpritePalette[0].data = gRegionMapCityZoomTiles_Pal;
    /* /home/tristen/work/pokeemerald-recomp/src/roulette.c */
    sSpriteSheet_Headers.data = gRouletteHeaders_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/roulette.c */
    sRouletteInterfaceSpriteSheets[0].data = gRouletteCredit_Gfx;
    sRouletteInterfaceSpriteSheets[1].data = gRouletteNumbers_Gfx;
    sRouletteInterfaceSpriteSheets[2].data = gRouletteMultiplier_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/roulette.c */
    sSpriteSheet_WheelCenter.data = gRouletteCenter_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/title_screen.c */
    sSpriteSheet_EmeraldVersion[0].data = gTitleScreenEmeraldVersionGfx;
    /* /home/tristen/work/pokeemerald-recomp/src/title_screen.c */
    sSpriteSheet_PressStart[0].data = gTitleScreenPressStartGfx;
    /* /home/tristen/work/pokeemerald-recomp/src/title_screen.c */
    sSpritePalette_PressStart[0].data = gTitleScreenPressStartPal;
    /* /home/tristen/work/pokeemerald-recomp/src/trainer_card.c */
    sHoennTrainerCardPals[0] = gHoennTrainerCardGreen_Pal;
    /* /home/tristen/work/pokeemerald-recomp/src/trainer_card.c */
    sKantoTrainerCardPals[0] = gKantoTrainerCardBlue_Pal;
    /* /home/tristen/work/pokeemerald-recomp/src/union_room_chat.c */
    sUnionRoomChatSpriteSheets[4].data = gUnionRoomChat_RButtonLabels;
    /* /home/tristen/work/pokeemerald-recomp/src/use_pokeblock.c */
    sSpriteSheet_UpDown.data = gUsePokeblockUpDown_Gfx;
    /* /home/tristen/work/pokeemerald-recomp/src/use_pokeblock.c */
    sSpritePalette_UpDown.data = gUsePokeblockUpDown_Pal;
    /* /home/tristen/work/pokeemerald-recomp/src/use_pokeblock.c */
    sSpritePalette_Condition.data = gUsePokeblockCondition_Pal;
    /* /home/tristen/work/pokeemerald-recomp/src/wallclock.c */
    sSpritePalettes_Clock[0].data = gWallClockMale_Pal;
    sSpritePalettes_Clock[1].data = gWallClockFemale_Pal;
}

void EmeraldUICompat_ClearStructPointers(void)
{
    /* /home/tristen/work/pokeemerald-recomp/src/battle_anim_smokescreen.c */
    sSmokescreenImpactSpriteSheet.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_anim_smokescreen.c */
    sSmokescreenImpactSpritePalette.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_anim_smokescreen.c */
    gSpriteSheet_EnemyShadow.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_arena.c */
    sBattleArenaJudgmentSymbolsSpriteSheet[0].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_bg.c */
    sVsLettersSpriteSheet.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_dome.c */
    sTourneyTreeButtonsSpriteSheet[0].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_dome.c */
    sTourneyTreeButtonsSpritePal[0].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_gfx_sfx_util.c */
    sSpriteSheet_SinglesPlayerHealthbox.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_gfx_sfx_util.c */
    sSpriteSheet_SinglesOpponentHealthbox.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_gfx_sfx_util.c */
    sSpriteSheets_DoublesOpponentHealthbox[0].data = NULL;
    sSpriteSheets_DoublesOpponentHealthbox[1].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_gfx_sfx_util.c */
    sSpriteSheet_SafariHealthbox.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_gfx_sfx_util.c */
    sSpriteSheets_HealthBar[0].data = NULL;
    sSpriteSheets_HealthBar[1].data = NULL;
    sSpriteSheets_HealthBar[2].data = NULL;
    sSpriteSheets_HealthBar[3].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_gfx_sfx_util.c */
    sSpritePalettes_HealthBoxHealthBar[0].data = NULL;
    sSpritePalettes_HealthBoxHealthBar[1].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_interface.c */
    sStatusSummaryBarSpriteSheet.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_interface.c */
    sStatusSummaryBarSpritePal.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_interface.c */
    sStatusSummaryBallsSpritePal.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/battle_pyramid_bag.c */
    sSpriteSheet_PyramidBag.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/berry_blender.c */
    sSpriteSheet_PlayerArrow.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/berry_blender.c */
    sSpritePal_BlenderMisc.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/berry_blender.c */
    sSpritePal_PlayerArrow.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/berry_blender.c */
    sSpriteSheet_ScoreSymbols.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/berry_blender.c */
    sSpriteSheet_Particles.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/berry_blender.c */
    sSpriteSheet_CountdownNumbers.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/berry_blender.c */
    sSpriteSheet_Start.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/cable_car.c */
    sCableCarSpriteSheets[0].data = NULL;
    sCableCarSpriteSheets[1].data = NULL;
    sCableCarSpriteSheets[2].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/cable_car.c */
    sCableCarSpritePalettes[0].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/contest.c */
    sSpriteSheet_SliderHeart.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/contest.c */
    sSpriteSheet_NextTurn[0].data = NULL;
    sSpriteSheet_NextTurn[1].data = NULL;
    sSpriteSheet_NextTurn[2].data = NULL;
    sSpriteSheet_NextTurn[3].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/contest.c */
    sSpritePalette_NextTurn.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/contest.c */
    sSpriteSheet_Faces.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/contest.c */
    sSpriteSheet_ApplauseMeter.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/contest.c */
    sSpritePalette_ApplauseMeter.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/contest.c */
    sSpriteSheet_Judge.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/contest.c */
    sSpriteSheet_JudgeSymbols.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/contest.c */
    sSpritePalette_JudgeSymbols.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/contest.c */
    sSpriteSheets_ContestantsTurnBlinkEffect[0].data = NULL;
    sSpriteSheets_ContestantsTurnBlinkEffect[1].data = NULL;
    sSpriteSheets_ContestantsTurnBlinkEffect[2].data = NULL;
    sSpriteSheets_ContestantsTurnBlinkEffect[3].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/contest_util.c */
    sContestConfettiSpriteSheet.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/contest_util.c */
    sContestConfettiSpritePalette.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/data/party_menu.h */
    sSpriteSheet_MenuPokeball.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/data/party_menu.h */
    sSpritePalette_MenuPokeball.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/data/party_menu.h */
    sSpriteSheet_MenuPokeballSmall.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/data/party_menu.h */
    sSpriteSheet_StatusIcons.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/data/party_menu.h */
    sSpritePalette_StatusIcons.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/data/trade.h */
    sCursor_SpriteSheet.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/data/trade.h */
    sCursor_SpritePalette.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/easy_chat.c */
    sEasyChatSpritePalettes[1].data = NULL;
    sEasyChatSpritePalettes[2].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/easy_chat.c */
    sEasyChatCompressedSpriteSheets[1].data = NULL;
    sEasyChatCompressedSpriteSheets[2].data = NULL;
    sEasyChatCompressedSpriteSheets[3].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/frontier_pass.c */
    sCursorSpriteSheets[2].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/frontier_pass.c */
    sFrontierPassSpritePalettes[0].data = NULL;
    sFrontierPassSpritePalettes[1].data = NULL;
    sFrontierPassSpritePalettes[2].data = NULL;
    sFrontierPassSpritePalettes[3].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/hall_of_fame.c */
    sHoFConfettiSpriteSheets[0].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/hall_of_fame.c */
    sHoFConfettiSpritePalettes[0].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/item_menu_icons.c */
    gBagMaleSpriteSheet.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/item_menu_icons.c */
    gBagFemaleSpriteSheet.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/item_menu_icons.c */
    gBagPaletteTable.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/menu_helpers.c */
    sSpriteSheet_SwapLine.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/menu_helpers.c */
    sSpritePalette_SwapLine.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/money.c */
    sSpriteSheet_MoneyLabel.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/money.c */
    sSpritePalette_MoneyLabel.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/naming_screen.c */
    sNextKeyboardPageTilemaps[0] = NULL; /* [KBPAGE_SYMBOLS] */
    sNextKeyboardPageTilemaps[1] = NULL; /* [KBPAGE_LETTERS_UPPER] */
    sNextKeyboardPageTilemaps[2] = NULL; /* [KBPAGE_LETTERS_LOWER] */
    /* /home/tristen/work/pokeemerald-recomp/src/naming_screen.c */
    sNamingScreenSpriteSheets[0].data = NULL;
    sNamingScreenSpriteSheets[1].data = NULL;
    sNamingScreenSpriteSheets[2].data = NULL;
    sNamingScreenSpriteSheets[3].data = NULL;
    sNamingScreenSpriteSheets[4].data = NULL;
    sNamingScreenSpriteSheets[5].data = NULL;
    sNamingScreenSpriteSheets[6].data = NULL;
    sNamingScreenSpriteSheets[8].data = NULL;
    sNamingScreenSpriteSheets[9].data = NULL;
    sNamingScreenSpriteSheets[10].data = NULL;
    sNamingScreenSpriteSheets[11].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/pokeblock.c */
    gPokeblockCase_SpriteSheet.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/pokeblock.c */
    gPokeblockCase_SpritePal.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/pokeblock_feed.c */
    sPokeblocksPals[PBLOCK_CLR_RED - 1] = NULL;
    sPokeblocksPals[PBLOCK_CLR_BLUE - 1] = NULL;
    sPokeblocksPals[PBLOCK_CLR_PINK - 1] = NULL;
    sPokeblocksPals[PBLOCK_CLR_GREEN - 1] = NULL;
    sPokeblocksPals[PBLOCK_CLR_YELLOW - 1] = NULL;
    sPokeblocksPals[PBLOCK_CLR_PURPLE - 1] = NULL;
    sPokeblocksPals[PBLOCK_CLR_INDIGO - 1] = NULL;
    sPokeblocksPals[PBLOCK_CLR_BROWN - 1] = NULL;
    sPokeblocksPals[PBLOCK_CLR_LITE_BLUE - 1] = NULL;
    sPokeblocksPals[PBLOCK_CLR_OLIVE - 1] = NULL;
    sPokeblocksPals[PBLOCK_CLR_GRAY - 1] = NULL;
    sPokeblocksPals[PBLOCK_CLR_BLACK - 1] = NULL;
    sPokeblocksPals[PBLOCK_CLR_WHITE - 1] = NULL;
    sPokeblocksPals[PBLOCK_CLR_GOLD - 1] = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/pokeblock_feed.c */
    sSpriteSheet_Pokeblock.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/pokedex.c */
    sInterfaceSpriteSheet[0].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/pokedex_area_screen.c */
    sAreaUnknownSpritePalette.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/pokemon_summary_screen.c */
    sBattleMoveTilemapCtrl.gfx = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/pokemon_summary_screen.c */
    sContestMoveTilemapCtrl.gfx = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/pokemon_summary_screen.c */
    sSpriteSheet_MoveTypes.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/pokemon_summary_screen.c */
    sMoveSelectorSpriteSheet.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/pokemon_summary_screen.c */
    sMoveSelectorSpritePal.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/pokemon_summary_screen.c */
    sStatusIconsSpriteSheet.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/pokemon_summary_screen.c */
    sStatusIconsSpritePalette.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/pokenav_main_menu.c */
    sMenuLeftHeaderSpriteSheet.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/pokenav_main_menu.c */
    sMenuLeftHeaderSpriteSheets[0].data = NULL;
    sMenuLeftHeaderSpriteSheets[1].data = NULL;
    sMenuLeftHeaderSpriteSheets[2].data = NULL;
    sMenuLeftHeaderSpriteSheets[3].data = NULL;
    sMenuLeftHeaderSpriteSheets[4].data = NULL;
    sMenuLeftHeaderSpriteSheets[5].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/pokenav_main_menu.c */
    sPokenavSubMenuLeftHeaderSpriteSheets[0].data = NULL;
    sPokenavSubMenuLeftHeaderSpriteSheets[1].data = NULL;
    sPokenavSubMenuLeftHeaderSpriteSheets[2].data = NULL;
    sPokenavSubMenuLeftHeaderSpriteSheets[3].data = NULL;
    sPokenavSubMenuLeftHeaderSpriteSheets[4].data = NULL;
    sPokenavSubMenuLeftHeaderSpriteSheets[5].data = NULL;
    sPokenavSubMenuLeftHeaderSpriteSheets[6].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/pokenav_menu_handler_gfx.c */
    sPokenavOptionsSpriteSheets[0].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/pokenav_menu_handler_gfx.c */
    sPokenavOptionsSpritePalettes[0].data = NULL;
    sPokenavOptionsSpritePalettes[1].data = NULL;
    sPokenavOptionsSpritePalettes[2].data = NULL;
    sPokenavOptionsSpritePalettes[3].data = NULL;
    sPokenavOptionsSpritePalettes[4].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/pokenav_region_map.c */
    sCityZoomTextSpriteSheet[0].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/pokenav_region_map.c */
    sCityZoomTilesSpritePalette[0].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/roulette.c */
    sSpriteSheet_Headers.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/roulette.c */
    sRouletteInterfaceSpriteSheets[0].data = NULL;
    sRouletteInterfaceSpriteSheets[1].data = NULL;
    sRouletteInterfaceSpriteSheets[2].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/roulette.c */
    sSpriteSheet_WheelCenter.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/title_screen.c */
    sSpriteSheet_EmeraldVersion[0].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/title_screen.c */
    sSpriteSheet_PressStart[0].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/title_screen.c */
    sSpritePalette_PressStart[0].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/trainer_card.c */
    sHoennTrainerCardPals[0] = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/trainer_card.c */
    sKantoTrainerCardPals[0] = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/union_room_chat.c */
    sUnionRoomChatSpriteSheets[4].data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/use_pokeblock.c */
    sSpriteSheet_UpDown.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/use_pokeblock.c */
    sSpritePalette_UpDown.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/use_pokeblock.c */
    sSpritePalette_Condition.data = NULL;
    /* /home/tristen/work/pokeemerald-recomp/src/wallclock.c */
    sSpritePalettes_Clock[0].data = NULL;
    sSpritePalettes_Clock[1].data = NULL;
}

#endif
