/* Generated by tools/gen3_resources/gameplay_family/gen_gameplay_family.py.
 * Do not edit by hand; re-run the generator and --check it.
 */
#include "emerald/resources/frontier_aux_native.generated.h"

const char *const kFrontierAuxFactoryMoves[7] =
{
    "emerald:data/frontier/factory/moves/total-preparation",
    "emerald:data/frontier/factory/moves/impossible-to-predict",
    "emerald:data/frontier/factory/moves/weakening-the-foe",
    "emerald:data/frontier/factory/moves/high-risk-high-return",
    "emerald:data/frontier/factory/moves/endurance",
    "emerald:data/frontier/factory/moves/slow-and-steady",
    "emerald:data/frontier/factory/moves/depends-on-the-battles-flow",
};
const char *const kFrontierAuxPalaceEarlyKey = "emerald:data/frontier/palace/prizes/early";
const char *const kFrontierAuxPalaceLateKey = "emerald:data/frontier/palace/prizes/late";
const char *const kFrontierAuxArenaShortKey = "emerald:data/frontier/arena/prizes/short";
const char *const kFrontierAuxArenaLongKey = "emerald:data/frontier/arena/prizes/long";
const char *const kFrontierAuxPikeNpcKey = "emerald:data/frontier/pike/npc";
const char *const kFrontierAuxPikeSpeeches[3] =
{
    "emerald:data/frontier/pike/speeches",
    "emerald:data/frontier/pike/room-hints",
    "emerald:data/frontier/pike/heals",
};
const char *const kFrontierAuxPikeWildMons[8] =
{
    "emerald:data/frontier/pike/wild-mons/lvl50/1",
    "emerald:data/frontier/pike/wild-mons/lvl50/2",
    "emerald:data/frontier/pike/wild-mons/lvl50/3",
    "emerald:data/frontier/pike/wild-mons/lvl50/4",
    "emerald:data/frontier/pike/wild-mons/lvlopen/1",
    "emerald:data/frontier/pike/wild-mons/lvlopen/2",
    "emerald:data/frontier/pike/wild-mons/lvlopen/3",
    "emerald:data/frontier/pike/wild-mons/lvlopen/4",
};
const char *const kFrontierAuxPyramidFloor[2] =
{
    "emerald:data/frontier/pyramid/floor-templates",
    "emerald:data/frontier/pyramid/floor-options",
};
const char *const kFrontierAuxPyramidItemKey = "emerald:data/frontier/pyramid/items/lvl50";
const char *const kFrontierAuxPyramidSlotsKey = "emerald:data/frontier/pyramid/item-slots";
const char *const kFrontierAuxBrainIdsKey = "emerald:data/frontier/brain/ids";
const char *const kFrontierAuxBrainMonsKey = "emerald:data/frontier/brain/mons";
const char *const kFrontierAuxBrainStreakKey = "emerald:data/frontier/brain/streak-appearances";
const char *const kFrontierAuxApprenticeKeys[16] =
{
    "emerald:data/frontier/apprentice/0",
    "emerald:data/frontier/apprentice/1",
    "emerald:data/frontier/apprentice/2",
    "emerald:data/frontier/apprentice/3",
    "emerald:data/frontier/apprentice/4",
    "emerald:data/frontier/apprentice/5",
    "emerald:data/frontier/apprentice/6",
    "emerald:data/frontier/apprentice/7",
    "emerald:data/frontier/apprentice/8",
    "emerald:data/frontier/apprentice/9",
    "emerald:data/frontier/apprentice/10",
    "emerald:data/frontier/apprentice/11",
    "emerald:data/frontier/apprentice/12",
    "emerald:data/frontier/apprentice/13",
    "emerald:data/frontier/apprentice/14",
    "emerald:data/frontier/apprentice/15",
};
const char *const kFrontierAuxPikeWildHeadersKey = "emerald:data/frontier/pike/wild/headers";
const char *const kFrontierAuxPyramidWildHeadersKey = "emerald:data/frontier/pyramid/wild/headers";

const struct FrontierWildInfoMeta kFrontierAuxPikeWildInfos[4] =
{
    {"emerald:data/frontier/pike/wild/pike-1", 10u, 12u, 0x08553964u, 0x08553934u},
    {"emerald:data/frontier/pike/wild/pike-2", 10u, 12u, 0x0855399cu, 0x0855396cu},
    {"emerald:data/frontier/pike/wild/pike-3", 10u, 12u, 0x085539d4u, 0x085539a4u},
    {"emerald:data/frontier/pike/wild/pike-4", 10u, 12u, 0x08553a0cu, 0x085539dcu},
};

const struct FrontierWildInfoMeta kFrontierAuxPyramidWildInfos[7] =
{
    {"emerald:data/frontier/pyramid/wild/pyramid-round-1", 4u, 12u, 0x0855373cu, 0x0855370cu},
    {"emerald:data/frontier/pyramid/wild/pyramid-round-2", 4u, 12u, 0x08553774u, 0x08553744u},
    {"emerald:data/frontier/pyramid/wild/pyramid-round-3", 4u, 12u, 0x085537acu, 0x0855377cu},
    {"emerald:data/frontier/pyramid/wild/pyramid-round-4", 4u, 12u, 0x085537e4u, 0x085537b4u},
    {"emerald:data/frontier/pyramid/wild/pyramid-round-5", 4u, 12u, 0x0855381cu, 0x085537ecu},
    {"emerald:data/frontier/pyramid/wild/pyramid-round-6", 4u, 12u, 0x08553854u, 0x08553824u},
    {"emerald:data/frontier/pyramid/wild/pyramid-round-7", 8u, 12u, 0x0855388cu, 0x0855385cu},
};

