/* Generated by tools/gen3_resources/text_family/gen_text_family.py.
 * Do not edit by hand; re-run the generator and --check it.
 */
#include "emerald/resources/text_skeleton_arrays.generated.h"
#include "easy_chat.h"
#include "frontier_pass.h"
#include "list_menu.h"
#include "match_call.h"
#include "menu.h"
#include "naming_screen.h"
#include "pokedex.h"
#include "pokemon_storage_system.h"
#include "pokenav.h"
#include "union_room_chat.h"
extern void BagAction_Cancel(u8);
extern void BagAction_Give(u8);
extern void BagAction_Toss(u8);
extern void BagAction_UseInBattle(u8);
extern void BagAction_UseOnField(u8);
extern void DecorationMenuAction_Cancel(u8);
extern void DecorationMenuAction_Decorate(u8);
extern void DecorationMenuAction_PutAway(u8);
extern void DecorationMenuAction_Toss(u8);
extern void ItemMenu_Cancel(u8);
extern void ItemMenu_CheckTag(u8);
extern void ItemMenu_ConfirmQuizLady(u8);
extern void ItemMenu_Give(u8);
extern void ItemMenu_GiveFavorLady(u8);
extern void ItemMenu_Register(u8);
extern void ItemMenu_Show(u8);
extern void ItemMenu_Toss(u8);
extern void ItemMenu_UseInBattle(u8);
extern void ItemMenu_UseOutOfBattle(u8);
extern void ItemStorage_Deposit(u8);
extern void ItemStorage_Exit(u8);
extern void ItemStorage_Toss(u8);
extern void ItemStorage_Withdraw(u8);
extern void Mailbox_Cancel(u8);
extern void Mailbox_DoMailRead(u8);
extern void Mailbox_Give(u8);
extern void Mailbox_MoveToBag(u8);
extern void PlayerPC_Decoration(u8);
extern void PlayerPC_ItemStorage(u8);
extern void PlayerPC_Mailbox(u8);
extern void PlayerPC_TurnOff(u8);
extern void PokeblockAction_Cancel(u8);
extern void PokeblockAction_GiveToContestLady(u8);
extern void PokeblockAction_Toss(u8);
extern void PokeblockAction_UseInBattle(u8);
extern void PokeblockAction_UseOnField(u8);
extern void PokeblockAction_UseOnPokeblockFeeder(u8);
extern void ReturnToMainRegistryMenu(u8);
extern void ShowRegistryMenuDeleteConfirmation(u8);
extern void StartMenuBagCallback(u8);
extern void StartMenuBattlePyramidBagCallback(u8);
extern void StartMenuBattlePyramidRetireCallback(u8);
extern void StartMenuExitCallback(u8);
extern void StartMenuLinkModePlayerNameCallback(u8);
extern void StartMenuOptionCallback(u8);
extern void StartMenuPlayerNameCallback(u8);
extern void StartMenuPokeNavCallback(u8);
extern void StartMenuPokedexCallback(u8);
extern void StartMenuPokemonCallback(u8);
extern void StartMenuSafariZoneRetireCallback(u8);
extern void StartMenuSaveCallback(u8);
extern void Task_FadeAndCloseBagMenu(u8);
extern void Task_HandleShopMenuBuy(u8);
extern void Task_HandleShopMenuQuit(u8);
extern void Task_HandleShopMenuSell(u8);
extern const u8 gStatusConditionString_BurnJpn[];
extern const u8 gStatusConditionString_ConfusionJpn[];
extern const u8 gStatusConditionString_IceJpn[];
extern const u8 gStatusConditionString_LoveJpn[];
extern const u8 gStatusConditionString_ParalysisJpn[];
extern const u8 gStatusConditionString_PoisonJpn[];
extern const u8 gStatusConditionString_SleepJpn[];
extern const u8 gText_DisplaySettings[];
extern const u8 gTypeNames[NUMBER_OF_MON_TYPES][TYPE_NAME_LENGTH + 1];
extern const struct MatchCallLocationOverride sWallyLocationData[];
extern const u8 sText_CommunicationStandby[];
extern const u8 sText_OnlyPkmnForBattle[];
extern const u8 sText_TheTradeHasBeenCanceled[];
extern const u8 sText_WaitingForYourFriend[];
extern const u8 sText_YourFriendWantsToTrade[];
extern const u8 sText_Exit[];
extern const u8 sText_Info[];

HOST_DATA const u8 *sMessages_berry_crush[9] = { NULL };
HOST_DATA const u8 *sRecordsTexts_dodrio_berry_picking[3] = { NULL };
HOST_DATA const u8 *sDeptStoreFloorNames[16] = { NULL };
HOST_DATA const u8 *sBattleFrontier_TutorMoveDescriptions1[11] = { NULL };
HOST_DATA const u8 *sBattleFrontier_TutorMoveDescriptions2[11] = { NULL };
HOST_DATA const u8 *sMalePresetNames[20] = { NULL };
HOST_DATA const u8 *sFemalePresetNames[20] = { NULL };
HOST_DATA const u8 *sRecordsTexts_pokemon_jump[3] = { NULL };
HOST_DATA struct StorageMessage sMessages_pokemon_storage_system[31] =
{
{ .text = NULL, .format = 0x00 },
{ .text = NULL, .format = 0x00 },
{ .text = NULL, .format = 0x00 },
{ .text = NULL, .format = 0x00 },
{ .text = NULL, .format = 0x01 },
{ .text = NULL, .format = 0x00 },
{ .text = NULL, .format = 0x00 },
{ .text = NULL, .format = 0x01 },
{ .text = NULL, .format = 0x00 },
{ .text = NULL, .format = 0x00 },
{ .text = NULL, .format = 0x08 },
{ .text = NULL, .format = 0x0c },
{ .text = NULL, .format = 0x00 },
{ .text = NULL, .format = 0x00 },
{ .text = NULL, .format = 0x00 },
{ .text = NULL, .format = 0x00 },
{ .text = NULL, .format = 0x00 },
{ .text = NULL, .format = 0x00 },
{ .text = NULL, .format = 0x00 },
{ .text = NULL, .format = 0x01 },
{ .text = NULL, .format = 0x00 },
{ .text = NULL, .format = 0x00 },
{ .text = NULL, .format = 0x00 },
{ .text = NULL, .format = 0x0d },
{ .text = NULL, .format = 0x00 },
{ .text = NULL, .format = 0x0d },
{ .text = NULL, .format = 0x00 },
{ .text = NULL, .format = 0x00 },
{ .text = NULL, .format = 0x0d },
{ .text = NULL, .format = 0x0d },
{ .text = NULL, .format = 0x00 },
};
HOST_DATA const u8 *sModeStrings[4] = { NULL };
HOST_DATA const u8 *sFrontierExchangeCorner_Decor1Descriptions[11] = { NULL };
HOST_DATA const u8 *sFrontierExchangeCorner_Decor2Descriptions[6] = { NULL };
HOST_DATA const u8 *sFrontierExchangeCorner_VitaminsDescriptions[7] = { NULL };
HOST_DATA const u8 *sFrontierExchangeCorner_HoldItemsDescriptions[10] = { NULL };
HOST_DATA const u8 *gStatusConditionStringsTable[7][2] = { NULL };
HOST_DATA const u8 *gStatNamesTable[8] = { NULL };
HOST_DATA const u8 *gPokeblockWasTooXStringTable[5] = { NULL };
HOST_DATA const u8 *gBattleStringsTable[369] = { NULL };
HOST_DATA const u8 *sStatNamesTable2[6] = { NULL };
HOST_DATA const u8 *gRoundsStringTable[4] = { NULL };
HOST_DATA const u8 *gRefereeStringsTable[9] = { NULL };
HOST_DATA struct MenuAction sMenuActions[6] =
{
{ .text = NULL, .func = { .void_u8 = &BagAction_UseOnField } },
{ .text = NULL, .func = { .void_u8 = &BagAction_Toss } },
{ .text = NULL, .func = { .void_u8 = &BagAction_Give } },
{ .text = NULL, .func = { .void_u8 = &BagAction_Cancel } },
{ .text = NULL, .func = { .void_u8 = &BagAction_UseInBattle } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA const u8 *sResultsTexts[6] = { NULL };
HOST_DATA const u8 *sBerryFirmnessStrings[5] = { NULL };
HOST_DATA const u8 *sTrainerCardColorNames[4] = { NULL };
HOST_DATA const u8 *sContestCategoryNames_Unused[5] = { NULL };
HOST_DATA const u8 *sContestRankNames[5] = { NULL };
HOST_DATA const u8 *sMuseumCaptions[15] = { NULL };
HOST_DATA struct ListMenuItem sLevelMenuItems[3] =
{
{ .name = NULL, .id = 0 },
{ .name = NULL, .id = 1 },
{ .name = NULL, .id = 5 },
};
HOST_DATA const u8 *sCompatibilityMessages[4] = { NULL };
HOST_DATA const u8 *sDecorationCategoryNames[8] = { NULL };
HOST_DATA struct MenuAction sDecorationMainMenuActions[4] =
{
{ .text = NULL, .func = { .void_u8 = &DecorationMenuAction_Decorate } },
{ .text = NULL, .func = { .void_u8 = &DecorationMenuAction_PutAway } },
{ .text = NULL, .func = { .void_u8 = &DecorationMenuAction_Toss } },
{ .text = NULL, .func = { .void_u8 = &DecorationMenuAction_Cancel } },
};
HOST_DATA const u8 *sSecretBasePCMenuItemDescriptions[4] = { NULL };
HOST_DATA const u8 *sRankingTexts[5] = { NULL };
HOST_DATA struct EasyChatScreenTemplate sEasyChatScreenTemplates[21] =
{
{ .type = 0x00, .numColumns = 0x02, .numRows = 0x02, .frameId = 0x00, .fourFooterOptions = 0x00, .titleText = NULL, .instructionsText1 = NULL, .instructionsText2 = NULL, .confirmText1 = NULL, .confirmText2 = NULL },
{ .type = 0x01, .numColumns = 0x02, .numRows = 0x03, .frameId = 0x01, .fourFooterOptions = 0x00, .titleText = NULL, .instructionsText1 = NULL, .instructionsText2 = NULL, .confirmText1 = NULL, .confirmText2 = NULL },
{ .type = 0x02, .numColumns = 0x02, .numRows = 0x03, .frameId = 0x01, .fourFooterOptions = 0x00, .titleText = NULL, .instructionsText1 = NULL, .instructionsText2 = NULL, .confirmText1 = NULL, .confirmText2 = NULL },
{ .type = 0x03, .numColumns = 0x02, .numRows = 0x03, .frameId = 0x01, .fourFooterOptions = 0x00, .titleText = NULL, .instructionsText1 = NULL, .instructionsText2 = NULL, .confirmText1 = NULL, .confirmText2 = NULL },
{ .type = 0x04, .numColumns = 0x02, .numRows = 0x05, .frameId = 0x02, .fourFooterOptions = 0x00, .titleText = NULL, .instructionsText1 = NULL, .instructionsText2 = NULL, .confirmText1 = NULL, .confirmText2 = NULL },
{ .type = 0x05, .numColumns = 0x02, .numRows = 0x02, .frameId = 0x05, .fourFooterOptions = 0x00, .titleText = NULL, .instructionsText1 = NULL, .instructionsText2 = NULL, .confirmText1 = NULL, .confirmText2 = NULL },
{ .type = 0x06, .numColumns = 0x02, .numRows = 0x03, .frameId = 0x01, .fourFooterOptions = 0x00, .titleText = NULL, .instructionsText1 = NULL, .instructionsText2 = NULL, .confirmText1 = NULL, .confirmText2 = NULL },
{ .type = 0x07, .numColumns = 0x01, .numRows = 0x01, .frameId = 0x04, .fourFooterOptions = 0x00, .titleText = NULL, .instructionsText1 = NULL, .instructionsText2 = NULL, .confirmText1 = NULL, .confirmText2 = NULL },
{ .type = 0x09, .numColumns = 0x02, .numRows = 0x01, .frameId = 0x03, .fourFooterOptions = 0x00, .titleText = NULL, .instructionsText1 = NULL, .instructionsText2 = NULL, .confirmText1 = NULL, .confirmText2 = NULL },
{ .type = 0x10, .numColumns = 0x02, .numRows = 0x05, .frameId = 0x07, .fourFooterOptions = 0x01, .titleText = NULL, .instructionsText1 = NULL, .instructionsText2 = NULL, .confirmText1 = NULL, .confirmText2 = NULL },
{ .type = 0x0f, .numColumns = 0x01, .numRows = 0x01, .frameId = 0x06, .fourFooterOptions = 0x01, .titleText = NULL, .instructionsText1 = NULL, .instructionsText2 = NULL, .confirmText1 = NULL, .confirmText2 = NULL },
{ .type = 0x11, .numColumns = 0x02, .numRows = 0x05, .frameId = 0x08, .fourFooterOptions = 0x01, .titleText = NULL, .instructionsText1 = NULL, .instructionsText2 = NULL, .confirmText1 = NULL, .confirmText2 = NULL },
{ .type = 0x12, .numColumns = 0x01, .numRows = 0x01, .frameId = 0x06, .fourFooterOptions = 0x01, .titleText = NULL, .instructionsText1 = NULL, .instructionsText2 = NULL, .confirmText1 = NULL, .confirmText2 = NULL },
{ .type = 0x06, .numColumns = 0x02, .numRows = 0x03, .frameId = 0x01, .fourFooterOptions = 0x00, .titleText = NULL, .instructionsText1 = NULL, .instructionsText2 = NULL, .confirmText1 = NULL, .confirmText2 = NULL },
{ .type = 0x13, .numColumns = 0x02, .numRows = 0x03, .frameId = 0x01, .fourFooterOptions = 0x00, .titleText = NULL, .instructionsText1 = NULL, .instructionsText2 = NULL, .confirmText1 = NULL, .confirmText2 = NULL },
{ .type = 0x0d, .numColumns = 0x02, .numRows = 0x01, .frameId = 0x03, .fourFooterOptions = 0x00, .titleText = NULL, .instructionsText1 = NULL, .instructionsText2 = NULL, .confirmText1 = NULL, .confirmText2 = NULL },
{ .type = 0x0a, .numColumns = 0x01, .numRows = 0x01, .frameId = 0x04, .fourFooterOptions = 0x00, .titleText = NULL, .instructionsText1 = NULL, .instructionsText2 = NULL, .confirmText1 = NULL, .confirmText2 = NULL },
{ .type = 0x0c, .numColumns = 0x01, .numRows = 0x01, .frameId = 0x04, .fourFooterOptions = 0x00, .titleText = NULL, .instructionsText1 = NULL, .instructionsText2 = NULL, .confirmText1 = NULL, .confirmText2 = NULL },
{ .type = 0x0b, .numColumns = 0x01, .numRows = 0x01, .frameId = 0x04, .fourFooterOptions = 0x00, .titleText = NULL, .instructionsText1 = NULL, .instructionsText2 = NULL, .confirmText1 = NULL, .confirmText2 = NULL },
{ .type = 0x0e, .numColumns = 0x01, .numRows = 0x01, .frameId = 0x04, .fourFooterOptions = 0x00, .titleText = NULL, .instructionsText1 = NULL, .instructionsText2 = NULL, .confirmText1 = NULL, .confirmText2 = NULL },
{ .type = 0x14, .numColumns = 0x02, .numRows = 0x02, .frameId = 0x00, .fourFooterOptions = 0x00, .titleText = NULL, .instructionsText1 = NULL, .instructionsText2 = NULL, .confirmText1 = NULL, .confirmText2 = NULL },
};
HOST_DATA const u8 *sFooterTextOptions[3][4] = { NULL };
HOST_DATA const u8 *sEasyChatGroupNamePointers[22] = { NULL };
HOST_DATA const u8 *sScrollableMultichoiceOptions[13][16] = { NULL };
HOST_DATA const u8 *sPassAreaDescriptions[15] = { NULL };
HOST_DATA struct MapLandmark sMapLandmarks[7] =
{
{ .name = NULL, .description = NULL, .x = 89, .y = 40, .animNum = 0x01 },
{ .name = NULL, .description = NULL, .x = 33, .y = 42, .animNum = 0x01 },
{ .name = NULL, .description = NULL, .x = 120, .y = 86, .animNum = 0x00 },
{ .name = NULL, .description = NULL, .x = 114, .y = 59, .animNum = 0x00 },
{ .name = NULL, .description = NULL, .x = 25, .y = 67, .animNum = 0x00 },
{ .name = NULL, .description = NULL, .x = 57, .y = 57, .animNum = 0x01 },
{ .name = NULL, .description = NULL, .x = 134, .y = 41, .animNum = 0x01 },
};
HOST_DATA const u8 *sRecordsWindowChallengeTexts[10][2] = { NULL };
HOST_DATA const u8 *sLevelModeText[2] = { NULL };
HOST_DATA const u8 *sHallFacilityToRecordsText[10] = { NULL };
HOST_DATA struct MenuAction sItemMenuActions[15] =
{
{ .text = NULL, .func = { .void_u8 = &ItemMenu_UseOutOfBattle } },
{ .text = NULL, .func = { .void_u8 = &ItemMenu_Toss } },
{ .text = NULL, .func = { .void_u8 = &ItemMenu_Register } },
{ .text = NULL, .func = { .void_u8 = &ItemMenu_Give } },
{ .text = NULL, .func = { .void_u8 = &ItemMenu_Cancel } },
{ .text = NULL, .func = { .void_u8 = &ItemMenu_UseInBattle } },
{ .text = NULL, .func = { .void_u8 = &ItemMenu_UseOutOfBattle } },
{ .text = NULL, .func = { .void_u8 = &ItemMenu_UseOutOfBattle } },
{ .text = NULL, .func = { .void_u8 = &ItemMenu_Register } },
{ .text = NULL, .func = { .void_u8 = &ItemMenu_CheckTag } },
{ .text = NULL, .func = { .void_u8 = &Task_FadeAndCloseBagMenu } },
{ .text = NULL, .func = { .void_u8 = &ItemMenu_Show } },
{ .text = NULL, .func = { .void_u8 = &ItemMenu_GiveFavorLady } },
{ .text = NULL, .func = { .void_u8 = &ItemMenu_ConfirmQuizLady } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction sMenuActions_Gender[2] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MatchCallText sMatchCallWildBattleTexts[15] =
{
{ .text = NULL, .stringVarFuncIds = { 0, 2, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 2, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 2, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 2, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 2, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 2, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 2, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 2, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 2, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 2, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 2, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 2, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 2, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 2, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 2, -1 } },
};
HOST_DATA struct MatchCallText sMatchCallNegativeBattleTexts[14] =
{
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
};
HOST_DATA struct MatchCallText sMatchCallPositiveBattleTexts[14] =
{
{ .text = NULL, .stringVarFuncIds = { 0, 3, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 3, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 3, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 3, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 3, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 3, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 3, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 3, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 3, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 3, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 3, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 3, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 3, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 3, -1 } },
};
HOST_DATA struct MatchCallText sMatchCallSameRouteBattleRequestTexts[14] =
{
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
};
HOST_DATA struct MatchCallText sMatchCallDifferentRouteBattleRequestTexts[14] =
{
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
};
HOST_DATA struct MatchCallText sMatchCallPersonalizedTexts[64] =
{
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 2, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 3, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 3, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 3, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 3, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 3, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 3, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, 1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
{ .text = NULL, .stringVarFuncIds = { 0, -1, -1 } },
};
HOST_DATA struct MatchCallText sMatchCallBattleFrontierStreakTexts[14] =
{
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
};
HOST_DATA struct MatchCallText sMatchCallBattleFrontierRecordStreakTexts[14] =
{
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
};
HOST_DATA struct MatchCallText sMatchCallBattleDomeTexts[14] =
{
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
};
HOST_DATA struct MatchCallText sMatchCallBattlePikeTexts[14] =
{
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
};
HOST_DATA struct MatchCallText sMatchCallBattlePyramidTexts[14] =
{
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
{ .text = NULL, .stringVarFuncIds = { 0, 4, 5 } },
};
HOST_DATA struct MultiTrainerMatchCallText sMultiTrainerMatchCallTexts[6] =
{
{ .trainerId = 0x0282, .text = NULL },
{ .trainerId = 0x01e1, .text = NULL },
{ .trainerId = 0x02a9, .text = NULL },
{ .trainerId = 0x02af, .text = NULL },
{ .trainerId = 0x0033, .text = NULL },
{ .trainerId = 0x011f, .text = NULL },
};
HOST_DATA const u8 *sBattleFrontierFacilityNames[7] = { NULL };
HOST_DATA const u8 *sLvlUpStatStrings[6] = { NULL };
HOST_DATA struct ListMenuItem sListMenuItems_CardsOrNews[3] =
{
{ .name = NULL, .id = 0 },
{ .name = NULL, .id = 1 },
{ .name = NULL, .id = -2 },
};
HOST_DATA struct ListMenuItem sListMenuItems_WirelessOrFriend[3] =
{
{ .name = NULL, .id = 0 },
{ .name = NULL, .id = 1 },
{ .name = NULL, .id = -2 },
};
HOST_DATA struct ListMenuItem sListMenuItems_ReceiveSendToss[4] =
{
{ .name = NULL, .id = 0 },
{ .name = NULL, .id = 1 },
{ .name = NULL, .id = 2 },
{ .name = NULL, .id = -2 },
};
HOST_DATA struct ListMenuItem sListMenuItems_ReceiveToss[3] =
{
{ .name = NULL, .id = 0 },
{ .name = NULL, .id = 2 },
{ .name = NULL, .id = -2 },
};
HOST_DATA struct ListMenuItem sListMenuItems_ReceiveSend[3] =
{
{ .name = NULL, .id = 0 },
{ .name = NULL, .id = 1 },
{ .name = NULL, .id = -2 },
};
HOST_DATA struct ListMenuItem sListMenuItems_Receive[2] =
{
{ .name = NULL, .id = 0 },
{ .name = NULL, .id = -2 },
};
HOST_DATA const u8 *sUnusedMenuTexts[4] = { NULL };
HOST_DATA const u8 *sTransferredToPCMessages[4] = { NULL };
HOST_DATA struct NamingScreenTemplate sPlayerNamingScreenTemplate =
{
.copyExistingString = 0x00, .maxChars = 0x07, .iconFunction = 0x01, .addGenderIcon = 0x00, .initialPage = 0x01, .unused = 0x23, .title = NULL
};
HOST_DATA struct NamingScreenTemplate sPCBoxNamingTemplate =
{
.copyExistingString = 0x00, .maxChars = 0x08, .iconFunction = 0x02, .addGenderIcon = 0x00, .initialPage = 0x01, .unused = 0x13, .title = NULL
};
HOST_DATA struct NamingScreenTemplate sMonNamingScreenTemplate =
{
.copyExistingString = 0x00, .maxChars = 0x0a, .iconFunction = 0x03, .addGenderIcon = 0x01, .initialPage = 0x01, .unused = 0x23, .title = NULL
};
HOST_DATA struct NamingScreenTemplate sWaldaWordsScreenTemplate =
{
.copyExistingString = 0x01, .maxChars = 0x0f, .iconFunction = 0x04, .addGenderIcon = 0x00, .initialPage = 0x01, .unused = 0x0b, .title = NULL
};
HOST_DATA const u8 *sOptionMenuItemsNames[8] = { NULL };
HOST_DATA const u8 *sItemStorage_OptionDescriptions[4] = { NULL };
HOST_DATA struct MenuAction sPlayerPCMenuActions[4] =
{
{ .text = NULL, .func = { .void_u8 = &PlayerPC_ItemStorage } },
{ .text = NULL, .func = { .void_u8 = &PlayerPC_Mailbox } },
{ .text = NULL, .func = { .void_u8 = &PlayerPC_Decoration } },
{ .text = NULL, .func = { .void_u8 = &PlayerPC_TurnOff } },
};
HOST_DATA struct MenuAction sItemStorage_MenuActions[4] =
{
{ .text = NULL, .func = { .void_u8 = &ItemStorage_Withdraw } },
{ .text = NULL, .func = { .void_u8 = &ItemStorage_Deposit } },
{ .text = NULL, .func = { .void_u8 = &ItemStorage_Toss } },
{ .text = NULL, .func = { .void_u8 = &ItemStorage_Exit } },
};
HOST_DATA struct MenuAction gMailboxMailOptions[4] =
{
{ .text = NULL, .func = { .void_u8 = &Mailbox_DoMailRead } },
{ .text = NULL, .func = { .void_u8 = &Mailbox_MoveToBag } },
{ .text = NULL, .func = { .void_u8 = &Mailbox_Give } },
{ .text = NULL, .func = { .void_u8 = &Mailbox_Cancel } },
};
HOST_DATA const u8 *gPokeblockNames[15] = { NULL };
HOST_DATA struct MenuAction sPokeblockMenuActions[6] =
{
{ .text = NULL, .func = { .void_u8 = &PokeblockAction_UseOnField } },
{ .text = NULL, .func = { .void_u8 = &PokeblockAction_Toss } },
{ .text = NULL, .func = { .void_u8 = &PokeblockAction_Cancel } },
{ .text = NULL, .func = { .void_u8 = &PokeblockAction_UseInBattle } },
{ .text = NULL, .func = { .void_u8 = &PokeblockAction_UseOnPokeblockFeeder } },
{ .text = NULL, .func = { .void_u8 = &PokeblockAction_GiveToContestLady } },
};
HOST_DATA struct SearchMenuTopBarItem sSearchMenuTopBarItems[3] =
{
{ .description = NULL, .highlightX = 0x00, .highlightY = 0x00, .highlightWidth = 0x05 },
{ .description = NULL, .highlightX = 0x06, .highlightY = 0x00, .highlightWidth = 0x05 },
{ .description = NULL, .highlightX = 0x0c, .highlightY = 0x00, .highlightWidth = 0x05 },
};
HOST_DATA struct SearchMenuItem sSearchMenuItems[7] =
{
{ .description = NULL, .titleBgX = 0x00, .titleBgY = 0x02, .titleBgWidth = 0x05, .selectionBgX = 0x05, .selectionBgY = 0x02, .selectionBgWidth = 0x0c },
{ .description = NULL, .titleBgX = 0x00, .titleBgY = 0x04, .titleBgWidth = 0x05, .selectionBgX = 0x05, .selectionBgY = 0x04, .selectionBgWidth = 0x0c },
{ .description = NULL, .titleBgX = 0x00, .titleBgY = 0x06, .titleBgWidth = 0x05, .selectionBgX = 0x05, .selectionBgY = 0x06, .selectionBgWidth = 0x06 },
{ .description = NULL, .titleBgX = 0x00, .titleBgY = 0x06, .titleBgWidth = 0x05, .selectionBgX = 0x0b, .selectionBgY = 0x06, .selectionBgWidth = 0x06 },
{ .description = NULL, .titleBgX = 0x00, .titleBgY = 0x08, .titleBgWidth = 0x05, .selectionBgX = 0x05, .selectionBgY = 0x08, .selectionBgWidth = 0x0c },
{ .description = NULL, .titleBgX = 0x00, .titleBgY = 0x0a, .titleBgWidth = 0x05, .selectionBgX = 0x05, .selectionBgY = 0x0a, .selectionBgWidth = 0x0c },
{ .description = NULL, .titleBgX = 0x00, .titleBgY = 0x0c, .titleBgWidth = 0x05, .selectionBgX = 0x00, .selectionBgY = 0x00, .selectionBgWidth = 0x00 },
};
HOST_DATA struct SearchOptionText sDexModeOptions[3] =
{
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
};
HOST_DATA struct SearchOptionText sDexOrderOptions[7] =
{
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
};
HOST_DATA struct SearchOptionText sDexSearchNameOptions[11] =
{
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
};
HOST_DATA struct SearchOptionText sDexSearchColorOptions[12] =
{
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = NULL },
};
HOST_DATA struct SearchOptionText sDexSearchTypeOptions[19] =
{
{ .description = NULL, .title = NULL },
{ .description = NULL, .title = gTypeNames[0] },
{ .description = NULL, .title = gTypeNames[1] },
{ .description = NULL, .title = gTypeNames[2] },
{ .description = NULL, .title = gTypeNames[3] },
{ .description = NULL, .title = gTypeNames[4] },
{ .description = NULL, .title = gTypeNames[5] },
{ .description = NULL, .title = gTypeNames[6] },
{ .description = NULL, .title = gTypeNames[7] },
{ .description = NULL, .title = gTypeNames[8] },
{ .description = NULL, .title = gTypeNames[10] },
{ .description = NULL, .title = gTypeNames[11] },
{ .description = NULL, .title = gTypeNames[12] },
{ .description = NULL, .title = gTypeNames[13] },
{ .description = NULL, .title = gTypeNames[14] },
{ .description = NULL, .title = gTypeNames[15] },
{ .description = NULL, .title = gTypeNames[16] },
{ .description = NULL, .title = gTypeNames[17] },
{ .description = NULL, .title = NULL },
};
HOST_DATA struct MainMenuText sMainMenuTexts[5] =
{
{ .text = NULL, .desc = NULL },
{ .text = NULL, .desc = NULL },
{ .text = NULL, .desc = NULL },
{ .text = NULL, .desc = NULL },
{ .text = NULL, .desc = NULL },
};
HOST_DATA const u8 *sMenuTexts[39] = { NULL };
HOST_DATA const u8 *sHelpBarTexts[12] = { NULL };
HOST_DATA struct MatchCallCheckPageOverride sCheckPageOverrides[4] =
{
{ .idx = 0x0007, .facilityClass = 0x004b, .flag = 0x0000ffffu, .flavorTexts = { NULL, NULL, NULL, NULL } },
{ .idx = 0x0007, .facilityClass = 0x004b, .flag = 0x000004f6u, .flavorTexts = { NULL, NULL, NULL, NULL } },
{ .idx = 0x0002, .facilityClass = 0x003c, .flag = 0x0000ffffu, .flavorTexts = { NULL, NULL, NULL, NULL } },
{ .idx = 0x0003, .facilityClass = 0x003f, .flag = 0x0000ffffu, .flavorTexts = { NULL, NULL, NULL, NULL } },
};
HOST_DATA struct MatchCallStructNPC sMrStoneMatchCallHeader =
{
.type = 0x00, .mapSec = 0x0a, .flag = 0xffff, .desc = NULL, .name = NULL, .textData = NULL
};
HOST_DATA struct MatchCallStructTrainer sNormanMatchCallHeader =
{
.type = 0x05, .mapSec = 0x07, .flag = 0x0132, .rematchTableIdx = 0x0045, .desc = NULL, .name = NULL, .textData = NULL
};
HOST_DATA struct MatchCallBirch sProfBirchMatchCallHeader =
{
.type = 0x03, .mapSec = 0x00, .flag = 0x0119, .desc = NULL, .name = NULL
};
HOST_DATA struct MatchCallStructNPC sMomMatchCallHeader =
{
.type = 0x00, .mapSec = 0x00, .flag = 0x00d8, .desc = NULL, .name = NULL, .textData = NULL
};
HOST_DATA struct MatchCallStructNPC sStevenMatchCallHeader =
{
.type = 0x00, .mapSec = 0xd5, .flag = 0x0131, .desc = NULL, .name = NULL, .textData = NULL
};
HOST_DATA struct MatchCallRival sMayMatchCallHeader =
{
.type = 0x04, .playerGender = 0x00, .flag = 0x00fd, .desc = NULL, .name = NULL, .textData = NULL
};
HOST_DATA struct MatchCallRival sBrendanMatchCallHeader =
{
.type = 0x04, .playerGender = 0x01, .flag = 0x00fd, .desc = NULL, .name = NULL, .textData = NULL
};
HOST_DATA struct MatchCallWally sWallyMatchCallHeader =
{
.type = 0x02, .mapSec = 0x00, .flag = 0x00d6, .rematchTableIdx = 0x0040, .desc = NULL, .textData = NULL, .locationData = sWallyLocationData
};
HOST_DATA struct MatchCallStructNPC sScottMatchCallHeader =
{
.type = 0x00, .mapSec = 0xd5, .flag = 0x00d7, .desc = NULL, .name = NULL, .textData = NULL
};
HOST_DATA struct MatchCallStructTrainer sRoxanneMatchCallHeader =
{
.type = 0x05, .mapSec = 0x0a, .flag = 0x01d3, .rematchTableIdx = 0x0041, .desc = NULL, .name = NULL, .textData = NULL
};
HOST_DATA struct MatchCallStructTrainer sBrawlyMatchCallHeader =
{
.type = 0x05, .mapSec = 0x02, .flag = 0x01d4, .rematchTableIdx = 0x0042, .desc = NULL, .name = NULL, .textData = NULL
};
HOST_DATA struct MatchCallStructTrainer sWattsonMatchCallHeader =
{
.type = 0x05, .mapSec = 0x09, .flag = 0x01d5, .rematchTableIdx = 0x0043, .desc = NULL, .name = NULL, .textData = NULL
};
HOST_DATA struct MatchCallStructTrainer sFlanneryMatchCallHeader =
{
.type = 0x05, .mapSec = 0x03, .flag = 0x01d6, .rematchTableIdx = 0x0044, .desc = NULL, .name = NULL, .textData = NULL
};
HOST_DATA struct MatchCallStructTrainer sWinonaMatchCallHeader =
{
.type = 0x05, .mapSec = 0x0b, .flag = 0x01d7, .rematchTableIdx = 0x0046, .desc = NULL, .name = NULL, .textData = NULL
};
HOST_DATA struct MatchCallStructTrainer sTateLizaMatchCallHeader =
{
.type = 0x05, .mapSec = 0x0d, .flag = 0x01d8, .rematchTableIdx = 0x0047, .desc = NULL, .name = NULL, .textData = NULL
};
HOST_DATA struct MatchCallStructTrainer sJuanMatchCallHeader =
{
.type = 0x05, .mapSec = 0x0e, .flag = 0x01d9, .rematchTableIdx = 0x0048, .desc = NULL, .name = NULL, .textData = NULL
};
HOST_DATA struct MatchCallStructTrainer sSidneyMatchCallHeader =
{
.type = 0x05, .mapSec = 0x0f, .flag = 0x01a5, .rematchTableIdx = 0x0049, .desc = NULL, .name = NULL, .textData = NULL
};
HOST_DATA struct MatchCallStructTrainer sPhoebeMatchCallHeader =
{
.type = 0x05, .mapSec = 0x0f, .flag = 0x01a6, .rematchTableIdx = 0x004a, .desc = NULL, .name = NULL, .textData = NULL
};
HOST_DATA struct MatchCallStructTrainer sGlaciaMatchCallHeader =
{
.type = 0x05, .mapSec = 0x0f, .flag = 0x01a7, .rematchTableIdx = 0x004b, .desc = NULL, .name = NULL, .textData = NULL
};
HOST_DATA struct MatchCallStructTrainer sDrakeMatchCallHeader =
{
.type = 0x05, .mapSec = 0x0f, .flag = 0x01a8, .rematchTableIdx = 0x004c, .desc = NULL, .name = NULL, .textData = NULL
};
HOST_DATA struct MatchCallStructTrainer sWallaceMatchCallHeader =
{
.type = 0x05, .mapSec = 0x0f, .flag = 0x01a9, .rematchTableIdx = 0x004d, .desc = NULL, .name = NULL, .textData = NULL
};
HOST_DATA struct MatchCallTextDataStruct sMrStoneTextScripts[12] =
{
{ .text = NULL, .flag = 0xffff, .flag2 = 0x0158 },
{ .text = NULL, .flag = 0x0158, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x00bd, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0110, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x006a, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x04f4, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0097, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x006f, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0070, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x04f7, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0864, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
};
HOST_DATA struct MatchCallTextDataStruct sNormanTextScripts[10] =
{
{ .text = NULL, .flag = 0x0132, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x04f1, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x04f3, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x04f4, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x00d4, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xfffe, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0864, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0864, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0864, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
};
HOST_DATA struct MatchCallTextDataStruct sMomTextScripts[4] =
{
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x04f4, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0864, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
};
HOST_DATA struct MatchCallTextDataStruct sStevenTextScripts[8] =
{
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x00c7, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x00d4, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0070, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x04f6, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0081, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0864, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
};
HOST_DATA struct MatchCallTextDataStruct sMayTextScripts[16] =
{
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x04f1, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0095, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0324, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x006a, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x04f3, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x04f4, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0097, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x00d4, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x006f, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0061, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0070, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0081, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x04f7, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0864, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
};
HOST_DATA struct MatchCallTextDataStruct sBrendanTextScripts[16] =
{
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x04f1, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0095, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0324, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x006a, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x04f3, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x04f4, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0097, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x00d4, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x006f, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0061, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0070, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0081, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x04f7, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0864, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
};
HOST_DATA struct MatchCallTextDataStruct sWallyTextScripts[8] =
{
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x00c7, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x04f3, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0097, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x006f, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0081, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x007e, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
};
HOST_DATA struct MatchCallTextDataStruct sScottTextScripts[8] =
{
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x008b, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0097, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x00d4, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0070, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x04f7, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0864, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
};
HOST_DATA struct MatchCallTextDataStruct sRoxanneTextScripts[5] =
{
{ .text = NULL, .flag = 0xfffe, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0864, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
};
HOST_DATA struct MatchCallTextDataStruct sBrawlyTextScripts[5] =
{
{ .text = NULL, .flag = 0xfffe, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0864, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
};
HOST_DATA struct MatchCallTextDataStruct sWattsonTextScripts[5] =
{
{ .text = NULL, .flag = 0xfffe, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0864, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
};
HOST_DATA struct MatchCallTextDataStruct sFlanneryTextScripts[5] =
{
{ .text = NULL, .flag = 0xfffe, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0864, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
};
HOST_DATA struct MatchCallTextDataStruct sWinonaTextScripts[5] =
{
{ .text = NULL, .flag = 0xfffe, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0864, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
};
HOST_DATA struct MatchCallTextDataStruct sTateLizaTextScripts[5] =
{
{ .text = NULL, .flag = 0xfffe, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0864, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
};
HOST_DATA struct MatchCallTextDataStruct sJuanTextScripts[5] =
{
{ .text = NULL, .flag = 0xfffe, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
{ .text = NULL, .flag = 0x0864, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
};
HOST_DATA struct MatchCallTextDataStruct sSidneyTextScripts[2] =
{
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
};
HOST_DATA struct MatchCallTextDataStruct sPhoebeTextScripts[2] =
{
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
};
HOST_DATA struct MatchCallTextDataStruct sGlaciaTextScripts[2] =
{
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
};
HOST_DATA struct MatchCallTextDataStruct sDrakeTextScripts[2] =
{
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
};
HOST_DATA struct MatchCallTextDataStruct sWallaceTextScripts[2] =
{
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
{ .text = NULL, .flag = 0xffff, .flag2 = 0xffff },
};
HOST_DATA const u8 *sMatchCallOptionTexts[3] = { NULL };
HOST_DATA const u8 *sPageDescriptions[14] = { NULL };
HOST_DATA const u8 *sEverGrandeCityNames[2] = { NULL };
HOST_DATA struct MenuAction sRegistryMenuActions[2] =
{
{ .text = NULL, .func = { .void_u8 = &ShowRegistryMenuDeleteConfirmation } },
{ .text = NULL, .func = { .void_u8 = &ReturnToMainRegistryMenu } },
};
HOST_DATA struct MenuAction sShopMenuActions_BuySellQuit[3] =
{
{ .text = NULL, .func = { .void_u8 = &Task_HandleShopMenuBuy } },
{ .text = NULL, .func = { .void_u8 = &Task_HandleShopMenuSell } },
{ .text = NULL, .func = { .void_u8 = &Task_HandleShopMenuQuit } },
};
HOST_DATA struct MenuAction sShopMenuActions_BuyQuit[2] =
{
{ .text = NULL, .func = { .void_u8 = &Task_HandleShopMenuBuy } },
{ .text = NULL, .func = { .void_u8 = &Task_HandleShopMenuQuit } },
};
HOST_DATA const u8 *sPyramidFloorNames[8] = { NULL };
HOST_DATA struct MenuAction sStartMenuItems[13] =
{
{ .text = NULL, .func = { .void_u8 = &StartMenuPokedexCallback } },
{ .text = NULL, .func = { .void_u8 = &StartMenuPokemonCallback } },
{ .text = NULL, .func = { .void_u8 = &StartMenuBagCallback } },
{ .text = NULL, .func = { .void_u8 = &StartMenuPokeNavCallback } },
{ .text = NULL, .func = { .void_u8 = &StartMenuPlayerNameCallback } },
{ .text = NULL, .func = { .void_u8 = &StartMenuSaveCallback } },
{ .text = NULL, .func = { .void_u8 = &StartMenuOptionCallback } },
{ .text = NULL, .func = { .void_u8 = &StartMenuExitCallback } },
{ .text = NULL, .func = { .void_u8 = &StartMenuSafariZoneRetireCallback } },
{ .text = NULL, .func = { .void_u8 = &StartMenuLinkModePlayerNameCallback } },
{ .text = NULL, .func = { .void_u8 = &StartMenuSaveCallback } },
{ .text = NULL, .func = { .void_u8 = &StartMenuBattlePyramidRetireCallback } },
{ .text = NULL, .func = { .void_u8 = &StartMenuBattlePyramidBagCallback } },
};
HOST_DATA const u8 *gBagMenu_ReturnToStrings[12] = { NULL };
HOST_DATA const u8 *gPyramidBagMenu_ReturnToStrings[4] = { NULL };
HOST_DATA const u8 *gPocketNamesStringsTable[5] = { NULL };
HOST_DATA const u8 *gTextTable_Players[4] = { NULL };
HOST_DATA const u8 *sDefaultTraderNames[4] = { NULL };
HOST_DATA const u8 *sLinkBattleTexts[3] = { NULL };
HOST_DATA const u8 *sFloorStrings[4] = { NULL };
HOST_DATA struct MessageWindowInfo sDisplayStdMessages[11] =
{
{ .text = NULL, .boxType = 0x01, .x = 0x00, .y = 0x01, .letterSpacing = 0x00, .lineSpacing = 0x00, .hasPlaceholders = 0x00, .useWiderBox = 0x00 },
{ .text = NULL, .boxType = 0x01, .x = 0x00, .y = 0x01, .letterSpacing = 0x00, .lineSpacing = 0x00, .hasPlaceholders = 0x00, .useWiderBox = 0x00 },
{ .text = NULL, .boxType = 0x01, .x = 0x00, .y = 0x01, .letterSpacing = 0x00, .lineSpacing = 0x00, .hasPlaceholders = 0x00, .useWiderBox = 0x00 },
{ .text = NULL, .boxType = 0x01, .x = 0x00, .y = 0x01, .letterSpacing = 0x00, .lineSpacing = 0x00, .hasPlaceholders = 0x00, .useWiderBox = 0x00 },
{ .text = NULL, .boxType = 0x02, .x = 0x00, .y = 0x01, .letterSpacing = 0x00, .lineSpacing = 0x00, .hasPlaceholders = 0x00, .useWiderBox = 0x00 },
{ .text = NULL, .boxType = 0x02, .x = 0x00, .y = 0x01, .letterSpacing = 0x00, .lineSpacing = 0x00, .hasPlaceholders = 0x01, .useWiderBox = 0x00 },
{ .text = NULL, .boxType = 0x02, .x = 0x00, .y = 0x01, .letterSpacing = 0x00, .lineSpacing = 0x00, .hasPlaceholders = 0x00, .useWiderBox = 0x01 },
{ .text = NULL, .boxType = 0x02, .x = 0x00, .y = 0x01, .letterSpacing = 0x00, .lineSpacing = 0x00, .hasPlaceholders = 0x00, .useWiderBox = 0x01 },
{ .text = NULL, .boxType = 0x02, .x = 0x00, .y = 0x01, .letterSpacing = 0x00, .lineSpacing = 0x00, .hasPlaceholders = 0x00, .useWiderBox = 0x01 },
{ .text = NULL, .boxType = 0x02, .x = 0x00, .y = 0x01, .letterSpacing = 0x00, .lineSpacing = 0x00, .hasPlaceholders = 0x01, .useWiderBox = 0x01 },
{ .text = NULL, .boxType = 0x02, .x = 0x00, .y = 0x01, .letterSpacing = 0x00, .lineSpacing = 0x00, .hasPlaceholders = 0x00, .useWiderBox = 0x01 },
};
HOST_DATA struct MenuAction sKeyboardPageTitleTexts[5] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA const u8 *sConditionNames[5] = { NULL };
HOST_DATA const u8 *sHeaderTexts[5] = { NULL };
HOST_DATA const u8 *gAbilityDescriptionPointers[78] = { NULL };
HOST_DATA const u8 *gGiftRibbonDescriptionPointers[64][2] = { NULL };
HOST_DATA const u8 *gMatchCallFlavorTexts[78][4] = { NULL };
HOST_DATA const u8 *gMoveDescriptionPointers[354] = { NULL };
HOST_DATA const u8 *gNatureNamePointers[25] = { NULL };
HOST_DATA const u8 *gRibbonDescriptionPointers[25][2] = { NULL };
HOST_DATA const u8 *gContestEffectDescriptionPointers[48] = { NULL };
HOST_DATA const u8 *sUnusedComboMoveNameTexts[14] = { NULL };
HOST_DATA const u8 *gContestMoveTypeTextPointers[5] = { NULL };
HOST_DATA const u8 *sUnusedAppealResultTexts[13] = { NULL };
HOST_DATA const u8 *sRoundResultTexts[32] = { NULL };
HOST_DATA const u8 *sAppealResultTexts[62] = { NULL };
HOST_DATA const u8 *sContestConditions[5] = { NULL };
HOST_DATA const u8 *sInvalidContestMoveNames[6] = { NULL };
HOST_DATA struct MenuAction MultichoiceList_BrineyOnDewford[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_EnterInfo[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_ContestInfo[4] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_ContestType[6] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_BasePCWithRegistry[4] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_BasePCNoRegistry[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_RegisterMenu[4] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_Bike[2] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_StatusInfo[6] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_BrineyOffDewford[2] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_ViewedPaintings[2] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_YesNoInfo2[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_ChallengeInfo[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_LevelMode[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_Mechadoll1_Q1[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_Mechadoll1_Q2[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_Mechadoll1_Q3[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_Mechadoll2_Q1[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_Mechadoll2_Q2[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_Mechadoll2_Q3[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_Mechadoll3_Q1[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_Mechadoll3_Q2[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_Mechadoll3_Q3[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_Mechadoll4_Q1[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_Mechadoll4_Q2[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_Mechadoll4_Q3[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_Mechadoll5_Q1[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_Mechadoll5_Q2[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_Mechadoll5_Q3[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_VendingMachine[4] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_MachBikeInfo[4] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_AcroBikeInfo[4] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_Satisfaction[2] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_SternDeepSea[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_UnusedAshVendor[8] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_GameCornerDolls[4] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_GameCornerTMs[6] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_GameCornerCoins[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_HowsFishing[2] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_SSTidalSlateportWithBF[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_SSTidalBattleFrontier[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_RightLeft[2] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_SSTidalSlateportNoBF[2] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_Floors[6] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_ShardsR[2] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_ShardsY[2] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_ShardsRY[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_ShardsB[2] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_ShardsRB[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_ShardsYB[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_ShardsRYB[4] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_ShardsG[2] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_ShardsRG[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_ShardsYG[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_ShardsRYG[4] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_ShardsBG[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_ShardsRBG[4] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_ShardsYBG[4] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_ShardsRYBG[5] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_TourneyWithRecord[6] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_TourneyNoRecord[5] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_Tent[2] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_LinkServicesNoBerry[4] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_YesNoInfo[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_BattleMode[5] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_LinkServicesNoRecord[4] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_LinkServicesAll[5] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_LinkServicesNoRecordBerry[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_WirelessMinigame[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_LinkLeader[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_ContestRank[5] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_FrontierItemChoose[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_LinkContestInfo[4] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_LinkContestMode[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_ForcedStartMenu[8] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_FrontierGamblerBet[4] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_UnusedSSTidal1[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_UnusedSSTidal2[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_UnusedSSTidal3[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_UnusedSSTidal4[4] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_Fossil[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_YesNo[2] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_FrontierRules[6] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_FrontierPassInfo[4] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_BattleArenaRules[5] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_BattleTowerRules[5] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_BattleDomeRules[4] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_BattleFactoryRules[6] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_BattlePalaceRules[6] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_BattlePyramidRules[5] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_BattlePikeRules[4] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_GoOnRecordRestRetire[4] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_GoOnRestRetire[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_GoOnRecordRetire[3] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_GoOnRetire[2] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_TVLati[2] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_BattleTowerFeelings[4] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_WheresRayquaza[4] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_SlateportTentRules[6] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_FallarborTentRules[6] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_TagMatchType[5] =
{
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
{ .text = NULL, .func = { NULL } },
};
HOST_DATA struct MenuAction MultichoiceList_Exit[1] =
{
{ .text = NULL, .func = { NULL } },
};
HOST_DATA const u8 *gStdStrings[30] = { NULL };
HOST_DATA const u8 *sPCNameStrings[4] = { NULL };
HOST_DATA const u8 *sLilycoveSSTidalDestinations[7] = { NULL };
HOST_DATA const u8 *sActionStringTable[27] = { NULL };
HOST_DATA const u8 *sDescriptionStringTable[13] = { NULL };
HOST_DATA const u8 *sUnionRoomTradeMessages[9] = { NULL };
HOST_DATA const u8 *sUnused_StatStrings[6] = { NULL };
HOST_DATA const u8 *sMessages[9] = { NULL };
HOST_DATA const u8 *sFavorLadyRequests[6] = { NULL };
HOST_DATA const u8 *sContestLadyMonNames[5] = { NULL };
HOST_DATA const u8 *sContestLadyCategoryNames[5] = { NULL };
HOST_DATA const u8 *sContestNames[5] = { NULL };
HOST_DATA struct ListMenuItem sRegisterForTradeListMenuItems[3] =
{
{ .name = NULL, .id = 1 },
{ .name = sText_Info, .id = 2 },
{ .name = sText_Exit, .id = 3 },
};
HOST_DATA const struct MatchCallText *sMatchCallBattleTopics[3] = { NULL };
HOST_DATA const struct MatchCallText *sMatchCallBattleRequestTopics[2] = { NULL };
HOST_DATA const struct MatchCallText *sMatchCallGeneralTopics[6] = { NULL };
HOST_DATA const struct NamingScreenTemplate *sNamingScreenTemplates[5] = { NULL };
HOST_DATA const u8 *gText_123Dot[3] = { NULL };