/* Generated by tools/gen3_resources/text_family/gen_text_family.py.
 * Do not edit by hand; re-run the generator and --check it.
 */
#include "emerald/resources/text_arenas.generated.h"

const struct TextArenaSummary kTextArenaSummaries[TEXT_ARENA_COUNT] =
{
    {"battle", 522u, 11989u},
    {"move", 355u, 17251u},
    {"ability", 78u, 1859u},
    {"nature", 25u, 162u},
    {"item", 310u, 15101u},
    {"pokedex", 387u, 58017u},
    {"system-shared", 2933u, 105557u},
    {"tv", 401u, 55507u},
    {"matchcall", 629u, 60934u},
    {"apprentice", 288u, 49891u},
    {"ribbon", 66u, 1265u},
    {"frontier", 180u, 11597u},
    {"frontier-brain", 28u, 882u},
    {"easy-chat", 1008u, 7101u},
    {"berry", 41u, 4305u},
    {"misc", 5546u, 504421u},
};
