/* gen3-elf-manifest - deterministic maintainer-side extraction manifest
 * generator for the Gen3 resource mod (Stage R1A).
 *
 * Reads a catalog (resources/catalogs/emerald/catalog.toml), a binding input
 * (resources/extraction/emerald/bpee01/bindings.toml), the linked GBA ELF and
 * the retail ROM, validates every resource end-to-end, and emits a
 * byte-for-byte deterministic manifest. `--check` verifies an existing
 * manifest was generated by this exact pipeline.
 *
 * Run from the repository root so binding-relative artifact paths resolve.
 */
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "manifest.h"
#include "gen3/resources/toml.h"
#include "gen3/resources/util.h"

struct Options
{
    const char *catalog;
    const char *bindings;
    const char *elf;
    const char *rom;
    const char *output;
    const char *romSha1;
    const char *romGameCode;
    const char *romMakerCode;
    const char *provenance;
    const char *qualification;
    unsigned romRevision;
    bool haveRevision;
    bool check;
};

static void Usage(FILE *stream)
{
    fprintf(stream,
        "usage: gen3-elf-manifest --catalog <path> --bindings <path>\n"
        "       --elf <path> --rom <path> --output <path> [options]\n"
        "\n"
        "required:\n"
        "  --catalog <path>    catalog.toml (emerald)\n"
        "  --bindings <path>   binding input (bpee01/bindings.toml)\n"
        "  --elf <path>        linked GBA ELF (pokeemerald.elf)\n"
        "  --rom <path>        GBA ROM image (pokeemerald.gba)\n"
        "  --output <path>     deterministic manifest output path\n"
        "\n"
        "options:\n"
        "  --check             verify --output matches deterministic regeneration\n"
        "  --rom-sha1 <hex>    expected ROM SHA-1 (default: retail Emerald hash)\n"
        "  --rom-game-code <4> expected game code (default: BPEE)\n"
        "  --rom-maker-code <2> expected maker code (default: 01)\n"
        "  --rom-revision <n>  expected software revision (default: 0)\n"
        "  --provenance <text>  deterministic provenance comment for the manifest\n"
        "  --qualification <q>  'fixture' or 'production' (default: fixture);\n"
        "                       production is only for manifests verified against\n"
        "                       the retail ROM from a pinned pret build\n"
        "  -h, --help          show this help\n"
        "\n"
        "exit codes: 0 success, 1 validation/generation failure, 2 usage error\n");
}

static const char *RequireValue(struct Options *options, int argc, char **argv,
                                int *index, const char *flag)
{
    (void)options;
    if (*index + 1 >= argc)
    {
        fprintf(stderr, "gen3-elf-manifest: option '%s' requires a value\n", flag);
        return NULL;
    }
    (*index)++;
    return argv[*index];
}

static bool ParseArgs(int argc, char **argv, struct Options *options)
{
    int i;
    for (i = 1; i < argc; i++)
    {
        const char *argument = argv[i];
        if (strcmp(argument, "-h") == 0 || strcmp(argument, "--help") == 0)
        {
            Usage(stdout);
            exit(0);
        }
        else if (strcmp(argument, "--check") == 0)
        {
            options->check = true;
        }
        else if (strcmp(argument, "--catalog") == 0)
        {
            options->catalog = RequireValue(options, argc, argv, &i, argument);
        }
        else if (strcmp(argument, "--bindings") == 0)
        {
            options->bindings = RequireValue(options, argc, argv, &i, argument);
        }
        else if (strcmp(argument, "--elf") == 0)
        {
            options->elf = RequireValue(options, argc, argv, &i, argument);
        }
        else if (strcmp(argument, "--rom") == 0)
        {
            options->rom = RequireValue(options, argc, argv, &i, argument);
        }
        else if (strcmp(argument, "--output") == 0)
        {
            options->output = RequireValue(options, argc, argv, &i, argument);
        }
        else if (strcmp(argument, "--rom-sha1") == 0)
        {
            options->romSha1 = RequireValue(options, argc, argv, &i, argument);
        }
        else if (strcmp(argument, "--rom-game-code") == 0)
        {
            options->romGameCode = RequireValue(options, argc, argv, &i, argument);
        }
        else if (strcmp(argument, "--rom-maker-code") == 0)
        {
            options->romMakerCode = RequireValue(options, argc, argv, &i, argument);
        }
        else if (strcmp(argument, "--provenance") == 0)
        {
            options->provenance = RequireValue(options, argc, argv, &i, argument);
        }
        else if (strcmp(argument, "--qualification") == 0)
        {
            options->qualification = RequireValue(options, argc, argv, &i, argument);
        }
        else if (strcmp(argument, "--rom-revision") == 0)
        {
            const char *value = RequireValue(options, argc, argv, &i, argument);
            char *end = NULL;
            unsigned long parsed;
            if (value == NULL)
                return false;
            errno = 0;
            parsed = strtoul(value, &end, 10);
            if (errno != 0 || end == value || *end != '\0' || parsed > 255u)
            {
                fprintf(stderr, "gen3-elf-manifest: invalid --rom-revision '%s'\n", value);
                return false;
            }
            options->romRevision = (unsigned)parsed;
            options->haveRevision = true;
        }
        else
        {
            fprintf(stderr, "gen3-elf-manifest: unknown option '%s'\n", argument);
            return false;
        }
    }
    if (options->catalog == NULL || options->bindings == NULL
     || options->elf == NULL || options->rom == NULL || options->output == NULL)
    {
        fprintf(stderr, "gen3-elf-manifest: missing required option(s)\n");
        return false;
    }
    return true;
}

static int LoadFiles(struct Options *options,
                     struct Gen3Buffer *catalog, struct Gen3Buffer *bindings,
                     struct Gen3Buffer *elf, struct Gen3Buffer *rom)
{
    char errbuf[512];
    if (!Gen3Util_ReadFile(options->catalog, catalog, errbuf, sizeof(errbuf)))
    {
        fprintf(stderr, "gen3-elf-manifest: %s\n", errbuf);
        return 1;
    }
    if (!Gen3Util_ReadFile(options->bindings, bindings, errbuf, sizeof(errbuf)))
    {
        fprintf(stderr, "gen3-elf-manifest: %s\n", errbuf);
        return 1;
    }
    if (!Gen3Util_ReadFile(options->elf, elf, errbuf, sizeof(errbuf)))
    {
        fprintf(stderr, "gen3-elf-manifest: %s\n", errbuf);
        return 1;
    }
    if (!Gen3Util_ReadFile(options->rom, rom, errbuf, sizeof(errbuf)))
    {
        fprintf(stderr, "gen3-elf-manifest: %s\n", errbuf);
        return 1;
    }
    return 0;
}

int main(int argc, char **argv)
{
    struct Options options;
    struct Gen3Buffer catalogBuffer;
    struct Gen3Buffer bindingsBuffer;
    struct Gen3Buffer elfBuffer;
    struct Gen3Buffer romBuffer;
    struct Gen3Buffer outputBuffer;
    struct Gen3TomlDocument catalogDocument;
    struct Gen3TomlDocument bindingsDocument;
    struct Gen3ManifestConfig config;
    enum Gen3ManifestResult result;
    char errbuf[512];
    int exitCode = 1;

    memset(&options, 0, sizeof(options));
    memset(&config, 0, sizeof(config));
    if (!ParseArgs(argc, argv, &options))
    {
        Usage(stderr);
        return 2;
    }
    config.expectedRomSha1Hex = options.romSha1;
    config.romGameCode = options.romGameCode;
    config.romMakerCode = options.romMakerCode;
    config.provenance = options.provenance;
    config.qualification = options.qualification;
    config.romRevision = options.haveRevision ? options.romRevision : 0;

    if (LoadFiles(&options, &catalogBuffer, &bindingsBuffer, &elfBuffer, &romBuffer) != 0)
        return 1;
    if (!Gen3Toml_Parse(catalogBuffer.data, catalogBuffer.length,
                        &catalogDocument, errbuf, sizeof(errbuf)))
    {
        fprintf(stderr, "gen3-elf-manifest: catalog parse failed: %s\n", errbuf);
        exitCode = 1;
        goto done;
    }
    if (!Gen3Toml_Parse(bindingsBuffer.data, bindingsBuffer.length,
                        &bindingsDocument, errbuf, sizeof(errbuf)))
    {
        fprintf(stderr, "gen3-elf-manifest: bindings parse failed: %s\n", errbuf);
        exitCode = 1;
        goto done;
    }

    result = Gen3Manifest_FromToml(&catalogDocument, &bindingsDocument,
                                   NULL /* artifact paths resolve against cwd */,
                                   (const uint8_t *)elfBuffer.data, elfBuffer.length,
                                   (const uint8_t *)romBuffer.data, romBuffer.length,
                                   &config, &outputBuffer, errbuf, sizeof(errbuf));
    if (result != GEN3_MANIFEST_OK)
    {
        fprintf(stderr, "gen3-elf-manifest: generation failed (%d): %s\n",
                (int)result, errbuf[0] != '\0' ? errbuf : "(no detail)");
        exitCode = 1;
        goto done;
    }

    if (options.check)
    {
        struct Gen3Buffer existing;
        if (!Gen3Util_ReadFile(options.output, &existing, errbuf, sizeof(errbuf)))
        {
            fprintf(stderr, "gen3-elf-manifest: --check cannot read '%s': %s\n",
                    options.output, errbuf);
            exitCode = 1;
            goto done;
        }
        if (existing.length == outputBuffer.length
         && memcmp(existing.data, outputBuffer.data, existing.length) == 0)
        {
            printf("gen3-elf-manifest: OK - '%s' matches deterministic regeneration\n",
                   options.output);
            exitCode = 0;
        }
        else
        {
            fprintf(stderr, "gen3-elf-manifest: FAIL - '%s' differs from deterministic regeneration\n",
                    options.output);
            exitCode = 1;
        }
        Gen3Buffer_Destroy(&existing);
    }
    else
    {
        if (!Gen3Util_WriteFile(options.output, outputBuffer.data, outputBuffer.length,
                                errbuf, sizeof(errbuf)))
        {
            fprintf(stderr, "gen3-elf-manifest: %s\n", errbuf);
            exitCode = 1;
            goto done;
        }
        printf("gen3-elf-manifest: wrote '%s'\n", options.output);
        exitCode = 0;
    }

done:
    Gen3Toml_Destroy(&catalogDocument);
    Gen3Toml_Destroy(&bindingsDocument);
    Gen3Buffer_Destroy(&catalogBuffer);
    Gen3Buffer_Destroy(&bindingsBuffer);
    Gen3Buffer_Destroy(&elfBuffer);
    Gen3Buffer_Destroy(&romBuffer);
    Gen3Buffer_Destroy(&outputBuffer);
    return exitCode;
}
