#ifndef GEN3_ELF_MANIFEST_MANIFEST_H
#define GEN3_ELF_MANIFEST_MANIFEST_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "gen3/resources/toml.h"
#include "gen3/resources/util.h"

#define GEN3_MANIFEST_VERSION 1
#define GEN3_ROM_SIZE (16u * 1024u * 1024u)
#define GEN3_GBA_ROM_BASE 0x08000000u
#define GEN3_SHA256_SIZE 32u
#define GEN3_SHA256_HEX_SIZE (GEN3_SHA256_SIZE * 2u + 1u)

/* Default expected SHA-1 of the retail Emerald (BPEE) ROM image. Synthetic
 * fixture ROMs used by the test suite override this via the config. */
#define GEN3_DEFAULT_ROM_SHA1_HEX "f3ae088181bf583e55daf962a92bb46f4f1d07b7"

enum Gen3ManifestResult
{
    GEN3_MANIFEST_OK = 0,
    GEN3_MANIFEST_BAD_ROM_SIZE,      /* ROM is not exactly 16 MiB */
    GEN3_MANIFEST_BAD_ROM_IDENTITY,  /* game code / maker code / revision mismatch */
    GEN3_MANIFEST_BAD_ROM_SHA1,      /* ROM SHA-1 does not match the expected hash */
    GEN3_MANIFEST_BAD_ELF,           /* ELF failed to parse */
    GEN3_MANIFEST_MISSING_SYMBOL,    /* binding symbol absent from the ELF */
    GEN3_MANIFEST_SYMBOL_NOT_ROM,    /* not an allocated ROM object >= 0x08000000 */
    GEN3_MANIFEST_ROM_RANGE_OVERFLOW,/* symbol extends past the end of the ROM */
    GEN3_MANIFEST_ARTIFACT_MISMATCH, /* source artifact != ELF bytes != ROM slice */
    GEN3_MANIFEST_LZ_FAILED,         /* strict LZ77 decode rejected the data */
    GEN3_MANIFEST_UNSUPPORTED_ENCODING, /* binding source_encoding is not
                                           "gba-lz77" or "raw" */
    GEN3_MANIFEST_DECODED_SIZE_MISMATCH,
    GEN3_MANIFEST_CANONICAL_MISMATCH,/* decoded bytes != canonical decoded artifact */
    GEN3_MANIFEST_DUPLICATE_ID,      /* duplicate catalog or binding canonical id */
    GEN3_MANIFEST_UNKNOWN_RESOURCE,  /* binding id not present in the catalog */
    GEN3_MANIFEST_TYPE_MISMATCH,     /* canonical_representation incompatible with type */
    GEN3_MANIFEST_DUPLICATE_RANGE,   /* overlapping ROM ranges not allowed */
    GEN3_MANIFEST_INVALID_NAME,      /* canonical id fails the M0/M1 name grammar */
    GEN3_MANIFEST_BAD_QUALIFICATION, /* qualification is not "fixture" or "production" */
    GEN3_MANIFEST_INVALID_INPUT,     /* null argument / allocation failure */
};

/* ROM identity + SHA-1 validation knobs. NULL / zero fields fall back to the
 * retail Emerald defaults (BPEE / "01" / revision 0 / GEN3_DEFAULT_ROM_SHA1). */
struct Gen3ManifestConfig
{
    const char *expectedRomSha1Hex;
    const char *romGameCode;
    const char *romMakerCode;
    unsigned romRevision;
    /* Optional one-line provenance note (e.g. "generated from the synthetic
     * bpee01 fixture") emitted as a comment so the manifest is self-flagging.
     * NULL/empty omits the line. Must be deterministic text. */
    const char *provenance;
    /* Manifest qualification: "fixture" (synthetic test ROM, generated by
     * fixture_build) or "production" (pinned pret build verified against the
     * retail ROM). NULL defaults to "fixture". The R3 importer fails closed:
     * a fixture-qualified manifest is never accepted for production import. */
    const char *qualification;
};

/* Manifest-level metadata copied from the catalog. `game` and `romProfile`
 * identify the source ROM profile (e.g. "emerald" / "bpee01-rev0"); NULL
 * omits the corresponding manifest fields. */
struct Gen3ManifestMeta
{
    const char *namespace;
    const char *resourceApi;
    const char *game;
    const char *romProfile;
};

/* One catalog contract (type + schema) keyed by canonical id. */
struct Gen3CatalogEntry
{
    const char *id;
    const char *type;
    uint32_t schema;
};

/* One semantic binding with its artifact bytes already loaded. */
struct Gen3BindingInput
{
    const char *id;
    const char *symbol;
    const char *sourceEncoding;
    const char *canonicalRepresentation;
    uint32_t expectedDecodedSize;
    bool allowSharedRange;
    const uint8_t *sourceArtifact;   /* encoded bytes (the .lz file) */
    size_t sourceArtifactSize;
    const uint8_t *canonicalDecoded; /* expected decoded bytes (.4bpp / .gbapal) */
    size_t canonicalDecodedSize;
};

/* The deterministic record emitted for one resource. */
struct Gen3ManifestRecord
{
    const char *id;
    uint8_t key[GEN3_SHA256_SIZE];
    const char *type;
    uint32_t schema;
    const char *symbol;
    uint32_t romOffset;
    uint32_t encodedLength;
    uint32_t decodedLength;
    const char *sourceEncoding;
    uint8_t sourceEncodedSha256[GEN3_SHA256_SIZE];
    uint8_t canonicalDecodedSha256[GEN3_SHA256_SIZE];
};

/* Runs the full R1A validation pipeline and serializes the deterministic
 * manifest (records sorted bytewise by canonical id) into *outManifest.
 * String pointers in the catalog/binding arrays must outlive the call. */
enum Gen3ManifestResult Gen3Manifest_Generate(
    const struct Gen3ManifestMeta *meta,
    const struct Gen3CatalogEntry *catalog, size_t catalogCount,
    const struct Gen3BindingInput *bindings, size_t bindingCount,
    const uint8_t *elfData, size_t elfSize,
    const uint8_t *romData, size_t romSize,
    const struct Gen3ManifestConfig *config,
    struct Gen3Buffer *outManifest,
    char *errbuf, size_t errbufSize);

/* High-level entry point used by the CLI: parses the two TOML documents,
 * resolves `source_artifact` / canonical-decoded paths against `baseDir`
 * (the canonical path is the artifact path with a trailing ".lz" removed),
 * then delegates to Gen3Manifest_Generate. */
enum Gen3ManifestResult Gen3Manifest_FromToml(
    const struct Gen3TomlDocument *catalogDoc,
    const struct Gen3TomlDocument *bindingsDoc,
    const char *baseDir,
    const uint8_t *elfData, size_t elfSize,
    const uint8_t *romData, size_t romSize,
    const struct Gen3ManifestConfig *config,
    struct Gen3Buffer *outManifest,
    char *errbuf, size_t errbufSize);

/* Serializes an already-built record set (which must be sorted bytewise by
 * canonical id) into the same deterministic TOML layout the tool emits.
 * `qualification` defaults to "fixture" when NULL. */
bool Gen3Manifest_Serialize(const struct Gen3ManifestMeta *meta,
                            const struct Gen3ManifestRecord *records, size_t recordCount,
                            const uint8_t romSha1[20], const uint8_t romSha256[GEN3_SHA256_SIZE],
                            uint32_t romSize, const char *provenance,
                            const char *qualification,
                            struct Gen3Buffer *out);

#endif
