catalog_version = 1
namespace = "emerald"
resource_api = "1.0.0"
game = "emerald"
rom_profile = "bpee01-rev0"

[[resources]]
id = "emerald:data/weather/drought-colors"
type = "binary"
schema = 1
required_for_base = true
